### ISSUE TITLE
Change the state icon when some of but not all the layers of a group are selected

### ISSUE THREAD

**Issue by olivierSemet** [camptocamp/ngeo#1008]
When some of but not all the layers of a group are selected, the group state icon is specific.

<img width="314" alt="capture d ecran 2016-04-11 a 10 15 55" src="https://cloud.githubusercontent.com/assets/8366681/14421287/0faf5240-ffd1-11e5-9f8d-75ea7d16daf5.png">

**Comment by pgiraud** [comment]
Fixed via #1010.
