### ISSUE TITLE
issues on the desktop app

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/ngeo#1012]
When I charge this https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/desktop/index.html I get:
![issue](https://cloud.githubusercontent.com/assets/353872/14429150/87d27af6-fffc-11e5-9dd3-4e9ed7975b95.png)

- Theme: OSM, but the groups of the theme Enseignement
- What's this field under the search?

**Comment by pgiraud** [comment]
I created 2 different issues. Closing.

**Comment by sbrunner** [comment]
Thanks @pgiraud :-)
