### ISSUE TITLE
When a layer have an "name" different than the "WMS layer name" it doesn't work

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/ngeo#1017]
see for example the layer named: `Layer with very very very very very long name`
with layers: `restaurant`

**Comment by fgravin** [comment]
We don't understand the issue, could you explain it more precisely please ?

**Comment by sbrunner** [comment]
- https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/mobile/index.html?lang=fr
- add theme OSM
- `Fonctions OSM/Layer with very very very very very long name` don't display anything but `Couches/Restaurants/Restaurants` display something and they use the same `layers` `restaurants`...

**Comment by olivierSemet** [comment]
@sbrunner I know where is the issue. For now the property "name" of a node is used to set the "LAYERS" parameter of the request url. I need to now if the property "layers" for each node (speaking about node grabbed from the theme service) can take more than one string value. I cannot find a such configuration in the themes used for the demo app but I need to know if it can happen.

**Comment by sbrunner** [comment]
The layers is only one string, but it can be something like: `layer1,layer2`...

**Comment by olivierSemet** [comment]
Ok that's what I called multiple values... So Right now there is a confusion in the gmfLayertree code. The "name" attributs is taken from each node to retrieve (or build) a map server request (more precisely, to feed the "LAYERS" param for the HTTP request). This is work for 99% of the nodes in the theme examples because node.name is always the same value as node.layers. Except for "Layer whith a very very very long name" which has node.layers="restaurants"

**Comment by pgiraud** [comment]
I agree with @olivierSemet.
In https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/src/directives/layertree.js `node.name` is used several times where sometimes we should use `node.layers`.
I'd go through each and check if using `node.name` is relevant.

**Comment by sbrunner** [comment]
Thanks @pgiraud :-)

**Comment by olivierSemet** [comment]
@sbrunner if node is a leaf, its parameter "layers" can't have multiple value i.e layers = "layer1, layer2, layer3"?

**Comment by sbrunner** [comment]
Normally not but if he can it's great

**Comment by fredj** [comment]
todo: check if it works

**Comment by fredj** [comment]
ok, tested in https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/desktop
