### ISSUE TITLE
Theme not stored in local storage

### ISSUE THREAD

**Issue by pgiraud** [camptocamp/ngeo#1026]
The state of the tree is stored in local storage but the currently selected theme is not.
This may result in UI showing groups from a theme and the theme selector telling user that a different theme is chosen.

Procedure to reproduce:
 - load application,
 - select other theme than the default one (example Water Management),
 - groups from theme Water Management are correctly shown in tree,
 - reload page.

What happens:
 - groups from theme Water Management are shown in layer tree,
 - theme OSM is selected in theme selector.

Expected:
In **flush mode**, the theme which was selected before reload should be selected again.

Supersedes #1012.

https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/desktop/index.html I get:
![issue](https://cloud.githubusercontent.com/assets/353872/14429150/87d27af6-fffc-11e5-9dd3-4e9ed7975b95.png)

**Comment by ybolognini** [comment]
Fixed ?

**Comment by pgiraud** [comment]
Not fixed.

**Comment by olivierSemet** [comment]
@pgiraud  can you assign it to me?

**Comment by olivierSemet** [comment]
@pgiraud @fredj we can easily store the selected theme in the localStorage. I have a question:

- Could it be useful to also add a query parameter with the selected theme in the permalink (for the future)? **If yes**:
 - Is it compatible with GMF 1.x ?

**Comment by sbrunner** [comment]
The theme is already in the URL path, than it will be duplicated => not useful...

**Comment by olivierSemet** [comment]
Yes you're right sorry. Forget my question

**Comment by sbrunner** [comment]
:-)
