### ISSUE TITLE
Modify feature - cursor to change when hovering vertices

### ISSUE THREAD

**Issue by pgiraud** [camptocamp/ngeo#1035]
**This is a nice-to-have.**

It would be nice to be able to have a "grab" when hovering a vertex in modify mode.

@adube Can you give your opinion on feasibility?

**Comment by adube** [comment]
Sure.

We have 3 different kind of modify interactions that we'll use: `ol.interaction.Modify`, `ngeo.interaction.ModifyCircle` and `ol.interaction.ModifyRectangle`.  All 3 have (will have) a vector layer in which the vertice features are added.  The idea would be to listen to the features added in there and register a map "pointermove" event and act accordingly when hovering one of these features.

It would require exposing the layer, in each case.  That means: a patch for ol3 for `ol.interaction.Modify`, the rest is within ngeo.

Does that make sense ?

**Comment by sbrunner** [comment]
https://jira.camptocamp.com/browse/GSGMF-530
