### ISSUE TITLE
Legend images should be downloaded only when displayed

### ISSUE THREAD

**Issue by pgiraud** [camptocamp/ngeo#1055]
Currently we add DOM elements even for legend block that are hidden (collapsed) by default. This may send a lot of http requests at page load even if the user never displays the legend.
It would be better to load the images only when required.

**Comment by arnaud-morvan** [comment]
+1 for this, this is very annoying as GetLegendGraphic requests are send on each zoom change before the tiles requests. This as a bad effect on tiles loading time on each zoom level change.
@olivierSemet : have planned to make a pull request ?

**Comment by fredj** [comment]
See also #2456

**Comment by llienher** [comment]
This issue being fixed with #2456 and #2758 fixing the loading on top of that, I close it.
