### ISSUE TITLE
"Source not available" displayed temporarily

### ISSUE THREAD

**Issue by pgiraud** [camptocamp/ngeo#1057]
In the desktop app, a "Source not available" appears furtively in layertree for the last two layers when loading the cadastre theme.

**Comment by ybolognini** [comment]
When loading, we could have the text "Loading..."

**Comment by pgiraud** [comment]
I would first be interested to know where this message comes from.

**Comment by sbrunner** [comment]
From here https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/less/layertree.less#L156
And the class from https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/src/directives/layertree.js#L744
After I'm lost...

**Comment by sbrunner** [comment]
See also: #1114

**Comment by pgiraud** [comment]
This is currently not reproducible since the `isExpanded` metadata is missing in 2.1.

**Comment by pgiraud** [comment]
@ybolognini we need to have a quick discussion on this topic.

**Comment by pgiraud** [comment]
Decision: we should use the spinner and display it when the source is not available. Just as if the layer was loading images.
