### ISSUE TITLE
Featurehash throw an error when we have a style without attributes...

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/ngeo#1069]
see: https://github.com/camptocamp/ngeo/pull/1062#issuecomment-214717285

**Comment by adube** [comment]
@sbrunner Would you please assign this to someone who'll be able to make a quick fix ?  I'm not fully aware how this format works, not what are the possible values.  It would take me more time than the author of this format to fix this.

**Comment by sbrunner** [comment]
=> unassigned ...
