### ISSUE TITLE
gmf-drawfeature - actions menu - don't add vertex

### ISSUE THREAD

**Issue by pgiraud** [camptocamp/ngeo#1085]
When a feature is already selected, the modify interaction is activated. This means that a vertex can be added on any segment.
A vertex is added even when the user only wants to display the actions menu.

**Comment by pgiraud** [comment]
Related to https://github.com/camptocamp/ngeo/issues/1091.

**Comment by adube** [comment]
@jlap, could you add this in #1129.

**Comment by adube** [comment]
For the record, this shouldn't be part of #1129.  We'll have to talk about this more.
