### ISSUE TITLE
[Edit] Menu open/close behavior

### ISSUE THREAD

**Issue by ybolognini** [camptocamp/ngeo#1088]
* [x] Action menu opens on right-click and long-press on mobile (so it won't open on geometry selection)
 * [x] Action menu should disappear when user clicks anywhere else or when an action is selected
 * [x] Remove "Action" title and cross to close the menu

**Comment by adube** [comment]
>  Action menu should disappear when user clicks anywhere else or when an action is selected

This is already the case, right ?

> Remove "Action" title and cross to close the menu

Okay, simple enough.


> The action menu shouldn't appear when user clicks on a vertex

Okay.
