### ISSUE TITLE
Print enhancements - better reset after end of pointerDrag event

### ISSUE THREAD

**Issue by ger-benjamin** [camptocamp/ngeo#1105]
Following of the PR #937 
Don't use timeout (temporary solution) to reset previous pointerDrag event position.

**Comment by sbrunner** [comment]
Fixed?

**Comment by ger-benjamin** [comment]
No, and finally I've no clue on how to do this... (But that's not urgent, I think that can be done for the 2.2).

**Comment by sbrunner** [comment]
https://jira.camptocamp.com/browse/GSGMF-509
