### ISSUE TITLE
input slider not correctly displayed on internet explorer

### ISSUE THREAD

**Issue by fredj** [camptocamp/ngeo#1107]
on IE 10:
![slider_ie](https://cloud.githubusercontent.com/assets/100959/14981932/e6be0034-1132-11e6-9b1e-38c24ba8c016.png)

**Comment by olivierSemet** [comment]
Fixed on latest version:
<img width="558" alt="capture d ecran 2016-05-11 a 14 10 34" src="https://cloud.githubusercontent.com/assets/8366681/15180486/44f4e474-1782-11e6-918e-1e9416aadeb5.png">

But margin are bigger than on FF/chrome..

**Comment by fredj** [comment]
thanks !

**Comment by olivierSemet** [comment]
Can we close the issue @fredj ?
