### ISSUE TITLE
print mask may appear even if print panel is closed

### ISSUE THREAD

**Issue by pgiraud** [camptocamp/ngeo#1133]
If the print capabilities request is pending and takes a lot of time, the print mask may appear after the print panel is closed by the user.

**Comment by fredj** [comment]
Fixed with #1118 ?

**Comment by ger-benjamin** [comment]
I think that's fixed with this PR yes. Can you confirm/invalidate @pgiraud ?

**Comment by pgiraud** [comment]
I don't think this is fixed. It's a different problem.

The `getCapabilities` promise is waiting for a response. When the response arrives, the `then` tasks are executed, no matter if the print panel is closed or not.

Steps to reproduce :
 - open application,
 - when loaded, launch the following command:
```
sudo wondershaper eth0 5 5
```
 - open the print panel and immediately close it.

After some seconds, the print mask appears.
(Note don't forget to clear all `wondershaper` jobs)

Also I'm surprised that a request on the capabilities service is launched every time the user opens the print panel.
