### ISSUE TITLE
Too much cursor change in layer tree

### ISSUE THREAD

**Issue by pgiraud** [camptocamp/ngeo#1134]
![sans titre 1](https://cloud.githubusercontent.com/assets/319774/15072136/5ab84cbe-1391-11e6-946f-f5a9ed6a04fb.gif)

When hovering group nodes in the layer tree, the cursor changes too much.
We should at least try to prevent the "select text" cursor.

**Comment by pgiraud** [comment]
An option is to use flexbox to position elements. This unfortunately may require a lot of work.

**Comment by ybolognini** [comment]
Moved in https://github.com/camptocamp/c2cgeoportal/issues/2022
