### ISSUE TITLE
The shaking loadings icons  on Firefox

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/ngeo#1140]
on layertree and on print

**Comment by pgiraud** [comment]
See http://fortawesome.github.io/Font-Awesome/examples/ (Animated icons).
And https://github.com/FortAwesome/Font-Awesome/issues/671

**Comment by ger-benjamin** [comment]
Use a gif or found another workaround but don't try to debug  font-awesome

**Comment by sbrunner** [comment]
Adding the CSS `filter: blur(0);` seam to work ...

**Comment by pgiraud** [comment]
This looks good indeed. Let's be a bit cautious though, see https://github.com/FortAwesome/Font-Awesome/issues/671#issuecomment-30692206

**Comment by sbrunner** [comment]
Why and how it breaks ie? He has a wrong implementation of the filter blur?
