### ISSUE TITLE
Layertree desktop fixes

### ISSUE THREAD

**Issue by ybolognini** [camptocamp/ngeo#1147]
* [x] -later- Larger grab zone for reorder (now two pixels wide, should be at least 4)
* [ ] -later- When dragging a group to the bottom, the dashed zone is displayed and then disappear forever. It should stay visible
* [x] -todo- Icon go-to-scale isn't as specified: icon should be magnifier and positionned after layer name
* [x] -todo- When layer out of scale, should its name be in italics
* [x] -todo- Tooltips (for "show/hide legend" and "zoom to scale") should be implemented using bootstrap. See for instance print/rotate widget
* [x] When we click on « show legend » the popover should be hidden
* [x] https://github.com/camptocamp/ngeo/pull/1155#issuecomment-218100623

**Comment by sbrunner** [comment]
see also: https://github.com/camptocamp/ngeo/pull/1155#issuecomment-218100623

**Comment by pgiraud** [comment]
Last remaining item should be addressed in a different issue. #1347.
Closing.
