### ISSUE TITLE
If search response is too slow, the script crashes

### ISSUE THREAD

**Issue by ger-benjamin** [camptocamp/ngeo#1154]
Tested on demo 2.1, last commit:  "Add isExpanded" May 9

I'm not totally sur but if you search something on https://geomapfish-demo.camptocamp.net/2.1/wsgi/ (a slow server), your application can wait eternally on the response.

Can someone comfirms the issue and the analyze ?

**Comment by sbrunner** [comment]
To test on next update ...

**Comment by tsauerwein** [comment]
I tend to say it's not related to the fact that the page is served from this server. When running on github.io or locally the same web-service is used.

But I think something is wrong with the build. I downloaded the build files (index.html + desktop.js + desktop.css) and I have the same problem locally. Like @sbrunner says, to test with master.
