### ISSUE TITLE
Selecting scale in print makes strange zoom / scale choice behaviour

### ISSUE THREAD

**Issue by ger-benjamin** [camptocamp/ngeo#1160]
Tested on demo 2.1, last commit:  "Add isExpanded" May 9

In print panel, play with the scale and select 1:25'000. Result scale is 1:10'000.
Choose again 1:25'000. Result scale is 1:25'000 but nothing has changed.
You must zoom in/out on the map to get a correct value of scale.

**Comment by ger-benjamin** [comment]
(Perhaps that a part of the solution: https://github.com/camptocamp/ngeo/pull/1203)

**Comment by fredj** [comment]
yes, it's probably the same thing
