### ISSUE TITLE
Layertree regressions

### ISSUE THREAD

**Issue by ger-benjamin** [camptocamp/ngeo#1162]
Tested on demo 2.1, last commit:  "Add isExpanded" May 9
Line striked seem resolved after this commit (view on github.io)

Not working (anymore) :
 1. ~~Visible by default (on mixed groups ?)~~
 1. Legend open by default
 1. Display the metadata URL
 1. ~~Groups open by default~~
 1. Show/hide legend tooltip is not translated

And for WMTS: If one layer is unavailable, it's not possible to activate them and so, the layer group icon can't be used to activate/deactivate all layers (always on state indeterminate (or off if all layer are deactivated manually))

**Comment by sbrunner** [comment]
1. Seam do work
2. I work on it
3. Will be fixed
4. Seam do work
5. Should be don on next build
6. ... :-)

WMTS: @tsauerwein can you have a look on it?

**Comment by sbrunner** [comment]
Finally @ger-benjamin  work on WMTS :-)

**Comment by pgiraud** [comment]
"Show/hide legend" and "opacity" are correctly translated. The translations seem to be missing in German.

**Comment by pgiraud** [comment]
@ybolognini We're not sure what still needs to be done.

**Comment by ger-benjamin** [comment]
@ybolognini I just checked and all is done.
