### ISSUE TITLE
Always use "::" CSS3 pseudo-element syntax instead of ":"

### ISSUE THREAD

**Issue by olivierSemet** [camptocamp/ngeo#1165]
Review all *.less of the project for chasing the old pseudo element syntax

**Comment by sbrunner** [comment]
... What's the deference?
Have you a link to the doc?

**Comment by olivierSemet** [comment]
This is a specification from CSS3. For compatibility reason ":" is also valid but in order to differentiate pseudo-element and pseudo-class, CSS3 introduced the "::" syntaxe 

more on [](https://developer.mozilla.org/fr/docs/Web/CSS/Pseudo-%C3%A9l%C3%A9ments)  

@pgiraud and I would like to refactor less files.

**Comment by sbrunner** [comment]
OK, thanks :-)
