### ISSUE TITLE
Draw feature improvements

### ISSUE THREAD

**Issue by fredj** [camptocamp/ngeo#1178]
- [ ] -todo- the length and area should be formatted (34'000 instead of 34000)
 - [x] -todo- the move icon should be on top (above the feature and the label) #1196 
 - [x] -todo- recenter the view to the selected feature (when a feature is selected in the list)

**Comment by ger-benjamin** [comment]
> the length and area should be formatted (34'000 instead of 34000)

Use the "number" filter for that: https://docs.angularjs.org/api/ng/filter/number

**Comment by adube** [comment]
>Use the "number" filter for that: https://docs.angularjs.org/api/ng/filter/number

I don't think we'll be able to use those methods in there.  The format methods are withing OpenLayers-oriented code, so we can't inject Angular stuff in there.

**Comment by ger-benjamin** [comment]
Oups, you're right ! I've don't think that we are not in a Angular component

**Comment by adube** [comment]
@fredj My repository is up-to-date.  When I visit either the 'desktop' or 'desktop_alt' application and use `lang=fr`, the buttons in the draw feature tool are still in English.  What am I missing ?

**Comment by sbrunner** [comment]
You probably have some old  i18n files,
probably if you remove the files `.build/locale/*/LC_MESSAGES/demo.po` and build again it will works :-)

**Comment by adube** [comment]
Thanks, got it working.

**Comment by adube** [comment]
Okay, about this issue:

>if the lang is 'fr', the buttons (Liste, Exporter, Supprimer) should be on the same line

Would simply making the panel larger work ?  If I remember correctly, you wanted to change the font sizes, which may affect this too.  Should we wait until that's done ?

**Comment by fredj** [comment]
Yes, we should wait for the font size correction

**Comment by pgiraud** [comment]
I just changed the last point.
WIKI page has been updated with the following detailed description: (https://github.com/camptocamp/c2cgeoportal/wiki/Spec-%231658-Measures-and-redlining)

> When selecting a feature clicking in items in the list, if the feature is not visible in the current view extent (even partially) the map should be centered (with pan animation) to the geometry (mid point for lines, interior point for polygons) with no zoom change.
> See example: http://plnkr.co/edit/KNTG7OqGZW2sdGbloubK

**Comment by adube** [comment]
@pgiraud, I have questions/suggestions:

1) I think the map should be centered when a partially visible feature is clicked from the map.  Imagine the scenario: a polygon is being partially shown, so you click on it from the map (not the list).  Unless the map gets panned, you can't fully see it.  I suppose it makes sense to make the map pan automatically.  Thoughts ?

2) Imagine the following scenario.  You have a polygon.  You zoom the map inside this polygon untill the map view is a 100% within it, i.e. you don't see any of its corners.  You click on it OR you select it from the list.  If we follow the spec, we do not zoom, nor do we pan I suppose.  The feature is selected, but we're not aware of it and unless we manually zoom out we can't really edit its geometry. What about this ?  Shouldn't we at least zoom out in those cases ?

**Comment by adube** [comment]
@pgiraud ping.

**Comment by ybolognini** [comment]
@adube @pgiraud 

Although I understand your concerns (problem with big polygon), I think we must keep it simple. Let's go for @pgiraud 's solution.

**Comment by adube** [comment]
You can check the 3rd checkbox. The task is now completed: https://github.com/camptocamp/ngeo/pull/1324

**Comment by fredj** [comment]
checkbox checked
