### ISSUE TITLE
layertree zoom to resolution issue

### ISSUE THREAD

**Issue by fredj** [camptocamp/ngeo#1195]
https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/desktop
 - click the "zoom to scale" icon for the "OSM scale" layer
 - `map_zoom` is `undefined` in the permalink

**Comment by pgiraud** [comment]
Has something changed? It doesn't seem to be an issue any more.

**Comment by sbrunner** [comment]
I have the issue ...
