### ISSUE TITLE
Search - Add layer don't enable the layer

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/ngeo#1220]
* Search for Police
* Select it in Add layer

=>

* The group is added as expected
* The layer Police isn't enable, he should be
* The layer Fuel is enable, he shouldn't

**Comment by marionb** [comment]
I can not reproduce this behaviour in the current version. The layer police is correctly added (there is no layer fuel in the group).

@sbrunner I will close this issue.

**Comment by sbrunner** [comment]
No:
- [ ] police is not selected if the group is already added ans the layer not selected,
- [ ] All the other layers should be deselected it the group is not already present...
