### ISSUE TITLE
Message "Webseite wurde neu geladen..." iOS (on BL instance)

### ISSUE THREAD

**Issue by vvmalbre** [camptocamp/ngeo#1233]
When testing, iOS several times gave the following message:
"Die Webseite wurde neu geladen, damit es ein Problem damit gab".
I don't have any specific workflow to reproduce it, but when "playing" with the application it happens quite often.
(I think this happens only on the BL instance)

**Comment by ger-benjamin** [comment]
@ybolognini @vvmalbre  I can't reproduce this bug...
I've tested with iPhone 5S (os7, safari) on Browserstack. Can I have more precision on this problem ?

**Comment by sbrunner** [comment]
To test again on 2.1

**Comment by vvmalbre** [comment]
I tested on https://geomapfish-demo.camptocamp.net/2.1/mobile.
While I was loading different themes and layers the same message appeared twice again (it doesn't happen too often but still seems to happen sometimes).

**Comment by marionb** [comment]
I can not reproduce this issue. 

Testing with:
* iPad iOS 9.3 with Safari 9 (live)
* iPod iOS 9.3 with Safari 9 (live)
* iPhone iOs 8.1 with Safari 8 (Browserstack)

I loaded different themes and activated/deactivated layers.

**Comment by marionb** [comment]
I re-tested and still can't reproduce this issue.

**Comment by ybolognini** [comment]
@vvmalbre 
Please give us more details to reproduce this

**Comment by vvmalbre** [comment]
I tested with iPad mini iOS 9.2 with Safari 9.
I cannot give you a workflow that reproduces the problem. I was loading themes / panning and zooming for about 10 minutes this morning and the problem happened only once. Seems better then when I tested last May and maybe we could set this issue back.
