### ISSUE TITLE
Result list closing when closing keyboard

### ISSUE THREAD

**Issue by vvmalbre** [camptocamp/ngeo#1235]
When typing a search string in the search field the results are opening in a list below. In my mobile phone (iOs) I only see 1.5 results in the list because the keyboard is open as well. When I close the keyboard the result list is eliminated as well --> should remain open.

**Comment by ger-benjamin** [comment]
That's an iPhone design problem. @ybolognini @sbrunner  I can keep the panel open as long as the search contains text. That resolve this problem but that's a change in the design.

So, the search field must : Close it on unfocus (current state) OR close it only when it is empty ?

**Comment by ybolognini** [comment]
@vvmalbre 
This problem is due to the fact that on iPhone focus is lost when keyboard is closed. We could change it but it would change behavior for all users including non-iPhone users. Note that this problem is also present when using Google Maps on Safari/iOS.

**Comment by sbrunner** [comment]
https://jira.camptocamp.com/browse/GSGMF-533
