### ISSUE TITLE
Query a WMTS layer (background or overlay)

### ISSUE THREAD

**Issue by gnerred** [camptocamp/ngeo#1238]
Is there a doc to configure querying on WMTS background layers ?

**Comment by sbrunner** [comment]
https://camptocamp.github.io/c2cgeoportal/master/integrator/ngeo.html?highlight=background#background-layers
and
https://camptocamp.github.io/c2cgeoportal/2.0/administrator/administrate.html#wmts-layer

**Comment by gnerred** [comment]
Isn't the "layer" property of WMTS layer used for printing ? Or it is only used for query ? Because for a WMTS layer we don't have the same layers for printing as for querying.

**Comment by gnerred** [comment]
No (I answer myself...), the layer property is used to define the WMTS layer. So I don't see where to configure layers that have to be queried for a backgroundlayer ? Is it still possible ?

**Comment by sbrunner** [comment]
It should be but it's not already implemented ...

**Comment by gnerred** [comment]
Sorry @sbrunner, but it has to be in 2.0...

**Comment by sbrunner** [comment]
Same for printing...

**Comment by gnerred** [comment]
If it is not implemented in 2.0, nobody would be able to put 2.0 in production

**Comment by sbrunner** [comment]
ping @ybolognini

**Comment by gnerred** [comment]
In all our portals, the backgroundlayer "Plan cadastral" is queried to get informations on parcels (owner, etc.). Ping @rbovard @mkalbermatten

**Comment by sbrunner** [comment]
This functionality is not in the sencha touch application ...

**Comment by gnerred** [comment]
Yes it is... Not for an overlay, but for a background layer. The original title of the issue did not contain "overlay".

1°/ Go to https://map.cartoriviera.ch/mobile/?theme=default_mobile&baselayer_ref=plan_cadastral&map_x=555377.25&map_y=145140.5&map_zoom=9&tree_layers=
2°/ Click or tab on map

**Comment by sbrunner** [comment]
OK..., thanks for the link :-)

**Comment by rbovard** [comment]
I confirm that we need to query the backgroud WMTS layer (I also see a PR fixing this, so I think it will be ok)

**Comment by sbrunner** [comment]
We will do it in 2.0 :-)

**Comment by gnerred** [comment]
Thanks :O)
