### ISSUE TITLE
WMS-time support

### ISSUE THREAD

**Issue by fredj** [camptocamp/ngeo#1241]
Spec: https://github.com/camptocamp/c2cgeoportal/wiki/Spec-%231708-Layertree-desktop#time-data
Doc: https://camptocamp.github.io/c2cgeoportal/master/integrator/wmstime.html

 * single date with a slider
 * single date with a date picker
 * date range with a slider
 * date range with two date picker

When a slider is used either:
 * min and max with an interval (step) date must be supported
 * list of values (dates) must be supported

When a date picker is used, min and max date must be supported.

Standard html5 input range can't be used but jQuery UI seems to have everything we need:
 * http://jqueryui.com/datepicker/ (https://github.com/angular-ui/ui-date)
 * http://jqueryui.com/slider/ (https://github.com/angular-ui/ui-slider)

The "time" configuration comes from the theme service, example:
```
time: {
  widget: "datepicker",
  maxValue: "2013-12-31T00:00:00Z",
  minValue: "2006-01-01T00:00:00Z",
  maxDefValue: null,
  minDefValue: null,
  resolution: "day",
  mode: "range"
}
```

**Comment by olivierSemet** [comment]
@fredj  I think the slider is ok for our needs but not the datepicker component. Regarding its documentation and the demo, I can't find the possibility of choosing 2 dates as a date range. Regarding the "osm_time" layer from the "OSM Function" theme used as sample for the demo app:

`time: {
    widget: "datepicker",
    interval: [
       0,
       1,
       0,
       0
    ],
    maxValue: "2013-12-31T00:00:00Z",
    minValue: "2006-01-01T00:00:00Z",
    maxDefValue: null,
    minDefValue: null,
    resolution: "day",
    mode: "range"
}` 

the last parameter "mode", when is set to "range", the spec is clear:

> The range mode displays a widget to select a time range. For a slider widget, a slider with two thumbs is shown. For the datepicker widget, two datepicker fields are displayed to select the start and end date. In mode range the layer will display data that is relative to the defined range.

**Comment by olivierSemet** [comment]
@ybolognini @fredj  this issue can be closed
