### ISSUE TITLE
A MIXED_GROUP can't have any sub groups.

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/ngeo#1248]

**Comment by olivierSemet** [comment]
@sbrunner I can't build the 2.0, compile-css does not work and 
`    <script src="/@?main/js/controller.js"></script> 
`
does not point to the right path

**Comment by sbrunner** [comment]
The path issue will be fixed with:  #1278
I don't succeed to reproduce the `compile-css` issue, do you try a `make cleanall`?

**Comment by olivierSemet** [comment]
yes a 'cleanallcache'

**Comment by olivierSemet** [comment]
@sbrunner  more info:

> (node:47511) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.

**Comment by olivierSemet** [comment]
@sbrunner It was my nodejs version. It's ok now.

**Comment by ybolognini** [comment]
@sbrunner will remove mixed attribute for sug-groups (not level 1)
@sbrunner will add an exemple in the demo of mixed group inside a mixed group
@olivierSemet will correct client side

**Comment by olivierSemet** [comment]
@sbrunner there is a problem:
IF _you remove mixed attribute for sug-groups (not level 1)_
THEN you can't _add an exemple in the demo of mixed group inside a mixed group_

because mixed group in mixed group will have no sens anymore
