### ISSUE TITLE
Could not connect...

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/ngeo#1250]
The message « Could not connect. » is not user friendly... shouldn't be something like « Wrong user name or password. »?

**Comment by adube** [comment]
Would you please define the exact sentence to use ?

**Comment by sbrunner** [comment]
@pgiraud , @ybolognini is the sentence « Wrong user name or password. » ok?

**Comment by ybolognini** [comment]
Maybe "Incorrect username or password". What do you think @adube ?

**Comment by adube** [comment]
>"Incorrect username or password"

+1
