### ISSUE TITLE
Drawing tools - It's impossible to cancel current drawing

### ISSUE THREAD

**Issue by pgiraud** [camptocamp/ngeo#1251]
If there's a drawing tool selected, it's impossible (or at least not easy) to cancel the activation of the tool.
It's even more an issue when an other element is already selected if the user clicks on "delete" the selected element is removed and the drawing tool is still selected.

I think that the selection should be dismissed if a drawing tool is selected.
Also I think that the drawing tool should be deactivated if the user click on the "esc" key.

**Comment by sbrunner** [comment]
https://jira.camptocamp.com/browse/GSGMF-534
