### ISSUE TITLE
Test feedback: check this and add issues if needed

### ISSUE THREAD

**Issue by ybolognini** [camptocamp/ngeo#1254]
from @vvmalbre
tested on https://geomapfish-demo.camptocamp.net/bl20/wsgi/mobile

1)

>> ·         I cannot activate all tree items; f.e. I’m not able to click on
>> the group Böden à Schutzbedürftige Böden or Naturgefahren à
>> Naturgefahrenkarte or Archäologie à Schutzzonen to display its content
>> in the map
>
> Not sure I understand. You mean you cannot activate the layer or you can
> activate it but the data isn't displayed?
>
> [ra] Both are groups. I cannot activate them and thus not display them. I
> can activate the whole group “Naturgefahren” or just one layer, f.e.
> “Subzonen”. But as I mentioned, it’s not possible to activate f.e.
> “Naturgefahrenkarte”.

2) 

>> ·         The “I” button is very hard to catch. And as for now, when using
>> the “I”-button, the viewer is loaded as it is in a new tab. No
>> metadata is shown.
>
> Could you please give me an example of layer with metadata so I can check?
>
> [ra] Example: Kulturobjekte à Inv. der geschützten Kulturdenkmäler

3) 

>> ·         On Android the results sometimes appeared and closed again.
>
> Could you tell me more?  They simply appear and disappear?
>
> [ra] Right.

**Comment by sbrunner** [comment]
1) On with theme ?
3) I get an error 500 on the service ...

**Comment by sbrunner** [comment]
@ger-benjamin can you fix the demo?

**Comment by ger-benjamin** [comment]
1) :arrow_right: in progress in https://github.com/camptocamp/ngeo/issues/1265

2) :arrow_right: https://github.com/camptocamp/ngeo/issues/1261 (will be done in 2.1)

3) :arrow_right: I can't reproduce that. I need more informations.

**Comment by ybolognini** [comment]
Dispatched in #1265 #1261 #1379
