### ISSUE TITLE
When we receive an error we should not redirect to donload the pdf ...

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/ngeo#1260]
We should display en error message and log the error?

**Comment by pgiraud** [comment]
So it looks like what happens is that the server may try to create the report, and finally send a "done" status report but with an "error" inside.

The response may look like this:
```js
{
done: true,
status: "error",
elapsedTime: 5936,
waitingTime: 0,
error: "org.apache.http.client.ClientProtocolException: URI does not specify a valid host name: file:///north.svg",
downloadURL: "/print-pgiraud/print/report/4f302ff3-5ccf-47fe-95de-172e1d770661@20981655-b95a-44f9-9995-84ad134f795c"
}
```

Currently the client code doesn't take that into account and considers it as a success creation response.
