### ISSUE TITLE
The metadata icon is too small

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/ngeo#1261]
from @vvmalbre #1254
tested on https://geomapfish-demo.camptocamp.net/bl20/wsgi/mobile

>> ·         The “I” button is very hard to catch. And as for now, when using
>> the “I”-button, the viewer is loaded as it is in a new tab. No
>> metadata is shown.
>
> Could you please give me an example of layer with metadata so I can check?
>
> [ra] Example: Kulturobjekte à Inv. der geschützten Kulturdenkmäler

**Comment by ger-benjamin** [comment]
> The “I” button is very hard to catch.

That's more a design problem. What can I do @pgiraud @ybolognini  ?

**Comment by ger-benjamin** [comment]
> the “I”-button, the viewer is loaded as it is in a new tab. No
metadata is shown.

@sbrunner the metadata url is filled with html (not a link, direct html). Is that a feature supported in 1.6 ? It seems not.

**Comment by ybolognini** [comment]
Will be done in 2.1 (layout harmonization) 
https://github.com/camptocamp/c2cgeoportal/issues/2022
