### ISSUE TITLE
Refactor all gmf examples to include new angular-ui dependencies 

### ISSUE THREAD

**Issue by olivierSemet** [camptocamp/ngeo#1274]
We included new dependancies to gmf in order to handle time selection for WMS layers #1241 

This will add two dependencies for the gmf angular module:

- 'ui.slider' for the slider
- 'ui.date' for the datepicker

The module declaration will be:
`gmf.module = angular.module('gmf', [ngeo.module.name, 'gettext',
    'ngAnimate', 'ngTouch', 'ngSanitize', 'ui.date', 'ui.slider']);`

Therefore all examples using the gmf angular module should be able to retrieve those modules.

**Comment by sbrunner** [comment]
Reopen because I add some questions in the pull request ...

**Comment by olivierSemet** [comment]
@sbrunner is good with the PR #1241 ?

**Comment by sbrunner** [comment]
I don't see any relation with this issue?

**Comment by sbrunner** [comment]
`contribs/gmf/third-party/jquery-ui/jquery-ui.min.js` steal missing in the gmf examples...

**Comment by olivierSemet** [comment]
You mean mean in hosted examples?

jquery-ui is copied to the lib folder as the others dependencies:

>.build/examples-hosted/lib/jquery-ui.min.js: contribs/gmf/third-party/jquery-ui/jquery-ui.min.js
	mkdir -p $(dir $@)
	cp $< $@
.build/examples-hosted/lib/jquery-ui.min.css: contribs/gmf/third-party/jquery-ui/jquery-ui.min.css
	mkdir -p $(dir $@)
	cp $< $@
.build/examples-hosted/lib/images/: contribs/gmf/third-party/jquery-ui/images/
	mkdir -p $@
	cp -r $< $@

And path are changed:
> -e 's|third-party/jquery-ui/jquery-ui.min\.js|\.\./lib/jquery-ui.min.js|' \
-e 's|third-party/jquery-ui/jquery-ui.min\.css|\.\./lib/jquery-ui.min.css|' \ 

Is it still not good?

**Comment by sbrunner** [comment]
Yes it's good but it's done only for the apps, I think that we should do the same for the examples :-)

**Comment by olivierSemet** [comment]
You mean ngeo examples?
