### ISSUE TITLE
elements in background and theme selectors not correctly aligned

### ISSUE THREAD

**Issue by pgiraud** [camptocamp/ngeo#1303]
The image and text are not correctly aligned.
We should make it so it adapts to the size (or at least size ratio) of the images.
Suggestion: use flexbox display.
![screenshot from 2016-05-27 10 03 40](https://cloud.githubusercontent.com/assets/319774/15601955/bd4c8018-23f2-11e6-85ed-90a789896b19.png)

**Comment by ger-benjamin** [comment]
@pgiraud Is that not resolved with #1448 ?

**Comment by pgiraud** [comment]
Indeed. Closing.
