### ISSUE TITLE
Not possible to hide a group

### ISSUE THREAD

**Issue by pgiraud** [camptocamp/ngeo#1305]
This looks like a regression.
Clicking on the label (or state icon) of a group should toggle from visible/invisible (activated/deactivated).

An invisible group is correctly made visible when clicked.
However, a visible group cannot be made invisible. One need to hide every single layer in the group.

Seem to be the case for top level groups. The issue doesn't seem to apply to other groups.

**Comment by pgiraud** [comment]
I found an other weird behavior which may be related to the current issue.
The "OSM Time range picker" behaves incorrectly. It seems to be deactivated by default. But when activating it, it does correctly display on the map (blue points), but it's not visually active in the layer tree. Also it's then impossible to deactivate it.

**Comment by marionb** [comment]
I think this issue can be split up in to two parts:

1. Mixed groups containing WMTS layers are not selected/deselected as expected:  https://github.com/camptocamp/ngeo/issues/1424

2.  Groups consisting of WMS layers only: If the group contains a layers consisting of two layers (i.e two_layer) it is not removed from the tee. (An example showing this behaviour is the `OSM functions` group in the OSM theme)

**Comment by olivierSemet** [comment]
Update: 

1. WMTS layers not selected/unselected
 -  **Fixed** by PR #1437. 
 - #1424 is closed. 

2. The group contains a layers consisting of two layers 

 - There is an open issue #1504

**Comment by sbrunner** [comment]
For me yes...
