### ISSUE TITLE
Mobile application broken due to missing dependency

### ISSUE THREAD

**Issue by pgiraud** [camptocamp/ngeo#1319]
Error is the following: "Module 'ui.date' is not available!"

**Comment by pgiraud** [comment]
desktop_alt application is broken as well

**Comment by fredj** [comment]
desktop_alt is missing jquery-ui.min.js and jquery-ui.min.css

**Comment by olivierSemet** [comment]
WIP it will be fixed with the PR for #1241

**Comment by ger-benjamin** [comment]
@olivierSemet Please resolve it in another PR, I need the mobile interface to be clean ASAP

**Comment by ger-benjamin** [comment]
@olivierSemet Missing also in the `alt_desktop`

**Comment by olivierSemet** [comment]
@ger-benjamin  ok I'm working on it

**Comment by ger-benjamin** [comment]
Thanks :sunglasses:
