### ISSUE TITLE
Cannot build the project

### ISSUE THREAD

**Issue by olivierSemet** [camptocamp/ngeo#1330]
On upstream/master after 
> make cleanallcache check
...
make -f npm.mk install
> npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE
npm ERR! ngeo@2.1.0-dev.7 prepublish: `make -f npm.mk install`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the ngeo@2.1.0-dev.7 prepublish script 'make -f npm.mk install'.
npm ERR! This is most likely a problem with the ngeo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     make -f npm.mk install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ngeo
npm ERR! Or if that isn't available, you can get their info via:

@sbrunner

**Comment by pgiraud** [comment]
I've tested on my computer with exactly the same versions of node/npm and `make check` works correctly.

**Comment by olivierSemet** [comment]
Problem occurs only on mac because of the add of command "convert" in the Makefile
Fixed with 
> brew install imagemagick
