### ISSUE TITLE
Groups reorder enhancement - dashed zone at the bottom

### ISSUE THREAD

**Issue by pgiraud** [camptocamp/ngeo#1347]
This is a nice-to-have.
When dragging a group to the bottom, the dashed zone is displayed and then disappear forever. It should stay visible.

**Comment by olivierSemet** [comment]
The simplest solution is to increase the size of the sortable ul element. This works well (tested) but this solution implies that there is no other element under the layertree.

@pgiraud @fredj @ybolognini what do you think?

**Comment by pgiraud** [comment]
As far as I know, there shouldn't be any other element under the tree in left panel. At least for now.

**Comment by fredj** [comment]
As discussed with @olivierSemet we could increase the size of the sortable element only when a drag is in progress
