### ISSUE TITLE
datepicker images

### ISSUE THREAD

**Issue by fredj** [camptocamp/ngeo#1351]
The images for the datepicker are not present in the demo.
https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/desktop_alt

**Comment by olivierSemet** [comment]
@sbrunner 

Does the rule I add for that is not correct?

> .build/examples-hosted/contribs/gmf/build/images/: contribs/gmf/third-party/jquery-ui/images/
	mkdir -p $@
	cp -r $< $@

On my side make examples-hosted adds the missing folder

**Comment by sbrunner** [comment]
It looks looks correct but it don't works ...

**Comment by fredj** [comment]
The images are in the gh-pages branch but there's an extra `images` directory:
https://github.com/camptocamp/ngeo/tree/gh-pages/master/examples/contribs/gmf/build/images/images
