### ISSUE TITLE
Uniforms scaleselector, elevation and mouseposition.

### ISSUE THREAD

**Issue by ger-benjamin** [camptocamp/ngeo#1360]
Because: 
- `scaleselector` is old, doesn't use filter for scales, use partial with dropdown included and with one option to configure it (dropup).
- `mouseposition` use partial with dropdown but without any option to configure it.
- `elevation` doesn't include any partial so the dropdown is full configurable but the `index.html` is less compact.

The creation of dropdown should be discussed. For me the dropdown is never a part of one of these components but there are advantages to include them into the component directive. Perhaps a new "dropdown" directive can be useful for ngeo...

**Comment by gberaudo** [comment]
Too old.
