### ISSUE TITLE
Display contextual information on right click

### ISSUE THREAD

**Issue by ger-benjamin** [camptocamp/ngeo#1361]
Part of https://github.com/camptocamp/c2cgeoportal/issues/1668
Specs ? : https://github.com/camptocamp/c2cgeoportal/wiki/Spec-%231668-Map-(Info-bar)

 :warning:  Still to be designed ( @ybolognini )

**Comment by sbrunner** [comment]
replaced with https://github.com/camptocamp/c2cgeoportal/issues/2309
