### ISSUE TITLE
XSD parser

### ISSUE THREAD

**Issue by fredj** [camptocamp/ngeo#1368]
This task is needed by the editing interface.

Given an XSD document, build an html (with bootstrap) form.
The form must display the correct input type (date picker, combobox, text, ...) and perform the validation (required field, ...)

XSD example: 
 * https://geomapfish-demo.camptocamp.net/2.0/wsgi/layers/70/md.xsd
 * https://geomapfish-demo.camptocamp.net/2.0/wsgi/layers/71/md.xsd

**Comment by sbrunner** [comment]
@adube cam we close it?

**Comment by adube** [comment]
Not yet.  There are things remaining to do:

 * validation (PR waiting for review: https://github.com/camptocamp/ngeo/pull/1601)
 * datepicker (Work in progress, https://github.com/camptocamp/ngeo/pull/1630)

**Comment by sbrunner** [comment]
OK, thanks :-)

**Comment by pgiraud** [comment]
Bof validation and datepicker are now taken into account. Closing.
