### ISSUE TITLE
Upgrade to Bootstrap 4 an JQuery 3

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/ngeo#1374]
see: #1373, http://v4-alpha.getbootstrap.com/getting-started/download/#npm

**Comment by fredj** [comment]
+1

**Comment by ger-benjamin** [comment]
With an alpha ?
I like to be up to date with libraries but it is not too extreme ?

**Comment by sbrunner** [comment]
Not with an alpha, we will wait to have at lease an rc :-)

**Comment by fredj** [comment]
Please note that `less` support has been dropped in bootstrap 4 ! replaced by SCSS

**Comment by ybolognini** [comment]
In Jira
