### ISSUE TITLE
Some GMF examples are not displayed correctly

### ISSUE THREAD

**Issue by ger-benjamin** [camptocamp/ngeo#1377]
Updated 30 juni 2016
# Full list
## NGEO (js errors)
- [x] https://camptocamp.github.io/ngeo/master/examples/mapfishprint.html (issue on localhost only)
- [x] https://camptocamp.github.io/ngeo/master/examples/measure.html (issue on localhost only)
## GMF (js errors)
- [x] https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/backgroundlayerselector.html
## GMF (css errors)
- [x] https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/datepicker.html (issue on localhost only)
- [ ] https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/drawfeature.html
- [ ] https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/featurestyle.html
- [ ] https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/layertree.html
- [ ] https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/mapquery.html
- [ ] https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/mobilemeasure.html
- [ ] https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/timeslider.html (issue on localhost only)
- [ ] https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/wfs-permalink.html
## GMF (~~js and~~ (ok) css errors)
- [ ] https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/print.html

**Comment by olivierSemet** [comment]
There is an other issue on the same topic #930 
@sbrunner for the CSS problems, IMO it must be fixed by adding the style sheet of the directive into its example as mentioned in #930.

**Comment by ger-benjamin** [comment]
(Checklist updated after #1567 merge)

**Comment by gberaudo** [comment]
There is also the query window: close cross and result arrows:

- [ ] https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/displayquerywindow.html?lang=fr&map_y=169139&map_x=661549&baselayer_ref=map&tree_groups=Enseignement%2CLayers%2CTransport&tree_group_layers_Layers&map_zoom=0

**Comment by sbrunner** [comment]
Witch kind of css error?

**Comment by ger-benjamin** [comment]
These examples don't even work now...
Shouldn't we close this issue and open another one "Restore examples" ?

**Comment by ger-benjamin** [comment]
Too old. I close.
