### ISSUE TITLE
On Android the results sometimes appeared and closed again

### ISSUE THREAD

**Issue by ybolognini** [camptocamp/ngeo#1379]
```
    · On Android the results sometimes appeared and closed again.

Could you tell me more? They simply appear and disappear?

[ra] Right.
```

**Comment by sbrunner** [comment]
To test again on 2.1

**Comment by marionb** [comment]
I can not reproduce this. Tested with:
- https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/desktop_alt
- https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/desktop
- https://geomapfish-demo.camptocamp.net/2.1
on 
Samsung Galaxy Tab 4
