### ISSUE TITLE
The GetLegendGraphics is done on the layer name, not on the layers

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/ngeo#1386]
Legend and layer icon ...

See layers in temps OSM

**Comment by olivierSemet** [comment]
I think the problem come from:
https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/src/directives/layertree.js#L758
The node name is used instead of the 'layers' node parameter.
@ger-benjamin  is there a reason when you committed this line:
https://github.com/camptocamp/ngeo/blame/master/src/services/layerHelper.js#L270 
To use 'LAYER' instead of 'LAYERS'  for the query parameters?

**Comment by ger-benjamin** [comment]
I don't remember. I don't think so. If that works fine, use 'LAYERS'

**Comment by olivierSemet** [comment]
@sbrunner @ger-benjamin  no, if the parameter is 'LAYERS' it's doesn't work

> WMS server error. Mandatory LAYER parameter missing in GetLegendGraphic request.

Should I understand the we should create a request for each layer when a node is attached to multiple layers?

**Comment by olivierSemet** [comment]
This is weird, icon  for multiple layers attached to a node should be the same

**Comment by ger-benjamin** [comment]
I'm not sur what you want.
Image is always for one layer. For an icon, like for a legend.

**Comment by olivierSemet** [comment]
Agreed. But a "node.layers" property can be composed with multiple layers names. 
e.g take from example in the OSM theme, the layer "two layers". The node name is "two layers" and its node.layers property is "restaurant,cafe". For now the name property is used to fill the 'LAYER' query parameter which is incorrect (there is no layer named "two layers" on the server). So we have to change the behavior and take the property node.layers to fill the LAYER query param.

**Comment by ger-benjamin** [comment]
I don't have all metadata in head but for me:
 - the tree node  'restaurant' must take 'restaurant' as LAYER GET params.
 - the tree node  'cafe' must take 'cafe' as LAYER GET params.
 - the tree node  'Two layers' should not ask for a legend. (perhaps an icon, I don't know).

If it's not the case, that's an error.

**Comment by sbrunner** [comment]
For the layer icon we should get the first layer,
For the legend 3 choice:
- not supported, the administrator should gives a `legend` metadata
- we get the legend for the first layer
- we display two images...
