### ISSUE TITLE
GMF Datepicker is not well documented

### ISSUE THREAD

**Issue by olivierSemet** [camptocamp/ngeo#1390]
The gmf datepicker is not well documented and does not follow all the project conventions 

- [ ] Provide an exemple for the jsdoc 
- [ ]  Rename gmf.DatePicker to gmf.datePickerDirective
- [ ] Use gmfx.TimeProperty as type 
- [ ] Use record type for datepicker options

**Comment by olivierSemet** [comment]
@sbrunner could you assign me to this ticket?

**Comment by sbrunner** [comment]
Done :-)

**Comment by olivierSemet** [comment]
thanks
