### ISSUE TITLE
Query on layers that aren't selected

### ISSUE THREAD

**Issue by ybolognini** [camptocamp/ngeo#1392]
When a layer is deselected, query is still possible and gives results.

**Comment by pgiraud** [comment]
Here's what I understand after some investigation:
A group of "not" mixed type corresponds to an OL3 layer. If this layer is visible then the `query` loops over all the "source ids" that are set on the given layer.
The list of "source ids" is set at the initialization of the layer.
https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/src/directives/layertree.js#L217-L218
https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/src/directives/layertree.js#L877-L893

This means that the fact that leaves are activated or not in an non-mixed group doesn't have any influence on the query at all.

By the way, I was not able to find where the "querySourceId" property is used other than in the examples or tests.

**Comment by fredj** [comment]
> By the way, I was not able to find where the "querySourceId" property is used other than in the examples or tests.

Used here: https://github.com/camptocamp/ngeo/blob/master/src/services/query.js#L441
`this.sourceIdProperty_` == `

**Comment by pgiraud** [comment]
@fredj OK but where does the `set` happen?

**Comment by fredj** [comment]
There's no set for `querySourceId` only for `querySourceIds` !

@sbrunner, @ger-benjamin: do we need to support both `querySourceId` and `querySourceIds`?

**Comment by ger-benjamin** [comment]
I don't have touched this part of the code. So I don't know.
But I've never saw `querySourceId` only `querySourceIds` here: https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/src/directives/layertree.js#L218

**Comment by fredj** [comment]
It's a regression introduced in #706 (`validateLayerParams`)
