### ISSUE TITLE
Query box ower flowing the bottom of page on Samsung Tab 4

### ISSUE THREAD

**Issue by marionb** [camptocamp/ngeo#1393]
When showing the application in portrait format on the tablet the query box overflows the bottom of the page when all information is shown.

(This was tested on Chrome browser.)

**Comment by pgiraud** [comment]
![screenshot from 2016-06-15 10 59 43](https://cloud.githubusercontent.com/assets/319774/16073902/55c31ec0-32e8-11e6-8b92-22c404782d6f.png)

**Comment by pgiraud** [comment]
Fixed in 2.0.
