### ISSUE TITLE
Not possible to choose FTS search suggestions on IPod 5

### ISSUE THREAD

**Issue by marionb** [camptocamp/ngeo#1395]
Showing the application on the the device in landscape formate:
- When typing there is no suggestion (+ there is no space for a suggestion).
- When the keyboard is closes there is still no suggestion to choose from

The effect is that it is not possible to launch a search request

This works OK when the application is showing on the device in portrait format

(testes on safari browser)

**Comment by sbrunner** [comment]
To test again on 2.1

**Comment by marionb** [comment]
I retested this on GMF 2.1 and the search suggestion are available but they are covered by the keyboard so they can not be seen or selected. The issue seems to be more of a space problem on the screen of the iPod than a bug.


![image](https://cloud.githubusercontent.com/assets/1460598/21770947/b86f2da2-d685-11e6-9f94-6c07fd8a1b8a.png)

I don't know of any good way to avoid this, but if the device is turned 90° so it it is in portrait format the search suggestions appear properly.
