### ISSUE TITLE
Layers may appear and disappear

### ISSUE THREAD

**Issue by pgiraud** [camptocamp/ngeo#1408]
Step to reproduce:
 - open desktop application,
 - select OSM theme,
 - remove all the group but the first one (OSM function),
 - reload desktop application.

Behavior:
The disclaimers for OSM ("les contributeurs d'OSM") appear for 1s and disappear.

Expected behavior:
The disclaimers for elements that are not added to the tree should not be displayed at all.

Update: This is not only a matter of disclaimer. We also see that the groups/layers are added to the tree before they're removed.

![disclaimer](https://cloud.githubusercontent.com/assets/319774/16082663/87e23ed4-3312-11e6-9bf6-4a00a58c7675.gif)

**Comment by pgiraud** [comment]
There seem to be something wrong with the way the localStorage is used.
Here's a way reproduce:
 - load https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/desktop,
 - go to the local storage and remove everything,
 - load https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/desktop once again, -> OSM theme is chosen by default and 4 groups appear in the layertree,
 - change theme to "learning" -> 1 group appears in the layertree,
 - click on "information" to hide it,
 - load https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/desktop -> the groups for the OSM theme appear and are quickly replaced by a collapsed "Learning" group with one "bus stop" layer.

Even more weird, at this point, if one loads https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/desktop_alt, there are 6 groups, 2 of which are "Learning". One with 2 leaves, one with only "bus stops".

**Comment by sbrunner** [comment]
Actually I can't reproduce it now can we close it?

**Comment by pgiraud** [comment]
Yes we can. This has been fixed with @olivierSemet's work on application state (permalink + local storage).
