### ISSUE TITLE
elevation computed even if infobar is collapsed

### ISSUE THREAD

**Issue by pgiraud** [camptocamp/ngeo#1423]
In the case where the info bar is collapsed (closed) at first, the elevation service is requested.

**Comment by pgiraud** [comment]
Can be seen in the elevation example as well:
https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/elevation.html

The checkbox is not checked though elevation values are displayed.

**Comment by ger-benjamin** [comment]
If we just need to remove the hardcorded assigned value (true) here: https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/src/directives/elevation.js#L106

**Comment by pgiraud** [comment]
@ger-benjamin I agree. Will be fixed once #1428 is merged.

**Comment by pgiraud** [comment]
#1428 has been merged. Elevation not computed any more if info bar is opened. Closing.
