### ISSUE TITLE
Unable to select/unselect all nodes in a group if one of its children node oparates for a WMTS layer

### ISSUE THREAD

**Issue by olivierSemet** [camptocamp/ngeo#1424]
1. Go to https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/desktop/
2. Clear your localStorage and reload
3. Click on OSM Function group to unselect all nodes 

- All nodes are unselected except the last one (named "ch.astra.ausnahmetransportrouten"). This node has a WMTS layer configuration attached. The other nodes have a WMS configuration.

4. Click again on OSM Function

- None of the nodes are unselected 

5. Click on the last node of OSM Function to have all child selected

- All nodes except the last one are unselected

**Comment by olivierSemet** [comment]
It seems to be fixed by clearing the localStorage and reload

**Comment by olivierSemet** [comment]
As discussed with @sbrunner a node for a WMTS layer should have a parameter named 'layer'. This parameter is missing in the demo for the node "ch.astra.ausnahmetransportrouten"

<img width="521" alt="capture d ecran 2016-06-20 a 11 00 07" src="https://cloud.githubusercontent.com/assets/8366681/16189294/efa7c4ba-36d9-11e6-92aa-cfafc2716a5a.png">

**Comment by sbrunner** [comment]
Steel have an issue: 
- open https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/desktop_alt/?tree_group_layers_undefined=restaurant%2Ccafe&lang=fr&map_y=161315&map_x=535742&tree_groups=OSM%20functions&rl_features=Fa(5sed-7yfGgVquL4g_hpL24*9cLppAuvKm7Ck8KapDnfJ82F9jI8bGngHmgH9bG8jI92FmfJbpDj8Kn7CtvKqpA8cL34*gpL5g_puLhVruLgVgpL4g_8cL24*tvKppAj8Km7CmfJapD8jI82FmgH8bG8bGmgH82F8jIapDmfJm7Cj8KppAtvK24*8cL4g_gpLgVpuLhVruL5g_gpL34*8cLqpAtvKn7Cj8KbpDmfJ92F8jI9bGmgHngH8bG9jI82FnfJapDk8Km7CuvKppA9cL24*hpL4g_suLgVquLhVhpL5g_9cL34*uvKqpAk8Kn7CnfJbpD9jI92FngH9bG9bGngH92F9jIbpDnfJn7Ck8KqpAuvK34*9cL5g_hpL~l*true%27n*Circle%25201%27c*%2523DB4436%27a*0%27o*0.2%27m*false%27s*10%27k*1)&baselayer_ref=map&tree_group_layers_OSM%20functions=osm_time%2Cosm_time2&map_zoom=3&tree_enable_Layer%20with%20very%20very%20very%20long%20name=true&tree_group_layers_OSM%20two%20time=osm_time%2Ccafe%2Cosm_time
* Try to deselect `Temps OSM popup interval` unwork :-(
* Try to deselect `Temps OSM popup interval 2` ok
* Try to deselect `Temps OSM popup interval` ok

 `Temps OSM popup interval`  name: `osm_time_r_dp`, layer:`osm_time`.

 `Temps OSM popup interval 2`  name: `osm_time_r_dp_2`, layer:`osm_time2`.

**Comment by olivierSemet** [comment]
This is a regex problem when searching the layer name into the LAYERS parameters. 
`osm_time2` will return true when it searches `osm_time`. We need to specify more constraints for the regex. WIP.

**Comment by sbrunner** [comment]
Witch regex do you speak about?

**Comment by olivierSemet** [comment]
- https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/src/directives/layertree.js#L550

- https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/src/directives/layertree.js#L569

- https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/src/directives/layertree.js#L573

- https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/src/directives/layertree.js#L664

**Comment by sbrunner** [comment]
Shouldn't we work with a layer list?
