### ISSUE TITLE
mobile login and nav state

### ISSUE THREAD

**Issue by fredj** [camptocamp/ngeo#1450]
https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/mobile

Open the right nav, select login and login. The right nav closes.
When the rigth nav is opened again, the login panel is displayed; IMHO the "main" menu should be displayed instead (the menu with measure and login).

It's the same when a background layer is selected

What do you think ?

**Comment by pgiraud** [comment]
I agree with you for the login panel. There's a little chance that the user wants to logout immediately.
I'm not convinced for the background. I suspect the user may want to change the background once again.
Let's wait for other opinions.

**Comment by fredj** [comment]
yes, your're right about the background selector
