### ISSUE TITLE
Font-Awesome fonts are broken ?

### ISSUE THREAD

**Issue by ger-benjamin** [camptocamp/ngeo#1455]
Can someone confirm ?

Example: 
https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/layertree.html

**Comment by pgiraud** [comment]
Confirmed.

**Comment by fredj** [comment]
The fonts directories are wrong: https://github.com/camptocamp/ngeo/tree/gh-pages/master/examples/fonts
