### ISSUE TITLE
All theme layers are queried, even if they are not visible (checked)

### ISSUE THREAD

**Issue by gnerred** [camptocamp/ngeo#1466]
To reproduce : 

1°/ Go to https://preprod.cartoriviera.ch/v2/mobile/theme/amenagement_du_territoire?lang=fr&baselayer_ref=plan_cadastral_201605&map_x=554359&map_y=145481&map_zoom=11
2°/ Click on the building of parcel 491 -> layers not visible are queried

**Comment by gnerred** [comment]
Sorry, my project is down for the moment for some other reason...

**Comment by gnerred** [comment]
My project works again, to test if necessary

**Comment by pgiraud** [comment]
Duplicated. See #1392.
