### ISSUE TITLE
Query should be disabled when the redlining is open (and the print)

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/ngeo#1470]
- open the redlining
- try to select a feature => a query is done ...

**Comment by fredj** [comment]
instead of listening for click on map, an ol.interaction should be used (to be tested)

**Comment by sbrunner** [comment]
Initially we do this to manage those cases https://github.com/camptocamp/ngeo/pull/412
But I don't know what's the current status...

**Comment by sbrunner** [comment]
On cgxp we do this because if we don't disable the interaction we had issues ans issues ...

**Comment by fredj** [comment]
forget my comment about ol.interaction; it won't solve the issue
