### ISSUE TITLE
The time on a group is hidden when it shouldn't

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/ngeo#1492]
* Go to https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/desktop_alt/
* Add theme OSM
* Disable the layer or group restaurants

=> the icon is hidden event if the layer Temps OSM popup interval is visible ...

**Comment by olivierSemet** [comment]
@fredj what is the problem?

**Comment by fredj** [comment]
the pull request is merged; i accidentally clicked the revert button ...

**Comment by olivierSemet** [comment]
:)
