### ISSUE TITLE
Change background layer on user change

### ISSUE THREAD

**Issue by fredj** [camptocamp/ngeo#1496]

**Comment by ger-benjamin** [comment]
@sbrunner We have multiple possibility for the choice of the backgroundlayer. Can you confirm this priority list:

Check if:

 - There is a background in the permalink
 - If not, then:
 - There is a background in the current theme:
 - If not, then:
 - There is a background in the current user:
 - If not then: use the first available background in the theme.json server object.

**Comment by ger-benjamin** [comment]
Mhhh, my list doesn't make sens. The permalink as always a background layer (except the first time but you will have no user and no selected theme too).

So it must be skipped in some case.
See that in my PR (soon)
