### ISSUE TITLE
Not all the layers will be disable

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/ngeo#1504]
- Open the theme `OSM`
- Click on the `Functions OSM` to disable it
=> the layer `Café` will not be disable ...

**Comment by olivierSemet** [comment]
After some discussion with @pgiraud and @sbrunner, the following constraint on the server side will be added:

**Two nodes in a group cannot act for the same layer**

With this constraint, the issue raised by @sbrunner  regarding the layer `Café` should be resolved
