### ISSUE TITLE
Translation of FTS layers

### ISSUE THREAD

**Issue by rbovard** [camptocamp/ngeo#1506]
The layer name in FTS results is not translated.

![image](https://cloud.githubusercontent.com/assets/4549666/16515907/0f259792-3f75-11e6-98a1-1ef10e6aeab0.png)

**Comment by gnerred** [comment]
Backgroundlayers are neither translated. Is this the same problem ? Or do I have to open another issue ?

**Comment by sbrunner** [comment]
We leave it at the same issue :-)

**Comment by gnerred** [comment]
You can forget my previous message concerning backgroundlayers. They are correctly translated, the fault was on my fr.js file that was not updated.
