### ISSUE TITLE
Inactive layers are queried

### ISSUE THREAD

**Issue by rbovard** [camptocamp/ngeo#1508]
Steps to reproduce:
* https://geomapfish-demo.camptocamp.net/2.0/mobile/theme/Transport?lang=fr&baselayer_ref=map&map_x=507621&map_y=137829&map_zoom=18
* Activate layer parking and remember position of point
* Deactivate layer parking
* Click on the position on the point --> The layer is queried

**Comment by sbrunner** [comment]
Duplicate of #1392

**Comment by rbovard** [comment]
Thanks but it was merged in 2.1, no?

**Comment by sbrunner** [comment]
no (difficult to follow), it was merge on 2.0 here: https://github.com/camptocamp/ngeo/pull/1490 :-)

**Comment by rbovard** [comment]
Ah... So OK, thanks :)
