### ISSUE TITLE
Map rotation does not work on mobile devices

### ISSUE THREAD

**Issue by gnerred** [camptocamp/ngeo#1528]
If I open https://preprod.cartoriviera.ch/v2/mobile/ on a desktop PC, I am able to rotate the map with Alt+Shift. On my mobile devices (Galaxy S6 with Android 6 and Galaxy note with Android 5), I cannot rotate the map with my fingers. Maybe it is a general problem with mobile touch devices.

**Comment by fredj** [comment]
That's because the "pinch rotate" (rotate map with fingers) interaction is not added to the map:
https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/src/controllers/abstractmobile.js#L126

**Comment by ybolognini** [comment]
@gnerred 
During a PSC meeting we talked about the rotation. There were many questions (rotate, autorotate, north button) and we decided to deactivate rotation for now. See also https://github.com/camptocamp/c2cgeoportal/issues/1861
So the problem here is that rotation isn't deactivated on desktop.

**Comment by ger-benjamin** [comment]
Duplicate issue, use: #2126
