### ISSUE TITLE
problem with print extent on macbook pro retina

### ISSUE THREAD

**Issue by jaykayone** [camptocamp/ngeo#1533]
The extent of the map choosen on screen does not match the extent in the PDF when printing on a mac with retina display
<img width="646" alt="screen shot 2016-07-06 at 20 52 37" src="https://cloud.githubusercontent.com/assets/1518019/16631017/19c144f2-43bd-11e6-8b37-f69d38fd002c.png">

cf https://github.com/Geoportail-Luxembourg/geoportailv3/issues/1367

**Comment by pgiraud** [comment]
Actually, the same scale doesn't display the same mask on different screen (retina or not).
Retina on the left.
<img width="580" alt="capture d ecran 2016-07-28 a 13 34 32" src="https://cloud.githubusercontent.com/assets/319774/17211285/d500845a-54c8-11e6-959b-edb013dcd5d7.png">

**Comment by pgiraud** [comment]
I just checked geoAdmin and it does behave correctly (ie. same mask size on both screens).

**Comment by pgiraud** [comment]
The following pull request may help us.
https://github.com/geoadmin/mf-geoadmin3/pull/1359
