### ISSUE TITLE
If two identical layers are on the map, query doesn't work

### ISSUE THREAD

**Issue by ger-benjamin** [camptocamp/ngeo#1535]
Steps to reproduce:
- Open OSM theme
- Active at least two same layers in different groups. Like "osm_time_r_dp" in groupe "Layers" and groupe osm_function.
- Do a query on "osm_time_r_dp"
- Navigate between results (animation bug and errors in your console)

From where the bug come ?
 - In the ngeo query component, the component count all features from all layers source but keep and share only distinct sources (no multiple sources with the same id). The total number of features don't match with the reality. Difficulty, in this component, new sources (from others groups) can come later and the number of feature will grow even ifb these new sources will be not really added.
 - In the "displayquerywindow" component, the next/previous function rely on the counted number of features

**Comment by sbrunner** [comment]
https://github.com/camptocamp/c2cgeoportal/pull/2388

**Comment by sbrunner** [comment]
This will be forbidden with https://github.com/camptocamp/c2cgeoportal/pull/2388

**Comment by ger-benjamin** [comment]
Forbidden yes, but the "missscount bug" will always watching us.
Perhaps we can at least  add a comment somewhere ?
