### ISSUE TITLE
The sortable directive doesn't work on touch devices

### ISSUE THREAD

**Issue by elemoine** [camptocamp/ngeo#154]
Probably because the jQuery UI Sortable plugin does not support touch devices/events.

See http://camptocamp.github.io/ngeo/master/layerorder.html.

In my [dragdrop](https://github.com/elemoine/ngeo/compare/dragdrop) branch the `ngeoSortable` directive uses `goog.fx.DragListGroup` instead of relying on the jQuery UI plugin. And `goog.fx.DragListGroup` does support touch devices, although I still have `preventDefault`-related issues. See http://erilem.net/ngeo/dragdrop/layerorder.html for a version of the `layerorder` example based on that branch.

**Comment by asaunier** [comment]
Nice!

I have tested on iOS and Android using Browserstack: the whole page moves when you try to drag-drop a layer => it's a bit hard to use.

The red-square handles are not very intuitive (without the tip in the example, not sure a user will see that the layers may be re-sorted): would it be possible to make the whole layer section responsive to the touch event?

**Comment by elemoine** [comment]
> I have tested on iOS and Android using Browserstack: the whole page moves when you try to drag-drop a layer => it's a bit hard to use.

That's what I meant by `preventDefault`-related issues in my previous comment.

> The red-square handles are not very intuitive (without the tip in the example, not sure a user will see that the layers may be re-sorted): would it be possible to make the whole layer section responsive to the touch event?

Yes, it is.

**Comment by pgiraud** [comment]
@asaunier I agree that the red squares are not intuitive. I'd like to keep the target thing though because it's a good example on how to use it.
I'll provide a patch to change the styling in order to make it more obvious to users.

**Comment by pgiraud** [comment]
Done in https://github.com/camptocamp/ngeo/pull/158

**Comment by elemoine** [comment]
> I have tested on iOS and Android using Browserstack: the whole page moves when you try to drag-drop a layer => it's a bit hard to use.

Unfortunately, this is a bug in `goog.fx.Dragger`: https://github.com/google/closure-library/issues/162 and https://code.google.com/p/closure-library/issues/detail?id=382.

**Comment by elemoine** [comment]
I've created a PR to closure-library for this problem: https://github.com/google/closure-library/pull/405.

**Comment by petzlux** [comment]
I wanted to attack the Layer reorder functionality, but it seems to me like you are still working through issues with ngeo / closure  ? Shall I wait till you have fixed changes upstream ?

**Comment by elemoine** [comment]
> I wanted to attack the Layer reorder functionality, but it seems to me like you are still working through issues with ngeo / closure ? Shall I wait till you have fixed changes upstream ?

No, it just doesn't work on touch devices currently.

**Comment by elemoine** [comment]
https://github.com/google/closure-library/pull/405 now closed.

**Comment by pgiraud** [comment]
Excellent! Well done Éric.

**Comment by elemoine** [comment]
Except that someone reported that it doesn't work on iOS 8.

**Comment by elemoine** [comment]
@pgiraud, curious to know whether http://erilem.net/ngeo/layerorder-touch/layerorder.html works in iOS 8.

**Comment by pgiraud** [comment]
Though it's not easy to use, I'm able to reorder the layers using touch drag/drop on safari on iOS8.

**Comment by elemoine** [comment]
> Though it's not easy to use, I'm able to reorder the layers using touch drag/drop on safari on iOS8.

Yep, it's also uneasy to use on Android/Chrome and Android/Firefox, but it's a different issue from the one I was looking at. Thanks a lot for testing!
