### ISSUE TITLE
Impossible to display some results in the display query window

### ISSUE THREAD

**Issue by pgiraud** [camptocamp/ngeo#1559]
With the following url, query the single point in the middle of the map.

https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/desktop/?baselayer_ref=map&lang=fr&map_x=563990&map_y=139800&map_zoom=4&rl_features&tree_group_layers_OSM%20functions=cafe%2Crestaurant%2Ccafe%2Cosm_time%2Cosm_scale%2Cosm_open%2Crestaurant%2Ccafe&tree_groups=OSM%20functions%20mixed%2CLayers%2CGroup%2COSM%20functions&tree_group_layers_Group=osm&tree_enable_two_layers=true&tree_enable_osm_time_v_s=true&tree_enable_osm_time_v_dp=true&tree_enable_osm_time_r_dp=true

The query window counts 10 results though there seem to be only 7.

![screenshot from 2016-07-12 09 42 40](https://cloud.githubusercontent.com/assets/319774/16759039/485a6558-4815-11e6-96d9-cf9b93c22ba0.png)

**Comment by olivierSemet** [comment]
This buggy for any point with feature information attached to it. @pgiraud can you assign it to me?

**Comment by ger-benjamin** [comment]
Perhaps this issue is related: https://github.com/camptocamp/ngeo/issues/1535

**Comment by sbrunner** [comment]
This is the case when we have a layer in two efferent group ...:
https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/desktop/theme/OSM?baselayer_ref=map&lang=fr&map_x=563811&map_y=140050&map_zoom=7&rl_features&tree_group_layers_OSM%20functions&tree_groups=OSM%20functions%20mixed%2CLayers%2CGroup%2COSM%20functions&tree_group_layers_Group&tree_enable_two_layers=false&tree_enable_osm_time_v_s=false&tree_enable_osm_time_v_dp=false&tree_enable_osm_time_r_dp=true&tree_enable_osm_time_r_s=false&tree_enable_osm_scale=false&tree_enable_ch.astra.ausnahmetransportrouten=false&tree_enable_osm_open=false&tree_enable_Layer%20with%20very%20very%20very%20very%20very%20long%20name=false&tree_group_layers_Layers=osm_time

**Comment by ger-benjamin** [comment]
Closed With https://github.com/camptocamp/ngeo/pull/1561
