### ISSUE TITLE
The layer order is wrong in the getmap

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/ngeo#1570]
It should be inverted

**Comment by pgiraud** [comment]
Is it the same problem as exposed in #1510?

**Comment by sbrunner** [comment]
No, #1510 is about the group order, and this one the layer order on the map inside a group (mixed and non mixed).
Example URLs:
* https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/desktop_alt/?lang=fr&baselayer_ref=map&tree_groups=OSM%20functions%20mixed&map_x=646915&map_y=178710&map_zoom=4&tree_enable_osm_open=false&tree_enable_Layer%20with%20very%20very%20very%20very%20very%20long%20name=true&tree_enable_osm_scale=false
* https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/desktop_alt/?lang=fr&baselayer_ref=map&tree_groups=OSM%20functions&map_x=646915&map_y=178710&map_zoom=4&tree_group_layers_OSM%20functions=osm_time%2Csrtm
