### ISSUE TITLE
Wrong loading order

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/ngeo#1576]
- Draw a shape with an area > 1000m2 and less than 1km2 (e.g. 1500m2) 
- Display the area on the map

=> On the map we see `1 500 m2`

- Reload the application

=> On the map we see `1,500 m2` but it should be `1 500 m2`

- Open the redligning panel

=> On the map we see `1 500 m2`

**Comment by olivierSemet** [comment]
@sbrunner  I'll work on it

**Comment by sbrunner** [comment]
Thanks :-)

**Comment by olivierSemet** [comment]
The `formats.GROUP_SEP` change between the initialization phase (value is: `","`) and the running phase (value is: `" "`)

When features are retrieved from the localStorage/permalink and displayed, the local is not well initialized yet. That is why we first have `1,500 m2 ` and after, when the user select the feature from the list, the value change to `1 500m2`

**Comment by sbrunner** [comment]
Effectively, then how to fix it ... :-)
