### ISSUE TITLE
When mousing over a line, the square symbol is below the line

### ISSUE THREAD

**Issue by ybolognini** [camptocamp/ngeo#1580]
* Edit a redlining polygon
* Pass the mouse on a line
* The square displayed to add a vertex is below the line, it should be on top

**Comment by ybolognini** [comment]
Maybe the PR does fix that too, but the "move" and "rotate" symbols are also displayed below the geometry

**Comment by olivierSemet** [comment]
@ybolognini agreed the issue is more complex than I thought... I can change a little bit the code (playing with zIndex) to fix "move" and "rotate" also. But for a better solution, It will take time..

**Comment by ybolognini** [comment]
@olivierSemet "playing" with zindex sounds good if the result is what we want :)
