### ISSUE TITLE
When zoomed in, recentering on feature should also change zoom

### ISSUE THREAD

**Issue by ybolognini** [camptocamp/ngeo#1581]
- Zoom in
- Choose a relining feature in the list
- The map moves but doesn't zoom out

@sbrunner and I think that it should zoom out when the feature isn't entirely visible. To be discussed with @pgiraud

**Comment by sbrunner** [comment]
* If the geometry is partially visible
  * We should zoom out to be able to see the geometry entirely (about size, no zoom in).
  * We should pan the map horizontally the mot to make the geometry horizontally visible.
  * Same on vertically.
  * All the animation should play together.
* Else
  * We should zoom out to be able to see the geometry entirely (about size, no zoom in).
  * We should center on the geometry.

**Comment by ybolognini** [comment]
--> GMF 2.4
