### ISSUE TITLE
Drawin tool isn't deactivated when feature is selected

### ISSUE THREAD

**Issue by pgiraud** [camptocamp/ngeo#1590]
Procedure to reproduce:
 - draw a feature on the map,
 - activate a drawing tool,
 - select a feature by clicking on an item in the list.

The feature is selected and the drawing tool is still activated. It's then impossible to modify the feature's geometry.

**Comment by olivierSemet** [comment]
We may avoid this application state:
<img width="269" alt="capture d ecran 2016-07-21 a 11 01 17" src="https://cloud.githubusercontent.com/assets/8366681/17017159/85da8ae2-4f32-11e6-9cb0-6fdfbd446454.png">

Have the "edit feature panel" and the "drawing feature toolbox" together.

**Comment by olivierSemet** [comment]
Please assign it to me.
