### ISSUE TITLE
Inconsistent use of scope attributes

### ISSUE THREAD

**Issue by tsauerwein** [camptocamp/ngeo#1658]
For the query grid directive I have a boolean property `removeEmptyColumns` which should be set on the directive:

```
      <gmf-displayquerygrid gmf-displayquerygrid-removeemptycolumns="true" ....
      </gmf-displayquerygrid>
```

This property is set at the instantiation, changes to the controller property should not be propagated to the outside, and you should not be able to change it from the outside.

I took a look at existing directives and noticed that several ways are used to handle this case:

**Using $attrs**

[ngeo.Share](https://github.com/camptocamp/ngeo/blob/54c5693/contribs/gmf/src/directives/share.js#L72-L76) uses `$attrs` and compares the passed-in string:

```
this.enableEmail = $attrs['gmfShareEmail'] === 'true';
```

**Using `&?`**

[gmf.Print](https://github.com/camptocamp/ngeo/blob/45ee0e7a047fba09347ae2f06ad476378e93f67a/contribs/gmf/src/directives/print.js#L100) uses `'rotateMask': '&?gmfPrintRotatemask'` and calls the expression function:

```
this.rotateMask_ = this['rotateMask'] ? this['rotateMask']() : false;
```

**Using `=`**

[gmf.Search](https://github.com/camptocamp/ngeo/blob/a2361d0836ae1cbbb5d48f5b2b07472c6712573a/contribs/gmf/src/directives/search.js#L100) uses a bidirectional binding with `'clearbutton': '=gmfSearchClearbutton'`.

After checking the [documentation](https://docs.angularjs.org/api/ng/service/$compile), in my opinion the best solution would be to use `&` or `&?` (for optional attributes). A bidirectional binding like with `=` is not needed. Using `$attrs` requires to manually parse the value to get a boolean or number.

Any opinions?

**Comment by ger-benjamin** [comment]
+1 to use the `&` `&?` when possible.

I don't know the context for the ngeoShare but the ngeoSearch `clearbutton` example must clearly use the `&?` notation.

See also our documentation: https://github.com/camptocamp/ngeo/blob/master/docs/guidelines.md#avoid-two-way-bindings-when-not-needed

Plus, our documentation don't explain the `<` binding symbol (one way binding, since AngularJS 1.5, listen and affect only the scope with changes from outside of the scope).

**Comment by sbrunner** [comment]
I put it for 2.2 is it OK?

**Comment by sbrunner** [comment]
https://jira.camptocamp.com/browse/GSGMF-550
