### ISSUE TITLE
Layertree does not support Vector layers

### ISSUE THREAD

**Issue by ohvitorino** [camptocamp/ngeo#1684]
I am trying to add a Vector layer to the layertree component/directive, but I get the following error:

```
angular.js:13920 AssertionError: Failure: unsupported source type
    at new goog.asserts.AssertionError (http://localhost:10000/ngeo/ngeo-debug.js:4815:20)
    at Object.goog.asserts.fail (http://localhost:10000/ngeo/ngeo-debug.js:4932:9)
    at ngeo.decorateLayerLoading (http://localhost:10000/ngeo/ngeo-debug.js:109557:20)
    at new ngeo.LayertreeController (http://localhost:10000/ngeo/ngeo-debug.js:109831:5)
    at Object.invoke (http://localhost:10000/bower_components/angular/angular.js:4718:19)
    at $controllerInit (http://localhost:10000/bower_components/angular/angular.js:10354:34)
    at nodeLinkFn (http://localhost:10000/bower_components/angular/angular.js:9263:34)
    at http://localhost:10000/bower_components/angular/angular.js:9673:13
    at processQueue (http://localhost:10000/bower_components/angular/angular.js:16383:28)
    at http://localhost:10000/bower_components/angular/angular.js:16399:27
```

It seems to be due to a deliberate limitation in `ngeoDecorateLayerLoading` service.

```
if (layer instanceof ol.layer.Layer) {
    source = layer.getSource();
    if (source === null) {
      return;
    } else if (source instanceof ol.source.Tile) {
      incrementEvents = ['tileloadstart'];
      decrementEvents = ['tileloadend', 'tileloaderror'];
    } else if (source instanceof ol.source.Image) {
      incrementEvents = ['imageloadstart'];
      decrementEvents = ['imageloadend', 'imageloaderror'];
    } else {
      goog.asserts.fail('unsupported source type');
    }
...
```

The assertion error is thrown because I am trying to add a `ol.source.Vector` (used for GML, KML, etc).

Does this mean that a Vector layer will not be supported? Because if I make a new `else if` statement specific for a `ol.source.Vector` the layertree does not seem to have a problem with that.

Thanks

**Comment by ohvitorino** [comment]
Is no one using vector layers with the layertree?

**Comment by sbrunner** [comment]
Not actually ...

**Comment by ohvitorino** [comment]
In our team, we are using ngeo to build a map viewer that will work as a component for several websites. But some of the layers we need to show are only available as GML.
I would be happy to add this feature to the layertree. I made the necessary changes to the code locally in order to get the Vector layers to work and also tests. But I not sure if I need to add some incrementEvents and decrementEvents. Would anyone be able to give some input on this?

**Comment by ohvitorino** [comment]
While inspecting the code again, I could also change the LayertreeController to not try to decorate the layer if it's a Vector layer. I cannot really say which way is the best.

**Comment by ohvitorino** [comment]
Could anyone give some thoughts on these solutions?
Again, I would be happy to contribute to the project, and get this to work.

**Comment by ybolognini** [comment]
Is it still relevant?
