### ISSUE TITLE
Not possible to log-off on safari

### ISSUE THREAD

**Issue by marionb** [camptocamp/ngeo#1693]
After login in with the mobile application using safari (iPod and IPad) it is not possible to log-off there is an error message that keeps showing: `Could not log out`

**Comment by marionb** [comment]
Result from further investigations on this issue:
This is an issue that comes up when testing on localhost and on github pages and only with iOS. The more detailed error message is:
```
XMLHttpRequest cannot load https://geomapfish-demo.camptocamp.net/2.1/wsgi/logout. Origin https://camptocamp.github.io is not allowed by Access-Control-Allow-Origin.
```

**Comment by pgiraud** [comment]
This may not be related but while testing in safari (9.1 on browserstack), if I login first then reload the page, I'm not logged in anymore.

**Comment by pgiraud** [comment]
Also, the themes are not correctly updated after login. The list remains the same just as if the user was not logged in.

Cookies don't seem to be correctly sent along with requests.

**Comment by pgiraud** [comment]
After some more search on the web, I found that Safari has a conservative policy on cookie. In other words cookies are not allowed for cross domain requests unless the site was visited earlier by the user or if the user explicitly changes its browser preferences.

![screenshot from 2016-09-05 11 12 37](https://cloud.githubusercontent.com/assets/319774/18243158/25c7ff9e-735a-11e6-862f-fc4e6ddb68a9.png)

See http://apple.stackexchange.com/questions/229628/cookies-in-safari-private-browsing-with-iframes

**Comment by pgiraud** [comment]
I'd suggest we close this issue since this is specific to the gmf applications demos and should not append in GMF real applications.

**Comment by sbrunner** [comment]
@ybolognini for me we can close it :-)
