### ISSUE TITLE
Double text in query result

### ISSUE THREAD

**Issue by marionb** [camptocamp/ngeo#1694]
When sliding from one query result to the next one the title and the text of the next result covers the the text of the previous result. Then in a next step the previous result disappears and the next one shows properly.
This is happening on the mobile application for iPod Safari and iPad Safari and Chrome

**Comment by sbrunner** [comment]
In the search?

**Comment by marionb** [comment]
No when doing a query on the map features in the query result window (that opens at the bottom right of the page).

**Comment by ger-benjamin** [comment]
I confirm the problem on Ipad. You will need to slide right then left (or left then right) to see the animation glitch.

There is some code to avoid that so I don't have any idea why that doesn't works on Ipad:

(displayquerywindow, function `animate_`
````
  this.scope_.$evalAsync(function() {                                            
    this.animate++;                                                              
  }.bind(this));
````
