### ISSUE TITLE
Layer list is not updated after logging in editing tools

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/ngeo#1704]
I try to test the editing on theme Edit with the user demo without any success here: https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/desktop/index.html?lang=en&map_y=152500&map_x=617500&baselayer_ref=map&tree_groups=Edit&rl_features=Fa(s2q6-73uMd6vF56JsjNm5wF89gC1rG~n*Polygon%25203%27c*%2523DB4436%27a*0%27o*0.2%27m*true%27s*10%27k*1)&map_zoom=0&tree_group_layers_undefined=restaurant%2Ccafe&tree_group_layers_OSM%20two%20time=osm_time%2Ccafe%2Cosm_time&tree_group_layers_Edit=line%2Cpoint

**Comment by ger-benjamin** [comment]
I try it and edition works well...
That's just strange to must select the layer you want to edit before to click on one of the layer's 'feature.

(demo/edit/webkit)

**Comment by ger-benjamin** [comment]
I doesn't have any problem to edit/create/remove existing/new features. Can you be more precise @sbrunner ?

**Comment by sbrunner** [comment]
I don't reload the page, it shouldn't be required ...

**Comment by ger-benjamin** [comment]
Ok, thanks, now it's clear (and reproducible)

**Comment by sbrunner** [comment]
To reporduce:
- logout
- reload the application
- open the editing
- login
- open the editing

=> the layer list is empty ...

**Comment by adube** [comment]
@sbrunner Would you please assign this to me?

**Comment by sbrunner** [comment]
Done :-)

**Comment by pgiraud** [comment]
Seems related to https://github.com/camptocamp/ngeo/issues/1730

**Comment by adube** [comment]
Could the title of this task be renamed, please?  Something like:

_Layer list is not updated after logging in editing tools_

**Comment by adube** [comment]
Fixed by https://github.com/camptocamp/ngeo/pull/1735
