### ISSUE TITLE
The desktop page has an error in the console

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/ngeo#1718]

**Comment by sbrunner** [comment]
see also: https://travis-ci.org/camptocamp/c2cgeoportal/builds/153300226#L4148

**Comment by tsauerwein** [comment]
These scripts seems to be missing in the c2cgeoportal app:
https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/apps/desktop/index.html#L246-L247

**Comment by sbrunner** [comment]
I'm having a look, thanks @tsauerwein :-)
