### ISSUE TITLE
When a geometry is edited, changes are lost when clicking anywhere else

### ISSUE THREAD

**Issue by ybolognini** [camptocamp/ngeo#1720]
In Specs below, it is noted that when changes are made there is a warning if feature is going to be unselected:

https://github.com/camptocamp/c2cgeoportal/wiki/Spec-%231662-Editing

This doesn't work:
 * Select a feature
 * Edit it
 * Click anywhere else on the map

The same happens when adding a new geometry. New geometry is lost when clicking elsewhere.

**Comment by pgiraud** [comment]
Fixed in #1753.

**Comment by ybolognini** [comment]
Still to do:
 * [ ] Show same popup for click on Stop editing
 * [ ] Show same popup for change tool

**Comment by adube** [comment]
We have already opened seperate issues for those:

 * #1740 
 * #1741 

I think we can leave this issue closed.

**Comment by sbrunner** [comment]
Thanks @adube :-)
