### ISSUE TITLE
During edition, it is impossible to delete a vertex

### ISSUE THREAD

**Issue by ybolognini** [camptocamp/ngeo#1721]
It looks like single click to delete a vertex (like in redlining) doesn't work for editing.

**Comment by adube** [comment]
Clicking on a vertex removes it, like the redlining.  Am I missing something?

**Comment by sbrunner** [comment]
For me it's blinking, and the vertex steel be here...

**Comment by adube** [comment]
Okay, I see what you mean.  I'll take a look at it.
