### ISSUE TITLE
How to run the examples?

### ISSUE THREAD

**Issue by gberaudo** [camptocamp/ngeo#175]
From a fresh clone of ngeo, I run `make check serve` then open `http://localhost:3000/examples/measure.html`.

An alert box pops up with the following content:
`Main script not in manager paths: /home/gberaudo/dev/ngeo/measure.js`.

This error message comes from closure-util.

**Comment by elemoine** [comment]
Strange. What node version do you have?

**Comment by gberaudo** [comment]
It is version v0.10.25.

**Comment by elemoine** [comment]
All the examples do not work for you?

**Comment by gberaudo** [comment]
Indeed, I have the same issue with all examples.

**Comment by gberaudo** [comment]
There were two issues: referrer and npm config or cache.

First, closure util behaves differently depending on the referrer. As I always send target base site url, the server was looking for the sources in the wrong place: `/home/gberaudo/dev/ngeo/measure.js` instead of `/home/gberaudo/dev/ngeo/examples/measure.js`. Thanks @elemoine for spotting this.

The second issue only occurred when connecting to `localhost`. Deleting the ~/.npm and ~/node_modules and remaking from scratch ngeo fixed the issue. It might be related to my use of `npm config set prefix ~/.npm` to set a local prefix for using `npm link`.
