### ISSUE TITLE
Display modal after drawfeature

### ISSUE THREAD

**Issue by AnasELMALEKI** [camptocamp/ngeo#1763]
Hi,

I am now working on a hybrid application using ionic and AngularJS, the application is designed to collect data by drawing features on the map.

I found the fabulous ngeo library on Github, now I am able to draw features on the map, but, I need to automatically display a modal after  drawing the feature in which the user will put the attribute data in order to store the feature and its data in an SQLite database.

I will be glad if someone helps me on this, I've been stuck for a week on it.

**Comment by ybolognini** [comment]
Stalled.
