### ISSUE TITLE
Right click menu in redlining is overlaped

### ISSUE THREAD

**Issue by marionb** [camptocamp/ngeo#1778]
When right clicking on a redlining shape the menu that opens is covered by the coordinate pop-up that opens at the same time.

- Image from demo:
![geometryediting_githubexample](https://cloud.githubusercontent.com/assets/1460598/18157781/b7dd03fe-701f-11e6-98ed-03bab5f3e1b3.png)

- image from github example (desktop):
![geometryediting](https://cloud.githubusercontent.com/assets/1460598/18157793/cbcab384-701f-11e6-9609-333df4050095.png)

- image from github example (desktop_alt): This seems OK because coordinated do not show on right click
![geometryediting_desktopalt](https://cloud.githubusercontent.com/assets/1460598/18158032/e35fe446-7020-11e6-890a-cf0bf5c21584.png)

**Comment by pgiraud** [comment]
Duplicate for #1725.
