### ISSUE TITLE
Deactivating subgroup in layer-tree deactivates the whole layer group

### ISSUE THREAD

**Issue by marionb** [camptocamp/ngeo#1779]
Test:
- activate the group *Layer* (in OSM Theme)
- activate all the layers in that group *Layer*
- deactivate all the layers of the sub-group *Hobbies*

--> this deactivates all the layers in the group *Layers*

(Testing with the subgroup OSM time in the group OSM functions mixed does not show this behaviour.)

**Comment by sbrunner** [comment]
Fixed with layertree refactoring
