### ISSUE TITLE
Zoom not working on table in default tab

### ISSUE THREAD

**Issue by marionb** [camptocamp/ngeo#1783]
When a new query is opened with multiple tables in different tabs the `Zoom to` function does not work on the table that is shown in the default tab. The `Zoom to` only works when switching to another table. From that point on it works as expected on all tables in the different tabs

**Comment by sbrunner** [comment]
When there is more than one tab

**Comment by tsauerwein** [comment]
I can't reproduce. I did the following:

1. Click somewhere
2. Two tabs are shown in the grid.
3. I select a row.
4. I click on "Zoom to".
5. The map zooms to the feature.

**Comment by sbrunner** [comment]
@marionb are you able to reproduce it?

**Comment by marionb** [comment]
At the moment I can not reproduce it because on all of the sites I checked (demo an github examples) with Chrome (Ubuntu) and Firefoxe (Ubuntu and Windows10) I can not do a point nor box query. I am not sure if this is another ngeo issue or something else.

**Comment by sbrunner** [comment]
??? can you provide a permalink?

**Comment by marionb** [comment]
Links I tried:
- [demo](https://geomapfish-demo.camptocamp.net/2.1/s/4yIU)
- [desktop_alt](https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/desktop_alt/?baselayer_ref=map&lang=en&map_x=544078&map_y=154848&map_zoom=2&tree_group_layers_Enseignement=information%2Cbus_stop&tree_group_layers_Layers=sustenance%2Centertainment%2Cosm_time%2Cpost_office%2Cpolice%2Ccinema&tree_group_layers_OSM%20functions=aster%2Csrtm%2Chalf_query%2Csustenance%2Centertainment%2Cbank%2Cosm_open%2Cosm_scale%2Cosm_time2%2Cosm_time&tree_groups=Transport%2COSM%20functions%20mixed%2CLayers%2CGroup%2COSM%20functions%2CExternal%2CEnseignement)

**Comment by sbrunner** [comment]
Just un-check the external and it will work :-)

**Comment by marionb** [comment]
OK, thanks it is now working :) . 
And no I can not reproduce this any more. 
I guess we can close this issue.
