### ISSUE TITLE
Querying area with no feature leads to strange behaviour for layer group "Learning"

### ISSUE THREAD

**Issue by marionb** [camptocamp/ngeo#1786]
1. Case (fixed with #1848)
  - Add theme Learning
  - make a box query on some of the bus stop features
  - make a box/point query on an area with no features

  ---> Endless loop for search result

2. Case
  - Add theme Learning
  - make many point queries close to a bus stop feature so that no query result is found
  - make a point query on a bus stop feature so that a query result is found

---> the result in the result grid is perturbed (compare result grid in the image below)
![queryonlearninglayer](https://cloud.githubusercontent.com/assets/1460598/18168327/65e2d138-7055-11e6-9415-8c0062ab58aa.png)

**Comment by adube** [comment]
I'm currently unable to reproduce any of the described cases.  Could someone else try to see if she or he is able to reproduce the issues?  If so, then I would like to have more explanation how to reproduce them, please.

@sbrunner, would you please take care of this?

**Comment by sbrunner** [comment]
Unable to reproduce, @marionb can you test it again?

**Comment by marionb** [comment]
I can reproduce this. I also checker with @ger-benjamin who originally reported the issue and we could also reproduce it on his machine. 

-  I can reproduced the first part using used this [permalink](https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/desktop_alt/?lang=en&map_x=560193&map_y=141696&map_zoom=7&tree_groups=OSM%20functions%20mixed%2CLayers%2CGroup%2COSM%20functions&tree_group_layers_Layers=sustenance%2Centertainment%2Cosm_time%2Cpost_office%2Cpolice%2Ccinema&tree_group_layers_OSM%20functions=aster%2Csrtm%2Chalf_query%2Csustenance%2Centertainment%2Cbank%2Cosm_open%2Cosm_scale%2Cosm_time2%2Cosm_time) on Chrome and Firefox with the following steps:
 1. Do a point query on some of the green point.
  2. Do a box query

- The second part of the issue might be related to https://github.com/camptocamp/ngeo/issues/1833. It can be more easily reproducible on Chrome than Firefox although I have managed to see it appear on Firefox as well.

**Comment by adube** [comment]
@marionb Thanks for the clarifications.  I'm able to reproduce the issue described in the first part locally so I'll be able to debug.

For the second part, that looks related to #1833, indeed.  Let's see if the issue disappears once that is fixed.
