### ISSUE TITLE
Disclaimer does not show when layer is selected

### ISSUE THREAD

**Issue by marionb** [camptocamp/ngeo#1787]
The disclaimer only shows when the layer is added in the layer tree but not when the layer is selected.

**Comment by sbrunner** [comment]
Wainting on layertree refactoring ...

**Comment by fredj** [comment]
not related to the layertree refactoring; the gmf.DisclaimerController simply doesn't check the visibility of the ol3 layer

**Comment by sbrunner** [comment]
After layer tree refactoring should he relay do that?
For me he should catch the changes directly on the LayerTree ...

**Comment by adube** [comment]
@sbrunner and I discussed about this together.  The behavior in the previous 1.6 version of GMF was to show only a disclaimer when the layer gets added to the map, regardless of its visibility.  The disclaimer is also removed when the layer is removed from the map in 1.6.  The visibility of the layers don't affect the disclaimers.

The behavior described above for 1.6 is currently the same that we have 2.0+, i.e. the visibility of a layer doesn't currently affect the disclaimers.

I think it is safe to consider this issue as invalid.  If it is a requirement, then we'd need to discuss the exact behaviour wanted.  I suggest we close this issue for now and re-open a new one with more details if this becomes a requirement.
