### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by marionb** [camptocamp/ngeo#1801]
The following Functionalities are missing translations:

- [x] **Login**: The error messages are not translated
- [x] **Edit**: The tool tip containing instruction when editing a feature on the map
- [x] **Profile**: Instruction when clicking on the button "Draw a profile line"
- [x] **Search**:
  * The standard text in the search box is "Search" for de, en and fr
  * "Recenter To" is always displayed in English (maybe related to https://github.com/camptocamp/ngeo/issues/1764).

**Comment by tsauerwein** [comment]
I started working on it, the fix for the authentication directive is in [this branch](https://github.com/tsauerwein/ngeo/tree/missing-translations) if someone wants to continue during my absence.
