### ISSUE TITLE
The query tool is broken for all applications

### ISSUE THREAD

**Issue by tsauerwein** [camptocamp/ngeo#1829]
Seems to be related to the latest update of the demo server. E.g. the following request fails: https://geomapfish-demo.camptocamp.net/2.1/wsgi/mapserv_proxy?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetFeatureInfo&FORMAT=image%2Fpng&TRANSPARENT=true&INFO_FORMAT=application%2Fvnd.ogc.gml&FEATURE_COUNT=20&I=50&J=50&CRS=epsg%3A21781&STYLES=&WIDTH=101&HEIGHT=101&BBOX=631763.9999999999%2C187876.99999999997%2C633783.9999999999%2C189896.99999999997&LAYERS=bus_stop%2Cinformation&QUERY_LAYERS=bus_stop%2Cinformation

**Comment by sbrunner** [comment]
On the `desptop_alt` I see that on click but no query is send on box...

And on `desptop` no query send...

**Comment by sbrunner** [comment]
Was it working yesterday?

**Comment by tsauerwein** [comment]
I only tried yesterday after you've updated the demo server, and it didn't work then.

**Comment by sbrunner** [comment]
Finally the GetFeatureInfo don't work on Mapserver cluster layers ...

**Comment by ger-benjamin** [comment]
@sbrunner can we close or "labelize" this issue ?

**Comment by fredj** [comment]
too old, closing
