### ISSUE TITLE
Do not use id in MousePosition directive

### ISSUE THREAD

**Issue by adube** [camptocamp/ngeo#1841]
In the `gmf-mouseposition` directive, an element defined in its html template has an `id`, which gets used in the controller in a `getElementById.getElementById` to get the element.  That is not a good practice, as the id is unique and if one wanted to have 2 of these directives in the same page then that wouldn't work.

The task at hand is about fixing this issue.

**Comment by adube** [comment]
@gberaudo agrees, see: https://github.com/camptocamp/ngeo/pull/1816

**Comment by adube** [comment]
@sbrunner This issue is similar to #1842.  Would you like me to work on it too?

**Comment by sbrunner** [comment]
ok :-)

**Comment by adube** [comment]
Fixed by #1849.
