### ISSUE TITLE
Do not use id in GMF LayerTree directive

### ISSUE THREAD

**Issue by adube** [camptocamp/ngeo#1842]
In the `gmf-layertree` directive, some elements are created with an `id`, for example: legend nodes.  Other elements define `ng-click` directives, which use the above `id` to let the controller get the element.  That is not a good practice to do.  If one wanted to use 2 layer trees in the same page and both shared common layers, we would get unwanted errors.

The task at hand is about fixing these issues.

**Comment by adube** [comment]
Let's wait for the layer tree refactoring to be completed before working on this one: #1814.

**Comment by fredj** [comment]
id in html are for example `id="gmf-layertree-node-{{::layertreeCtrl.uid}}"` and `layertreeCtrl.uid` is unique.
we can guarantee that we wont have multiple elements with the same id.
