### ISSUE TITLE
Do not use id in GMF Share directive

### ISSUE THREAD

**Issue by fredj** [camptocamp/ngeo#1858]
See https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/src/directives/partials/share.html

The `id` are only used for the `label` `for` attribute but it can be simplified:

``` html
<label for="gmfShareInputShortLink" translate>Permalink</label>
<input type="text" class="form-control" id="gmfShareInputShortLink">
```

simplified:

``` html
<label translate>Permalink
  <input type="text" class="form-control">
</label>
```

See https://www.w3.org/TR/html4/interact/forms.html#h-17.9:
"To associate a label with another control implicitly, the control element must be within the contents of the LABEL element."

**Comment by pgiraud** [comment]
We'll have problems with the layout.

**Comment by sbrunner** [comment]
We should have a look when bootstrap 4 is out

**Comment by sbrunner** [comment]
https://jira.camptocamp.com/browse/GSGMF-551
