### ISSUE TITLE
Wrong layer group order

### ISSUE THREAD

**Issue by fredj** [camptocamp/ngeo#1884]
The first level groups in the layertree are inverted after a page reload:
 - https://geomapfish-demo.camptocamp.net/2.1/
 - reload the page

-> the layers are inverted (reload again to invert)

**Comment by fredj** [comment]
maybe fixed in #1867 (to be checked)

**Comment by sbrunner** [comment]
Not present on desktop alt ...

**Comment by sbrunner** [comment]
Fixed with layertree refactoring
