### ISSUE TITLE
The theme selector directive documentation should explain how to use it in flush or non flush mode

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/ngeo#1914]
https://camptocamp.github.io/ngeo/master/apidoc/gmf.themeselectorDirective.html

I try this to simplify it but it don't works ...
https://github.com/camptocamp/ngeo/commit/9eaa1dd7de5cabebf91a0a27b50ff68db3e7f4b4

**Comment by tsauerwein** [comment]
The flush mode is described in the docs for `gmf.TreeManager`, I added a reference (see https://github.com/camptocamp/ngeo/pull/1976).
