### ISSUE TITLE
Delay registration of layertree children in their parents

### ISSUE THREAD

**Issue by gberaudo** [camptocamp/ngeo#1921]
Currently the ngeo layertree directive registers on its parent in the controller (`this.parent.children.push(this)`).

This causes issues: the layer tree starts to be navigated before it is fully created.

Moving this code to a postlink function should ensure a layertree children are created.

**Comment by ger-benjamin** [comment]
> This causes issues: ...

For my understanding, do you have an example ?

**Comment by gberaudo** [comment]
Yes, @fredj found an issue with the code managing editable layers. The editable layers list is created before the full hierarchy of layertree directives is instanciated. As a workaround we added a setTimeout.

**Comment by sbrunner** [comment]
Does it steel valid?

**Comment by gberaudo** [comment]
Indeed we implemented a workaround for this.
