### ISSUE TITLE
Get the snapping config from the metadata

### ISSUE THREAD

**Issue by fredj** [camptocamp/ngeo#1923]
See https://github.com/camptocamp/ngeo/pull/1922/files/a51159347198ba323bedd34c94189a92befba95e#r81754029

**Comment by sbrunner** [comment]
see also: https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/src/services/snapping.js#L249-L264

**Comment by sbrunner** [comment]
Can it be closed?

**Comment by sbrunner** [comment]
featureNS: can be computed with the server type
        featurePrefix: can be computed with the server type
        geometryName: from metadata

**Comment by sbrunner** [comment]
https://jira.camptocamp.com/secure/RapidBoard.jspa?rapidView=283&view=planning&selectedIssue=GSGMF-488&versions=visible
