### ISSUE TITLE
Share warning is not accurate

### ISSUE THREAD

**Issue by pgiraud** [camptocamp/ngeo#1927]
I get a message telling that there is a lot of drawn elements which is not true (no drawn elements in my case).

![screenshot from 2016-10-05 10 04 08](https://cloud.githubusercontent.com/assets/319774/19105619/367ef414-8ae3-11e6-8124-f71cf70bd277.png)

**Comment by sbrunner** [comment]
For me it's fixed by don't put unwanted element in the permalink...
