### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/ngeo#1931]
This file is not visible in the documentation ...
https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/externs/gmf-themes.js

**Comment by ger-benjamin** [comment]
It is. But there is no link clear in the left menu.

Look at the end of the "global" page: http://localhost:3000/.build/apidoc/global.html#GmfThemesResponse

**Comment by sbrunner** [comment]
Is there a reason that we don't had a namespace in this file?

**Comment by ger-benjamin** [comment]
Not especially. What would you like ? "gmx" as the others ?

**Comment by sbrunner** [comment]
Yes (gmfx or gmf-themes) I suspect that with that it will directly be displayed in the menu :-)
