### ISSUE TITLE
Problem with translations

### ISSUE THREAD

**Issue by gnerred** [camptocamp/ngeo#1939]
In migration process, I use the command below to migrate my translation file : 

.build/venv/bin/l10nv1tov2 fr cartoriviera/static/js/Proj/Lang/fr.js cartoriviera/locale/fr/LC_MESSAGES/cartoriviera-client.po

In ngeo mobile application, only layer names are translated. Attributes and FTS headers are not translated. Can be reproduced on https://preprod.cartoriviera.ch/v2/mobile/ by querying or doing a search. In my cartoriviera-client.po file, only the first third part is translated, the rest (containing attributes and FTS) is commented (see below). Problem with l10nv1tov2  ?

```
msgid "zones_s"
msgstr "Zones de protection des eaux"

msgid "zones_s_sige"
msgstr "Zones de protection des eaux"

msgid "zones_tampon_bti"
msgstr "Zones tampon"

#~ msgid "00Abonnés"
#~ msgstr "SIGE Abonnés"

#~ msgid "00Chambre EU Montreux"
#~ msgstr "Chambre EU Montreux"

#~ msgid "00Dossiers BTI"
#~ msgstr "Dossiers BTI"
```

**Comment by sbrunner** [comment]
No, it's just that thoes string will not be used anymore :-)

**Comment by gnerred** [comment]
So translations are missing...

**Comment by sbrunner** [comment]
From where should they come from?

**Comment by gnerred** [comment]
They should come from original file .build/venv/bin/l10nv1tov2 fr cartoriviera/static/js/Proj/Lang/fr.js . For example in that file, I have this translation : 

"03adresse": "Adresse",

This translation is migrate like that in cartoriviera-client.po : 

#~ msgid "03adresse"
#~ msgstr "Adresse"

So the translation is commented... And the result in ngeo mobile is (translation is missing) : 

![image](https://cloud.githubusercontent.com/assets/1989467/19640418/dccb4306-99dc-11e6-8760-0e4d41cd42bb.png)

**Comment by sbrunner** [comment]
Thanks @gnerred , I will investigate :-)
