### ISSUE TITLE
Consider using Yarn as replacement for npm

### ISSUE THREAD

**Issue by tsauerwein** [camptocamp/ngeo#1945]
We often have problems with npm, this line in the [Makefile](https://github.com/camptocamp/c2cgeoportal/blob/a54f43254a1316ce6b5f84ebcb812dae835ee2f2/c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl#L933) is saying all:

```
$(NPM_CMD) install || sleep 20 || $(NPM_CMD) install || sleep 90 || $(NPM_CMD) install
```

We might give Yarn a try which aims to be a more reliable replacement for npm:
https://yarnpkg.com/

**Comment by tonio** [comment]
As a side note, those ugly tricks shouldn’t be necessary with recent node versions: see https://github.com/npm/registry/issues/10#issuecomment-217141066
