### ISSUE TITLE
A lot of examples are broken

### ISSUE THREAD

**Issue by ger-benjamin** [camptocamp/ngeo#1959]
Almost every example that using the gmf map directive are broken because we not provide the permalink, snapping and, or, ngeo featureoverlay manager.

But I wonder, did we really want to provide it every time ?

The probleme come from theses lines: https://github.com/camptocamp/ngeo/blob/283037d4e34f21f6bc032aef1a3439c4ac8a3827/contribs/gmf/src/directives/map.js#L68-L72

Why are we doing this ? Can we not instanciate the map for these component elsewhere ?

**Comment by fredj** [comment]
We should probably use an `$injector` and treat them as optional. What do you think?

**Comment by ger-benjamin** [comment]
Can we not just give the map to these components in the abstract / main controller file ?

**Comment by fredj** [comment]
> Can we not just give the map to these components in the abstract / main controller file ?

+1, and if we remove these three function call the ` gmf-map` will be useless ...
