### ISSUE TITLE
Cannot read property split of undifined

### ISSUE THREAD

**Issue by gnerred** [camptocamp/ngeo#1973]
js error "Cannot read property 'split' of undefined" on loading of https://preprod.cartoriviera.ch/v2/mobile/

**Comment by sbrunner** [comment]
this `source.wmsSource.getParams()['LAYERS']` is undefined here: https://github.com/camptocamp/ngeo/blob/master/src/services/query.js#L246 ...

**Comment by gnerred** [comment]
Should I do something on my side or is this an issue that will be fixed in a next version ?

**Comment by sbrunner** [comment]
It will be fixed in the next RC :-), Thanks @gnerred
