### ISSUE TITLE
Strange things in the permalink

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/ngeo#1987]
Like `...Bflex-direction%3Acolumn%3Bmin-height%3A0%7D.x-layout-fit.x-stretched%3E.x-layout-fit-item%7Bdisplay%3Aflex%3Bdisplay%3A-webkit-box%3Bdisplay%3A...`

related to: https://github.com/camptocamp/c2cgeoportal/issues/2610

**Comment by sbrunner** [comment]
Actually not able to reproduce it ...

**Comment by fredj** [comment]
I saw this type of params in the url when we used the lesscss javascript for the debug. This is not the case anymore.

we can close this issue

**Comment by sbrunner** [comment]
Behavior to have it:
* open http://geomapfish-demo.camptocamp.net/1.6/mobile
* open http://geomapfish-demo.camptocamp.net/2.1
