### ISSUE TITLE
Already loaded groups messages on application startup

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/ngeo#1988]
To produce:
- clear the localstorage
- go to https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/desktop_alt/

Result:
- Message: Transport Le groupe est déjà chargé.
- Loaded Group: Tansport

Expected result:
- No message
- Loaded Group: OSM theme

**Comment by ger-benjamin** [comment]
@sbrunner Do you think that there is a case on which we should see this message when we load a theme ? (Result will be easier to read if you say yes)

**Comment by sbrunner** [comment]
Yes if we load the theme manually :-)
