### ISSUE TITLE
The modal disclamer is not at the right place

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/ngeo#1989]
Step to produce:
- Open: https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/desktop_alt
- Select Theme OSM

Result:
=> box at the top-left

Expected result:
=> box at the center or whatever integrated with the application

**Comment by ger-benjamin** [comment]
`whatever integrated with the application` -> need spec

**Comment by sbrunner** [comment]
spec: https://github.com/camptocamp/c2cgeoportal/wiki/Spec-%231770-Modal-disclamer
