### ISSUE TITLE
The logic between modals and popups could be better

### ISSUE THREAD

**Issue by ger-benjamin** [camptocamp/ngeo#2010]
For now, we have:
- A ngeo popup directive (that are create by a ngeo popup service and based on a ngeo.popover directive).
- A ngeo modal directive

In a use case I've tried to display the disclaimer in a modal, but that's not easily possible for now because the scope is unreachable. So I've tried to transform a popup in a modal but the popup is not developed in this purpose and that need more development that expected.

These components should be simplified to be more usable, with a greater possibility to evolve.

Plus, perhaps that we could just have one "popup" component that can be "modal" instead to have two components to show a "popup".

See also: https://github.com/camptocamp/ngeo/issues/1357

**Comment by sbrunner** [comment]
Also contribs/gmf/src/directives/disclaimer.js  should be in ngeo...
