### ISSUE TITLE
[To discuss] Should we take more care on our watcher ?

### ISSUE THREAD

**Issue by ger-benjamin** [camptocamp/ngeo#2022]
I don't know if that can be a problem or not... From the doc:

> After a watcher is registered with the scope, the listener fn is called asynchronously (via $evalAsync) to initialize the watcher. In rare cases, this is undesirable because the listener is called when the result of watchExpression didn't change. To detect this scenario within the listener fn, you can compare the newVal and oldVal. If these two values are identical (===) then the listener was called due to initialization.

https://docs.angularjs.org/api/ng/type/$rootScope.Scope.

I already saw that in the doc but we have some watcher that ignore that. Is that a problem that we should solve ? (I currently don't have tested if we have useless call to our watcher functions)

**Comment by gberaudo** [comment]
- this is old;
- it does not seem to have been an issue;
- recent AngularJS versions have changed the way they call watchers.
