### ISSUE TITLE
ngeox.js and gmfx.js are not extern files ...

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/ngeo#2026]
move `externs/ngeox.js` to `src/typedef.js`,
and `contribs/gmf/externs/gmfx.js` to `contribs/gmf/src/typedef.js`.

**Comment by gberaudo** [comment]
If you don't pass the ngeox.js file as an extern to the compiler, the properties will be minified.

**Comment by gberaudo** [comment]
This recommendation is about function symbols, not about the options they take in parameter.
There is no guidance about how to handle options in this tutorial.
