### ISSUE TITLE
Weird alignment of search results

### ISSUE THREAD

**Issue by pgiraud** [camptocamp/ngeo#2043]
In both desktop and mobile applications, the results in the search are shifted to the right. Does someone a good reason for this? I can't easily find which commit(s) introduced this.

If there's no good reason to have this left space, I'd be in favor to remove it.

![screenshot from 2016-11-22 14 10 09](https://cloud.githubusercontent.com/assets/319774/20524974/846c61e8-b0bd-11e6-9b51-4832dfcedfa1.png)
![screenshot from 2016-11-22 14 10 31](https://cloud.githubusercontent.com/assets/319774/20524975/847d9a62-b0bd-11e6-8751-3fcc4edbdf51.png)

**Comment by fredj** [comment]
maybe the results must be aligned to the search text ?
