### ISSUE TITLE
User can launch a lot of print requests

### ISSUE THREAD

**Issue by pgiraud** [camptocamp/ngeo#2055]
Currently the users can click several times on the print button. This may result in a lot of print requests being sent to the service which may eventually kill the server.
To avoid this, we could disable the print buttons when a request is pending until either the response is received or an abort request is sent.

**Comment by sbrunner** [comment]
Or cancel the previus print...

**Comment by sbrunner** [comment]
It can't kill the server... because the jobs are queued :-)
