### ISSUE TITLE
JSTS doesn't work

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/ngeo#2066]
JSTS use OpenLayers, but he don't use the types...

Then we can't compile it with Google Closure Compiler...

Does the SIMPLE compilation mode will fix the issue?

**Comment by sbrunner** [comment]
Or should we export the OpenLayers @api? :-/

**Comment by gberaudo** [comment]
Yes.
Another approach is like you said, to create an export file with the OL3 parts we actually need.

**Comment by adube** [comment]
@gberaudo Would you please explain in more details what needs to be done?

**Comment by gberaudo** [comment]
All OL3 symbols actually used by JSTS (or the subset we intend to use) must be exported like this:
```
goog.provide('ngeo.jstsExports');
goog.require('ol.animation');
goog.exportSymbol(
    'ol.animation.bounce',
    ol.animation.bounce);
```

**Comment by adube** [comment]
Thanks for the explanation.  I'll begin working on this.
