### ISSUE TITLE
We should be able to compile even if external services don't work

### ISSUE THREAD

**Issue by ger-benjamin** [camptocamp/ngeo#2073]
In these examples:

 - examples/backgroundlayer.js
 - examples/backgroundlayerdropdown.js
 - examples/layerloading.js
 - examples/layerorder.js
 - examples/layervisibility.js

We use external server (http://demo.boundlessgeo.com/geoserver/wms and http://demo.opengeo.org/geoserver/wms)

If these external servers don't work, we can not longer compile ngeo...

**Comment by gberaudo** [comment]
Done, thanks.
