### ISSUE TITLE
dependencies versus devDependencies

### ISSUE THREAD

**Issue by elemoine** [camptocamp/ngeo#208]
In `package.json` we define `dependencies` and `devDependencies`. I think we need to be clearer on what needs to be a dependency and what needs to be a dev dependency.

For example, `d3.js` and `typeahead.js` are currently `devDependencies` while ngeo includes directives that depend on these librairies. So we may want to change them to regular `dependencies`.

**Comment by sbrunner** [comment]
Difficult to decide because we are so wide from this distinction...

**Comment by fredj** [comment]
dependencies is now empty
