### ISSUE TITLE
Desktop application not working on iPad3

### ISSUE THREAD

**Issue by marionb** [camptocamp/ngeo#2082]
The desktop application is not working properly on iPad 3 (tested on Safari browser using https://camptocamp.github.io/ngeo/2.1/examples/contribs/gmf/apps/desktop)
The main points that are causing issues is the right menu. 
- [x] Double touch is needed to open an element of the right menu which is not intuitive.
- [x] It is practically impossible to use the Draw & Measure tool as well as the edit tool.
- [x] For the Profile tool it is not possible to following the profile line on the map and hard to place a point on the profile graph.
- [x] When rotating the tablet the application layout shows some issues: elements start to overlap i.e the header overlaps the themes menu.

**Comment by fredj** [comment]
> Double touch is needed to open an element of the right menu which is not intuitive.

Same issue when selecting a drawing action (draw point, draw  line, ...)

**Comment by fredj** [comment]
> When rotating the tablet the application layout shows some issues: elements start to overlap i.e the header overlaps the themes menu.

no issue with master:
camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/desktop/
