### ISSUE TITLE
CSV export not working for Profiles

### ISSUE THREAD

**Issue by marionb** [camptocamp/ngeo#2083]
It is not possible to make a CSV export from the profile.
This issue occurred for:
- IE11 Win8.1
- Edge Win10
- Safari latest Mac El Cap.
- Chrome Samsung Galaxy Tab 4 (tested with https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/desktop)

**Comment by sbrunner** [comment]
It's working on Firefox 50 Ubuntu Xenial

**Comment by tsauerwein** [comment]
I can't reproduce with IE11/Win8.1, Edge/Win10 and Chrome/Samsung Galaxy Tab 4, but I am looking into the issue with Safari (https://github.com/eligrey/FileSaver.js/issues/215).

**Comment by ger-benjamin** [comment]
@ybolognini  I close and remove "Done" label.
