### ISSUE TITLE
Not possible to add new feature in edit interface

### ISSUE THREAD

**Issue by marionb** [camptocamp/ngeo#2084]
It is not possible to safe a new feature in the edit interface (editing the geometry and attributes of an existing feature is possible)
Tested with:
- IE 11 Win 8.1
- Edge Win10
- Safari latest Mac El Cap.
- Chrome Samsung Galaxy Tab 4

**Comment by sbrunner** [comment]
The editing tool shouldn't send Polygon(not multi) on layer with geometry type: `gml:MultiPolygonPropertyType`
