### ISSUE TITLE
Not possible to export KML on Windows

### ISSUE THREAD

**Issue by marionb** [camptocamp/ngeo#2085]
It is not possible to export a KML from the Measuring & Drawing tools using
- IE11 Win8.1
- Edge Win10

**Comment by tsauerwein** [comment]
I can't reproduce the problem. I tested with IE11/Win8.1 and Edge/Win10 on Browserstack, and in both cases a download started. Both for KML and GPX.

**Comment by marionb** [comment]
Note
I originally tested this on https://geomapfish-demo.camptocamp.net/2.1 where I still don't see the download starting. On https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/desktop_alt however it seems to be working.

**Comment by sbrunner** [comment]
We will testing again after updating the demo server :-)

**Comment by marionb** [comment]
I retested this for the following urls
- https://geomapfish-demo.camptocamp.net/2.1
- https://camptocamp.github.io/ngeo/2.1/examples/contribs/gmf/apps/desktop_alt
- https://camptocamp.github.io/ngeo/2.1/examples/contribs/gmf/apps/desktop
- https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/desktop_alt

on two different win10 (an asus tablet and a hp laptop) devices with the following result:

For Edge14:
1. The github.io examples generate downloads that are OK
2. The geomapfish-demo site does not generate a download (nothing happens when trying to download)

For Firefox50:
This is working fine for all urls and both devices that I tested on.

**Comment by llienher** [comment]
Works on the following urls:
