### ISSUE TITLE
Problem with background layers in ngeo mobile

### ISSUE THREAD

**Issue by gnerred** [camptocamp/ngeo#2105]
Version 2.1.0.dev25 

https://preprod.cartoriviera.ch/v2/mobile/

-> JS error (Cannot read property 'url' of undefined) and backgroundlayers are not loaded. Something is missing somewhere... Thanks.

**Comment by gnerred** [comment]
@sbrunner , is there a temporary solution or have I to wait next release ? Because with this issue, I cannot test the backgroundlayers querying. Thanks.

**Comment by fredj** [comment]
C'est peut être lié au [WMTS Capabilities](https://preprod.cartoriviera.ch/tiles/1.0.0/WMTSCapabilities_preprod.xml): apparemment OpenLayers n'arrive pas a trouver la projection dans le matrixSet parce que 'epsg' est en minuscule.

Il faut essayer de changer dans le WMTS Capabilities:
```
urn:ogc:def:crs:epsg::21781
```
en:
```
urn:ogc:def:crs:EPSG::21781
```

**Comment by gnerred** [comment]
Yes it works with this workaround, thanks @fredj

**Comment by fredj** [comment]
related to https://github.com/camptocamp/ngeo/pull/2025

**Comment by gnerred** [comment]
Version 2.1.2.dev1

When I do ./.build/venv/bin/generate_controller --capabilities, the capabilities file still contains epsg in lowercase... Reopen ?

**Comment by gnerred** [comment]
I confirm that it should be changed in config.yaml.mako ! Now it works, thanks
