### ISSUE TITLE
Problem with login in ngeo mobile, application not reloaded

### ISSUE THREAD

**Issue by gnerred** [camptocamp/ngeo#2111]
Version 2.1.0.dev25

https://preprod.cartoriviera.ch/v2/mobile/

Once logged, the application is not reloaded, and no secured layer is visible. Secured layers appear only after changing theme.

**Comment by sbrunner** [comment]
Hello,

I just test it, and:

* The applications shouldn't be reloaged as the CGXP application
* The theme is reloaded (with the user c2c)

=> I don't know witch new layer I should be be able to see, than I can't continue the test...

**Comment by gnerred** [comment]
You should see the layer "proprietes_communales_vevey" in theme "cadastre". To reproduce : 

1°/ https://preprod.cartoriviera.ch/v2/mobile/
2°/ Go to theme "cadastre"
3°/ Login -> the layer is not visible
4°/ Change theme and come back to theme "cadastre" -> the layer is visble
5°/ Logout -> the layer is still in theme "cadastre"
6°/ Change theme and come back to theme "cadastre" -> the layer disappeared

**Comment by sbrunner** [comment]
Thanks, reproduced (One of the concerne layer: `adresse`!)

**Comment by rbovard** [comment]
Related to #966?

**Comment by sbrunner** [comment]
Not exactly, #966 is about reloading the theme, this one is about updating the layers present in the LayerTree :-)

**Comment by pgiraud** [comment]
> Thanks, reproduced (One of the concerne layer: adresse!)

@sbrunner Did you manage to reproduce the issue in the GMF demo?

**Comment by ger-benjamin** [comment]
> Did you manage to reproduce the issue in the GMF demo?

Yes in the administration theme for instance (layer: firestations (no data I think, but it's enough to view the bug))
