### ISSUE TITLE
bindToController and scope

### ISSUE THREAD

**Issue by rbovard** [camptocamp/ngeo#2114]
In some directives, `bindToController`and `scope` are defined the old way:
* https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/src/directives/contextualdata.js#L52
* https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/src/directives/drawprofileline.js#L43
* https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/src/directives/search.js#L119
* https://github.com/camptocamp/ngeo/blob/master/src/directives/attributes.js#L31
* https://github.com/camptocamp/ngeo/blob/master/src/directives/drawfeature.js#L95
* https://github.com/camptocamp/ngeo/blob/master/src/directives/exportfeatures.js#L35

**Comment by gberaudo** [comment]
There is a difference in the way binding is declared between components (through the bindings property) and with directives (thourgh the bindToController property).

Please reopen if I misunderstood your point.
