### ISSUE TITLE
Query multiple polygons - Highlight issue

### ISSUE THREAD

**Issue by ger-benjamin** [camptocamp/ngeo#2117]
Project: All (tested on demo)

Permalink directly where we can reproduce the issue:
https://geomapfish-demo.camptocamp.net/2.1/theme/Edit?baselayer_ref=asitvd.fond_gris&lang=en&map_x=761841&map_y=192439&map_zoom=6&tree_enable_Layer%20with%20very%20very%20very%20very%20very%20long%20name=false&tree_enable_ch.are.alpenkonvention=true&tree_enable_ch.astra.ausnahmetransportrouten=true&tree_enable_ch.swisstopo.dreiecksvermaschung=false&tree_enable_ch.swisstopo.geologie-geotechnik-gk500-gesteinsklassierung=false&tree_enable_ch.swisstopo.geologie-geotechnik-gk500-lithologie_hauptgruppen=false&tree_enable_ch.swisstopo.geologie-gravimetrischer_atlas=false&tree_enable_osm_open=false&tree_enable_osm_scale=false&tree_enable_osm_time_r_dp=false&tree_enable_osm_time_r_s=false&tree_enable_osm_time_v_dp=false&tree_enable_osm_time_v_s=false&tree_enable_two_layers=false&tree_group_layers_External=ch.swisstopo.geologie-geotechnik-gk500-lithologie_hauptgruppen&tree_group_layers_Group&tree_group_layers_Layers=cinema%2Cpolice%2Cpost_office%2Cosm_time_r_dp%2Centertainment%2Csustenance%2Chospitals&tree_group_layers_OSM%20functions=osm_scale&tree_group_layers_Snapping=point%20snap%2Cline%20snap%2Cpolygon%20snap&tree_group_layers_Snapping%20no%20edge&tree_group_layers_Snapping%20no%20vertex&tree_group_layers_Transport=fuel&tree_opacity_osm_open=1&tree_groups=Edit

Steps to reproduce the issue:
 - Select (query) the polygon on Chur (Grisons)

Result:
 - Only one part of the polygon is highlighted

Expected result:
 - Both part of this multiple polygons should be highlighted
 - <s>OR: Splitting a polygon with the edit tool should create two separate polygon</s>

**Comment by pgiraud** [comment]
This is not ngeo's fault.
It's rather a matter of bad configuration of the mapfile in the demo.
https://github.com/camptocamp/demo_geomapfish/blob/master/mapserver/edit.map.mako#L133

**Comment by pgiraud** [comment]
Demo fixed. Closing.

**Comment by ger-benjamin** [comment]
Thanks @pgiraud
