### ISSUE TITLE
The gmfRasterUrl is missing in the mobile app

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/ngeo#2121]
for the mobile measure point...

missing here:
https://github.com/camptocamp/ngeo/blob/466d094144980aa0e4edc02cf59047261850b491/contribs/gmf/apps/mobile/index.html#L186

like here:
https://github.com/camptocamp/ngeo/blob/466d094144980aa0e4edc02cf59047261850b491/contribs/gmf/apps/desktop/index.html#L282

**Comment by sbrunner** [comment]
Should we relay provide default values that hide the missing required value?

**Comment by ger-benjamin** [comment]
> Should we really provide default values that hide the missing required value?

I'm not sur if I understand. In this case, the value is really required by the measure components. (And, in AngularJS, a value that is injected in a component should be always defined).

**Comment by sbrunner** [comment]
It's defined here https://github.com/camptocamp/ngeo/blob/28c6141d85741f94aaa19955b323efb231323c9a/contribs/gmf/examples/elevation.js#L19 and here https://github.com/camptocamp/ngeo/blob/9a2852407321cec34e1485ebb573649ffa1441c7/contribs/gmf/src/controllers/abstractmobile.js#L33, that make the demo working, but for me it should be removed...

**Comment by ger-benjamin** [comment]
First point link is done with my commit.
I'll do a second commit to move the constant into the html

**Comment by sbrunner** [comment]
The first link is in the examples then it's correct :-)
