### ISSUE TITLE
Print - Can't print svg symbols

### ISSUE THREAD

**Issue by ger-benjamin** [camptocamp/ngeo#2149]
The ngeo print service use "image/png" for png like for others symbole type. The result is that SVG can't be printed. (should be "image/svg" for svg)

Issue in these lines: https://github.com/camptocamp/ngeo/blob/a859f97ed0e411fc78598b4ba44bdd3c679e27b8/src/services/print.js#L614-L618

**Comment by ger-benjamin** [comment]
I think we don't want to wait on another http request on the src of the image to get the right mime-type. Perhaps we can search the information through he $cacheFactory with a fallback that use the extension of the file (like in https://www.npmjs.com/package/mime). We should create a Service to do that...

**Comment by ger-benjamin** [comment]
Perhaps we can do something `acceptable for now` (juste based on the extention of the src, in this print service) and something that we can use in all cases for the 2.2 ?

**Comment by sbrunner** [comment]
We should remove this parameter and do it directly in the print by getting the Content-Type header ...

**Comment by fredj** [comment]
@sbrunner can be closed ?

**Comment by sbrunner** [comment]
+1
