### ISSUE TITLE
On login / logout, visibility is not kept

### ISSUE THREAD

**Issue by ger-benjamin** [camptocamp/ngeo#2161]
Since 2.1 (see: https://github.com/camptocamp/ngeo/pull/2156)

Step to reproduce:
 - Set the visibility on a layer or a layer group
 - Login or logout
 - Visibility is lost.

**Comment by sbrunner** [comment]
Actually the visibility in only in the layer, and it should probably be moved in the layer tree nodes controllers.

**Comment by ger-benjamin** [comment]
Wait on: https://github.com/camptocamp/c2cgeoportal/wiki/Spec-%232804-Pre-defined-opacity-for-WMS-WMTS

**Comment by sbrunner** [comment]
Looks to be fixed
