### ISSUE TITLE
Desktop example broken since PR 2152

### ISSUE THREAD

**Issue by ger-benjamin** [camptocamp/ngeo#2173]
(Branch 2.1 !)
If I do a `make serve` with commits of this PR: #2152 
My browsers (chrome-based like firefox) crash.

**Comment by tsauerwein** [comment]
See https://github.com/camptocamp/ngeo/issues/2172

**Comment by ger-benjamin** [comment]
No, that's not related.
I've got back to node 4 and use the 2.1 branch. The crash is without error. Only an infinite loop or somethings like that somewhere.

**Comment by tsauerwein** [comment]
Indeed.
