### ISSUE TITLE
Modernisation of NGEO

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/ngeo#2180]
Ready for 2.2:
* [x] Use D3 version 4.x.
* [x] Use latest version of OpenLayers.
* [x] Use angular 1.6.

Ready for 2.3:
* [ ] Removes all `goog` (except `requires`, `provide`, `module`, `asserts`), `git grep goog src/ contribs/gmf/src/|grep -v 'goog\.require'|grep -v 'goog\.provide'|grep -v 'goog\.asserts'|grep -v 'goog\.module'|grep -v 'goog\.exportProperty'|grep -v 'goog\.exportSymbol'|wc -l` => 71.
* [ ] Use only one provide per file.
* [ ] stop using ol3 enums for events (eg: `'click'` instead of `ol.MapBrowserEvent.EventType.CLICK`)
* [ ] stop using `ol.Object.getChangeEventType`, use `'change': + xxx`

Ready:
* [ ] Use the components in place of the directives.
* [ ] Use the new module folder structure and stop registering stuff in `ngeo.module`.
* [ ] Switch to `goog.module`, it can be done automatically using https://github.com/gberaudo/googshift

Backlog:
* [ ] Use `for` `of` in place old `for` and `forEach`.
* [ ] In the file `contribs/gmf/src/directives/displayquerygrid.js` contains many brackets arguments :-(
* [ ] Use webpack to build the application
* [ ] Use angular 1.6 with angular 2.0?
* [ ] Use the es6 classes (Actually there is an issue with Firefox).
* [ ] Don't use dangerous type cast everywhere... actually `git grep '\/\*\* @type' src/ contribs/gmf/src/|grep -v ngeox|grep -v gmfx|grep -v olx|grep -v gmfThemes|wc -l` => 178...

**Comment by sbrunner** [comment]
See also: #2057

**Comment by fgravin** [comment]
I've tested a bit [lebab](https://lebab.io/#)

I tried the **class** upgrade, here the drawback:

1. Before lebab run 
- LIMITATION does not support namespaced classes (from lebab doc)
- So we must change the contructor declaration
`ngeo.ColorpickerController` -> var `ColorpickerController`

Then we can run `lebab src/directives/colorpicker.js -o src/directives/colorpicker6.js --transform class`

2. After lebab run
- we must move some jsdoc/closure annotations from class to constructor
```js
 * @param {angular.Scope} $scope Directive scope.
 * @param {angular.JQLite} $element Element.
 * @param {angular.Attributes} $attrs Attributes.
```

- need to remove the `@constructor` and `@struct` annotation.

Result is pretty ok

```js
/**
 * @export
 * @ngdoc controller
 * @ngname NgeoScaleselectorController
 */
class ColorpickerController {

  /**
   * @param {angular.Scope} $scope Directive scope.
   * @param {angular.JQLite} $element Element.
   * @param {angular.Attributes} $attrs Attributes.
   * @ngInject
   *
   */
  constructor($scope, $element, $attrs) {

    /**
     * The set of color
     * @type {Array.<Array.<string>>}
     * @export
     */
    this.colors = this.colors || defaultColors;

    /**
     * The selected color
     * @type {undefined|string}
     */
    this.color;
  }

  /**
   * @param {string} color The color to select.
   * @export
   */
  setColor(color) {
    this.color = color;
  }
}
```

I tried the **for-of** upgrade as well, looks straight forward.

**Comment by sbrunner** [comment]
Don't we lost some check if we removes the `@struct`?

**Comment by fgravin** [comment]
As lebab class transform is not straightforward and need manual fixes, we might need to automate the transformation.

I haven't found other tools for this issue.
Maybe codemod would be a good start.
- https://github.com/facebook/codemod
- https://github.com/cpojer/js-codemod/

Don't know if we go for it now, or wait a bit as ol3 community could do this as well.

**Comment by fgravin** [comment]
> Don't we lost some check if we removes the @struct?

@sbrunner i'm not sure about the `@struct`, might need more investigation to tell.

**Comment by gberaudo** [comment]
I think that the `@struct` is the default for ES6 classes.

**Comment by sbrunner** [comment]
Moved to Jira
