### ISSUE TITLE
Instruction text appears when FTS is active

### ISSUE THREAD

**Issue by marionb** [camptocamp/ngeo#2193]
Project:

* GitHub URL: https://github.com/camptocamp/ngeo
* GeoMapFish version: master

Permalink directly where we can reproduce the issue:
- https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/desktop_alt
- https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/desktop
- https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/mobile

Steps to reproduce the issue:
- In the FTS field enter a search text for example "Lauerz"

Result:
- The following text appears between the search field and the result examples:
   ```
   0 results are available, use up and down arrow keys to navigate
   ```
   The texts stays as long as the FTS is active, it disappears when clicking on the x of the search field (see screen shot).

![fts](https://cloud.githubusercontent.com/assets/1460598/21892102/11e671d6-d8d6-11e6-94d0-f36b971193c9.png)

Expected result:
- There is no spec. indicating that the text should appear
- For mobile devices the instructions are wrong there are no arrow keys.

The issue concern the following environment:

- Safari - iPad3
- Safari - iPod5
- Chromium, FF - Ubuntu 16.04
- Edge - Win10
- IE 11 - Win8.1

The following environment is working as expected:

- all environments tested showed the same behaviour

**Comment by fredj** [comment]
I think #2204 will fix this issue

**Comment by marionb** [comment]
It is not appearing on the Samsung Tablet any more but it is still appearing on the other devices. I am not sure if this is a cash problem.

**Comment by fredj** [comment]
fixed
