### ISSUE TITLE
Edit tools don't appear for Safari

### ISSUE THREAD

**Issue by marionb** [camptocamp/ngeo#2194]
Project:

* GitHub URL: https://github.com/camptocamp/ngeo
* GeoMapFish version: 2.1

Permalink directly where we can reproduce the issue:
- https://camptocamp.github.io/ngeo/2.1/examples/contribs/gmf/apps/desktop
- https://camptocamp.github.io/ngeo/2.1/examples/contribs/gmf/apps/desktop_alt

Steps to reproduce the issue:

* log in on the application
* activate the edit theme

Result:
- there is no edit tool on the right hand side tool bar

Expected result:
- the edit tool is added to the right hand side tool bar

The issue concern the following environment:

* Safari iOS iPad3
* Safari latest Mac El Cap.

The following environment is working as expected:

* Edge Win10
* FF latest Win10
* IE11 Win8.1
* Chrome Samsung Galaxy Tab4
* Chrome Latest Mac El Cap.

**Comment by ger-benjamin** [comment]
I can reproduce on example but not on real pages...

**Comment by marionb** [comment]
This is now working for (I can no longer reproduce this issue)
 
- https://camptocamp.github.io/ngeo/2.1/examples/contribs/gmf/apps/desktop
- https://camptocamp.github.io/ngeo/2.1/examples/contribs/gmf/apps/desktop_alt

on:
- Safari iOS iPad3
- Safari latest Mac El Cap.

**Comment by sbrunner** [comment]
OK, thanks for the tests :-)
