### ISSUE TITLE
Link in query does not open

### ISSUE THREAD

**Issue by marionb** [camptocamp/ngeo#2195]
Project:

* GitHub URL: https://github.com/camptocamp/ngeo
* GeoMapFish version: master

Permalink directly where we can reproduce the issue:
- https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/desktop
- https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/desktop_alt
- https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/mobile

Steps to reproduce the issue:

1. Select the layer OSM/OSM function/osm_open
2. Do a query on it
3. Click open

Result:
- nothing happens.
- Note: URL of the element points to
  ```
  javascript:cgxp.tools.openInfoWindow('/sbrunner20/wsgi/resourceproxy?target=point&values=1453005622','OSM',800,500)
  ```

Expected result:
- The window should open (the content dependencies don't work)

The issue concern the following environment: 
* Safari - iPad3
* Safari - iPod5
* Chromium, FF - Ubuntu 16.04
* Edge - Win10
* IE 11 - Win8.1

The following environment is working as expected:

* none that were tested

**Comment by ger-benjamin** [comment]
Mhh that's a problem in the demo_geomapfish mapfile, not in ngeo.
I'll change that. $

`DATA "geom FROM (SELECT '<a href=\"javascript:cgxp.tools.openInfoWindow(''/sbrunner20/wsgi/resourceproxy?target=point&values='||osm_id||''',''OSM'',800,500)\">Open</a>' AS open,`

**Comment by sbrunner** [comment]
Where is this function defined?
We need it for backward compatibility...

**Comment by rbovard** [comment]
Why did you remove the options `width` and `height`? It's very important.

And a popup should be draggable, like it was in `cgxp`.

**Comment by kalbermattenm** [comment]
> And a popup should be draggable, like it was in `cgxp`.

This is something we have to talk about at the PSC...
