### ISSUE TITLE
dists lib are broken

### ISSUE THREAD

**Issue by fgravin** [camptocamp/ngeo#2201]
Maybe related to goog.module upgrade ?

`ngeo.js` and `ngeo-debug.js` are not working anymore as standalone lib versions.

On page load:
```
Uncaught Error: Module ngeo.fileService has been loaded incorrectly.goog.module 
@ ngeo-debug.js:356(anonymous function) 
@ ngeo-debug.js:76840
closure_deps.js:520 Uncaught ReferenceError: Ext is not defined(anonymous function) 
@ closure_deps.js:520
```

The code that fails:

```js
goog.module = function(name) {
  if (!goog.isString(name) || !name ||
      name.search(goog.VALID_MODULE_RE_) == -1) {
    throw Error('Invalid module identifier');
  }
if (!goog.isInModuleLoader_()) {
    throw Error('Module ' + name + ' has been loaded incorrectly.');
```

`goog.moduleLoaderState_` is null.

**Comment by gberaudo** [comment]
I looked at the generated code. The `goog.module` code should be wrapped by the compiler, which is obviously not the case. It should be supported though: see https://github.com/google/closure-compiler/commit/5afe95683b3ed020f7dfed772b7f2eacd332c9fe.

**Comment by ybolognini** [comment]
Moved to Jira
