### ISSUE TITLE
Attributes name are truncated in query result

### ISSUE THREAD

**Issue by gnerred** [camptocamp/ngeo#2230]
When querying the map, attributes name are truncated. How to display them on multiple lines like in CGXP or Sencha app ? It is not good for end user, because information is missing. 

![image](https://cloud.githubusercontent.com/assets/1989467/22210253/8039c74e-e189-11e6-8622-d0e2d3472cc0.png)

**Comment by ybolognini** [comment]
@gnerred 
The current behavior is that labels are truncated with the full string in a tooltip. We may change that if the user group (or PSC) also thinks it could be improved.

**Comment by gnerred** [comment]
We have to talk about it at next PSC. The tooltip is not very useful on a mobile device... 
Ping @rbovard @kalbermattenm

**Comment by rbovard** [comment]
+1 We need to do something, the current situation is not satisfying.

Ideas:
* Allow multilines
* Make window bigger
* Use smaller font
* ...

**Comment by kalbermattenm** [comment]
OK, as the next PSC meeting is next Monday, I think we could add a little discussion about this.

**Comment by rbovard** [comment]
@ybolognini is there a tracking issue about the design of query results, because after some testing I noticed a lot of improvements to do?

**Comment by kalbermattenm** [comment]
I would like to have the PSC's thoughts about this one...

If I resume what has been talked about until now (mainly by @rbovard...) :
* Allow multilines
* Make window bigger
* Use smaller font

What would be the ideal solution for everyone ? (my preference would go to resize the windows has as long as possible, and then use multiline...)

ping @rbovard @gnerred @vvmalbre @mriedo @gsollberger @svavoi @cedricmoullet

**Comment by fredj** [comment]
Please note that the multilines in already implemented in 2.1 (with #2384)
It can be seen in:
https://preprod.cartoriviera.ch/v2/mobile/theme/cadastre?lang=fr&tree_group_layers_cadastre=batiments_egid&tree_group_layers_couverture_du_sol&baselayer_ref=plan_cadastral_201704&map_x=554740&map_y=145981&map_zoom=8&tree_groups=cadastre

![query_window_multiline](https://cloud.githubusercontent.com/assets/100959/24539221/c1e12d48-15ed-11e7-8ffc-212165114d21.png)

**Comment by rbovard** [comment]
Hi @kalbermattenm 

As you said, I pointed some UI issues with the results window in `2.1.2.dev1`:
* https://github.com/camptocamp/ngeo/issues/2383
* https://github.com/camptocamp/ngeo/issues/2366
* https://github.com/camptocamp/ngeo/issues/2371
* https://github.com/camptocamp/ngeo/issues/2360

I think some of them are solved in `2.1.2`, I need to upgrade to check that.

**Comment by kalbermattenm** [comment]
Thanks @fredj, I think that we completely missed that with @ybolognini 

So, what should we do with this specific issue ? Close it ?

@rbovard, yes, please test on close each specific issue if OK ?

**Comment by rbovard** [comment]
> @rbovard, yes, please test on close each specific issue if OK ?

Yes, that's the goal.

> So, what should we do with this specific issue ? Close it ?

Since it's solved yes, that's why I asked @ybolognini if there was a tracking issue about the design of query results

**Comment by fredj** [comment]
The window size and font can be changed at the application level

**Comment by ybolognini** [comment]
This issue is closed. Global issue for Query results window improvements is here: https://github.com/camptocamp/ngeo/issues/2497

**Comment by rbovard** [comment]
> @rbovard, yes, please test on close each specific issue if OK ?

I did and reported back in the tracking issue.
