### ISSUE TITLE
Headers of search results are not translated

### ISSUE THREAD

**Issue by gnerred** [camptocamp/ngeo#2251]
Version 2.1.0rc7

To test : https://preprod.cartoriviera.ch/v2/mobile/

In my fr.js file I have the following : 
.....
	//En-têtes recherche
    "01ddp": "DDP",
    "01parcelle": "Parcelle",
    "02eca": "Num. ECA de bâtiment",
    "03adresse": "Adresse",
    "04rue": "Rue",
.....

Other translations seems to be OK (layers, attributes, etc.)

![image](https://cloud.githubusercontent.com/assets/1989467/22337046/4fcf1cdc-e3e4-11e6-876e-097db09dab18.png)

**Comment by rbovard** [comment]
Was supposed to be fixed on 12 Jul 2016... See my issue #1506

**Comment by ger-benjamin** [comment]
Close with https://github.com/camptocamp/ngeo/pull/2252

**Comment by sbrunner** [comment]
@gnerred  Effectively it just miss the 2.1.1 release ... (for less than one hour)

**Comment by gnerred** [comment]
:O/
