### ISSUE TITLE
Permalink does not work on ngeo mobile

### ISSUE THREAD

**Issue by gnerred** [camptocamp/ngeo#2255]
Version 2.1.1. To reproduce : 

1°/ Go to https://preprod.cartoriviera.ch/v2/mobile/
2°/ Change theme and zoom somewhere
3°/ Copy the URL
4°/ Paste it in a new browser or tab -> application loads on initial extent and default theme...

You can try with this URL too, that should go to theme cadastre and activate some layers : 
https://preprod.cartoriviera.ch/v2/mobile/theme/cadastre?lang=fr&tree_group_layers_default_mobile_group=tp_arret_bus%2Ctp_arret_train%2Ctp_ligne_bus%2Ctp_ligne_train&baselayer_ref=plan_cadastral_201701&map_x=553852&map_y=146418&map_zoom=7&tree_groups=cadastre%2Ccouverture_du_sol&tree_group_layers_cadastre=batiments_egid%2Climite_commune%2Cbatiments_projetes

**Comment by sbrunner** [comment]
Some developer notes:
 * This and some other https://github.com/camptocamp/ngeo/blob/master/src/services/statemanager.js#L56 shouldn't be in ngeo part ...
 * This should be reverted https://github.com/camptocamp/ngeo/commit/4c6e1014629eef4b405b72766ae11e6242920783
* The `angular.{from,to}Json` should be removed it made the localStorage and the locationURL incompatible :-(
