### ISSUE TITLE
'Zoom to' button does not zoom enough

### ISSUE THREAD

**Issue by gnerred** [camptocamp/ngeo#2265]
Version 2.1.1

To test : 
1°/ Go to https://preprod.cartoriviera.ch/v2/mobile/ 
2°/ Zoom out to see all communes
3°/ Go to theme "Infrastructures"
4°/ Click on the zoomto button of layer "Hydrantes (EP)" -> the application does not zoom enough, blue circles are not visible, you have to zoom manually to see them

**Comment by sbrunner** [comment]
Do you try to change your resolutions?
https://github.com/camptocamp/cartoriviera_geomapfish/blob/v2/cartoriviera/static-ngeo/js/mobile.js#L35

**Comment by gnerred** [comment]
Why do I have to change my resolutions... ?

**Comment by sbrunner** [comment]
Sorry, I miss understand, It's a relay issue... :-)

**Comment by gnerred** [comment]
This problem is solved on mobile app on desktop, but not on mobile device. If I do the steps of my first message on my S6, the map zooms in until scale "200 m" is written, but the layer is not show. What is strange is that when scale "200 m" is written on a desktop browser, the layer is shown ! So for a same zoom level, a layer is shown on desktop but not on mobile device... Reopen ?
