### ISSUE TITLE
Difficult to query points on NGEO mobile

### ISSUE THREAD

**Issue by gnerred** [camptocamp/ngeo#2267]
Version 2.1.1

It is very difficult to query a point on NGEO mobile, even if mapserver tolerance is set to 10 pixels (that is a lot). Tested on a Galaxy S6 with native browser AND Chrome. 

To reproduce : 
1°/ Go to https://preprod.cartoriviera.ch/v2/mobile/ on a real mobile device
2°/ Go to theme "Infrastructures"
3°/ Zoomin and try to query blue circles of layer "Hydrantes (EP)", they have a tolerance of 10 pixels -> difficult to get a result

**Comment by sbrunner** [comment]
Modern screen can have more than 500 dpi screen than the tolerance is :`10/500*2.54 =>~ 0.05` it's less than 1mm, than it's  relay not a lot...

I think that 0.003 meters is better
```
TOLERANCE 0.003
TOLERANCEUNITS metres
```

**Comment by gnerred** [comment]
Ok thanks, so it is due to resolution... But I think your proposal is not ideal, because if you are zoomed out, you will neither be able to query...

**Comment by sbrunner** [comment]
I should test it ...

**Comment by sbrunner** [comment]
I'm completely wrong, It's a WFS query...

**Comment by gnerred** [comment]
Ok thanks for PR
