### ISSUE TITLE
Layertree refresh takes a long time after secured connexion

### ISSUE THREAD

**Issue by gnerred** [camptocamp/ngeo#2269]
Version 2.1.1

Once logged, it takes near 10 seconds before layertree is refreshed and secured layers appear. To reproduce : 

1°/ Go to https://preprod.cartoriviera.ch/v2/mobile/ in theme "Cadastre"
2°/ Connect with camptcamp user (ask me if you forgot the credentials)
3°/ Just after connected, open the layertree and wait -> several seconds after, the secured layers appear. 

Not a good user experience. I fist thought that the secured layers did not work.

**Comment by sbrunner** [comment]
I just tested and it takes about 0.1s.
In your case I think that's because it's the first time after a server application restart...

**Comment by gnerred** [comment]
Ok fine, it seems that you are right, if I try to reproduce, it is instantaneous
