### ISSUE TITLE
Github repository is too heavy

### ISSUE THREAD

**Issue by pgiraud** [camptocamp/ngeo#2274]
Hi all,
While the library itself is less than 2MB, cloning the ngeo repository weights more than 379MB.
This is essentially due to the fact that there's a lot of commits in the gh-pages branch. This should not be the case.
For a comparison, "git clone -b master --single-branch" retrieves 13MB.

Proposed actions:
 - clean the gh-pages branch on github to remove all the history,
 - use "commit --amend" and "push --force" when modifying gh-pages.

Any opinion?

**Comment by sbrunner** [comment]
I just merge the history of gh pages but I don't agree to do automated git push force ...

**Comment by tonio** [comment]
So you will have to do it again from time to time ? What’s the goal of keeping history for generated content ?

**Comment by sbrunner** [comment]
It's not that the goal, its to be sure that the Travis job don't lost what's done by an other Travis job...
