### ISSUE TITLE
dist build (ngeo.js) removes all ngeo Angular components

### ISSUE THREAD

**Issue by fgravin** [camptocamp/ngeo#2279]
During dist advanced build, all ngeo angular components (services, directives ..) attached to main angular module `ngeo` are removed.
```js
ngeo.module.value('ngeoDecorateLayer', ngeo.decorateLayer);
```
For example `ngeoDecorateLayer` is not in ngeo.js.

Only components attached on submodules like `ngeo.search.searchDirective` are kept.
I guess @gberaudo it's related to your work on organizing ngeo on more and smaller modules.

**Comment by fgravin** [comment]
Anything about this ?
`ngeo` is a library and must provide a `dist` version.
This is a huge regression.
Some projects are using it at c2c.

**Comment by gberaudo** [comment]
@fgravin what you are seeing is unrelated to my changes for smaller modules.

I checked the content of `dist/ngeo.js` in version `9f64cb5`, which is anterior to my modifications: in that version, there are only 2 exported symbols: `ngeo.FeatureProperties` and `ngeo.GeometryType`.

The breaking must come from earlier.

**Comment by fgravin** [comment]
Severals issues reported

1. `goog.module` cannot be used in debug mode so it breaks `dist/ngeo-debug.js`
2. All externals angular modules like `ui.date` are not declared in dist files so they cannot be used, this makes a angular injection error because ngeo module depends on them.
3. in `ADVANCED` mode, nothing is exported from ngeo exept code that is `goog.required` from `ngeo.js`
https://github.com/camptocamp/ngeo/blob/master/src/ngeo.js#L30-L31.
`ngeo.LayertreeController` is never required so it's not loaded. If you require it in `ngeo.js`, it creates a dependency loop.

We cannot do anything i guess for 1., but 2. and 3. can be fixed to provide at least advanced built ngeo.js dist.

**Comment by ybolognini** [comment]
Moved to Jira
