### ISSUE TITLE
Transifex account may be corrupted

### ISSUE THREAD

**Issue by pgiraud** [camptocamp/ngeo#2303]
The password provided at the following line allows anyone to change the translation in Camptocamp's transifex account.
https://github.com/camptocamp/ngeo/blob/master/Makefile#L908

**Comment by sbrunner** [comment]
This account don't have any rights ...

**Comment by pgiraud** [comment]
I wouldn't be so sure about this.
https://www.transifex.com/camptocamp/geomapfish/translate/#fr/c2cgeoportal-2_0/97677343?qt=caca

**Comment by pgiraud** [comment]
This user doesn't have rights to change reviewed translations at least.

**Comment by sbrunner** [comment]
Every body can do it ...

**Comment by pgiraud** [comment]
Are we sure that only reviewed translations are pulled from transifex?
If this is the case, then we can close this issue.

**Comment by pgiraud** [comment]
It looks like we don't use "--mode=reviewed" when calling `tx pull` so all the translations are pulled.
https://github.com/camptocamp/ngeo/blob/master/Makefile#L947-L953

**Comment by sbrunner** [comment]
+1, we should add it :-)
