### ISSUE TITLE
We shouldn't use ['...'] notation to access directive's optional bound variables

### ISSUE THREAD

**Issue by ger-benjamin** [camptocamp/ngeo#2305]
Wait on #2306 

Like there: 

 - https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/src/directives/displayquerygrid.js#L196
 - https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/src/directives/profile.js#L195
 - ...

**Comment by ger-benjamin** [comment]
To discuss:

We use the this['totoFn'] to verify if the there is a value bound like this: `totoFn: &ngeo-directive-toto`.
If we use the `&` symbol, it's to restrict the binding to 'one-time binding'.

What is the advantage to do that ? Can't we just do a one-direction binding (`<`) and restrict the binding into the html ? (`ngeoDirectiveToto="::aValue"`). With this, we can just use the value `toto` as it, and wouldn't pass by the `totoFn`.

**Comment by gberaudo** [comment]
Yes you are right, these can be leftovers from:
- usage of `&` and function call for custom one-way binding;
- untyped access to property (we should have always used `@export`).

**Comment by sbrunner** [comment]
https://jira.camptocamp.com/browse/GSGMF-550
