### ISSUE TITLE
Unable to print some layers

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/ngeo#2340]
Permalink directly where we can reproduce the issue:
https://camptocamp.github.io/ngeo/2.1/examples/contribs/gmf/apps/desktop_alt/?lang=fr&tree_groups=OSM%20functions%20mixed&tree_group_layers_Edit=line%2Cpolygon%2Cpoint&tree_group_layers_Snapping%20no%20edge&tree_group_layers_Snapping%20no%20vertex&baselayer_ref=map&tree_enable_map=true&tree_enable_osm_time_r_s=false&tree_enable_osm_time_v_s=false&tree_enable_osm_time_v_dp=false&tree_enable_osm_time_r_dp=false&tree_enable_osm_scale=false

Steps to reproduce the issue:

* Print

Result:

Erreur durant l’impression, merci de réessayer.

The layer 'Carte' has a legend with a `null` URL...

**Comment by ger-benjamin** [comment]
Closed with #2423
