### ISSUE TITLE
Permalink enable layers

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/ngeo#2341]
Permalink directly where we can reproduce the issue:
https://camptocamp.github.io/ngeo/2.1/examples/contribs/gmf/apps/desktop_alt/?lang=fr&tree_groups=OSM%20functions%20mixed&tree_enable_osm_time_r_s=false&tree_enable_osm_time_v_s=false&tree_enable_osm_time_v_dp=false&tree_enable_osm_time_r_dp=false&tree_enable_osm_scale=false

Steps to reproduce the issue:

* Open the URL

Result:

We have 4 layer enable

Expected result:

No overlay should be enable...

**Comment by ger-benjamin** [comment]
Closed with #2422
