### ISSUE TITLE
ID attribute field is not used in mobile

### ISSUE THREAD

**Issue by rbovard** [camptocamp/ngeo#2358]
* GeoMapFish version: **2.1.2.dev1**

The identifier attribute field is not used in mobile:

![image](https://cloud.githubusercontent.com/assets/4549666/23250366/210d4f9c-f9a9-11e6-8d46-bb5f241c538f.png)

On desktop it's ok:

![image](https://cloud.githubusercontent.com/assets/4549666/23250361/15cf9e96-f9a9-11e6-9ac5-fc105bb4b9f4.png)

**Comment by rbovard** [comment]
By the way, if there is not id attribute defined, the space should be removed to optimize place.

**Comment by gnerred** [comment]
Right, we talked about this blank space with @ybolognini at our last meeting, and it has to be removed.

**Comment by ybolognini** [comment]
We just tried this on demo and it looks like it's working, do you have an example?

We'll create another issue for removing the white space when nothing has to be shown.

**Comment by rbovard** [comment]
Sure:
* Mobile: https://map-demo.nyon.ch/v2/mobile/theme/mobilite?lang=fr&tree_group_layers_adresses&tree_group_layers_cadastre=cad_projete_non_cadastre_mobile&tree_group_layers_limites_administratives&baselayer_ref=asitvd.fond_couleur&map_x=508057&map_y=137607&map_zoom=10&theme=mobilite&tree_groups=transports_publics&tree_group_layers_transports_publics=mb_bus_arrets --> KO
* Desktop: https://map-demo.nyon.ch/v2/s/BfgZ --> OK

**Comment by sbrunner** [comment]
The field is not configured, but the migration tool had an issue
this: https://github.com/camptocamp/c2cgeoportal/blob/master/c2cgeoportal/scripts/themev1tov2.py#L258-L262 use not the same case as this: https://github.com/camptocamp/c2cgeoportal/blob/master/c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl#L171

**Comment by fredj** [comment]
fixed with https://github.com/camptocamp/c2cgeoportal/pull/2866

**Comment by rbovard** [comment]
Fixed, thanks.
