### ISSUE TITLE
The interface is not translated

### ISSUE THREAD

**Issue by rbovard** [camptocamp/ngeo#2359]
* GeoMapFish version: **2.1.2.dev1**

The interface is not translated, it should be by default for common interface strings like:
* Backgroud
* Themes
* Measure
* ...

**Comment by sbrunner** [comment]
Where is it displayed?

**Comment by rbovard** [comment]
Left and right panels.

And there is `lang=fr` in url.

**Comment by sbrunner** [comment]
You probably didn't translate it in the `<package>/locale/fr/LC_MESSAGES/<package>-client.po` file :-)

**Comment by rbovard** [comment]
So the application is not translated by default??

**Comment by sbrunner** [comment]
The component yes but not the layout..., it's just about 20 strings :-)

**Comment by rbovard** [comment]
So why not include them by default? ;)

**Comment by sbrunner** [comment]
Because we can change it in the application, than it will be present in tow localization files, than it's not the best...

**Comment by rbovard** [comment]
It's not a good point for me, because we can change *everything* in the application.

I think it's much better to have default values translated by default, for the ones who want to edit source value, they know what they do and sould also adapt translated value. No?

**Comment by rbovard** [comment]
@sbrunner Any news on this one?

**Comment by rbovard** [comment]
Seriously, you want to ship an application which is half translated?

![image](https://cloud.githubusercontent.com/assets/4549666/25884700/9b02c002-3554-11e7-9c8a-c3e780982ae0.png)

Tell me which file I need to edit in source project and I'll do it.

**Comment by sbrunner** [comment]
I can add in the project creation the translated files...

**Comment by rbovard** [comment]
Yes, please :)

**Comment by rbovard** [comment]
@sbrunner I'm testing `2.1.8` and it's still not translated.

![image](https://user-images.githubusercontent.com/4549666/30697437-4775397a-9edf-11e7-889e-467066b59262.png)

Did I missed something?

**Comment by rbovard** [comment]
@sbrunner Any news on this one?

**Comment by sbrunner** [comment]
you should copy or call `msgmerge` the file `CONST_create_template/+package+/locale/*/LC_MESSAGES/+package+-client.po` to `+package+/locale/*/LC_MESSAGES/+package+-client.po`

**Comment by rbovard** [comment]
Ok, thanks.
