### ISSUE TITLE
Result window cannot be swipped down

### ISSUE THREAD

**Issue by rbovard** [camptocamp/ngeo#2360]
* GeoMapFish version: **2.1.2.dev1**

Result window cannot be swiped down, but only left/right. It's not straight forward for the user: why can we swipe horizontally but not vertically?

Horizontally with arrows and swipe:

![image](https://cloud.githubusercontent.com/assets/4549666/23250778/d44c65ce-f9aa-11e6-85de-d03e82a1579a.png)

Vertically only with arrow:

![image](https://cloud.githubusercontent.com/assets/4549666/23250804/e818f8a6-f9aa-11e6-99e6-5fee3b15ecd7.png)

It should be possible to swipe down to reduce window.

**Comment by fredj** [comment]
Note that this swipe down will interfere with the content scrolling.

**Comment by rbovard** [comment]
As also noticed during PSC, it should be only for the zone outside the content (in blue) to avoid interferences:

![image](https://cloud.githubusercontent.com/assets/4549666/25945201/5818a37c-3646-11e7-9da2-ca3c25accdfa.png)

Maybe it's more simple/logical to do it only the arrow?

![image](https://cloud.githubusercontent.com/assets/4549666/25945286/a53024c8-3646-11e7-8466-8d61d979ddae.png)

What do you think?

**Comment by sbrunner** [comment]
moved to jira
