### ISSUE TITLE
The order of raster layers is not used

### ISSUE THREAD

**Issue by rbovard** [camptocamp/ngeo#2361]
* GeoMapFish version: **2.1.2.dev1**

The order of raster layers is not used:

```
this.elevationLayersConfig = {
  'mnt': {unit: 'm'},
  'mns': {unit: 'm'}
};
```

![image](https://cloud.githubusercontent.com/assets/4549666/23251591/33f8f138-f9ae-11e6-9350-1e0d47b7cf58.png)

```
this.elevationLayersConfig = {
  'mns': {unit: 'm'},
  'mnt': {unit: 'm'}
};
```

![image](https://cloud.githubusercontent.com/assets/4549666/23251594/36b5ca86-f9ae-11e6-96f4-82e1575fcc59.png)

**Comment by sbrunner** [comment]
The `elevationLayersConfig` is a dictionary, it can't defined the order, have you tried to change the order on the server side?

**Comment by rbovard** [comment]
Just tried and it doesn't change the result.

**Comment by rbovard** [comment]
@fredj Could you please reopen it, it's not working.

With the changes:

```
   /**
-   * @type {Object.<string, gmf.MobileMeasurePointController.LayerConfig>}
+   * @type {Array.<gmf.MobileMeasurePointController.LayerConfig>}
    * @export
    */
-  this.elevationLayersConfig = {
-    'mnt': {unit: 'm'},
-    'mns': {unit: 'm'}
-  };
+  this.elevationLayersConfig = [
+    {name: 'mnt', unit: 'm'},
+    {name: 'mns', unit: 'm'}
+  ];
```

I have following errors:
```
Failed to load resource: the server responded with a status of 404 (Not Found)
GET https://map-demo.nyon.ch/v2/wsgi/raster?lat=137804&layers=0,1&lon=507308
```

It's logical since I do not have the layer `mnt` or `mns` in the URL...

**Comment by fredj** [comment]
@rbovard I have made the modification for the 2.2 branch, not the 2.1
