### ISSUE TITLE
 The layer icons are not displayed in mobile

### ISSUE THREAD

**Issue by rbovard** [camptocamp/ngeo#2364]
* GeoMapFish version: **2.1.2.dev1**

 The layer icons are not displayed in mobile:

![image](https://cloud.githubusercontent.com/assets/4549666/23255227/143c1cc8-f9bb-11e6-923d-74e1401b7cbe.png)

It's fine on desktop:

![image](https://cloud.githubusercontent.com/assets/4549666/23255267/3be7bf84-f9bb-11e6-8971-e0d8f7a8ed8b.png)

**Comment by sbrunner** [comment]
@rbovard Where can we see that?

**Comment by rbovard** [comment]
@sbrunner Could you please reopen this one, it's not fixed in `2.1.2`.

You can see it [here](https://map-demo.nyon.ch/v2/mobile/theme/mobilite?lang=fr&baselayer_ref=asitvd.fond_couleur&tree_group_layers_points_interet=poi_poi_sante%2Cpoi_poi_bat%2Cpoi_poi_culture%2Cpoi_poi_sport%2Cpoi_poi_ecole&tree_group_layers_itineraires_sportifs&theme=mobilite&map_x=508013&map_y=137328&map_zoom=6&tree_group_layers_assainissement_mobile=ass_regards_visite_mobile_v2%2Cass_collecteurs_ec_mobile_v2&tree_groups=mobilite_douce%2Ctransports_publics%2Ccirculation).

**Comment by sbrunner** [comment]
Its fixed for the next version 2.1.3...

**Comment by rbovard** [comment]
Oh... Is there a release date?

**Comment by sbrunner** [comment]
Soon..., in about 10 days...

**Comment by rbovard** [comment]
It's better but not all layers got their icons (see "Supports vélos" in my previous link)...

KO on mobile:

![image](https://cloud.githubusercontent.com/assets/4549666/25844126/d3a43f04-34a9-11e7-98c1-3859eb9855c6.png)

OK on desktop:

![image](https://cloud.githubusercontent.com/assets/4549666/25844111/c376e0b4-34a9-11e7-8764-79d63fad4cbf.png)

Could you please reopen this issue?

**Comment by rbovard** [comment]
@sbrunner any news on this one?

**Comment by sbrunner** [comment]
For me tit's fixed :-)

**Comment by rbovard** [comment]
Oh nice thanks, so you can close it ;)
