### ISSUE TITLE
Background color of legends

### ISSUE THREAD

**Issue by rbovard** [camptocamp/ngeo#2365]
* GeoMapFish version: **2.1.2.dev1**

Why use a grey background for legends on mobile?

![image](https://cloud.githubusercontent.com/assets/4549666/23255429/cdb3b7ce-f9bb-11e6-8581-02302dc6da25.png)

It's much better without like it is in desktop:

![image](https://cloud.githubusercontent.com/assets/4549666/23255387/aec98906-f9bb-11e6-874d-6ba6d44e02c6.png)

**Comment by kalbermattenm** [comment]
Same issue on desktop app

**Comment by fredj** [comment]
See https://github.com/camptocamp/c2cgeoportal/wiki/Spec-%231708-Layertree-desktop#legend
"Complete legend (when available) is displayed using a light gray background."

**Comment by fredj** [comment]
FYI, here's an example how to remove the background and border: https://github.com/camptocamp/ngeo/commit/0102d8979163881f53845fb5fc9acada9ad41f3a

**Comment by rbovard** [comment]
Okay, thanks @fredj.
