### ISSUE TITLE
Long attributes values are hidden

### ISSUE THREAD

**Issue by rbovard** [camptocamp/ngeo#2366]
* GeoMapFish version: **2.1.2.dev1**

Long attributes values are hidden (red), and the content is not centred (blue)

![image](https://cloud.githubusercontent.com/assets/4549666/23256306/282f201e-f9bf-11e6-885a-f9380e5934a1.png)

**Comment by ybolognini** [comment]
Same solution as #2371

**Comment by fredj** [comment]
note: according to the existing CSS rules, the text should go to the next line.

**Comment by rbovard** [comment]
Fixed, thanks.
