### ISSUE TITLE
Layers without attributes are queried

### ISSUE THREAD

**Issue by rbovard** [camptocamp/ngeo#2367]
* GeoMapFish version: **2.1.2.dev1**

Layers without attributes (`"gml_include_items"  ""`) are queried:

![image](https://cloud.githubusercontent.com/assets/4549666/23257127/be68dd42-f9c2-11e6-9378-73ae45c87aef.png)

**Comment by fredj** [comment]
Same issue in https://testgmf.sig.cloud.camptocamp.net/2.1/theme/Demo and the "Main lithological groups" layer (external WMS layer)

**Comment by fredj** [comment]
This is specific to `gmf-displayquerywindow`; `gmf-displayquerygrid` already hide features without properties.

**Comment by rbovard** [comment]
Fixed, thanks.
