### ISSUE TITLE
Background layers

### ISSUE THREAD

**Issue by rbovard** [camptocamp/ngeo#2369]
* GeoMapFish version: **2.1.2.dev1**

According to the doc:

> The background layers are configured in the database, with the layer group named background (by default).

Here is my config and it doesn't work:

![image](https://cloud.githubusercontent.com/assets/4549666/23259035/712ebe62-f9cb-11e6-8d66-883d7e599bc6.png)

I only have that:

![image](https://cloud.githubusercontent.com/assets/4549666/23259001/3ebb90c2-f9cb-11e6-9fbd-39dca5bc22ff.png)

Is there something else to do?

**Comment by sbrunner** [comment]
The layer are not in any interfaces :-(

**Comment by rbovard** [comment]
Thanks, it's better but I don't have the local ones:

![image](https://cloud.githubusercontent.com/assets/4549666/23260557/af8b9bd8-f9d2-11e6-9bdc-d2a5a31ef413.png)

**Comment by sbrunner** [comment]
Will be fixed with #2855

**Comment by rbovard** [comment]
Ok, I'll try with next `2.1.2` release

**Comment by gnerred** [comment]
Strange, I did not have this problem...

**Comment by sbrunner** [comment]
@gnerred it's not directly related to the background but related to the URL generation, then you are probably not in the same case as @rbovard :-)

**Comment by gnerred** [comment]
OK ;-)

**Comment by rbovard** [comment]
@sbrunner Could you please reopen this one, it's not fixed.

I have a lot of JS errors on loading:

```
unable to get capabilities asitvd.fond_couleur https://ows.asitvd.ch/wmts/WMTSCapabilities.xml
unable to get capabilities asitvd.fond_gris https://ows.asitvd.ch/wmts/WMTSCapabilities.xml
TypeError: Cannot read property 'u' of null
unable to get capabilities plan_cadastral https://map-demo.nyon.ch/v2/tiles/1.0.0/WMTSCapabilities-v2.xml
Cannot read property 'u' of null
TypeError: Cannot read property 'u' of null
TypeError: Cannot read property 'u' of null
unable to get capabilities cartes_nationales https://map-demo.nyon.ch/v2/tiles/1.0.0/WMTSCapabilities-v2.xml
Cannot read property 'u' of null
TypeError: Cannot read property 'u' of null
TypeError: Cannot read property 'TileMatrixSetLink' of null
unable to get capabilities orthophotos https://map-demo.nyon.ch/v2/tiles/1.0.0/WMTSCapabilities-v2.xml
Cannot read property 'TileMatrixSetLink' of null
TypeError: Cannot read property 'TileMatrixSetLink' of null
```

**Comment by sbrunner** [comment]
It's an other issue that I just open it.
