### ISSUE TITLE
Title on href values

### ISSUE THREAD

**Issue by rbovard** [camptocamp/ngeo#2371]
* GeoMapFish version: **2.1.2.dev1**

The HTML code is displayed as title on link attributes:

![image](https://cloud.githubusercontent.com/assets/4549666/23261460/7d54c942-f9d6-11e6-9afb-d08378aa64e4.png)

**Comment by ybolognini** [comment]
Proposal:
 * Word wrap on attribute name AND value
 * Remove titles

**Comment by rbovard** [comment]
Fixed, thanks.
