### ISSUE TITLE
FTS results order

### ISSUE THREAD

**Issue by rbovard** [camptocamp/ngeo#2375]
* GeoMapFish version: **2.1.2.dev1**

The FTS results are sorted alphabetically, it would be nice to sort them alphanumerically:

![image](https://cloud.githubusercontent.com/assets/4549666/23293768/4981fd64-fa68-11e6-9aa5-e0b5b5df426a.png)

In this case: 1, 3, 5, 11, 13, etc.

**Comment by kalbermattenm** [comment]
PSC meeting decided that this issue can be closed.

**Comment by rbovard** [comment]
... because it will be fixed in FTS improvements
