### ISSUE TITLE
Not all attributes are translated

### ISSUE THREAD

**Issue by rbovard** [camptocamp/ngeo#2376]
* GeoMapFish version: **2.1.2.dev1**

I don't know why, but not all attributes are translated.

Mobile (only Rayonne... is translated):

![image](https://cloud.githubusercontent.com/assets/4549666/23293903/189eb664-fa69-11e6-8007-432e93fd75b7.png)

Desktop (all are translated):

![image](https://cloud.githubusercontent.com/assets/4549666/23293932/43afa124-fa69-11e6-9c99-eaf4d6e063eb.png)

**Comment by sbrunner** [comment]
It's not related but I notice that in your localization file you keep some lines with `#, fuzzy`, this is automatically when the localization found an approximate translation, it should be removed because it will be ignored :-/

**Comment by sbrunner** [comment]
Something isn't working as expected in the string collection.

**Comment by sbrunner** [comment]
The WMS groups should be supported...

**Comment by rbovard** [comment]
@sbrunner Could you please repopen this one, it's not fixed.

I still have some unstranslated attributes. If I checkt the `<package>-client.po`, there is:
* 99 `#, fuzzy`
* 360 `#~ msgid`

Is it normal?

**Comment by sbrunner** [comment]
99 => https://camptocamp.github.io/c2cgeoportal/2.1/integrator/internationalization.html?highlight=fuzzy
360 => old localisation...

**Comment by rbovard** [comment]
Thanks for your answers.

* What do you mean by verified, should I just remove the `#, fuzzy`? By the way, why some strings are marked as fuzzy, could I avoid this situation during next attempt to upgrade to 2.x?
* From where those values are coming from? I also would like avoid this situation during next attempt to upgrade to 2.x.

**Comment by sbrunner** [comment]
* It's added when a new string to translate is found and when a suggestion is found :-)
* It's produce every-time a string is present in the current file and he isn't necessary anymore.

**Comment by rbovard** [comment]
Thanks, it's working.
