### ISSUE TITLE
FTS doesn't activate layers if any

### ISSUE THREAD

**Issue by rbovard** [camptocamp/ngeo#2385]
* GeoMapFish version: **2.1.2.dev1**

On mobile, the FTS doesn't activate layers if any.

Steps to reproduce:
* https://map-demo.nyon.ch/v2/mobile
* Search `Arrêt Nyon Usine à Gaz`
* The map is centered but the layer is not activated

On desktop it activate the layer `Arrêts de bus`

**Comment by sbrunner** [comment]
The fulltext search configuration changed on GeoMapFish 2.x, see: https://camptocamp.github.io/c2cgeoportal/master/integrator/fulltext_search.html?highlight=fulltextsearch#actions

**Comment by rbovard** [comment]
Thanks for the info.

Is it used in your demo?

**Comment by ger-benjamin** [comment]
Hello yes, you can try to search somethings without anything in the layertree and it will open a theme, a group or a layer (depend on the configuration, see stephan's link). You must also activate these actions in ngeo: https://github.com/camptocamp/demo_geomapfish/blob/master/demo/templates/desktop.html#L317-L319

(Update: Sadly, our demo is down...)

**Comment by ger-benjamin** [comment]
Try to search "Lausanne" without any layers there: https://camptocamp.github.io/ngeo/2.1/examples/contribs/gmf/apps/desktop_alt

**Comment by sbrunner** [comment]
Can we close this issue?

**Comment by rbovard** [comment]
According to the doc:

> The actions column contains a JSON with an array of actions like [...]

I'm sorry, but it's not so clear for me. Where should we add this action column?

**Comment by sbrunner** [comment]
the `actions` column should exists in the `tsearch` table...

**Comment by rbovard** [comment]
Ok thanks.

So could you please add an example in the doc, like you did here: https://github.com/camptocamp/c2cgeoportal/blob/master/doc/integrator/fulltext_search.rst.mako#L63-L69
