### ISSUE TITLE
Theme in permalink

### ISSUE THREAD

**Issue by rbovard** [camptocamp/ngeo#2386]
* GeoMapFish version: **2.1.2.dev1**

The theme in permalink is meaningless because not taken in consideration.

Steps to reproduce:
* https://map-demo.nyon.ch/v2/mobile
* Choose theme `Mobilité`
* Close the browser tab
* Open https://map-demo.nyon.ch/v2/mobile/theme/amenagement_territoire --> No layers from `Aménagement Territoire` are displayed because permalink keep old layers...

**Comment by sbrunner** [comment]
When a theme is specified the local storage should be disable...

**Comment by ger-benjamin** [comment]
Close with #2386

**Comment by rbovard** [comment]
Thanks, fixed.
