### ISSUE TITLE
NGEO mobile first load not centered

### ISSUE THREAD

**Issue by gnerred** [camptocamp/ngeo#2393]
Version 2.1.2.dev1

At first load of the mobile application on a clean cache browser, the map is not centered and is grey. 

To reproduce, just open https://preprod.cartoriviera.ch/v2/mobile/ or https://map.nyon.ch/v2/mobile/ in a browser in Browserstack. The URL generated does not contain a XY information : 

https://preprod.cartoriviera.ch/v2/mobile/theme/default_mobile?lang=fr&tree_group_layers_default_mobile_group=tp_arret_bus%2Ctp_arret_train%2Ctp_ligne_bus%2Ctp_ligne_train&baselayer_ref=plan_cadastral_201702&tree_groups=default_mobile_group

or  (ping @rbovard)

https://map.nyon.ch/v2/mobile/theme/cadastre?lang=fr&tree_groups=adresses%2Ccadastre%2Climites_administratives&tree_group_layers_adresses&tree_group_layers_cadastre=cad_projete_non_cadastre_mobile&tree_group_layers_limites_administratives&baselayer_ref=asitvd.fond_couleur

**Comment by rbovard** [comment]
Same as #2381?

**Comment by gnerred** [comment]
Yes... sorry for double issuing, I close this one
