### ISSUE TITLE
Add a message for Android Browser

### ISSUE THREAD

**Issue by ybolognini** [camptocamp/ngeo#2431]
Linked to #2214. 

Add a message when user is browsing with Android Browser and suggest an upgrade to Chrome. Needs a pretty good browser detection.

**Comment by rbovard** [comment]
And what about @sbrunner comment here https://github.com/camptocamp/ngeo/issues/2377#issuecomment-285373257

**Comment by ybolognini** [comment]
@rbovard 
As far as I know, this issue (blocking bug on Android Browser, see #2214) is not linked to the performance problem (#2377). We will resolve the Android Browser problem with this issue (adding a message to suggest an upgrade to Chrome) and we will follow the performance problem on #2377 issue.

**Comment by rbovard** [comment]
Okay.

**Comment by ger-benjamin** [comment]
@ybolognini What is the specs for this message ?
A simple "alert" is enough ?
And I think that the message should be localized ? (That 's hard because the error come before the localization process, so, I prefer to ask.)

**Comment by ybolognini** [comment]
@ger-benjamin 
Okay for a simple alert.
If the message is configurable, no need to localize
