### ISSUE TITLE
WMTS layer - Automatically open opacity slider

### ISSUE THREAD

**Issue by gnerred** [camptocamp/ngeo#2436]
ping @rbovard @svarim @vvmalbre @mriedo @gsollberger @svavoi @kalbermattenm @ybolognini 

What do you think of the possibility to automatically open the opacity slider when checking a WMTS layer ? It has been asked here by some users. 

![image](https://cloud.githubusercontent.com/assets/1989467/23906714/1a6d653e-08cf-11e7-8c1b-e4d537ab710f.png)

It shows users that the layer, often an opaque layer like an orthophoto, can be made transparent. A lot of users do not know or find this functionnality. Then, when the user clicks on map do navigate, the slider disappears (already working).

**Comment by rbovard** [comment]
I agree that the ability to change opacity of a layer is not straightforward but I don't think to show it on activation is a good solution because it's too invasive for me.

**Comment by mriedo** [comment]
+1

**Comment by gnerred** [comment]
@rbovard is it too invasive even if it disappears at first click on map ? 
@mriedo, +1 for automatically open or +1 for too invasive ?

**Comment by gsollberger** [comment]
+1 too invasive

**Comment by rbovard** [comment]
> @rbovard is it too invasive even if it disappears at first click on map ?

Yes.

**Comment by gnerred** [comment]
Ok fine let's forget that ;-)
