### ISSUE TITLE
Strange behavior with themeManager.themeName when not in mode flush

### ISSUE THREAD

**Issue by ger-benjamin** [camptocamp/ngeo#2437]
Version 2.2

To discuss with @sbrunner @fredj @ybolognini 

Open the desktop alt. For now the "themes" name in the themanager is hardcoded. in the html (here: https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/apps/desktop_alt/index.html#L29)
It is really the right manner to have a clean "themeName"  when we are not in mode flush ? (if you set the themeName manually in the js you get a strange behavior with the permalink and which theme that should be open on init.)

**Comment by sbrunner** [comment]
The line you pointed isn't the theme name, it's just the label of the button...

**Comment by ger-benjamin** [comment]
That's precisely my Problem. But I'll discuss that with you, that's not hurry

**Comment by sbrunner** [comment]
I don't understand the issue, In the project we can put what we want...
