### ISSUE TITLE
App loading

### ISSUE THREAD

**Issue by kalbermattenm** [camptocamp/ngeo#2444]
Our desktop interface is quite heavy, and it takes a few seconds for the app to load. During this time (or more specifically until theme?interface=desktop... has loaded).

The user sees this image:

![image](https://cloud.githubusercontent.com/assets/1681332/23950473/62d4c4ea-098b-11e7-8887-88b7cb51b52d.png)

It is a bit depressing... Shouldn't the user see some kind of spinning wheel (or I do not know what...) ?

**Comment by rbovard** [comment]
+1 We need the same as now with `cgxp`:

![image](https://cloud.githubusercontent.com/assets/4549666/23953254/63150330-0994-11e7-88b0-0f69b8343089.png)

**Comment by ybolognini** [comment]
--> GMF 2.4
