### ISSUE TITLE
Layers not checked are queried

### ISSUE THREAD

**Issue by gnerred** [camptocamp/ngeo#2447]
Version 2.1.2.dev3. To reproduce

1°/ Go to https://preprod.cartoriviera.ch/v2/mobile/theme/cadastre?lang=fr&tree_groups=cadastre%2Ccouverture_du_sol&tree_group_layers_cadastre=batiments_egid&tree_group_layers_couverture_du_sol&baselayer_ref=plan_cadastral_201703&map_x=554721&map_y=145938&map_zoom=8
2°/ Click somewhere -> limite de commune is queried but is not checked !

All the layers of a group containing on layer checked are queried...

**Comment by gnerred** [comment]
I don't know if it is related, but we have another query issue... layergroups are no more queried...
Go here below and try to query a colored building, it does not work...

https://preprod.cartoriviera.ch/v2/wsgi/mobile/theme/amenagement_du_territoire?lang=fr&baselayer_ref=orthos_2014_mobile&map_x=559082&map_y=143226&map_zoom=9&theme=amenagement_du_territoire&tree_group_layers_cadastre=batiments_egid%2Climite_commune%2Cbatiments_projetes&tree_groups=amenagement_du_territoire%2Cllavaux&tree_group_layers_amenagement_du_territoire=lpnms_1%2Clpnms_2%2Clpnms_3%2Clpnms_4%2Clpnms_5%2Clpnms_6%2Clpnms_7

**Comment by fredj** [comment]
With the given url, the queried layers are:
 - plan_cadastral_201703 (background layer)
 - batiments_egid
 - limite_commune
 - batiments_projetes

**Comment by gnerred** [comment]
And layers lpnms_1, lpnms_1, ..., lpnms_7 are missing from the query results

**Comment by fredj** [comment]
probably a regression caused by #2425
