### ISSUE TITLE
Zoom level problem in permalink between mobile and desktop CGXP

### ISSUE THREAD

**Issue by gnerred** [camptocamp/ngeo#2448]
Version 2.1.2.dev3

A same permalink does not go to same zoom level between mobile and desktop, but not for all zoom levels : 

Mobile
https://preprod.cartoriviera.ch/v2/mobile/theme/amenagement_du_territoire?lang=fr&tree_group_layers_enquetes_bti&tree_group_layers_zones_tampon_bti&tree_group_layers_amenagement_du_territoire=camac%2Ccamac_termine&tree_group_layers_llavaux&baselayer_ref=plan_cadastral_201703&tree_groups=amenagement_du_territoire%2Cllavaux&map_x=555303&map_y=146050&map_zoom=4

Desktop (without /mobile)
https://preprod.cartoriviera.ch/v2/theme/amenagement_du_territoire?lang=fr&tree_group_layers_enquetes_bti&tree_group_layers_zones_tampon_bti&tree_group_layers_amenagement_du_territoire=camac%2Ccamac_termine&tree_group_layers_llavaux&baselayer_ref=plan_cadastral_201703&tree_groups=amenagement_du_territoire%2Cllavaux&map_x=555303&map_y=146050&map_zoom=4

If you put map_zoom=7,8 or 9, there is no problem and maps are identical

**Comment by gnerred** [comment]
Other problem that seems to be related... when a permalink is opened on a real mobile device (tested on galaxy s6), the zoom level and coordinates are not taken into account...

**Comment by sbrunner** [comment]
You don't have the same resolutions list...
https://github.com/camptocamp/cartoriviera_geomapfish/blob/v2/cartoriviera/templates/desktop.js#L702
https://github.com/camptocamp/cartoriviera_geomapfish/blob/v2/cartoriviera/static-ngeo/js/mobile.js#L35

**Comment by gnerred** [comment]
You're right, my fault, I fixed the resolutions and now it works thanks !
