### ISSUE TITLE
NGEO mobile - permalink does not work with WMTS layers

### ISSUE THREAD

**Issue by gnerred** [camptocamp/ngeo#2470]
Version 2.1.2

To reproduce : 
1°/ Generate a permalink with CGXP application, here is one : https://preprod.cartoriviera.ch/v2/s/es2I 
2°/ Open the link in a new tab > you see a WMTS overlay layer (historic color map of 2000)
3°/ Add mobile/ after V2 in the URL > NGEO mobile opens, but the WMTS layer is not activated...

Tested with several WMTS layers of this theme, does not work.

**Comment by gnerred** [comment]
But with WMTS layers of the theme "Photos aériennes", it works...

**Comment by gnerred** [comment]
In the example above, when opening the short link, we have "tree_enable_plan_ville_vevey_2000=true"

After adding mobile/ in the URL, the value of "tree_enable_plan_ville_vevey_2000" is changed from "true" to "false" by GMF...

**Comment by sbrunner** [comment]
The short URL don't works anymore, can you update it?

**Comment by gnerred** [comment]
Oh sorry, I did an update that erased the permalinks... I have updated it in my first message.

**Comment by sbrunner** [comment]
Thanks @gnerred :-)

**Comment by fredj** [comment]
fixed with #2511
