### ISSUE TITLE
Query results window improvements

### ISSUE THREAD

**Issue by ybolognini** [camptocamp/ngeo#2497]
This is the issue to gather all improvements needed for the Query results window.

**Comment by rbovard** [comment]
Here are my issues:
* https://github.com/camptocamp/ngeo/issues/2383 --> Fixed in `2.1.2`
* https://github.com/camptocamp/ngeo/issues/2366 --> Fixed in `2.1.2`
* https://github.com/camptocamp/ngeo/issues/2371 --> Fixed in `2.1.2`
* https://github.com/camptocamp/ngeo/issues/2360
