### ISSUE TITLE
streetview RefererNotAllowedMapError

### ISSUE THREAD

**Issue by fredj** [camptocamp/ngeo#2503]
camptocamp.github.io referrer must be authorized in Google Maps API

**Comment by sbrunner** [comment]
Then testgmf.sig.cloud.camptocamp.net and geomapfish-demo.camptocamp.net also :-)

**Comment by sbrunner** [comment]
Then geomapfish-demo.camptocamp.net and testgmf.sig.cloud.camptocamp.net also :-)

**Comment by ybolognini** [comment]
Done.
