### ISSUE TITLE
QGIS only - Query looking in wrong layers when more than one is active

### ISSUE THREAD

**Issue by llienher** [camptocamp/ngeo#2509]
### Initial situation
The current issue is when multiple layers are displayed and a query is done against any of them. Some queries are not looking in the correct layer, result is not displayed in the info window.

This issue is visible and can be reproduced on the current project :
http://lb.lb.tich-sdi.caas.camptocamp.com/desktop?debug&lang=en&tree_group_layers_GWSZonen_group&baselayer_ref=blank&tree_groups=Punti_fissi_group%2CBeni_immobili_group%2CNomenclatura_group&tree_group_layers_Punti_fissi_group=pfa2%2Cpfa3

### Step to reproduce
- Go on the above url (should load the correct layers to reproduce this issue)
- The following layers are loaded : pfa2 and pfa3 (group layer punti_fissi / theme MOpublic). 
- Desactivate pfa2
- Select a point from pfa3, when this layer is displayed alone. Result is displayed in info window.
- Reactivate pfa2, click the same point. The query is done on layer pfa2 even if we know it's a point from pfa3 (we can check that via the request payload in browser debugger).

Another test:
- Load all three layers, and select a group of features (ctrl+left click) you know is on the pfa1 layers. As there is three layers active, the shown result is multiplied by three even if no features are to be requested on pfa2&pfa3. 

So a group of 4 features in pfa1 with all three layers active will show 12 results in the info windows, with 3 duplicates of each features.

**Comment by ger-benjamin** [comment]
That's specific to QGIS.
**We de the expected request to QGIS but it answers bad.** (bug only in QGIS side)

if we do a request with pfa1, pfa2 and pfa3, it will reply third times for pfa1 (twice with two layer, and one, correctly with one layer).
Our displayer doesn't understand why there is multiple time the exactly same data.

**Comment by ger-benjamin** [comment]
**See also -> https://issues.qgis.org/issues/16509**

**Comment by sbrunner** [comment]
Moved in 2.3 because it don't block the 2.2 release

**Comment by llienher** [comment]
Fixed with the the last 2.18.9 qgis minor. Closing it.
