### ISSUE TITLE
transformUrl is not a promise

### ISSUE THREAD

**Issue by oterral** [camptocamp/ngeo#2517]
In map.geo.admin, we use the import online component.
We would like to make a HEAD request first (to test CORS) before loading the resource. Currently we want to do it in the `transformUrl` function passed to the scope's `options` object so the `transformUrl` function should return a promise instead of an url.

But looking at the code I see others solutions:

1) Implement the HEAD request in handleFileUrl function in ngeo
2) Makes `transformUrl` function returning a promise
3) Allow to specify a custom `handleFileUrl` function via scope's  `options`  
 

Maybe solution 3 allows more possibilities.

What do you think?

**Comment by oterral** [comment]
@fredj @gberaudo ?

**Comment by gberaudo** [comment]
@oterral, happy easter!
Solution 3 seems more fragile to me: a change in the library may easily break application code. So I would rather go with solution 2.

**Comment by oterral** [comment]
@gberaudo happy easter too!!

Ok I see what I can do.
