### ISSUE TITLE
CGXP and NGEO together on desktop 

### ISSUE THREAD

**Issue by gnerred** [camptocamp/ngeo#2521]
Is it possible to have CGXP client and NGEO client running together on desktop application ? Or at least is there a way to easily switch between the two clients ? The goal is to be able to test NGEO desktop application on the pre-production environment, without installing another project. 

Thanks

**Comment by sbrunner** [comment]
You can add a link between the interfaces with to following code:
```
<a href="${request.route_url('cgxp_desktop')}">Legacy desktop</a>
```
and 
```
<a href="${request.route_url('desktop')}">New desktop</a>
```

**Comment by gnerred** [comment]
So it possible to have both interfaces running together on same project ? Is there a doc to configure desktop NGEO client ?

**Comment by sbrunner** [comment]
Yes it's here: http://camptocamp.github.io/c2cgeoportal/2.1/integrator/ngeo.html?highlight=ngeo#add-a-new-interface

**Comment by gnerred** [comment]
Thanks :O)
