### ISSUE TITLE
image scale in print

### ISSUE THREAD

**Issue by rmichaelis** [camptocamp/ngeo#2528]
Hi,

I try to print rectangular symbols, but the results don't look to what I'm expecting. 

What I have on the screen :
![image](https://cloud.githubusercontent.com/assets/5594996/25184238/2cd0dcf8-251a-11e7-9f72-447d90785db2.png)

Result in the PDF :

![image](https://cloud.githubusercontent.com/assets/5594996/25184386/90fc8650-251a-11e7-9811-00c3debe0557.png)

Only the circle in the middle is properly scaled.

After a quick look into ngeo I saw that graphicWidth and graphicHeight are properly computed from the scale. 
https://github.com/camptocamp/ngeo/blob/master/src/services/print.js#L625

But in mapfish-print, it seems that graphicHeight is never used. 
https://github.com/mapfish/mapfish-print/blob/master/core/src/main/java/org/mapfish/print/map/style/json/JsonStyleParserHelper.java#L220

Is the graphicHeight used in the print ? How may I do, to properly render my graphic ?

Thanks,

**Comment by sbrunner** [comment]
https://jira.camptocamp.com/browse/GSGMF-511
