### ISSUE TITLE
const ATTRIBUTION is declared twice

### ISSUE THREAD

**Issue by fgravin** [camptocamp/ngeo#2529]
https://github.com/camptocamp/ngeo/blob/dbe73a412fd26795727fac695722be0f90df7ea9/src/source/swisstopo.js#L15

https://github.com/camptocamp/ngeo/blob/54bfe0db8cd9133363f2f05f2c2ceea4cb8c88ed/src/source/asitvd.js#L13

can't work in dist mode

**Comment by ybolognini** [comment]
Not relevant with Webpack
