### ISSUE TITLE
ngeo.DataSource and gml format

### ISSUE THREAD

**Issue by fredj** [camptocamp/ngeo#2534]
It is currently possible to set the wfs output format (`options.wfsOutputFormat`) but the features are always read using the GML3 format

**Comment by ger-benjamin** [comment]
@fredj which milestone ?

**Comment by sbrunner** [comment]
For me we can merge it now :-)

**Comment by fredj** [comment]
merge #2535 and work on #2538 later?

**Comment by sbrunner** [comment]
Yes :-)
