### ISSUE TITLE
Add possibility to import WMTS layers with ngeo.import.importModule

### ISSUE THREAD

**Issue by Jenselme** [camptocamp/ngeo#2537]
Hi,

Currently we can import WMS layers with `ngeo.import.importModule`. Would you be interested in a PR that adds the possibility to import WMTS layers as well? I looked into it today and was able to put together a working solution. It still needs finishing before I can create a PR. Let me know if you are interested.

**Comment by fredj** [comment]
Thanks @Jenselme, a pull request will be highly welcomed

**Comment by Jenselme** [comment]
OK, I'll work on it then.
