### ISSUE TITLE
No more asking to save password from 2.1

### ISSUE THREAD

**Issue by gnerred** [camptocamp/ngeo#2542]
Version 2.1.2

Since migration from 1.6 to 2.1, it is no more asked to save password once entered. I have tried several browsers, but no one ask to save password. 

https://map.cartoriviera.ch

**Comment by sbrunner** [comment]
I just tested with Chrome and it's working...

**Comment by gnerred** [comment]
Yes you're right, I did not test Chrome. But it doesn't work with FF, IE and Chromium.

**Comment by fredj** [comment]
It's working for me with firefox 53 and chrome 58 (https://map.cartoriviera.ch/mobile/ and https://map.cartoriviera.ch/)

**Comment by sbrunner** [comment]
We just tested with IE 11 on Windows, Chome on Linux, Firefox on Windows and on Linux and everyone is working...

**Comment by gnerred** [comment]
Okay, I do not undestand, this issue has been related to me by other Cartoriviera users too... Impossible for me to make it ask for IE (tested on Browserstack). Ok for FF and Chrome on Browserstack. So the problem still remains for IE...

**Comment by fredj** [comment]
It's not working on Browserstack but it's working on a real Windows; maybe it's a "feature" of Browserstack?

**Comment by gnerred** [comment]
Okay, let's forget this issue...
