### ISSUE TITLE
Shadows in UI

### ISSUE THREAD

**Issue by rbovard** [camptocamp/ngeo#2600]
I noticed you removed the shadow in search input #2599. I thinks it's a good choice but why not apply it to all the UI?

Like on the panels:

![image](https://cloud.githubusercontent.com/assets/4549666/25845246/7b02bc8c-34ad-11e7-81f1-968d0121f86d.png)

I think shadow is a little outdated in modern web UI, what do you think?

**Comment by fredj** [comment]
Or it can be disable in your project by adding:
```css
main {
  box-shadow: none;
}
```
in `static-ngeo/less/mobile.less`

**Comment by rbovard** [comment]
Thanks for the hint but I think it's preferable to be consistent in fresh version.

**Comment by ybolognini** [comment]
Done
