### ISSUE TITLE
First level panel title

### ISSUE THREAD

**Issue by rbovard** [camptocamp/ngeo#2601]
When opening left and right panels, there is no title in the header

![image](https://cloud.githubusercontent.com/assets/4549666/25845465/4a1506b0-34ae-11e7-8952-44821490e482.png)

It appears only when a subpanel is open

![image](https://cloud.githubusercontent.com/assets/4549666/25845479/562426fc-34ae-11e7-91eb-10673a087c21.png)

My suggestion is to add default titles:
* Left panel: **Layers**
* Right panel: **Tools**

What do you think?

*BTW: a bold style for the title could be better*

**Comment by ybolognini** [comment]
--> GMF 2.4
