### ISSUE TITLE
Query issue with layer that's mark as query (WMS) but is not present as WFS

### ISSUE THREAD

**Issue by rbovard** [camptocamp/ngeo#2602]
* GeoMapFish version: `2.1.4`

[Permalink directly where we can reproduce the issue](https://map-demo.nyon.ch/v2/mobile/theme/accueil_enfance?lang=fr&baselayer_ref=asitvd.fond_couleur&tree_group_layers_affaires_sociales&tree_group_layers_secteurs_ecole=sct_ecole&tree_groups=secteurs_ecole&map_x=506515&map_y=138115&map_zoom=3)

Steps to reproduce the issue:

* Query the overlay layer

Result:

```
<ows:ExceptionText>msWFSGetFeature(): WFS server error. TYPENAME 'sct_ecole_geom2' doesn't exist in this server.  Please check the capabilities and reformulate your request.</ows:ExceptionText>
```

Expected result:

Same as on [desktop](https://map-demo.nyon.ch/v2/theme/accueil_enfance?map_x=506999.99999757&map_y=137849.99984252&map_zoom=3&tree_group_layers_secteurs_ecole=sct_ecole&tree_groups=secteurs_ecole&baselayer_opacity=100&baselayer_ref=asitvd.fond_couleur):

```
<msGMLOutput>
...
</msGMLOutput>
```

**Comment by rbovard** [comment]
@sbrunner I just tested in `2.1.8` and it's not working. Could you please re open this issue?

FYI the original is still valid to reproduce it.

**Comment by sbrunner** [comment]
How is it possible that your layer sct_ecole_geom2 is querryable but not available in the WFS?

**Comment by rbovard** [comment]
Only `sct_ecole_geom` is queriable, see https://github.com/camptocamp/nyon_c2cgeoportal/blob/v2/mapserver/mapfiles/accueil_enfance.map.mako#L1-L64

**Comment by sbrunner** [comment]
Actually sct_ecole_geom2 is also queryable, 
DUMP don't do anything, see http://mapserver.org/fr/mapfile/layer.html
To disable the WMS query you should remove the TEMPLATE tag, see: http://mapserver.org/fr/ogc/wms_server.html

**Comment by fredj** [comment]
@sbrunner @rbovard can we close this issue?

**Comment by rbovard** [comment]
Yep, thanks.
