### ISSUE TITLE
Mobile NGEO query on Android and Chrome does not work 

### ISSUE THREAD

**Issue by gnerred** [camptocamp/ngeo#2605]
Reproduced on 2.1.2 Cartoriviera and on 2.1.4 demo. When trying to query (touch) with Chrome on Android (tested on a Galaxy S6) it doesn't work. It seems the map moves a little bit, and query is not fired. No problem with native Android browser.

**Comment by rbovard** [comment]
It reminds me an old [issue](https://github.com/camptocamp/c2cgeoportal/issues/1201), I was just 1.5 year earlier than you @gnerred ;)

**Comment by fredj** [comment]
@gnerred can you try if this is better in this demo https://codepen.io/anon/pen/QvOPzp ?

**Comment by gnerred** [comment]
@rbovard yes, but it was an issue with Sencha touch...  ;O)

**Comment by gnerred** [comment]
@fredj same problem with your link...

**Comment by fredj** [comment]
related to https://bugs.chromium.org/p/chromium/issues/detail?id=632067

**Comment by rbovard** [comment]
So what do you propose?

**Comment by fredj** [comment]
it will be fixed in OpenLayers

**Comment by gnerred** [comment]
Any idea of the delay ?

**Comment by fredj** [comment]
should be fixes in the next few days

**Comment by fredj** [comment]
@gnerred can you try again https://codepen.io/anon/pen/QvOPzp  ?

**Comment by gnerred** [comment]
@fredj now it works :O) 

Will it be automatically fixed in next release of GMF 2.1 ?

**Comment by fredj** [comment]
> Will it be automatically fixed in next release of GMF 2.1 ?

yes, if we update the OpenLayers version in 2.1
let's keep this issue open to not forget to do it

**Comment by fredj** [comment]
Will be fixed in the master branch with #2624

**Comment by rbovard** [comment]
Master = 2.2 ?

**Comment by fredj** [comment]
yes, 2.2

I'm preparing a backport of OpenLayers for the 2.1 branch

**Comment by fredj** [comment]
Can be tested here (2.1 + OpenLayers fix):
https://camptocamp.github.io/ngeo/update_ol_2.1/examples/contribs/gmf/apps/mobile

**Comment by gnerred** [comment]
Thank it works

**Comment by fredj** [comment]
fix merged into 2.1
