### ISSUE TITLE
Curly brackets visible in browser tab title before Angular initialization

### ISSUE THREAD

**Issue by llienher** [camptocamp/ngeo#2618]
Currently the app translations are loaded when Angular finishes loading. 
Title is defined in the templates as:  
```
<title>{{'Desktop Application'|translate}}</title>
```

This result to some curly brackets briefly showing in the browser tab page title, as: 
> {{ 'Application Desktop'|translate }}

> {{ 'Application Mobile'|translate }}

The solution I found was to replace with the following code:
```
<title ng-bind-template="{{'Desktop Application'|translate}}"> Desktop Application </title>
```
The default value (here 'Desktop Application' as well) is of course adaptable in each project.

**Comment by ybolognini** [comment]
Please put 'GeoMapFish' instead of 'Desktop Application'
