### ISSUE TITLE
Geolocation does not work anymore in GMF 2.1

### ISSUE THREAD

**Issue by gnerred** [camptocamp/ngeo#2620]
Geolocation does not work anymore on ngeo mobile. Nothing happens with touching the geolocation button. Strange, because it worked some weeks ago, with the same version... 

Tested on Android native and Chrome, with https://map.cartoriviera.ch/mobile (2.1.2) and demo https://geomapfish-demo.camptocamp.net/2.1/mobile (2.1.4)

On Chrome desktop, there is an error displayed on map : "Network location provider at 'https://www.googleapis.com/' : Returned error code 400." Don't know if it is related or not.

**Comment by sbrunner** [comment]
I just tested on Chrome Linux and Android and it's looks working well, any other feedback?

**Comment by fredj** [comment]
It's working for me with Chrome 58 on a Nexus 5x

**Comment by gnerred** [comment]
Oh sorry, it was related to a configuration on my phone :O( !

**Comment by gnerred** [comment]
Thanks for fast feedback
