### ISSUE TITLE
Import WMTS and capabilities URL

### ISSUE THREAD

**Issue by Jenselme** [camptocamp/ngeo#2622]
Hi,

In #2543 in [src/modules/import/wmtsgetcap.js](https://github.com/camptocamp/ngeo/pull/2543/files#diff-f151565514501ede85331a91ce88cb83R41), I store for each layer a `capabilitiesUrl`. This is useful to automatically reimport the layer later on from the capabilities file. I currently get it from:
```js
getCap['OperationsMetadata']['GetCapabilities']['DCP']['HTTP']['Get'][0]['href']
```

I did my tests with WMTS from swisstopo. In these capabilities, `getCap['OperationsMetadata']['GetCapabilities']['DCP']['HTTP']['Get'][0]['href']` correctly contains the capabilities URL. But, from what I see, it is not the case for most WMTS. My question is, how should I handle this? I see several options:

1. Add a `ngeo-wmts-get-cap-url` attribute to the directive so the user can pass the proper URL. Use the value from `getCap['OperationsMetadata']['GetCapabilities']['DCP']['HTTP']['Get'][0]['href']` if it is undefined.
1. Add a `ngeo-wmts-get-cap-url` attribute to the directive so the user can pass the proper URL. Leave the value empty if it is undefined.
2. Do nothing, let the user correct the URL if needed.

What do you think?

**Comment by Jenselme** [comment]
Any opinion on this?

**Comment by oterral** [comment]
Why not using the url you used to get the GetCapabitlites instead of getting through the xml?

**Comment by oterral** [comment]
I've my answer. Sometime it's not the same url like this one https://www.basemap.at/wmts/1.0.0/WMTSCapabilities.xml

**Comment by Jenselme** [comment]
@oterral indeed. That's why I think using the URL used to get the XML is more reliable. My question is more: where should it be fixed. In ngeo or in the application that uses the component.

**Comment by sbrunner** [comment]
I think that the solution 2 is the best, finally I think that we don't need this URL, it's just informational :-)

**Comment by Jenselme** [comment]
Should I create a PR for option 2 then?

**Comment by sbrunner** [comment]
+1 for me :-)
