### ISSUE TITLE
Issue with params in desktop redirection

### ISSUE THREAD

**Issue by rbovard** [camptocamp/ngeo#2625]
* GeoMapFish version: `2.1.x` (your demo)

Permalink directly where we can reproduce the issue: https://geomapfish-demo.camptocamp.net/2.1/mobile/

Steps to reproduce the issue:

* Check content of link `Passer à la version standard`

Result:

* URL **without** params https://geomapfish-demo.camptocamp.net/2.1/wsgi/desktop?no_redirect=

Expected result:

* Reload the mobile page with F5
* Check content of link `Passer à la version standard`
* URL **with** params https://geomapfish-demo.camptocamp.net/2.1/wsgi/desktop?lang=fr&tree_group_layers_Enseignement=bus_stop&baselayer_ref=OSM&no_redirect=&tree_groups=Enseignement&map_x=507492&map_y=137740&map_zoom=6

**Comment by sbrunner** [comment]
It's not a permalink..., then this is because you call the mobile page without any parameters ...

**Comment by rbovard** [comment]
But with parameters stored in local storage...

**Comment by sbrunner** [comment]
The local storage is the same on the desktop application, we should just use it event if we have the no_redirect= argument :-)

**Comment by rbovard** [comment]
Nice, thanks.
