### ISSUE TITLE
Contextual data - latitude / longitude

### ISSUE THREAD

**Issue by kalbermattenm** [camptocamp/ngeo#2641]
I do not know if this is done on purpose, but for the WGS84 coordinates, once it shows longitude / latitude (decimal version) and once latitude / longitude (DMS version).

Would it not be more consistent to use the same order for both of them ? (or if not, what is the point in doing so...?)

![image](https://cloud.githubusercontent.com/assets/1681332/26158715/e1433736-3b1c-11e7-9ebb-2cae7de18905.png)

**Comment by sbrunner** [comment]
Any opinion @yjacolin?

**Comment by rbovard** [comment]
Lat / Long is more usual I think, it's also the choice of GeoAdmin: https://help.geo.admin.ch/?id=12&lang=fr

**Comment by yjacolin** [comment]
Progamer will use lon, lat as it stand (in some way) for x,y but geographer would prefer lat, lon. There is so much discussion about the right order if you google it :)

That's why we have some much headache now with WMS version 1.3.0 vs version  1.2.0 :p

**Comment by sbrunner** [comment]
Then we should use Lat / Long in booth case, @yjacolin the big error made by the OGC people is to have sometimes lon/lat and other times lat/lon in the data structure, this is completely crazy but it how the OGC writ the standards. The display part is an other thing :-)
