### ISSUE TITLE
Add documentation for query parameters

### ISSUE THREAD

**Issue by pfirpfel** [camptocamp/ngeo#2658]
It would be useful to have a list of all available query parameters including their type, purpose, etc.

**Comment by ger-benjamin** [comment]
Please always add a label 'ready' and a milestone for our dashboard

**Comment by ger-benjamin** [comment]
@pfirpfel I don't understand what you mean by "available query parameters". Can you be more precise please ?

**Comment by pfirpfel** [comment]
More or less the application state the permalink feature "persists" in the URL. 

Simple ones include map_x and map_y to center the map on specific coordinates. More complex ones are the layer tree configuration with all the acitve layers.

As far as I know there is no documentation on this, we can refer to when customers ask about it.

**Comment by ger-benjamin** [comment]
Thanks :ok_hand:  I understand now

**Comment by sbrunner** [comment]
https://jira.camptocamp.com/browse/GSGMF-513
