### ISSUE TITLE
gmf-mobile-measurelength-decimals is not used

### ISSUE THREAD

**Issue by ochriste** [camptocamp/ngeo#2664]
the mobileMeasureLengthDirective api
http://camptocamp.github.io/ngeo/master/apidoc/gmf.mobileMeasureLengthDirective.html
say we can use a gmf-mobile-measurelength-decimals option.
but that option value is never used,
see:

https://github.com/camptocamp/ngeo/blob/master/src/ol-ext/interaction/measure.js#L275-L285

since the decimal, according to @sbrunner has no meaning (see with him directly), remove that unused gmf-mobile-measurelength-decimals option

**Comment by sbrunner** [comment]
Or replaced it by precision and use it...
