### ISSUE TITLE
ngeo: scaleselector example no scale labels

### ISSUE THREAD

**Issue by fgravin** [camptocamp/ngeo#2671]
In https://camptocamp.github.io/ngeo/master/examples/scaleselector.html
The scale `select` input does not display the label of the scales

![image](https://cloud.githubusercontent.com/assets/1491924/26828370/6982ab96-4ac1-11e7-9a65-2779e37e080a.png)

**Comment by ger-benjamin** [comment]
Please always add a label 'ready' and a milestone for our dashboard
