### ISSUE TITLE
ngeo: mapquery examples do not list the features

### ISSUE THREAD

**Issue by fgravin** [camptocamp/ngeo#2672]
In https://camptocamp.github.io/ngeo/master/examples/mapquery.html
When querying the features layer, we see in the tab title the number of features but we don't see the list of features as expected in the example.

Same for https://camptocamp.github.io/ngeo/master/examples/bboxquery.html

**Comment by ger-benjamin** [comment]
Please always add a label 'ready' and a milestone for our dashboard

**Comment by ger-benjamin** [comment]
Closedwith #3025
