### ISSUE TITLE
Date filters crash

### ISSUE THREAD

**Issue by ybolognini** [camptocamp/ngeo#2679]
When setting a date in a filter, the result map is empty (0 byte response). The problem is for all dates, not only for Time layers.

Tested on desktop_alt with "Filtres" layers.

**Comment by adube** [comment]
It seems to be working from my side.  See the following url with TIME param:

https://geomapfish-demo.camptocamp.net/2.2/wsgi/mapserv_proxy?ogcserver=Main+PNG&cache_version=58cddeaa36774ca5a1227d4759185a25&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=osm_time2&TIME=2006-12%2F2013-11&SERVERTYPE=mapserver&CRS=EPSG%3A21781&STYLES=&WIDTH=1386&HEIGHT=1311&BBOX=532555.3249654942%2C156338.1499309886%2C539485.3249654942%2C162893.1499309886

Would you please give me more details the problem?

**Comment by adube** [comment]
Here's an example of query that returns an error.

https://geomapfish-demo.camptocamp.net/2.2/wsgi/mapserv_proxy?ogcserver=Main+PNG&cache_version=58cddeaa36774ca5a1227d4759185a25&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=osm_open&SERVERTYPE=mapserver&FILTER=%3CFilter%20xmlns%3D%22http%3A%2F%2Fwww.opengis.net%2Fogc%22%3E%3CPropertyIsEqualTo%3E%3CPropertyName%3Etimestamp%3C%2FPropertyName%3E%3CLiteral%3E1497276222038%3C%2FLiteral%3E%3C%2FPropertyIsEqualTo%3E%3C%2FFilter%3E&CRS=EPSG%3A21781&STYLES=&WIDTH=467&HEIGHT=1311&BBOX=533519.7130346831%2C150958.55030553328%2C538189.7130346831%2C164068.55030553328

Seeing the error log would be helpful.
