### ISSUE TITLE
Query tolerance on NGEO mobile is too big

### ISSUE THREAD

**Issue by gnerred** [camptocamp/ngeo#2684]
Query tolerance on real mobile device is too big. Too much feature as expected are reurned (V 2.1.7). To reproduce : 

1°/ Go to https://map.cartoriviera.ch/main/wsgi/mobile/theme/amenagement_du_territoire?lang=fr&tree_groups=amenagement_du_territoire%2Cllavaux&tree_group_layers_amenagement_du_territoire=plans_speciaux&tree_group_layers_llavaux&baselayer_ref=plan_cadastral&map_x=556964&map_y=147166&map_zoom=8 on a real mobile device
2°/ Touch parcel 186 -> 3 to 5 parcels are returned, but we expect to recieve only the 186, because it is big enough on screen. This can be disturbing for user

Is there a way to configure that tolerance ? It is not related to mapserver tolerance, because same it cannot be reproduced with mobile application on a desktop browser.

**Comment by sbrunner** [comment]
Yes it's configurable you should define something like this in the controller js file:
```
  gmf.module.value('ngeoQueryOptions', {
    'tolerance': 10
  });
```

**Comment by gnerred** [comment]
Is it right to put it like that ? If yes, it has no effect. 

cartoriviera.MobileController = function($scope, $injector) {
  gmf.AbstractMobileController.call(this, {
    srid: 21781,
    mapViewConfig: {
      center: [559045, 144195],
      zoom: 3,
      resolutions: [50,20,10,5,2.5,2,1.5,1,0.5,0.25,0.1,0.05,0.025]
    }
  }, $scope, $injector);

  /**
   * @type {Object.<string, gmf.MobileMeasurePointController.LayerConfig>}
   * @export
   */
  this.elevationLayersConfig = {
    'mns': {unit: 'm'},
    'mnt': {unit: 'm'},
    'rayglobal': {unit: 'kwh/m2/an'}
  };  
  
  /**
   * @type {Array.<string>}
   * @export
   */
  this.searchCoordinatesProjections = ['EPSG:21781', 'EPSG:2056', 'EPSG:4326'];

  gmf.module.value('ngeoQueryOptions', {
    'tolerance': 1
  });	
  
};

**Comment by sbrunner** [comment]
no, it should be outside of the constructor ...

**Comment by gnerred** [comment]
Thanks now it works fine :O) !

**Comment by sbrunner** [comment]
:-)
