### ISSUE TITLE
Translation of "User denied Geolocation" on mobile devices

### ISSUE THREAD

**Issue by gnerred** [camptocamp/ngeo#2691]
When trying to geolocate on a mobile device, if GPS is not active, the user gets an error message "User denied Geolocation" (see attached image). It seems that it is not possible at this time to translate this message, but it is necessary to do it. 

![image](https://user-images.githubusercontent.com/1989467/27134139-e9ea9326-5114-11e7-8316-83cffbedcd07.png)

**Comment by ger-benjamin** [comment]
I tag it 2.1, you use this version, right ?

**Comment by gnerred** [comment]
Yes right

**Comment by ger-benjamin** [comment]
We transmit the error directly from the device.
So if your device is in French, I hope that you get a French error.

Otherwise, do you want **one** generic error message (that we can internalionalize ?)

( include @ybolognini )

**Comment by gnerred** [comment]
My device is in french, and I get the error in english... Yes it should be a generic error, that explains to the user what to do. 

But I think it should be in 2.1, because some other users want to get in production with 2.1, and I think it is an important point for UI.

**Comment by sbrunner** [comment]
Possible error codes: https://developer.mozilla.org/fr/docs/Using_geolocation

**Comment by ger-benjamin** [comment]
Same here: https://www.w3.org/TR/geolocation-API/#position-error
 That's not perfect, for instance, yet I get a "Unable to connect... bla..." if I'm not connected. And that's an error 2: position_unavailable. So we will lost some information.
But ok, I'll make one different error for each code (3 + 1 for other cases).

**Comment by gnerred** [comment]
Thanks @ger-benjamin for adding this translation ! Could you please explain how to translate these mobile messages ? Like other strings of application ?

**Comment by gnerred** [comment]
@ger-benjamin , could you please explain how to translate these mobile messages ?

**Comment by ger-benjamin** [comment]
In transifex. But we forgot to translate the new strings in ngeo 2.1.
What do you think about:

Géolocalisation: Vous n’avez pas donné la permission (for Permission denied)
Géolocalisation: La position n’a pu être déterminée (for a position unavailable)
Géolocalisation: Délais de recherche dépassé (for a timeout)
Géolocalisation: Erreur inconnue (for an unknow error)

**Comment by ger-benjamin** [comment]
Mhhh, And I just see that my PR was not good. I must use "real english" and not "technical english". Because now the english translation is ugly. I'll change that right now

**Comment by gnerred** [comment]
Ok for the new strings, thanks.
