### ISSUE TITLE
iOS 10 safari UI overlaps with gmf 2.1

### ISSUE THREAD

**Issue by llienher** [camptocamp/ngeo#2695]
The problem appears on Safari for iOS 10. All devices were using iOS 10.3.2 (last stable version). I saw that this issue appears on Iphone 5S and Iphone 5C by clients as well in my own tests on Browserstack with more recent devices using this version of iOS. So it seems it is more about the OS version that the devices itself.

Reproduced on GMF 2.1.4 on landscape orientation.

Screen from the client:
![img_0669](https://user-images.githubusercontent.com/25748389/27140812-caabe340-5126-11e7-8113-6f2a87473594.PNG)

**Comment by llienher** [comment]
Few research and tests about this problem again today.

My test found that on iOS10 (Browserstack with iphone7/7 Plus) changing orientation from portrait to landscape then opening the safari bar, gmf overlapsed. 
However orienting my device in landscape then reloading the page will load everything fine. 

So basically, opening the Safari bar while it is first closed will trigger the ovelapsing issue, while just loading the page, keeping the bar open, will not. Again I'm not totally sure, being not able to test it with a physical device using iOS10... 

I found the following information in the Safari 10.0 changelog for the native API (WKWebView Behavior with Keyboard Displays):
> Safari and WKWebView on iOS 10 do not update the window.innerHeight property when the keyboard is shown. On previous versions of iOS WKWebView would update the window.innerHeight property when the keyboard is shown.

Source here: https://developer.apple.com/library/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_10_0.html#//apple_ref/doc/uid/TP40014305-CH11-SW38

**Comment by fredj** [comment]
I've checked this again: no solution to this issue. All the previous CSS hacks are not working on iOS 10 +

**Comment by ybolognini** [comment]
@llienher For iOS, move search + menu bar down so we can still use GMF
