### ISSUE TITLE
Geolocation problem with ngeo mobile

### ISSUE THREAD

**Issue by gnerred** [camptocamp/ngeo#2706]
Version 2.1.7, reproduced with an iPhone 7

Several users reported me problems with geolocation precision. The old Sencha touch application gave an accurate position when touching geolocation button in a forest on Montreux montains. Since ngeo mobile, the same procedure with the same device gives a point in the middle of the lake with an giant circle around. With Google Maps, no problem. This is a very annoying issue, because since ngeo mobile, it is not more possible to use geolocation in forest (in city it seems to be OK...). It seems that something is configurated differently between OL2 Sencha Touch and OL3 ngeo...

Can be reproduced with map.cartoriviera.ch

**Comment by fredj** [comment]
@gnerred should be fixed with #2707 (untested)

**Comment by gnerred** [comment]
Ok thanks. Will it be integrated in next release of 2.2 and 2.1 ?

**Comment by gnerred** [comment]
Tested, it works.

**Comment by gnerred** [comment]
@sbrunner , could you please add the tag 2.2 ?

**Comment by fredj** [comment]
@gnerred the fix is now merged, it willbe in 2.1 and 2.2

**Comment by gnerred** [comment]
Thanks !
