### ISSUE TITLE
Background layer query does not work anymore on NGEO 2.2

### ISSUE THREAD

**Issue by gnerred** [camptocamp/ngeo#2712]
Since 2.2, it is no more possible to query a background layer on NGEO mobile : 

Version 2.2.0rc2, query does not work : 
https://preprod.cartoriviera.ch/mobile/theme/default_mobile?lang=fr&tree_group_layers_mobilite=points_vente_vmcv%2Ctp_arret_bus%2Ctp_ligne_bus%2Ctp_arret_train%2Ctp_ligne_train&baselayer_ref=plan_cadastral&map_x=555477&map_y=145313&map_zoom=9&theme=default_mobile&tree_groups=cadastre%2Ccouverture_du_sol

Version 2.1.7, query works : 
https://map.cartoriviera.ch/mobile/theme/default_mobile?lang=fr&baselayer_ref=plan_cadastral&tree_group_layers_mobilite=tp_arret_bus%2Ctp_ligne_bus%2Ctp_arret_train%2Ctp_ligne_train&map_x=555415&map_y=145137&map_zoom=8&theme=default_mobile&tree_groups=cadastre%2Ccouverture_du_sol

**Comment by ger-benjamin** [comment]
I can reproduce it and understand the bug.
We create a datasource for the the background layers but we never add it to the ngeoDatasources (used for the query).

Just to try if I add this line here: `this.ngeoDataSources_.push(this.dataSourcesCache_[7506]`) here: https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/src/services/datasourcesmanager.js#L171
I'm able to query the background (7506 is the id of the background queryable layer)

**Comment by gnerred** [comment]
Ok, I wait for next RC...
