### ISSUE TITLE
backgroundlayer example not working

### ISSUE THREAD

**Issue by fredj** [camptocamp/ngeo#273]
http://camptocamp.github.io/ngeo/master/backgroundlayer.html

The select element is empty

**Comment by asaunier** [comment]
It seems that some included files are 404:
http://camptocamp.github.io/ngeo/utils/watchwatchers.js 
http://camptocamp.github.io/ngeo/master/angular.min.js.map

**Comment by fredj** [comment]
@asaunier see #278
