### ISSUE TITLE
print: zIndex not respected

### ISSUE THREAD

**Issue by fredj** [camptocamp/ngeo#2731]
The layers list should be sorted by zIndex

**Comment by ybolognini** [comment]
Is this important? Should it be corrected in 2.2? 
Please set label and milestone
@sbrunner @fredj

**Comment by sbrunner** [comment]
I don't understand this issue ...

**Comment by fredj** [comment]
In OpenLayers, the order of the layers displayed on the depends on the order they have been added and on the `zIndex` property of the layer. The print service must use the `zIndex`

**Comment by sbrunner** [comment]
OK, but it don't concern GeoMapFish :-)

**Comment by fredj** [comment]
Note: this issue affects schweizmobil

**Comment by gberaudo** [comment]
Yes, would be great to have it directly handled inside mapfish-print.
The print should accept an optional `zIndex` property and sort the layers accordingly.

**Comment by fredj** [comment]
fixed with #3663
