### ISSUE TITLE
Problem when rotating mobile NGEO with iOS 10

### ISSUE THREAD

**Issue by gnerred** [camptocamp/ngeo#2741]
When rotating device twice with mobile NGEO (tested on 2.1 and 2.2), the map is streched. It has been reproduced on several latest iOS devices (only with iOS 10 on Safari AND Chrome) and on Cartoriviera application (https://map.cartoriviera.ch) AND official demo application (https://geomapfish-demo.camptocamp.net/2.2/mobile/). 

This is a relative important issue that has to be fixed ASAP. 

![image](https://user-images.githubusercontent.com/1989467/28108961-a99ae64c-66ed-11e7-80cc-221867747b53.png)

**Comment by gnerred** [comment]
Can be reproduced on Browserstack, not necessary to have a real device

**Comment by fredj** [comment]
see also #2695

**Comment by gnerred** [comment]
Please set a milestone (2.2) to this issue, just to not forget to fix it... thanks

**Comment by adube** [comment]
Note to self:



```
  // Adapt the map size to avoid stretching
  window.onresize = function() {
    // Necessary due to the 0.3s transition on the main element.
    const start = Date.now();
    let loop = true;
    const adjustSize = function() {
      controller.map.updateSize();
      controller.map.renderSync();
      if (loop) {
        window.requestAnimationFrame(adjustSize);
      }
      if (Date.now() - start > 300) {
        loop = false;
      }
    };
    adjustSize();
  };
```
