### ISSUE TITLE
Drawing: rotation lost when resizing a rectangle

### ISSUE THREAD

**Issue by llienher** [camptocamp/ngeo#2742]
I don't know if it is a current limitation or a new issue. 
When drawing a rectangle, then rotate it (right click action), the resize action will reset the rotation.

**Comment by ybolognini** [comment]
This is clearly a bug. This works on 2.1 demo

**Comment by llienher** [comment]
The simplification done in https://github.com/camptocamp/ngeo/pull/2637 break the rotation support.
In reason of feature breaking over a bugfix, I'm reverting the code to the previous state.

- [x] Revert to previous commit on modifyrectangle.js
- [ ] Find a solution to ngeo.interaction.ModifyRectangle creating triangle: https://github.com/camptocamp/ngeo/issues/2611
