### ISSUE TITLE
Drawing: azimut angles are too precise

### ISSUE THREAD

**Issue by ybolognini** [camptocamp/ngeo#2756]
This is the case on 2.2 demo and master but not in 2.1 demo
![drawing_angle](https://user-images.githubusercontent.com/1180264/28270462-db9b7d7a-6b05-11e7-8693-f8c4f6042f17.png)

**Comment by llienher** [comment]
We forgot to set the settings specific to this parameter in the js or html files in the demo. This is more likely to be different for each projects.

If i'm not wrong, default value will show 3 decimals if nothing else is given.

Here is an exemple to set to two decimals in the html:
`module.value('ngeoMeasureDecimals', 2);`

Or in the js file:
`gmf.module.value('ngeoMeasureDecimals', 2);`

**Comment by llienher** [comment]
Fixed on gmf demo: https://github.com/camptocamp/demo_geomapfish/commit/e85e605d4da9bd81903b2d3a768c9ba8f3822714

**Comment by sbrunner** [comment]
Steel be on https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/desktop/
and this camptocamp/demo_geomapfish@e85e605 is not a good solution :-(
