### ISSUE TITLE
Demo: layers "time value" don't work

### ISSUE THREAD

**Issue by ybolognini** [camptocamp/ngeo#2785]
On mobile and desktop. On all browsers.

Querying while layers "time value" is enabled, group "Fonctions OSM mixed", sub-group "Temps OSM" gives a JS error: 

`ReferenceError: moment is not defined`

**Comment by fredj** [comment]
Note: it works on https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/desktop
