### ISSUE TITLE
Print dpi problem with QGIS Server

### ISSUE THREAD

**Issue by ybolognini** [camptocamp/ngeo#2793]
Originally discussed in https://github.com/camptocamp/ngeo/issues/2654

1°/ Go to https://preprod.cartoriviera.ch/s/Hvds
2°/ Do a print on the red lines -> symbols are too small in PDF result

The problem is that the print in the CGXP interface doesn't use the server type; the value is fixed to `mapserver`. See:
https://github.com/camptocamp/cgxp/blob/master/core/src/script/CGXP/plugins/Print.js#L344-L347

@fredj says: Need to be checked with @ger-benjamin and @sbrunner but the following code could be added to the project to set the correct serverType when encoding the wms layer:

```
printProvider.on('encodelayer', function(printProvider, layer, encodedLayer) {
  if (encodedLayer.baseURL.indexOf('qgis') > -1) {
    Ext.apply(encodedLayer, {
      serverType: 'qgisserver'
    }
  });
});
```

**Comment by sbrunner** [comment]
@gnerred the permalink don't works anymore :-(

**Comment by gnerred** [comment]
Now it works again :-)

**Comment by sbrunner** [comment]
sorry I just miss that's we should be login :-)

**Comment by sbrunner** [comment]
:-)

**Comment by sbrunner** [comment]
@gnerred Can you test if it's working as you expected here?
https://preprod.cartoriviera.ch/sbrunner/theme/cadastre?map_x=554199.7689876&map_y=145508.640031&map_zoom=9&tree_group_layers_cadastre=&tree_group_layers_couverture_du_sol=&tree_enable_export_reach=true&tree_enable_export_wastewater_structure=true

**Comment by gnerred** [comment]
Yes now it seems to run OK :-), thanks !
