### ISSUE TITLE
Filter issue with 2 layers

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/ngeo#2802]
Steps to reproduce the issue:

* Open https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/desktop_alt/
* Open the Démo theme
* De-select all the layers (don't remove)
* Select the layer Filtre/Overture OSM
* Open Filter
* Select Overture OSM (in filter)
* Add a filter
* => Not working :-(
* De-select the layer (in the layer tree)
* Open Function OSM mixed/Overture OSM
* => it's working ...

(in some cases it's the inverse ...)

**Comment by fredj** [comment]
The reason is that the "Ouverture OSM" layer is present in two groups: "Functions OSM mixed" and "Filter".

The filter is applied to the layer in the first group which is not visible

**Comment by fredj** [comment]
ping @sbrunner

**Comment by fredj** [comment]
Other issue:
 * Open https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/desktop_alt/
 * Open the Demo theme
 * Click "clear all" in the layer tree
 
-> The layer list in the filter should be empty

**Comment by fredj** [comment]
My previous remark was not an error, the layer "OSM map" that stays in the list is a background layer.

**Comment by fredj** [comment]
The problem with this "osm_open" layer is that we have two OpenLayers layer in the map but only one dataSource
