### ISSUE TITLE
Filter - Print

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/ngeo#2805]
* Open http://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/desktop_alt/
* Clear all
* Open theme filter
* Select only the layer ouverture OSM
* Add a filter on this layer (e.g. filter on a circle)
* Open the print panel
* => the filter isn't visible anymore is it releay what we want?
* Print
* => The ouverture OSM layer isn't printed (In the print request we have `customParams: {FILTER: null}`)

**Comment by ger-benjamin** [comment]
Reproduced in EPFL but "bug" case different:
 - Login in EPFL
 - print

Layers aren't printed.
Background layer is faded.

One request contains "FILTER=NULL" (see it in the apache log during a print task). If you paste this request you get an error. (filter can't be null). If you remove this filter, you see the layer.

**Comment by fredj** [comment]
I've tried to update mapfish print to the latest version but it didn't fix this issue.

**Comment by fredj** [comment]
@sbrunner what about changing the filter code in ngeo to remove the `FILTER` param is the value is empty?
https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/src/services/datasourcesmanager.js#L643-L675

**Comment by sbrunner** [comment]
Looks good to me :-)
