### ISSUE TITLE
gh-pages branch keeps increasing repository size

### ISSUE THREAD

**Issue by romanzoller** [camptocamp/ngeo#2815]
Every time I fetch ngeo after a few days, I see that the repo size has increased by several MiB.
As far as I can tell, this is mostly due to frequent large commits on the gh-pages branch by travis, done through `buildtools/deploy.sh`. Do we really need to keep the history of the gh-pages branch, or could the script instead just replace what is there? This seems to be the typical workflow for gh-pages, see e.g. [here](https://www.npmjs.com/package/deploy-to-gh-pages).

(The problem that I'm trying to address is not the few MiB I have to fetch every few days, but the fact that cloning ngeo from scratch takes a lot of time, and I think gh-pages is a significant part of that.)

**Comment by fredj** [comment]
see also #2274

**Comment by sbrunner** [comment]
> Do we really need to keep the history of the gh-pages branch

no

> could the script instead just replace what is there?

Personally I think that's dangerous especially because more than one job do some change in gh-pages ...

**Comment by sbrunner** [comment]
One big part of the heavy commit will be on the build files, that can be better when we will use webpack.

**Comment by sbrunner** [comment]
I just simplify the history :-)

**Comment by ybolognini** [comment]
Fixed
