### ISSUE TITLE
GMF 2.2.0rc5 - upgrading

### ISSUE THREAD

**Issue by kalbermattenm** [camptocamp/ngeo#2820]
I am upgrading from 2.2.0rc2 to 2.2.0rc5. I used to use a property of the `gmf.ThemeManager` to watch the current theme name (see https://github.com/camptocamp/sitn_c2cgeoportal/blob/v2/sitn/static-ngeo/js/desktop.js#L115-L127). It seems that this property has been renamed and gone private.

Is there any reason why this was done ? And is there any way to retrieve the theme name ?

Error log when building:
```
node node_modules/ngeo/buildtools/build.js .build/desktop.json .build/desktop.js
info ol Parsing dependencies
info ol Compiling 588 sources
ERR! compile C:/git_projects/sitn_c2cgeoportal/sitn/static-ngeo/js/desktop.js:118: ERROR - Property themeName never defined on gmf.ThemeManager
ERR! compile       return this.gmfThemeManager_.themeName;
ERR! compile                                    ^^^^^^^^^
ERR! compile
ERR! compile
ERR! compile 1 error(s), 0 warning(s), 96.7% typed
ERR! compile
ERR! Process exited with non-zero status, see log for more detail: 1
make: *** [CONST_Makefile:931: .build/desktop.js] Error 1
```

**Comment by fredj** [comment]
The `themeName` was made private in #2736

You can change you're code to `return this.gmfThemeManager_.getThemeName();`

**Comment by kalbermattenm** [comment]
+1, thanks a lot @fredj, I missed this one !

Closing
