### ISSUE TITLE
Layertree: Show visual indicator, that layers are being loaded right now

### ISSUE THREAD

**Issue by pfirpfel** [camptocamp/ngeo#2845]
Currently it only shows "Loading..." as the content of the layertree dropdown during the initial loading procedure of the application. If a user logs in, it can take quite a while for the layertree to load all the new content. During this time period there is no visual indicator to the user, that the application is doing something.

Proposed change:
Display "Loading..." everytime as the content of the layertree dropdown as long the layertree is loading content.

This should work in flush and non-flush-mode.

**Comment by ger-benjamin** [comment]
Please always add a label 'ready' and a milestone for our dashboard

**Comment by fredj** [comment]
So it takes a long time to have a response the auth server and to load the themes ?

**Comment by pfirpfel** [comment]
The themes call takes seconds in this particular case, because it contains about 1k layers.

**Comment by fredj** [comment]
fixed with #3077
