### ISSUE TITLE
Filters are case sensitive

### ISSUE THREAD

**Issue by yjacolin** [camptocamp/ngeo#2855]
## Steps to reproduce the issue

* create a filter with an upper case for the value if the value in the database is lower case

## Result
* No result

## Expected result
* result of the query with all case (upper and lower)

PostgreSQL request send by MapSever used ~ operator instead of ~* (to mean not case sensitive). There should be something similar in the WFS request.

**Comment by fredj** [comment]
@ybolognini do we have something about it in the specs?

**Comment by ger-benjamin** [comment]
Please always add a label 'ready' and a milestone for our dashboard

**Comment by sbrunner** [comment]
We should use `matchCase="false"` in the `PropertyIsLike` of the WFS request

**Comment by asaunier** [comment]
> We should use matchCase="false" in the PropertyIsLike of the WFS request

I have looked at the code and I think this could be done by editing https://github.com/camptocamp/ngeo/blob/2.2.0/src/services/rulehelper.js#L626-L631 and set the optional ``matchCase`` parameter to ``false``.
See http://openlayers.org/en/latest/apidoc/ol.format.filter.html#.like

**Comment by asaunier** [comment]
A PR fixing this issue is now available at https://github.com/camptocamp/ngeo/pull/3107

**Comment by asaunier** [comment]
The PR has been merged and the fix will be available in the next (2.2.x?) release.

**Comment by sbrunner** [comment]
> Should we switched the "Ready" label to "Done"?

No, to ongoing and close th issue, I just do it :-)

Closed mean that's tested and accepted on production environment.

**Comment by yjacolin** [comment]
@sbrunner  Has it been backported to GMF 2.2?
