### ISSUE TITLE
Theme, layergroup, layers and background layer loading

### ISSUE THREAD

**Issue by yjacolin** [camptocamp/ngeo#2856]
When loading a GMF application, themes, layer group and layer are retrieve from a theme services. Then the application load the theme selected, the layer group and layer in the layer tree.

GMF application then load GetLegendGraphic for all layer (icon of layers with RULE definition) then load background layer. If we have a lot of layer (around 50 for example) the user experience is not good as user should wait that all layer get their icons to see the background layer.

Expected result:
* background layer are loaded before the getlegendgraphic
* load icon for layer only when they are visible in an opened group

**Comment by ger-benjamin** [comment]
Please always add a label and a milestone for our dashboard

**Comment by jwkaltz** [comment]
This seems related to https://github.com/camptocamp/ngeo/issues/2845 ?

**Comment by yjacolin** [comment]
not related to this issue. But they are both linked to wrong UX.

**Comment by fredj** [comment]
> load icon for layer only when they are visible in an opened group

this is now the case in version 2.2

**Comment by sbrunner** [comment]
https://jira.camptocamp.com/browse/GSGMF-556
