### ISSUE TITLE
Legend display problem while adding a group via search

### ISSUE THREAD

**Issue by ybolognini** [camptocamp/ngeo#2877]
* Choose a theme and display some layers on map
 * Search "Lausanne" and select OSM result "Lausanne"
 * A new group "Groupe" is added (closed)
 * Open group, there a fine gray line below the layer name
 * Open menu and choose "Hide/show legend", the line disappear
 * Open menu and choose "Hise/show legend", the legend is displayed normally

--> Legend should be open or closed (depending on configuration) but this gray line shouldn't be there

**Comment by sbrunner** [comment]
In this case the img tag is missing..., but added on a little action ...
