### ISSUE TITLE
Backgroup map on login with a theme and a role that defined a background layer

### ISSUE THREAD

**Issue by ybolognini** [camptocamp/ngeo#2878]
1)
 * Start as being logged out
 * Choose background "Carte OSM"
 * Login as "admin" 
 * No background layer displayed and no background layer selected in the widget (if the background layer displayed is "empty", at least "Vide" should be selected in the widget)

2) 
 * Logout
 * Carte OSM background layer is displayed but no background layer is selected in the widget

**Comment by sbrunner** [comment]
1. in this case the img tag is missing..., but added on a little action ...
