### ISSUE TITLE
Popups: move/resize is a 2.3 feature

### ISSUE THREAD

**Issue by ybolognini** [camptocamp/ngeo#2879]
2.3 feature move/resize has been added to 2.2 release. And this feature still has some bugs, see: 

https://jira.camptocamp.com/browse/GSGMF-69
https://jira.camptocamp.com/browse/GSGMF-70

Ideally, remove this feature from 2.2.

**Comment by ger-benjamin** [comment]
Look also: https://github.com/camptocamp/ngeo/issues/2010

**Comment by sbrunner** [comment]
reverted
