### ISSUE TITLE
2.2.0rc5 - Grid display

### ISSUE THREAD

**Issue by kalbermattenm** [camptocamp/ngeo#2908]
I just realized that in version 2.2.0rc5 I am having issues with the grid results:

![image](https://user-images.githubusercontent.com/1681332/30482130-2525f6dc-9a22-11e7-88c6-395edff9bf49.png)

I checked my defs inside my template and it looks like the one used by desktop_alt.

I looked as well to the ngeo code which throws the error here: https://github.com/camptocamp/ngeo/blob/2.2/contribs/gmf/src/directives/displayquerygrid.js#L330

`this.mergeTabs_` is effectively `undefined` (using a `console.log(this.mergeTabs_)`) which clearly makes the whole thing go wrong.

I have the exact same definition of the ` gmf-displayquerygrid-mergetabs` property as in https://github.com/camptocamp/ngeo/blob/2.2/contribs/gmf/apps/desktop_alt/index.html#L328. This one seems to be the value setter for `this.mergeTabs_`

Is there somewhere a running demo of 2.2.0rc5 using the display grid ? And am I doing something wrong ?

**Comment by kalbermattenm** [comment]
https://sitndevssl.ne.ch/dev_internet2/wsgi/neophyte/announce

**Comment by sbrunner** [comment]
You miss add something like this:
https://github.com/camptocamp/ngeo/blob/1062e21169430d9ee43f03578322375cd41f055d/contribs/gmf/apps/desktop_alt/js/controller.js#L116-L118
Or, probably better, simply remove this line:
https://github.com/camptocamp/ngeo/blob/2.2/contribs/gmf/apps/desktop_alt/index.html#L328
:-)

**Comment by kalbermattenm** [comment]
Ah.... I get it... Sorry my fault... Effectively this variable is missing because we do not need any merges tabs...

Now it is working... Is it normal that HTML code is not interpreted in the column headers (see column "Surface m<sup>2</sup>") ?

Moreover, I always have a column entitled `wp` (Well Play, Working Paper, Washington Post, WordPress, other `). Is there a way to hide this one (and why is that here anyway...?)

![image](https://user-images.githubusercontent.com/1681332/30642175-1fc1425a-9e0a-11e7-89b6-5e09d30282b3.png)

**Comment by sbrunner** [comment]
This column (`wp`) isn't create by us, it should be returned by your mapserver... (I don't succeed to open your URL then I can't say more ...)

**Comment by fredj** [comment]
@kalbermattenm the html issue should be fixed with #2918

**Comment by kalbermattenm** [comment]
@sbrunner, the problem is that our Mapserver layers do not contain anything referring a column `wp`:

https://github.com/camptocamp/sitn_c2cgeoportal/blob/v2/mapserver/mensuration.map.mako#L3532

I opened a dev instance on Internet. You might tested here: https://sitnssl.ne.ch/dev_internet2/

You can activate any layer, query it and you will get the famous `wp` column back...

**Comment by kalbermattenm** [comment]
@fredj, thanks a lot !

**Comment by sbrunner** [comment]
The column is hidden in debug mode :-/

**Comment by kalbermattenm** [comment]
Oh yes, I hadn't noticed that... This is really weird...

**Comment by sbrunner** [comment]
The issue comes from here: https://github.com/camptocamp/ngeo/blob/1cb834b758a9d6dc67331acea1b0c93e0039d975/contribs/gmf/src/directives/displayquerygrid.js#L610

**Comment by kalbermattenm** [comment]
Thanks a lot @sbrunner !
