### ISSUE TITLE
Disclaimers of Layers within LayerGroups are not displayed

### ISSUE THREAD

**Issue by pfirpfel** [camptocamp/ngeo#2912]
Using 2.2 branch, instance: https://geomapfish-demo.camptocamp.net/2.2

This seems to be just a symptom. I have not found the cause yet. 

I use the [2.2-demo](https://geomapfish-demo.camptocamp.net/2.2/theme/Demo) as an example. The Demo-Theme includes multiple LayerGroups which contain multiple layers.

Yet in in registerLayer_, the [recursive registering](https://github.com/camptocamp/ngeo/blob/f322efaad5b107d159b5ede6f88c2893105eb5b4/contribs/gmf/src/directives/disclaimer.js#L239) never happens, because the LayerGroups thrown at it are all empty or not LayerGroups.

**Comment by ger-benjamin** [comment]
Closed with #3067
