### ISSUE TITLE
HTML code in attribute names

### ISSUE THREAD

**Issue by rbovard** [camptocamp/ngeo#2932]
* GeoMapFish version: `2.1.8`

[Permalink directly where we can reproduce the issue](https://map-demo.nyon.ch/v2/mobile/theme/mobilite?lang=fr&tree_group_layers_cadastre_solaire_pv=cs_toits&baselayer_ref=asitvd.fond_couleur&map_x=508261&map_y=137650&map_zoom=10&theme=mobilite&tree_enable_te_wc_publics=true&tree_enable_te_wc_accueillants=true&tree_enable_te_mobilier_sacs=true&tree_enable_te_mobilier_corbeilles_all=true&tree_enable_te_mobilier_corbeilles_batiment=true&tree_enable_te_mobilier_corbeilles_ecole=true&tree_enable_te_mobilier_corbeilles_voirie=true&tree_enable_te_mobilier_corbeilles_esve=true&tree_enable_te_mobilier_corbeilles_autre=true&tree_enable_te_mobilier_bancs=true&tree_group_layers_mobilier_panneaux&tree_group_layers_orthophotos_grid&tree_groups=mobilite_douce%2Ctransports_publics%2Ccirculation&tree_group_layers_mobilite_douce=mb_support_2roues&tree_group_layers_transports_publics)

Steps to reproduce the issue:

* Query POI

Result: `&nbsp;`

Expected result: ` ` (empty string)

It's in the same logical as for the attribute values: https://github.com/camptocamp/ngeo/issues/965

**Comment by ybolognini** [comment]
In current versions of GeoMapFish, attribute name are treated as strings, not HTML

**Comment by rbovard** [comment]
Yes, I can see that. But it was the case with cgxp...

**Comment by rbovard** [comment]
Thanks, it's working.
