### ISSUE TITLE
Weird characters in mobile template

### ISSUE THREAD

**Issue by kalbermattenm** [camptocamp/ngeo#2937]
The tree little characters of the search string (https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/apps/mobile/index.html#L57) produce quite a strange result when the file is used as a GMF template:

![image](https://user-images.githubusercontent.com/1681332/31005358-9f4dffaa-a4f8-11e7-972e-f53be217e621.png)

I am wondering if this character (because it is only one character) was used on purpose or if this should / could simply be replaced using tree points: `Search...`

It is not a blocker, because, as a a GMF integrator, one can easily replaced that string...

**Comment by fredj** [comment]
Do you see the same issue here: 
https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/mobile/ ?

**Comment by kalbermattenm** [comment]
Nope !

So I suspect this has more to do with character encoding on my side, right ?

**Comment by fredj** [comment]
yes, that probably an encoding issue: `…` is a UTF-8 character

**Comment by kalbermattenm** [comment]
OK, I think I got it ! Sorry for the noise and thanks for the advices !
