### ISSUE TITLE
2.2.0 - disable password change not working

### ISSUE THREAD

**Issue by kalbermattenm** [camptocamp/ngeo#2938]
Using the `gmf-authentication-allow-password-change="false"` in the `<gmf-authentication>` tag seems not to work.

Demo:

https://sitnssl.ne.ch/dev_internet2/

or on the mobile:

https://sitnssl.ne.ch/dev_internet2/mobile/

**Comment by fredj** [comment]
@kalbermattenm thanks for the bug report, fixed with #2939 (in the 2.2 branch)

**Comment by kalbermattenm** [comment]
Great !!! Thanks a lot @fredj for the rapid fixing...
