### ISSUE TITLE
Query of QGIS server layers does not work on ngeo

### ISSUE THREAD

**Issue by gnerred** [camptocamp/ngeo#2948]
Version 2.2.0

To reproduce : 
1°/ Go to https://preprod.cartoriviera.ch/mobile/
2°/ Connect with user c2c
3°/ Go to theme Sige
4°/ Try to query the blue network

The query of QGIS server layers works well on CGXP. To test, do the same with https://preprod.cartoriviera.ch/

**Comment by sbrunner** [comment]
On CGXP the request is served by mapserver, then it seem that QGIS can't serve your request...

**Comment by gnerred** [comment]
I don't think that on CGXP the request is served by mapserver... Here is the request done on CGXP : 

https://preprod.cartoriviera.ch/qgis/qgis_mapserver.fcgi?map=/var/sig/qgis/qwat.qgs&transparent=true&LAYERS=sige_qgis_conduite_fonctionnelle%2Csige_qgis_noeud%2Csige_qgis_piece%2Csige_qgis_croisement&QUERY_LAYERS=sige_qgis_conduite_fonctionnelle%2Csige_qgis_noeud%2Csige_qgis_piece%2Csige_qgis_croisement&STYLES=%2C%2C%2C&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetFeatureInfo&BBOX=554543.4%2C145673.75%2C554680.7%2C145709.25&FEATURE_COUNT=200&HEIGHT=355&WIDTH=1373&FORMAT=image%2Fpng&INFO_FORMAT=application%2Fvnd.ogc.gml&SRS=EPSG%3A21781&X=250&Y=49&LAYER=sige_qgis_conduite_fonctionnelle%2Csige_qgis_noeud%2Csige_qgis_piece%2Csige_qgis_croisement

**Comment by gnerred** [comment]
Is it possible that the problem comes from WFS configuration on QGIS side ? If WFS is not allowed ?

**Comment by gnerred** [comment]
Yes it was that the problem... Now it works if WFS is allowed in QGIS project. Thanks

**Comment by gnerred** [comment]
It was not only WFS, there is a real problem on NGEO with query of QGIS server layers. 

Version 2.2.0

To reproduce : 
1°/ Connect with c2c user on https://preprod.cartoriviera.ch/mobile/ 
2°/ Go to theme "SIGE"
3°/ Zoom in and try to query a pipe -> it doesn't work and sometimes a JS error appears
4°/ Uncheck all layers but not "Conduite fonctionnelle"
5°/ Try to query a blue pipe -> it works

Conclusion : query does work only when one QGIS server layer is active

**Comment by gnerred** [comment]
@sbrunner , is ti possible that it is related to version of QGIS server ? I work with 2.14, and @ebelo told me that it works well with 2.18.

**Comment by gnerred** [comment]
Problem solved by installing QGIS server 2.18 ! Thanks @mbornoz and @ebelo !
