### ISSUE TITLE
QGIS server layers - Legend not shown if multiple layers

### ISSUE THREAD

**Issue by gnerred** [camptocamp/ngeo#2950]
Version 2.2.0

In ngeo, the legend of a GMF layer could not be opened if the GMF layer is composed of more than one QGIS server layer. 

![image](https://user-images.githubusercontent.com/1989467/31124577-56e65a46-a845-11e7-907b-b7226d39d78c.png)

To reproduce, connect with c2c user and go to https://preprod.cartoriviera.ch/mobile/theme/sige?lang=fr&tree_group_layers_cadastre&tree_group_layers_couverture_du_sol&baselayer_ref=plan_cadastral&theme=sige&tree_group_layers_amenagement_du_territoire=camac%2Clpnms_1%2Clpnms_2%2Clpnms_3%2Clpnms_4%2Clpnms_5%2Clpnms_6%2Clpnms_7&tree_groups=sige_assainissement%2Csige_distribution%2Csige_autres_reseaux%2Csige_cadastre%2Ccadastre_valais

In CGXP, with the same layer, it works : 

![image](https://user-images.githubusercontent.com/1989467/31124636-984a753a-a845-11e7-8fb2-20081dbd9f5d.png)

**Comment by ger-benjamin** [comment]
Closed with #2968 / will be in the next release.
