### ISSUE TITLE
CGXP references in ngeo

### ISSUE THREAD

**Issue by ger-benjamin** [camptocamp/ngeo#2972]
@sbrunner 
Should we really keep the "cgxp" namespace in ngeo for some (unrelated) functions ? :
https://github.com/camptocamp/ngeo/blob/2.2/contribs/gmf/src/controllers/abstract.js#L544

Appears in 2.2, not existing in 2.1, 2.0: 
https://github.com/camptocamp/ngeo/blob/2.1/contribs/gmf/src/controllers/abstract.js#L462

**Comment by sbrunner** [comment]
Yes for backward compatibility :-)
If we don't have it it's impossible to have an application using this function working on ngeo and CGXP ...

**Comment by ger-benjamin** [comment]
Ah ha
