### ISSUE TITLE
2.2 - Static legends are not taken into account when printing

### ISSUE THREAD

**Issue by kalbermattenm** [camptocamp/ngeo#2980]
I have a layer with a static legend image, thus one which is not called through a getLegendGraphic request.

When printing using this layer, this static legend is not taken into account, but the getLegendGraphic is passed onto mapfish print (in the layertree who can see the static legend, which would have http://localhost/michael/wsgi/static-cgxp/ba9db0562ce0401b8963629bbe3746e3/images/legends/legend_poi_administration.png as link):

![static_legend](https://user-images.githubusercontent.com/1681332/31487132-057628ac-af3a-11e7-92fd-75cc1c718706.PNG)

**Comment by ger-benjamin** [comment]
I can reproduce the bug. I'll investigate how to fix it

**Comment by ger-benjamin** [comment]
That was an issue. The fix will be available within the next release.

**Comment by kalbermattenm** [comment]
Thanks a lot for your work on that @ger-benjamin !
