### ISSUE TITLE
Scaleselector does not get updated after language change

### ISSUE THREAD

**Issue by pfirpfel** [camptocamp/ngeo#2983]
Due to a race condition, this is easier to reproduce on the compiled version.

How to reproduce (on current master):
`make build-gmf-apps examples-hosted-apps serve`
Got to: http://localhost:3000/.build/examples-hosted/contribs/gmf/apps/desktop_alt/?lang=fr

(I'm using a browser that request German as language)

The scale selector should show "1 : 20,000" (the English default, I guess).

Zoom into the map.

The scale selector shows "1 : 20 000" (the french formatting)

Open the scale selector. All values should still use the old, English formatting.

I assume, because the model of the scaleselector does not change, the template does not get refreshed.

**Comment by fredj** [comment]
Same issue with the scales in the print

**Comment by fredj** [comment]
fixed with #2987
