### ISSUE TITLE
Broken gmf examples - Unknown provider: gmfPermalink

### ISSUE THREAD

**Issue by romanzoller** [camptocamp/ngeo#3013]
Affects versions 2.2 and master.

For example:

https://camptocamp.github.io/ngeo/2.2/examples/contribs/gmf/contextualdata.html
`Unknown provider: gmfUserProvider <- gmfUser <- gmfPermalink`

https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/contextualdata.html
`Unknown provider: gmfLayersUrlProvider <- gmfLayersUrl <- gmfEditFeature <- gmfObjectEditingManager <- gmfPermalink`

And the same for:
https://camptocamp.github.io/ngeo/2.2/examples/contribs/gmf/backgroundlayerselector.html
https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/backgroundlayerselector.html

as well as several other gmf examples.

**Comment by fredj** [comment]
see #2844
