### ISSUE TITLE
Private WMTS layer

### ISSUE THREAD

**Issue by rbovard** [camptocamp/ngeo#3028]
* GeoMapFish version: **2.1.8**

When a WMTS layer is not set as public, it doesn't appear in mobile layertree but it appears fine in cgxp interface (beeing connected of course).

![image](https://user-images.githubusercontent.com/4549666/32052137-8d9f8cc8-ba57-11e7-8b81-759f0721e645.png)

If I set layer as public, it appears in mobile layertree.

*PS: I know that tiles are not impacted by this setting, it's just to hide it in public layertree.*
*PS2: I think it's my last issue to go live with 2.1 :)*

**Comment by sbrunner** [comment]
You change it on the WMTS layer but CGXP use LayerV1, do you also try to change on it?

**Comment by rbovard** [comment]
Just to be sure: the bug is on ngeo mobile interface with a WMTS layer set as private, because it doesn't appear. On cgxp desktop interface, a V1 layer set as private does appear as it should be.

Is that clear? Because I don't understand the goal of your question.

**Comment by sbrunner** [comment]
No a private WMTS layer shouldn't appear in the layertree...

**Comment by rbovard** [comment]
But it should if we are connected, as it is with a V1 layer...

**Comment by sbrunner** [comment]
Throw a restrictionarea, it's not working?

**Comment by rbovard** [comment]
I don't know, I cannot test today because I'm out of office. Could you test on your side please?

For me it should work like it is with V1 layer.

**Comment by sbrunner** [comment]
Effectively it don't looks to work ...

**Comment by rbovard** [comment]
Yep, I hope you can fix it easily... *in 2.1.9 :)*

**Comment by rbovard** [comment]
@sbrunner Any news about this issue?

**Comment by sbrunner** [comment]
I'm currently working in it :-)

**Comment by rbovard** [comment]
Oh, thanks!

**Comment by jwkaltz** [comment]
@rbovard for your information, the fix was tried on another site (BS), and is working.

**Comment by rbovard** [comment]
Thanks, it's working!

So I'll close this one but I noticed another [issue](#3070) on WMTS layer...
