### ISSUE TITLE
2.2 - Attributes still printed when grid is closed

### ISSUE THREAD

**Issue by kalbermattenm** [camptocamp/ngeo#3029]
Go to: https://camptocamp.github.io/ngeo/2.1/examples/contribs/gmf/apps/desktop_alt 

(I know that this is the 2.1 demo, but on the 2.2 demo the print is not working and I have the same problem on our instance using 2.2)

* Query some data
* Print with the result grid opened -> Attributes are printed -> OK
* Close the result grid
* Print -> Attributes are printed -> not good...

**Comment by kalbermattenm** [comment]
Anyone ??

**Comment by fredj** [comment]
Same issue with the query window

**Comment by fredj** [comment]
fixed with #3083

**Comment by kalbermattenm** [comment]
Thanks a lot @fredj !
