### ISSUE TITLE
ngeo mobile on iOS 11.03 freezes

### ISSUE THREAD

**Issue by gnerred** [camptocamp/ngeo#3036]
With the new iOS 11.03, GMF mobile does not work anymore. To reproduce, open Cartoriviera (GMF 2.2.0) on an iOS 11.03 device on Safari (not tested on Chrome) and navigate. After some zooms, the application freezes.

**Comment by gnerred** [comment]
Reproduced on official demo too 
https://geomapfish-demo.camptocamp.net/2.2/mobile

**Comment by fredj** [comment]
@gnerred we have updated OpenLayers in the 2.2 branch. This issue should be fixed now.

**Comment by gnerred** [comment]
Thanks @fredj . How can I update GMF ? Is there a release with that update ?

**Comment by fredj** [comment]
There's no release yet with this fix. @sbrunner ?

**Comment by gnerred** [comment]
Any new about the merge of this fix ?

**Comment by sbrunner** [comment]
This will be fixed in the 2.2.1 release, can be tested here: https://camptocamp.github.io/ngeo/2.2/examples/contribs/gmf/apps/mobile/?

I close it, reopen it it's not fixed in 2.2.1.

**Comment by gnerred** [comment]
Thanks @sbrunner . Could you please tell me when this release is planned ? Thanks

**Comment by gnerred** [comment]
Any idea of 2.2.1 release date ?

**Comment by sbrunner** [comment]
Next week :-)

**Comment by rbovard** [comment]
@gnerred Does it also concern 2.1 versions?

**Comment by sbrunner** [comment]
yes

**Comment by rbovard** [comment]
Thanks @sbrunner 
So do you plan to backport this fix in 2.1 branch?

**Comment by sbrunner** [comment]
No because it's not trivial to update OpenLayers...

**Comment by gnerred** [comment]
Thanks for informations

**Comment by rbovard** [comment]
Seriously?! So all iOS users will encounter this bug in 2.1...

**Comment by gnerred** [comment]
I confirm that the problem is solved with version 2.2.1, that I've installed in production on Cartoriviera.
