### ISSUE TITLE
findGroupByName searches only two levels deep

### ISSUE THREAD

**Issue by pfirpfel** [camptocamp/ngeo#3041]
## Steps to reproduce

1. Go to the [demo](https://geomapfish-demo.camptocamp.net/2.2/theme/Demo?lang=de&tree_group_layers_Transport=fuel&baselayer_ref=OSM%20map&theme=Demo&tree_enable_ch.swisstopo.dreiecksvermaschung&tree_group_opacity_Group=0.65&tree_groups&tree_enable_osm_scale=true&tree_group_layers_Group&tree_group_layers_OSM%20functions=osm_scale&tree_group_layers_External&tree_enable_osm_open&tree_enable_ch.swisstopo.geologie-geotechnik-gk500-gesteinsklassierung&tree_enable_OSM%20map&tree_enable_osm_time_r_dp_2&tree_group_layers_Filters&tree_group_layers_Layers=entertainment%2Csustenance)

2. Search for "Unterhaltung" (loisirs in french) and try to add the sub theme:
![fts_subtheme](https://user-images.githubusercontent.com/621371/32223523-f548e5e2-be3d-11e7-94dc-3da0c9ce2edf.png)

Response from fulltext search:
![fts_subtheme_chrome](https://user-images.githubusercontent.com/621371/32223562-145af4fc-be3e-11e7-89e7-64505396eee3.PNG)

## Expected
Theme gets added

## Actual result
Nothing happens

**Comment by pfirpfel** [comment]
After some debugging I discovered, that "Unterhaltung" is a child of a child. gmf.Themes.findGroupByName, which will be called to retrieve the group by name, only checks the first level of children.

**Comment by fredj** [comment]
with master, no error in the console but nothing happens

**Comment by fredj** [comment]
fixed with #3052
