### ISSUE TITLE
jQueryUI draggable doesn't work on desktop_alt app

### ISSUE THREAD

**Issue by adube** [camptocamp/ngeo#3056]
The issue is this: the jQueryUI draggable widget doesn't work on the desktop_alt application.  This was raised while developing the new `gmf-displaywindow` component, which replaces the `ngeo.Popup`, in all applications in order to make the window open when the "Open" link (in query results) is clicked.

The issue was present before the introduction of `gmf-displaywindow`.  The cause has not been found yet.

**Comment by fredj** [comment]
@adube it seems to work now on:
https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/desktop_alt/

can you confirm and close this issue if it's correct?

**Comment by adube** [comment]
@fredj It works fine now, indeed.  I'm curious about what fixed the issue.

Closing this...
