### ISSUE TITLE
Query on WMS-T work even on off-time features

### ISSUE THREAD

**Issue by ger-benjamin** [camptocamp/ngeo#3061]
Backlog (because it work in 2.2 and nobody require it in 2.1 for now. It's also doesn't work in CGXP)

- Go on a 2.1 (or 1.6) GMF
- Load a WMS-T layer
- Look for a zone with features
- Set time to have any features on the zone.
- Do a query on the zone

--> you have result on not visible features

Expected result:
--> no result for this query.

To resolve this bug, we can limit queries on visible features, or we can give WMS-T parameters in the payload of the GetFeatures Info.

**Comment by sbrunner** [comment]
Unable to reproduce on 2.3
