### ISSUE TITLE
Text from Drawing Tools is Rendered with a too large Buffer when Printed

### ISSUE THREAD

**Issue by marionb** [camptocamp/ngeo#3065]
Project:
* GitHub URL: https://github.com/camptocamp/ngeo/
* Host: geomapfish-demo.camptocamp.net
* GeoMapFish version: 2.1, 2.2 and master

Permalink directly where we can reproduce the issue: 
 - https://geomapfish-demo.camptocamp.net/2.2/s/PWfg
 - https://geomapfish-demo.camptocamp.net/2.1/s/nliS
 - https://camptocamp.github.io/ngeo/2.1/examples/contribs/gmf/apps/desktop/theme/Demo?lang=en&tree_group_layers_Transport=fuel&baselayer_ref=OSM&rl_features=Fl(ye61Hncnn!15XzhOh5d-18T~n*LineString%25201%27c*%2523DB4436%27a*0%27o*0.2%27m*false%27s*10%27k*1)a(ywjzG5vap!zsUz21_..hx6_1U~n*Polygon%25202%27c*%2523DB4436%27a*0%27o*0.2%27m*false%27s*10%27k*1)p(fsh1Hn8bp!~t*true%27n*Text%25203%27c*%2523000000%27a*0%27o*0.2%27m*false%27s*10%27k*1)&map_x=630724&map_y=188277&map_zoom=3&tree_groups=Transport
 - https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/desktop/?lang=en&baselayer_ref=OSM%20map&tree_groups=Transport&tree_group_layers_Transport=fuel&rl_features=Fp(yfy2Hnzjm!~t*true%27n*Text%25201%27c*%2523000000%27a*0%27o*0.2%27m*false%27s*10%27k*1)a(9fw3Hku8m!cD1bAzTd9Aaa-36Act-91Ar9_wt*gr_1k*c6!q9*ak!3y!2y!bk!p9*d6!zj*hr_vt*s9_81Adt-26Aba-c9A1UxaAdDzaAcDc9AzT26Aaa-81Act-vt*r9_zj*gr_p9*c6!2y!ak!ak!2y!c6!p9*gr_zj*r9_vt*ct-81Aaa-26AzTc9AcDzaAdDxaA1Uc9Aba-26Adt-81As9_vt*hr_zj*d6!p9*bk!2y!3y!ak!q9*c6!1k*gr_wt*r9_91Act-36Aaa-d9AzT1bAcDyaAdDd9A1U36Aba-91Adt-wt*s9_1k*hr_q9*d6!3y!bk!bk!3y!d6!q9*hr_1k*s9_wt*dt-91Aba-36A1Ud9A~l*true%27z*103.33510634104591%27n*Circle%25202%27c*%2523DB4436%27a*0%27o*0.2%27m*false%27s*10%27k*1)p(12pzG3shj!~t*true%27n*Text%25203%27c*%2523000000%27a*0%27o*0.2%27m*false%27s*10%27k*1)&map_x=630244&map_y=186237&map_zoom=3

Steps to reproduce the issue:
* Open a GMF application
* Add some text on the map with the draw and measure tool
* Print the map containing the text

Result:
Text elements are rendered with a buffer that is too large compared to what we actually see on the map.

Expected result:
The print should look like what we see on the map. With a smaller buffer.

The issue concern the following environment:
* Chromium 62 Ubuntu 16.04
* Firefox 55 Ubuntu 16.04
* likely also others

The following environment is working as expected:

* -

**Comment by ger-benjamin** [comment]
I'm not sure if the error is in Openlayers or in MapFish Print.

In the example below, I've made a text with some different value. Each time, we set the `haloradius` of MapFish Print with the `stroke` value from ol3.

the report spec:
![selection_054](https://user-images.githubusercontent.com/1792111/32771165-26445836-c922-11e7-9e38-6e1d8c651d38.png)

The OpenLayers ("on web") result
![selection_050](https://user-images.githubusercontent.com/1792111/32771172-2b025076-c922-11e7-9b0a-aabdd1ee01cc.png)

The MapFish Print ("on pdf") result:
![selection_053](https://user-images.githubusercontent.com/1792111/32771209-54c815ee-c922-11e7-906b-2ed0be5974e4.png)

Stroke is slightly different.
Text size is also slightly different (see the length of the text compared to the size of my red square)

Nothing to do in NGEO I think.

**Comment by ger-benjamin** [comment]
@sbrunner What should we do with this issue ? (I think, that concern more MapFish Print)

**Comment by sbrunner** [comment]
Are we sure that's an issue in mapfish print, and not in openlayers?

**Comment by ger-benjamin** [comment]
In OpenLayers, we want a stroke of 3 pixels, we get a stroke of 3 pixels. 

In MapFish Print, 3 pixels is not 3 pixels, OR the value "3" doesn't use the unit "pixel*. I don't know, I don't see any mention to the unit they use in the documentation: http://mapfish.github.io/mapfish-print-doc/styles.html#haloproperties

**Comment by sbrunner** [comment]
OK, then it should be reported on MapfishPrint

**Comment by ger-benjamin** [comment]
Reported: https://github.com/mapfish/mapfish-print/issues/605

**Comment by sbrunner** [comment]
Thanks :-)

**Comment by pvalsecc** [comment]
IMHO, the problem is in ngeo:
  * In openlayers, it's a stoke width. Meaning that a straight line has a halo of that width.
  * In the print, it's a halo *radius*. Meaning that a straight line has a halo of double that radius.

To me, https://github.com/camptocamp/ngeo/blob/master/src/services/print.js#L790 should be:
```javascript
symbolizer.haloRadius = width / 2.0;
```

**Comment by yjacolin** [comment]
ping @ger-benjamin what do you think about this?

**Comment by ger-benjamin** [comment]
Make sens. I'll re-open this issue and close the other

**Comment by ger-benjamin** [comment]
Done
