### ISSUE TITLE
WMTS layer with resolutions

### ISSUE THREAD

**Issue by rbovard** [camptocamp/ngeo#3070]
GeoMapFish version: **2.1.10**

When a WMTS layer has `minResolution` and `maxResolution`, it doesn't seems to be taken in account in mobile layertree, but it's working fine in cgxp interface.

![image](https://user-images.githubusercontent.com/4549666/32552662-f332b546-c494-11e7-8be9-9965bef75830.png)

I cannot share a permalink since the only WMTS layer with resolutions defined is private but you can reproduce it on one of your layer is you set those values.

On `cgxp`, the layer is disabled and grayed out outside the visibility range:

![image](https://user-images.githubusercontent.com/4549666/32553240-8f58c6b2-c496-11e7-882d-dc2e1792a2a9.png)

On `ngeo`, the layer is active outside the visibility range:

![image](https://user-images.githubusercontent.com/4549666/32553248-958c4040-c496-11e7-83ec-558ccdfd9b89.png)

**Comment by sbrunner** [comment]
Visible on Conversion des alpes:
https://geomapfish-demo.camptocamp.net/2.2/theme/Demo?lang=fr&tree_enable_ch.swisstopo.dreiecksvermaschung&tree_enable_ch.swisstopo.geologie-gravimetrischer_atlas&tree_enable_ch.swisstopo.geologie-geotechnik-gk500-lithologie_hauptgruppen&tree_enable_ch.swisstopo.geologie-geotechnik-gk500-gesteinsklassierung&tree_enable_ch.are.alpenkonvention=true&tree_enable_ch.astra.ausnahmetransportrouten&baselayer_ref=OSM%20map&theme=Demo&tree_group_opacity_Group=0.65&tree_group_layers_OSM%20functions&tree_enable_osm_scale&tree_enable_osm_open&tree_enable_Layer%2520with%2520very%2520very%2520very%2520very%2520very%2520long%2520name&tree_enable_osm_time_r_s&tree_enable_osm_time_v_s&tree_enable_osm_time_v_dp&tree_enable_osm_time_r_dp&tree_enable_osm_time_r_year_mounth&tree_enable_osm_time_d_year_mounth&tree_enable_osm_time_r_mounth_year&tree_enable_osm_time_v_mounth_year&tree_enable_long%2520wms-t%2520layer%2520name%2520name%2520name%2520name%2520name%2520name%2520name&tree_enable_two_layers&tree_enable_no_wfs&tree_group_layers_External&map_x=567169&map_y=152870&map_zoom=4&tree_groups=OSM%20functions%20mixed%2CLayers%2CGroup%2COSM%20functions%2CExternal%2CFilters%20mixed%2CFilters&tree_enable_Layer%20with%20very%20very%20very%20very%20very%20long%20name&tree_enable_long%20wms-t%20layer%20name%20name%20name%20name%20name%20name%20name&tree_group_layers_Layers&tree_group_layers_Group&tree_enable_OSM%20map&tree_enable_osm_time_r_dp_2&tree_group_layers_Filters

**Comment by rbovard** [comment]
Thanks, it's working.
