### ISSUE TITLE
Query of backgroundlayer does not work anymore after login

### ISSUE THREAD

**Issue by gnerred** [camptocamp/ngeo#3113]
GMF 2.2.0

To reproduce : 
1°/ Go to  https://preprod.cartoriviera.ch/mobile/?lang=fr&tree_group_layers_cadastre&tree_group_layers_couverture_du_sol&baselayer_ref=plan_cadastral&map_x=558186&map_y=143494&map_zoom=8&tree_groups=cadastre%2Ccouverture_du_sol
2°/ click wherever on the map => a WFS GetFeature request is done and results are shown
3°/ open the login form and sign in
4°/ clicking on the map no longer has an effect (no request triggered)
5°/ reload the page as is: we are still logged in but clicking on the map now triggers the WFS request
6°/ log out: clicking on the map no longer triggers a request
7°/ reload the page => OK

=> it seems the log in / out actions somehow disable the WFS request.

Thanks @asaunier for help in identifying abnormal behaviour

**Comment by fredj** [comment]
it's maybe related to #3106; the background layer was not correctly set after login/logout

**Comment by gnerred** [comment]
Ok, let's wait the next 2.2 release to see if it's fixed.

**Comment by gnerred** [comment]
I've just installed 2.2.1 on https://preprod.cartoriviera.ch/, but the problem is not solved...

**Comment by fredj** [comment]
I know what's wrong, pull request to come

**Comment by fredj** [comment]
fixed with #3158
