### ISSUE TITLE
Keep Makefile_windows ?

### ISSUE THREAD

**Issue by fredj** [camptocamp/ngeo#3183]
Do we want to keep and maintain Makefile_windows?

ping @sbrunner

**Comment by sbrunner** [comment]
ping @kalbermattenm

**Comment by kalbermattenm** [comment]
This is still an issue: https://github.com/camptocamp/ngeo/blob/master/Makefile#L890

Could we wait until @monodo will have to compile is work on the Lidar profile in ngeo, which is developed in Windows ?

After that, I will be able to give a clear answer...

**Comment by fredj** [comment]
No problem keeping the file. Just wanted to let you know that we are updating the Makefile without testing on windows.
