### ISSUE TITLE
Encoding in csv export

### ISSUE THREAD

**Issue by svades** [camptocamp/ngeo#3197]
When opening the exported .csv in Excel the text is wrongly encoded (the mutated vowels are wrong). Changing the encoding in https://github.com/camptocamp/ngeo/blob/master/src/services/csvdownload.js#L33 to utf-8-bom or similar inputs didn’t work.

By changing in https://github.com/camptocamp/ngeo/blob/master/src/services/csvdownload.js#L135 „attachment/csv“ to „text/csv“ the mutated vowels are correctly shown in Excel. Would it be possible to change this in your code?

Project:
* GeoMapFish version: 2.2.0

**Comment by fredj** [comment]
you're proposed change make sense to me: the mime type is `text/csv`.
See https://developer.mozilla.org/en-US/docs/Web/API/Blob/type

**Comment by fredj** [comment]
fixed with #3198
