### ISSUE TITLE
The theme is lost in the mobile URL of the auto redirect

### ISSUE THREAD

**Issue by gnerred** [camptocamp/ngeo#3201]
Version 2.2.1

~~Permalink is supposed to be compatible between CGXP and NGEO. A permalink created in CGXP must be "openable" in NGEO interface, but it doesn't work anymore (it worked more or less in an early release).~~ To reproduce : 

1°/ Try to open https://map.cartoriviera.ch/s/4S7a or https://map.cartoriviera.ch/theme/infrastructures?map_x=554268.14022373&map_y=145744.13691876&map_zoom=10&baselayer_opacity=100&baselayer_ref=plan_cadastral (long version of the first one) on a mobile device -> it doesn't work (compare with a desktop device), The theme is not loaded

ping @rbovard

**Comment by rbovard** [comment]
Open the desktop link with a mobile.

**Comment by gnerred** [comment]
On a mobile device, as said in the first message ;-)

**Comment by rbovard** [comment]
@sbrunner If it's possible, could you please target the 2.1 branch for the fix of this issue?

**Comment by gnerred** [comment]
I've installed the 2.2.2, but this issue is not solved ! Could you please reopen it ? What is the problem ?

**Comment by gnerred** [comment]
@rbovard, do you still have this problem too ?

**Comment by rbovard** [comment]
No it was fixed with the last release. Can you reproduce it here?

**Comment by gnerred** [comment]
Yes, if you try to open this URL on a mobile, it looses the theme like before : 
 https://map.cartoriviera.ch/theme/infrastructures?map_x=2554268.14022373&map_y=1145744.13691876&map_zoom=10&baselayer_opacity=100&baselayer_ref=plan_cadastral

**Comment by rbovard** [comment]
The question was if you can reproduce it on my server ;)

**Comment by sbrunner** [comment]
Do you apply the changes on your html file from the ngeo.diff?

**Comment by gnerred** [comment]
Yes I apply all the changes, but it is not impossible that I missed something... Could you please tell me which part I have to check ? The ngeo diff is no more available

**Comment by gnerred** [comment]
@rbovard  on your app it works :-)

**Comment by gnerred** [comment]
@sbrunner, I did now some corrections on my mobile.html, based on the mobile.html of CONST_create_template, on my preprod, but I always get the "default_mobile" theme (instead of the one in permalink) after using a short permalink on a mobile : 

https://preprod.cartoriviera.ch/s/fQcp 

Any other idea please ?

**Comment by sbrunner** [comment]
In your desktop.html you should have something like this: https://github.com/camptocamp/c2cgeoportal/blob/60e2ac0324c0ca76a2402bd05d45b8d8597baacd/c2cgeoportal/scripts/import_ngeo_apps.py#L204-L208

**Comment by gnerred** [comment]
Fine now it's OK thanks a lot !
