### ISSUE TITLE
Error message when changing password

### ISSUE THREAD

**Issue by rbovard** [camptocamp/ngeo#3203]
* GeoMapFish version: 2.1.11

Steps to reproduce the issue:

* Open login form and connect to the application
* Open change password form
* Put the same passwords 3 times

Result:
> L'ancien et le nouveau mots de passe sont différents.

Expected result:
> L'ancien et le nouveau mots de passe sont identiques.

**Comment by fredj** [comment]
```
#: contribs/gmf/src/directives/authenticationdirective.js:213
msgid "The old and new passwords are the same."
msgstr "L'ancien et le nouveau mots de passe sont différents."
```
:man_facepalming:

**Comment by rbovard** [comment]
Uh...

**Comment by fredj** [comment]
Changed in transifex

**Comment by sbrunner** [comment]
@fredj Can we close it?

**Comment by fredj** [comment]
yep, let's close it
