### ISSUE TITLE
Editing: Showing a link tag as a clickable link in a input field

### ISSUE THREAD

**Issue by svaabs** [camptocamp/ngeo#3210]
With cgxp we were able to insert an html link tag in a text field (for example `<a href="http://www.geo.bs.ch">Geoportal</a>`) of an editable layer. This text was interpreted as html and showed to the user as a link.
![image](https://user-images.githubusercontent.com/9248944/33610164-f0db382c-d9ca-11e7-9ad2-dddad6bc7037.png)
![image](https://user-images.githubusercontent.com/9248944/33610178-fde6c5d6-d9ca-11e7-97f4-38df39f004fd.png)

In ngeo this is not possible anymore.
![image](https://user-images.githubusercontent.com/9248944/33610255-38cac224-d9cb-11e7-8dd0-ea604ba8f76e.png)

How can we do this in ngeo?

Project:

* GitHub URL: https://github.com/camptocamp/baselstadt_mapbs
* GeoMapFish version: 2.2

Permalink directly where we can reproduce the issue:
 * https://geomapfish-demo.camptocamp.net/1.6/wsgi/edit
 * https://geomapfish-demo.camptocamp.net/2.2/theme/Edit

Steps to reproduce the issue:

* open GMF 1.6 with edit interface
* edit a feature
* insert a link tag in a input field
* leave the input field and click the link
* same with GMF 2.2, but you can't click the link

**Comment by sbrunner** [comment]
https://jira.camptocamp.com/browse/GSGMF-536
