### ISSUE TITLE
Editing: Saving the value "false" of a boolean does not work with constraint not null

### ISSUE THREAD

**Issue by svaabs** [camptocamp/ngeo#3212]
We do have an editable layer with boolean fields which can not be null. They also do have default values in the database.
In ngeo you can only save a feature of this layer when the boolean is set to _true_. Otherwise (with _false_) the field is treated as not set.

Project:

* GitHub URL: https://github.com/camptocamp/baselstadt_mapbs
* GeoMapFish version: 2.2

**Comment by sbrunner** [comment]
What the schema of the table?
`\d <schema>.<table>`

**Comment by sbrunner** [comment]
I don't need it anymore :-)

**Comment by sbrunner** [comment]
I just add a check column on the plygon layer on the demo :-)

**Comment by ger-benjamin** [comment]
> In ngeo you can only save a feature of this layer when the boolean is set to true. Otherwise (with false) the field is treated as not set.

You mean that you cannot save because it's treated as not filled and so, not valid ? right ?

**Comment by svaabs** [comment]
Yes, that's it

**Comment by ger-benjamin** [comment]
Done
