### ISSUE TITLE
Editing: Mandatory fields with lookup-table are not treated as mandatory

### ISSUE THREAD

**Issue by svaabs** [camptocamp/ngeo#3213]
If an editable layer has a mandatory field with foreign key (lookup-table), the dropdown is shown in the user interface, but there is no error message (like "This field is required") when no value is set (as if the field was optional) and you can click the save button. While saving, a server error occurs (since the database needs a value).

Project:

* GitHub URL: https://github.com/camptocamp/baselstadt_mapbs
* GeoMapFish version: 2.2

**Comment by sbrunner** [comment]
It seem that's not working on 1.6, than it's an new functionality...

**Comment by sbrunner** [comment]
https://jira.camptocamp.com/browse/GSGMF-537
