### ISSUE TITLE
MapServer run time substitution in ngeo

### ISSUE THREAD

**Issue by svaabs** [camptocamp/ngeo#3214]
For limiting the displayed features of a layer you could use MapServer run time substitution in cgxp and add the parameter _map_param_<param_name>_ to the URL. We were told, that the parameter in ngeo is called _dim_<param_name>_, but it does not work for us. Is there some more configuration needed?

Project:

* GitHub URL: https://github.com/camptocamp/baselstadt_mapbs
* GeoMapFish version: 2.2

**Comment by sbrunner** [comment]
Yes, in the database the layer should have a dimension with the same name and no value :-)

**Comment by svaabs** [comment]
Solved the problem, thank you!
