### ISSUE TITLE
Wrong coordinates labels in mobile measure

### ISSUE THREAD

**Issue by rbovard** [camptocamp/ngeo#3230]
* GeoMapFish version: 2.1.11

How to edit the `X` and `Y` since in Switzerland it's `Y` and `X` with CH1903 coordinates?

![image](https://user-images.githubusercontent.com/4549666/33754160-3e110cd0-dbeb-11e7-86ce-2df1c8e2bf90.png)

**Comment by sbrunner** [comment]
The X / Y are no more visible on 2.2
