### ISSUE TITLE
Issues with saving the date while editing

### ISSUE THREAD

**Issue by svaabs** [camptocamp/ngeo#3241]
There is an issues with date fields in the editing toolbox. When you edit an object, enter a date in a date field and save it, the wrong value is saved. In the database you can see that the date/time saved is the day before at 11pm. I assume that there is a problem with timezones.

Project:

* GitHub URL: https://geomapfish-demo.camptocamp.net/2.2/theme/Edit
* GeoMapFish version: 2.2

Permalink directly where we can reproduce the issue:
https://geomapfish-demo.camptocamp.net/2.2/theme/Edit?lang=de&tree_groups=Edit%2CSnapping%2CSnapping%20tollerance%2CSnapping%20no%20edge%2CSnapping%20no%20vertex&tree_group_opacity_Group=0.65&tree_enable_osm_scale=true&tree_group_layers_Layers=cinema%2Cpost_office%2Centertainment%2Csustenance%2Chospitals&tree_group_layers_Group&tree_group_layers_OSM%20functions=osm_scale&tree_group_layers_External=ch.swisstopo.geologie-geotechnik-gk500-lithologie_hauptgruppen&tree_enable_osm_open&tree_enable_ch.swisstopo.geologie-geotechnik-gk500-gesteinsklassierung&tree_enable_OSM%2520map&tree_enable_osm_time_r_dp_2&baselayer_ref=OSM%20map&theme=Edit&map_x=622155&map_y=178547&map_zoom=2&tree_group_layers_Edit=polygon

Steps to reproduce the issue:

* Edit layer "Polygon"
* Add a new polygon
* Enter a date in "timestamp" (for example 11.12.2017)
* Save the object
* Edit the saved feature
* The timestamp shown is the day before (in this case 10.12.2017)
* In the database you should see something like 10.12.2017 23:00:00 as value for "timestamp"

**Comment by sbrunner** [comment]
I just add a date, time and datetime on the plygon layer of the demo =>

* date shouldn't send the time on the PUT request
* datetime didn't show us the time
* time isn't supported

**Comment by sbrunner** [comment]
Shouldn't we use https://github.com/angular-ui/bootstrap?
Who has a time picker

**Comment by sbrunner** [comment]
Or directly https://eonasdan.github.io/bootstrap-datetimepicker/
