### ISSUE TITLE
How to set the coordinate format in mobileMeasurePointDirective

### ISSUE THREAD

**Issue by rbovard** [camptocamp/ngeo#3254]
* GeoMapFish version: 2.2.1

Because the default format is unreadable...

![image](https://user-images.githubusercontent.com/4549666/33878809-cc43d7b4-df2c-11e7-8e9c-bca6f3ee8043.png)

Nothing found there https://camptocamp.github.io/ngeo/2.2/apidoc/gmf.mobileMeasurePointDirective.html

**Comment by rbovard** [comment]
Is it possible to set the format or no?

**Comment by sbrunner** [comment]
We just can configure the number of decimals
with `gmf-mobile-measurepoint-coordinatedecimals` ...

**Comment by rbovard** [comment]
@sbrunner Any news on this one?

**Comment by sbrunner** [comment]
You see the following message?
https://github.com/camptocamp/ngeo/issues/3254#issuecomment-353064951

**Comment by rbovard** [comment]
Yes, ff course.

So you're telling me it's good enough to see coordinates like this?!

![image](https://user-images.githubusercontent.com/4549666/33878809-cc43d7b4-df2c-11e7-8e9c-bca6f3ee8043.png)

**Comment by rbovard** [comment]
Thanks, it's working.

@sbrunner FYI I noticed that the doc was not updated...
