### ISSUE TITLE
coordinate decimals in mobile measure

### ISSUE THREAD

**Issue by svaabs** [camptocamp/ngeo#3256]
The html attribute _gmf-mobile-measurepoint-coordinatedecimals_ does not work since the default value (0) is always used.

Configuration: https://github.com/camptocamp/demo_geomapfish/blob/master/demo/templates/mobile.html#L55
Result: 
![image](https://user-images.githubusercontent.com/9248944/33880926-7d78194a-df33-11e7-9228-de07317f0ac7.png)

Project:

* GitHub URL: https://github.com/camptocamp/demo_geomapfish
* GeoMapFish version: 2.2

Permalink directly where we can reproduce the issue:
https://geomapfish-demo.camptocamp.net/2.2/mobile

**Comment by sbrunner** [comment]
https://jira.camptocamp.com/browse/GSGMF-538
