### ISSUE TITLE
Legend button

### ISSUE THREAD

**Issue by svaabs** [camptocamp/ngeo#3258]
In the layer tree code I found a legend button called _.gmf-layertree-legend-button_ (see https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/src/directives/partials/layertree.html#L180-L187) which seems to do the same thing as the legend button within the extra actions (see https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/src/directives/partials/layertree.html#L139-L145). The difference is that the one in the extra actions is displayed and the other not, what is a pity since it is more userfrendly (directly clickable).
My question now is: What is the legend button (_.gmf-layertree-legend-button_) for, respectively is it possible to disable the legend button within the extra action and only enable the other legend button?

Project:

* GitHub URL: https://github.com/camptocamp/ngeo
* GeoMapFish version: 2.2

**Comment by sbrunner** [comment]
Should be reported on Jira as support issue
