### ISSUE TITLE
Zooming in with double tap/click should not fire a query

### ISSUE THREAD

**Issue by rbovard** [camptocamp/ngeo#3261]
Project:
* Host: https://geomapfish-demo.camptocamp.net/2.2/mobile
* GeoMapFish version: 2.2

Permalink directly where we can reproduce the issue:
* https://geomapfish-demo.camptocamp.net/2.2/mobile

Steps to reproduce the issue:

* Open above link with a mobile device
* Double tap to zoom in

Result:
* The map is zoomed in (OK)
* A query is fired (KO)

Expected result:
* No query should be fired

In fact this issue is also present in desktop interface with a double click, so it's a ngeo issue (it was fine in cgxp).

**Comment by fredj** [comment]
fixed with #3264

**Comment by rbovard** [comment]
Thanks, it's working.
