### ISSUE TITLE
Title of query results on more than one OGC layer on one GMF layer is not translated

### ISSUE THREAD

**Issue by rbovard** [camptocamp/ngeo#3263]
Project:

* GeoMapFish version: `2.2.1`

[Permalink directly where we can reproduce the issue](https://map-demo.nyon.ch/dev/mobile/theme/cadastre?lang=fr&baselayer_ref=plan_cadastral&tree_groups=adresses%2Ccadastre%2Climites_administratives&tree_group_layers_adresses&tree_group_layers_cadastre&tree_group_layers_limites_administratives&map_x=507843&map_y=137446&map_zoom=10)

Steps to reproduce the issue:

* Query the building **666**

Result:
* The title of the 2 results are "mo_par_prive" and "mo_baths"

Expected result:
* The title of the 2 results should be "Parcelles" and "Bâtiments" like in [desktop](https://map-demo.nyon.ch/dev/theme/cadastre?map_x=507843&map_y=137446&map_zoom=10&tree_group_layers_adresses=&tree_group_layers_cadastre=&tree_group_layers_limites_administratives=)

For history, you can take a look to #2604

**Comment by sbrunner** [comment]
When I build the project I have it in the `fr.json`, in your project not, can you remove `nyon/static-ngeo/build/fr.json` and redo a `make build`

**Comment by rbovard** [comment]
Thanks, it's better now...

But why the file was not uptodate? Some collateral effect of https://github.com/camptocamp/c2cgeoportal/issues/3308 ?

**Comment by sbrunner** [comment]
Probably yes...

**Comment by rbovard** [comment]
So I guess you will consider it when solving https://github.com/camptocamp/c2cgeoportal/issues/3308 ?
