### ISSUE TITLE
Behaviour of the authentication component with intranet user detection enabled

### ISSUE THREAD

**Issue by svaabs** [camptocamp/ngeo#3282]
We are using the intranet user detection which works well. Unhappily in the authentication component the intranet user is handled as a normal user. This means that anyone can change the password of the intranet user and this does not make sense. Other than this, you have to log out as intranet user and then log in with the personal user to get your specific authorisation. This is not very userfriendly.
Is there a way to change this?

Project:

* GitHub URL: https://github.com/camptocamp/baselstadt_mapbs
* GeoMapFish version: 2.2

**Comment by sbrunner** [comment]
Should be reported on Jira as support issue

**Comment by svaabs** [comment]
Since the expected behaviour is the same as it was in cgxp, we do not think that this is a support issue...
Are we wrong?

**Comment by ybolognini** [comment]
This "intranet user" behavior has been implemented (via the support contract) as a specific feature in CGXP version. It isn't part of the generic framework. That's why we think it should be implemented in Ngeo as a support issue.

**Comment by svaabs** [comment]
Ok, I see... Thank you for clarification.
