### ISSUE TITLE
Translation of the button tooltips in the edit feature form

### ISSUE THREAD

**Issue by svaabs** [camptocamp/ngeo#3342]
In the edit feature form there is a syntax issue with the translation of the button tooltips. The string of the title-attribute includes the translate-filter by mistake.
See https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/src/directives/partials/editfeature.html#L104-L125.

![image](https://user-images.githubusercontent.com/9248944/34667964-971dfe1c-f46b-11e7-9d4b-0989138eaf8f.png)

**Comment by llienher** [comment]
Fixed here:
https://github.com/camptocamp/ngeo/pull/3267

This is going with the next minor release: 2.2.2. We will port it to master as well.
I close this issue.
