### ISSUE TITLE
change color of search result

### ISSUE THREAD

**Issue by svagap** [camptocamp/ngeo#3348]
in cgxp the user had the possibility to change the color of search result. Is this feature implemented (or will it be implemented) in ngeo?

![change_color_searchresult](https://user-images.githubusercontent.com/29245949/34707115-87b07b38-f503-11e7-8de4-5f8470dd0887.PNG)

**Comment by ger-benjamin** [comment]
Hello,

Yes this feature exist in ngeo.
You may add a `gmf-search-colorchooser=::true` attribute to the gmf-search markup in your index.html 
See: https://camptocamp.github.io/ngeo/2.2/apidoc/gmf.searchDirective.html

**Comment by svagap** [comment]
Ok, if found it, and set it to true. No I can choose a color but the search result is still blue. In the demo the color-chooser is not activated. Does this feature work?

**Comment by ger-benjamin** [comment]
Yes it should work.
We don't have it on our demo. But our "desktop_alt" page and the search example on github have it (search a locality): 
 - https://camptocamp.github.io/ngeo/2.2/examples/contribs/gmf/apps/desktop_alt/
 - https://camptocamp.github.io/ngeo/2.2/examples/contribs/gmf/search.html
(You can find these links in the README of the ngeo project).

So, that should work.

Can you try to add 
`/** @suppress {extraRequire} */`
`goog.require('ngeo.colorpickerDirective') 
here: https://github.com/camptocamp/baselstadt_mapbs/blob/master/mapbs/static-ngeo/js/ngeodesktop.js#L16

Then rebuild, and test

If that doesn't work, can you add "?debug" at the url and in the "developer tool" (ctrl+maj+i) of your browser, open "source" (or debugger on firefox) and search a file (ctrl+p) named "colorpicker.js". Do you have it ?

**Comment by svagap** [comment]
thank you. I could manage to activate the color-chooser. As mentioned above, it does not work for "point-search-result" (see attached images)
![gmfsearch_notwork](https://user-images.githubusercontent.com/29245949/34824785-cedd68ac-f6c7-11e7-8c76-d2db11ff1820.PNG)
![Uploading gmfsearch_work.PNG…]()

**Comment by ger-benjamin** [comment]
Nice :-)

**Comment by svagap** [comment]
not so nice if it doesn't work as expected. **the point search result does not change its color** is this working as expected?

**Comment by ger-benjamin** [comment]
Oh, sorry I doesn't see this. It's effectively an issue. I take it !

**Comment by ger-benjamin** [comment]
This time it's fixed with #3387 
It fixes the color on points. It was already working on Linestrings and Polygons.
