### ISSUE TITLE
2.2.1 - Timeslider

### ISSUE THREAD

**Issue by kalbermattenm** [camptocamp/ngeo#3380]
The timeslider should take into account the type of time interval (year, day, month).

Typically, we have a layer having the following metadata:

```
    METADATA
        ${mapserver72}
        "ows_title" "fusion_communes"
        "wms_srs" "EPSG:${srid}"
        "gml_include_items" "cadnom1,annee1"
        "wfs_enable_request" "*"
        "gml_geometries" "geom"
        "gml_geom_type" "polygon"
        "wms_timeextent" "1870,1875,1888,1900,1930,2009,2013,2016,2018"
        "wms_timedefault" "2018"
        "wms_timeitem" "date"
END
```

This results in:

![image](https://user-images.githubusercontent.com/1681332/34879481-ade9023c-f7ad-11e7-9e36-f5c572a06b58.png)

In GMF 1.6, this was better taken into account (regarding the type of time/date):

![image](https://user-images.githubusercontent.com/1681332/34879628-1f76ee46-f7ae-11e7-97d3-d4ddd9e56d35.png)

**Comment by sbrunner** [comment]
Reproducible with: https://camptocamp.github.io/ngeo/2.2/examples/contribs/gmf/apps/desktop_alt/?lang=fr&baselayer_ref=OSM%20map&tree_enable_ch.swisstopo.dreiecksvermaschung&tree_enable_ch.swisstopo.geologie-gravimetrischer_atlas&tree_enable_ch.swisstopo.geologie-geotechnik-gk500-lithologie_hauptgruppen&tree_enable_ch.swisstopo.geologie-geotechnik-gk500-gesteinsklassierung&tree_enable_ch.are.alpenkonvention&tree_enable_ch.astra.ausnahmetransportrouten&tree_group_opacity_Group=0.65&tree_enable_osm_time_v_s&tree_groups=OSM%20functions%20mixed&tree_enable_osm_scale&tree_group_layers_Layers=cinema%2Cpolice%2Cpost_office%2Centertainment%2Csustenance%2Chospitals&tree_group_layers_Group&tree_group_layers_OSM%20functions=osm_scale&tree_group_layers_External&tree_enable_osm_open&tree_enable_OSM%20map&tree_enable_osm_time_r_dp_2&tree_group_layers_Filters&tree_enable_osm_time_r_year_mounth&tree_enable_osm_time_r_mounth_year&tree_enable_osm_time_r_s&tree_enable_osm_time_v_mounth_year=true

**Comment by ger-benjamin** [comment]
Will be fixed with : #3390 But you should localize it Otherwise, it use these formats: "M/d/yy", "M/yy", "yy", so same format as shortdate: https://docs.angularjs.org/api/ng/filter/date

**Comment by kalbermattenm** [comment]
Thanks @ger-benjamin !

But the localize stuff means what ? That:

```
  "wms_timeextent" "70,75,88,00,30,09,13,16,18"
  "wms_timedefault" "18"
```

How is the system supposed to understand that some date are from de 18th century, others from de 19th, etc. ??

Sorry, I might have misunderstood something here ?

**Comment by ger-benjamin** [comment]
One change is that it take the time resolution to write the date: 80 (year), or 1/80 (month) or 1/23/80 (day). That will be automatically with the "wms_timeextent" via the specified resolution..
But with your special case, I think we can't know if that's day, month or year and there is no manner to fix it properly in ngeo. Can you try with: "1970,1975,1988,2000,2030,2009,2013,2016,2018" ?
Otherwise, you can try with multiple range values and by specified the resolution of each range. Looks the 4th example: http://mapserver.org/ogc/wms_time.html#specifying-time-extents

Then, about i18n, if you want that in french the displayed value is 1980, 01.1980 or 23.01.1980, you must translate the strings "yy", "M/yy", "M/dd/yy" by respectively "yyyy", "MM.yyyy", "dd.MM.yyyy".

**Comment by kalbermattenm** [comment]
OK, thanks, but where do I have to do that:

> Then, about i18n, if you want that in french the displayed value is 1980, 01.1980 or 23.01.1980, you must translate the strings "yy", "M/yy", "M/dd/yy" by respectively "yyyy", "MM.yyyy", "dd.MM.yyyy".

I mean, where are the translations stored (file) ?

**Comment by sbrunner** [comment]
We will put the year on 4 digit in all the cases, it's clearer :-)

**Comment by ger-benjamin** [comment]
> I mean, where are the translations stored (file) ?

In your client i18n files:
`<proj>/locale/<lang>/LC_MESSAGES/<proj>-client.po`

**Comment by kalbermattenm** [comment]
Alright !!! Thanks a lot @ger-benjamin, I will give it a try tomorrow !!
