### ISSUE TITLE
2.2.1 - Metadata link in mobile is wrong

### ISSUE THREAD

**Issue by kalbermattenm** [camptocamp/ngeo#3408]
Metadata link in the mobile app is not the same as in the desktop app.

We have the `gmf-layertree-openlinksinnewwindow` option set to true.

In the desktop app, this generates a correct URL: https://sitn.ne.ch/dev_internet2/metadata/show?id=axe_rue_adresses

In the mobile app, the generated URL contains the `mobile` alias (and it should not....): https://sitn.ne.ch/dev_internet2/mobile/metadata/show?id=axe_rue_adresses

![image](https://user-images.githubusercontent.com/1681332/35087782-b34f88b2-fc31-11e7-8d64-cde09e896118.png)

**Comment by fredj** [comment]
That's because the `metadataUrl` is relative: `../metadata/show?id=mo02_adresses_sitn`

Would it be possible to change it to `/metadata/show?id=mo02_adresses_sitn` or even fully absolute to `https://sitn.ne.ch/metadata/show?id=mo02_adresses_sitn` ?

**Comment by sbrunner** [comment]
With this https://camptocamp.github.io/c2cgeoportal/2.2/integrator/customise.html#url
You should be able to have deferent URL between deferent environments.

**Comment by kalbermattenm** [comment]
OK, thanks ! I get it.

@fredj's solution is working, because it is always calling the production instance which is stable (but our metadata page style has changed).

I was not aware about @sbrunner's solution, which is elegant but which needs some conf.

I will use @fredj's solution first and implement @sbrunner's solution ;-)

Thanks a lot !
