### ISSUE TITLE
IE/Edge print console error

### ISSUE THREAD

**Issue by llienher** [camptocamp/ngeo#3417]
Demo 2.2 using IE11/Edge, the print send an error.
I did try on Firefox/Chrome (both Win10) and it worked correctly... Also it is only appear when having a visible layer in the layer-tree. If I just send a wmts background layer it works.

com.vividsolutions.jts.util.AssertionFailedException: Expected 200 but encountered 500: Http status code for http://127.0.0.1/2.2/wsgi/mapserv_proxy?ogcserver=Main%2BPNG&TRANSPARENT=true&MAP_RESOLUTION=254&cache_version=a694de341ba749619cf4ee7b348a659c&BBOX=614377.6041666666%2C182047.4375%2C619272.3958333333%2C188000.5625&VERSION=1.1.1&FORMAT=image%2Fpng&SERVICE=WMS&HEIGHT=2382&REQUEST=GetMap&LAYERS=fuel&STYLES=&SRS=EPSG%3A21781&WIDTH=1958 was not OK.  It was: 500. The response message was: 'Internal Server Error'

I'm not sure if it is an issue with the demo environment or is going to have an impact on projects ...

**Comment by sbrunner** [comment]
In this case we have a doulbe encoding of the ogcserver ' ' => '+' => '%2B' :-(

**Comment by llienher** [comment]
The issue comes from url-polyfill dependency. It doesn't return the right value in Edge 16 (17 is supposed to fully support URL and URLsearchParams APIs), but encode the plus sign instead of replacing it with a space as do Chrome and Firefox in the native implementation. I opened a issue in their repo: https://github.com/lifaon74/url-polyfill/issues/15.

**Comment by llienher** [comment]
No more work to do, full js implementation (look url-polyfill issue above) is not going to be used and the provided fix we did is fine for us.
