### ISSUE TITLE
Time layers filter only once

### ISSUE THREAD

**Issue by ybolognini** [camptocamp/ngeo#3419]
Tested on demo server and github.io

 * Clean start
 * "Filters" theme
 * Activate only "Temps OSM popup interval 2" from group "Filtres mixés"
 * Zoom out to have a wider view and more points
 * Select a smaller interval (for instance 2012 to 2013)
 * Number of points displayed is smaller --> OK
 * Select back a larger interval (for instance 2003 to 2013)
 * Number of points stays the same --> It should go back to the initial number of points

Looks like Date filters work. So this problem would be only on time interval in the layer tree?

More tests...

It looks like this problem appears only for certain time intervals. Is this linked to the number of points displayed?  When displaying a lot of points from the "Temps OSM popup interval 2" layer, it works with intervals [1/1/2013 - 1/12/2013], [1/1/2012 - 1/12/2013] but it doesn't work with interval [1/1/2006 - 1/12/2013].

**Comment by sbrunner** [comment]
We get the server response...:
```
<?xml version='1.0' encoding="UTF-8" standalone="no" ?>
<ServiceExceptionReport version="1.3.0" xmlns="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/ogc http://schemas.opengis.net/wms/1.3.0/exceptions_1_3_0.xsd">
<ServiceException code="InvalidDimensionValue">
msWMSApplyTime: WMS server error. Time value(s) 2000-01/2013-12 given is invalid or outside the time extent defined (2006-01/2013-12/P1M).
</ServiceException>
</ServiceExceptionReport>
```

**Comment by fredj** [comment]
This is because the min and max date are not correctly passed to the jquery ui datepicker.
Patch to come.
