### ISSUE TITLE
2.2.1 - Mobile measure sketch colors

### ISSUE THREAD

**Issue by kalbermattenm** [camptocamp/ngeo#3420]
Currently the sketch colors are something in between gray and black. Is there any reason or would another color (notably red) be acceptable ?

The problem is when measuring on the famous "Plan cadastral" which almost all Swiss GMF users have, it is hardly possible to see the measure lines and pointer.

Could @rbovard @gnerred @vvmalbre @mriedo @gsollberger @svaabs give me there point of view ?

The colors are currently hard coded:

https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/src/mobile/measure/lengthComponent.js#L127-L148

**Comment by rbovard** [comment]
It is not exposed? See https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/src/mobile/measure/lengthComponent.js#L49

**Comment by kalbermattenm** [comment]
Ah.... you're right ! Sorry for the noise...
