### ISSUE TITLE
mobile measure length: sketchStyle broken

### ISSUE THREAD

**Issue by pfirpfel** [camptocamp/ngeo#3436]
Affected versions: 2.2, master

https://github.com/camptocamp/ngeo/blob/fd3bb5695ec839e67690955711c13c3b10822d2a/contribs/gmf/src/directives/mobilemeasurelength.js#L121-L123

If a gmf-mobile-measurelength-sketchstyle parameter is supplied, it does not get applied. Since eveything happens in the constructor, the external style object is just not present at that time.
The component should be initialized in the init-function. I tested that in a messy hack, it works.

gmf-mobile-measurepoint has it implemented like [this](https://github.com/camptocamp/ngeo/blob/fd3bb5695ec839e67690955711c13c3b10822d2a/contribs/gmf/src/directives/mobilemeasurepoint.js#L234), an there the style is working.

**Comment by fredj** [comment]
fixed with #3438
