### ISSUE TITLE
[apidoc] Use tag to split or mark the angular components types?

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/ngeo#345]
* Use the tag `@ngdoc` defied by `angular-jsdoc` https://github.com/allenhwkim/angular-jsdoc#tags-available

* Takes car about it in `buildNav`: https://github.com/camptocamp/ngeo/blob/master/jsdoc-template/publish.js#L341
  To group by angular types or add a mark.

**Comment by elemoine** [comment]
Could you please be more specific?

**Comment by sbrunner** [comment]
Description updated :-)
