### ISSUE TITLE
Filter: get data only works if layer is displayed in map

### ISSUE THREAD

**Issue by svades** [camptocamp/ngeo#3468]
Project:
* GeoMapFish version: 2.2.0, can also be reproduced on 2.2.2
* URL: https://map.geo.test.bs.ch/ngeodesktop

Steps to reproduce the issue:
* open theme "Wald, Flora, Fauna", don't load/activate any layers
* open filter for "Bäume"
* choose some filter condition (e.g. spatial filter)
* choose get data
* same issue could also be reproduced on demo https://geomapfish-demo.camptocamp.net/2.2

Result: nothing happens!

Expected result: the filtered data should appear in the displayquerygrid

At least something should happen. Thinkable possibilitites:
- the filtered data appear in the displayquerygrid without the layer being activated/loaded in the map and is highlighted in the map (like cgxp)
- the layer is only chooseable in the filterpanel if the layer is activated/displayed in the map
- the layer gets activated/displayed by choosing "get data"

**Comment by yjacolin** [comment]
on Demo, you can [test on the GMF 2.2 instance](https://geomapfish-demo.camptocamp.net/2.2/theme/Demo?lang=fr&baselayer_ref=OSM%20map&theme=Demo&tree_groups=OSM%20functions&map_x=632484&map_y=185457&map_zoom=3&tree_group_layers_Filters=osm_open&tree_group_layers_OSM%20functions=osm_open) (filter on "Ouverture OSM")

There is something similar with "apply filter" on background layer. User should know that the request has been sent and why nothing happen.

**Comment by eleu** [comment]
reported to jira

**Comment by ger-benjamin** [comment]
(reopen, wrong issue)

**Comment by sbrunner** [comment]
Managed on JIRA
