### ISSUE TITLE
Layer groups are marked as indeterminate even if every layer is deactivated

### ISSUE THREAD

**Issue by svaabs** [camptocamp/ngeo#3479]
Some times layer groups are marked as _indeterminate_ although no layer or group within this group is activated. After enabling and disabling any layer, the groups state changes from _indeterminate_ to _off_.

Perhaps it is because we have a hierarchy of three layer groups?

Result:
![image](https://user-images.githubusercontent.com/9248944/35736300-ca313fd8-0827-11e8-8bb7-f60a5123c50f.png)

Expected result:
![image](https://user-images.githubusercontent.com/9248944/35736320-e150c418-0827-11e8-9e76-9f25945e1b95.png)

**Comment by sbrunner** [comment]
Unable to reproduce in 2.3...
