### ISSUE TITLE
[apidoc] Do not show the directive controllers

### ISSUE THREAD

**Issue by elemoine** [camptocamp/ngeo#349]
The apidoc currently includes directive controllers (e.g. [`MapController`](http://camptocamp.github.io/ngeo/master/apidoc/gmf.MapController.html)). This should not be the case as, in most cases, directives controllers are not used at the application-level, they're private to their directives.

**Comment by sbrunner** [comment]
Why should we hide it?

**Comment by sbrunner** [comment]
They shouldn't be marked as `@private`?

**Comment by fredj** [comment]
`@private` is for properties not class so it shouldn't work (to be tested)

**Comment by sbrunner** [comment]
`@private` work in the documentation generation but not in the closure build :-(

**Comment by sbrunner** [comment]
Tested here: https://github.com/camptocamp/ngeo/commit/4203826
