### ISSUE TITLE
gmf 2.2.2 - mobile location (iOS)

### ISSUE THREAD

**Issue by svagap** [camptocamp/ngeo#3492]
We tried to use the location feature in mobile interface of GMF but the browser shows the message "Location is not available" instead of requesting the permission to use the location.

On other website with location service, the request for permission is available.

The location Service works with other mobile (Windows Phone)

![locationnotavailable](https://user-images.githubusercontent.com/29245949/35965228-1d2e6df8-0cb2-11e8-8d15-977562eea1d4.PNG)
![locationrequestother](https://user-images.githubusercontent.com/29245949/35965230-1d4ae21c-0cb2-11e8-8aff-1c98098303a7.PNG)

You can test ist yourself https://map.geo.test.bs.ch/mobile (gmf 2.2.2)
or https://map.geo.bs.ch/mobile (gmf 2.2.0)

**Comment by fredj** [comment]
@svagap In the first screenshot, the `https` in the address bar is not green as in the second screenshot: that means that the site was loaded in http instead of https. The geolocation only works in https mode.

**Comment by svagap** [comment]
OK, thank you. I see the problem. 

In the moment, "our" https configuration is not "complete" as some data (tiles of wmts etc) is loaded by http and so it "breaks" the "secure" connection (the sign is green, and as soon as some data is loaded switches to gray/black
