### ISSUE TITLE
Popup (z-index)

### ISSUE THREAD

**Issue by kalbermattenm** [camptocamp/ngeo#3494]
Info popup (created using `ngeoCreatePopup`) should always be on top, even regarding the contextual data window:

![image](https://user-images.githubusercontent.com/1681332/35978171-4877d264-0ce5-11e8-8633-f2a61bb4ae93.png)

**Comment by llienher** [comment]
Fixed with #3602

**Comment by kalbermattenm** [comment]
Thanks @llienher ,
