### ISSUE TITLE
Print with Drawings

### ISSUE THREAD

**Issue by svagap** [camptocamp/ngeo#3495]
When a user draw anything and tries to print the drawings, an error is created (see attachment)

It seams to me that the content-type is set wrong. See attachment.

In our dev environment, the printing is successfull, in Test environment, the printing fails (see also https://github.com/camptocamp/ngeo/pull/3369)

![dev_report_draw](https://user-images.githubusercontent.com/29245949/35978801-8e237ffe-0cde-11e8-880b-2092f7cb1d11.PNG)
![dev_report_nodraw](https://user-images.githubusercontent.com/29245949/35978802-8e515d16-0cde-11e8-88f9-00c9494f460c.PNG)
![test_report_draw](https://user-images.githubusercontent.com/29245949/35978803-8e79696e-0cde-11e8-93fb-0637e055f970.PNG)
![test_report_nodraw](https://user-images.githubusercontent.com/29245949/35978804-8e94e5f4-0cde-11e8-870f-fac78b9ea8a5.PNG)

**Comment by llienher** [comment]
Third and fourth screenshots are on the test server (where the request failed). What was the manipulation that lead to the 'failed' request, then the successfully generated request ? 
I'm able to get this on your server, but not our demo.
Does it means it works sometimes or the last screen is without drawn geometry ?

We already have the print request header set here with content-type 'application/json; charset=UTF-8':
https://github.com/camptocamp/ngeo/blob/2.2/src/services/print.js#L875

**Comment by svagap** [comment]
the only manipulation was to draw something.
go to http://map.geo.test.bs.ch/ngeodesktop?lang=de&baselayer_ref=Grundkarte%20grau&map_x=2611260&map_y=1267465&map_zoom=10
print -> success, open drawing, place a circle print -> error

But me assumtation was not correct. The request header content type is correct (application/json) on both successfully and not successfully request.

After further investigations, it seams our proxy does not allow the format of the payload in the request. I will see with our IT. This ticket can be closed.
