### ISSUE TITLE
Contextual data popup size

### ISSUE THREAD

**Issue by kalbermattenm** [camptocamp/ngeo#3496]
There is something strange with the popup size of the contextual data window.

The line containing the latitude / longitude data in DMS coordinates is always just a bit to small. We have the same behavior on the SITN project.

I did not see any parameter to set the width nor height, thus is it some kind of compiling bug ?

![image](https://user-images.githubusercontent.com/1681332/35978892-29e614b2-0ce7-11e8-8c63-7ec422cd51b0.png)

**Comment by gnerred** [comment]
@kalbermattenm FYI I solved this problem by creating a static-ngeo/components/contextualdata/contextualdata.less containing that : 

div.gmf-contextualdata {
  min-width: 320px;
}
and added @import "../components/contextualdata/contextualdata.less"; in desktop.less file

**Comment by fredj** [comment]
This issue in (at least) firefox, it's fine on chrome

**Comment by fredj** [comment]
See #3562

**Comment by fredj** [comment]
with #3562, the content of the table (keys and values) will stay is one line

**Comment by kalbermattenm** [comment]
Great ! Thanks a lot @fredj
