### ISSUE TITLE
Logout if DisplayQueryGrid is open

### ISSUE THREAD

**Issue by svagap** [camptocamp/ngeo#3497]
if the display query grid (bottom) is open an a logout is perfomed, the display query grid disappear but the area/html element stays open and cannot be removed.

The display query grid should be closed before the logout is performed 
Logged in with display query grid open:
![beforelogout](https://user-images.githubusercontent.com/29245949/36015774-ed1b2604-0d67-11e8-998e-ae62f9feb3cf.PNG)

After clicking "logout" -> display query grid gone but "space" still there:
![afterlogout](https://user-images.githubusercontent.com/29245949/36015773-ecf76c78-0d67-11e8-85e1-187ec8366042.PNG)

**Comment by sbrunner** [comment]
https://jira.camptocamp.com/browse/GSGMF-515
