### ISSUE TITLE
[apidoc] Directives should not be presented as constructors

### ISSUE THREAD

**Issue by elemoine** [camptocamp/ngeo#350]
Currently, the apidoc presents directives as constructors, by advertising the use of `new` to create a directive. See the [`ngeo.layertreeDirective` doc page](http://camptocamp.github.io/ngeo/master/apidoc/ngeo.layertreeDirective.html) for example.

**Comment by sbrunner** [comment]
We should find the right way to do it because I will have some issue to add directive in the documentation if I don't add the `@constructor`...

**Comment by elemoine** [comment]
I did not see that you added `@constructor` annotations to directive factories. Adding `@constructor` to directives is not correct as the directive factories are not constructors for Closure Compiler.

**Comment by fredj** [comment]
see #371
