### ISSUE TITLE
Displayquerywindow: long layer name cut off

### ISSUE THREAD

**Issue by svades** [camptocamp/ngeo#3507]
Project:

* GeoMapFish version: 2.2.2

Steps to reproduce the issue:

* query a layer with a long name
* have a look at the titel in displayquerywindow

Result: the layer name is cut off and overflows the "x" to close the window (see screenshot). Not the whole layer name is visible.

Expected result: there is a word wrap for long layer names and the whole layer name is visible

![longname_displayquerywindow](https://user-images.githubusercontent.com/22655359/36097968-763bf5d4-0ffd-11e8-9b45-a332b8cc9bcf.PNG)

**Comment by sbrunner** [comment]
https://jira.camptocamp.com/browse/GSGMF-539
