### ISSUE TITLE
Objects of permalink are not compatible between CGXP and NGEO

### ISSUE THREAD

**Issue by gnerred** [camptocamp/ngeo#3515]
To reproduce : 

1°/ Open this permalink : https://preprod.cartoriviera.ch/s/PW3H -> some objects are drawn
2°/ Switch to NGEO interface by adding "new" after ""preprod.cartoriviera.ch/" : https://preprod.cartoriviera.ch/new/theme/cadastre?map_x=2556083.5671509&map_y=1145050.0126103&map_zoom=4&rl_features=Fa(kc1sh-9gvuQ.75E3dG..65E~r*true%27c*%2523ff0000%27k*5)l(eh-bkGtrHsNmrBj-xf!prDdE2gCksGgh!fpGkV~c*%2523339966%27k*8)a(auMn3E.h3Asg*..g3A~r*true%27c*%252333CCCC%27k*4)&lang=fr&tree_groups=cadastre%2Ccouverture_du_sol&tree_group_layers_cadastre=limite_commune%2Cbatiments_projetes&tree_group_layers_couverture_du_sol=&baselayer_ref=plan_cadastral -> objects are not shown

It is important to keep permalink compatibility between versions, as discussed in PSC.

**Comment by sbrunner** [comment]
https://jira.camptocamp.com/browse/GSGMF-516
