### ISSUE TITLE
print and filter

### ISSUE THREAD

**Issue by svagap** [camptocamp/ngeo#3518]
It is not possible to print a filtered view

see 
![filterprint](https://user-images.githubusercontent.com/29245949/36197564-04390402-116c-11e8-8c04-3ac8e8cf1f38.gif)

I suppose this is a bug not a feature...

**Comment by llienher** [comment]
@ybolognini Is there any discussion over this use case ?

**Comment by sbrunner** [comment]
https://jira.camptocamp.com/browse/GSGMF-535
