### ISSUE TITLE
No loading message when querying features

### ISSUE THREAD

**Issue by svades** [camptocamp/ngeo#3519]
Steps to reproduce the issue:

* query a big dataset or a lot of features
* wait a long time until the displayquerygrid or the displayquerywindow appears

Result:
No loading message appears and the user doesn't know if anything is happening or not.

Expected result:
A loading message or some feedback appears so the user knows the features are beeing queried.

**Comment by sbrunner** [comment]
https://jira.camptocamp.com/browse/GSGMF-540
