### ISSUE TITLE
[apidoc] Classes have no namespace

### ISSUE THREAD

**Issue by elemoine** [camptocamp/ngeo#352]
Classes like `ngeo.interaction.Measure` have no namespaces in the documentation. See http://camptocamp.github.io/ngeo/master/apidoc/ngeo.interaction.Measure.html.

**Comment by sbrunner** [comment]
I don't understand this issue ...

**Comment by tsauerwein** [comment]
Just by looking at the [page](http://camptocamp.github.io/ngeo/master/apidoc/ngeo.interaction.Measure.html) you don't know that this class `Measure` has the namespace `ngeo.interaction.Measure`. For example the OpenLayers docs show the full name: http://openlayers.org/en/master/apidoc/ol.interaction.Select.html

**Comment by sbrunner** [comment]
OK then it's the case for all objects, not only for this one!
