### ISSUE TITLE
Filter: recognize numbers and date

### ISSUE THREAD

**Issue by svades** [camptocamp/ngeo#3522]
Project:

* GitHub URL: https://github.com/camptocamp/baselstadt_mapbs
* GeoMapFish version: 2.2.2

Permalink directly where we can reproduce the issue:
http://map.geo.test.bs.ch/ngeodesktop?lang=de&baselayer_ref=Grundkarte%20grau&tree_groups=Baumkataster&tree_group_layers_Allmendbewilligungen=&tree_group_layers_Solarkataster=SX_Solarpotenzial_Solarthermie_Gebaeude&tree_enable_BA_Baeume=true&map_x=2611357&map_y=1267536&map_zoom=7

Steps to reproduce the issue:

* open the permalink
* open the filter for "Bäume"
* the attributes of type number and date are not recognized as such

numbers:
Only the field type "numeric" is recognized as number.
The field types "integer", "bigint" and "double precision" and similar should also be recognized as numbers.

date:
Only the field type "timestamp" is recognized as date.
The field type "date" sould also be recognized as date.

![filter_number](https://user-images.githubusercontent.com/22655359/36206226-e74a3412-1191-11e8-9d90-40367c518bcd.png)
![filter_date](https://user-images.githubusercontent.com/22655359/36206232-edccb774-1191-11e8-814d-35a02ce7e1b0.png)

**Comment by eleu** [comment]
reported to jira

**Comment by fredj** [comment]
fixed with #3650
