### ISSUE TITLE
print - different result cgxp vs. ngeo

### ISSUE THREAD

**Issue by svagap** [camptocamp/ngeo#3545]
When printing the same situation with the same scale the result looks very different in cgxp and ngeo. 

The request payload in cgxp is:
`{"layout":"A4 Hochformat","outputFormat":"pdf","attributes":{"title":"","comment":"","map":{"projection":"EPSG:2056","dpi":254,"rotation":0,"center":[2611217.5,1267284.25],"scale":750,"longitudeFirst":true,"layers":[{"baseURL":"http://map.geo.dev.bs.ch/main/wsgi/mapserv_proxy?username=svagapx&cache_version=86b7babe7fd7452f81d5a1c5a880efcc","opacity":1,"type":"wms","version":"1.0.0","imageFormat":"image/png","layers":["Parzellenplan_Bodenbedeckung_sw"],"useNativeAngle":true,"serverType":"mapserver"}]}}}`

and the result looks nice:
[cgxp_MapBS.pdf](https://github.com/camptocamp/ngeo/files/1740509/cgxp_MapBS.pdf)

the same "location" in ngeo creates a payload like this:
`{"attributes":{"map":{"dpi":254,"rotation":0,"center":[2611206.8604263472,1267272.25],"projection":"EPSG:2056","scale":750,"layers":[{"baseURL":"http://map.geo.dev.bs.ch/main/tiles/1.0.0/Parzellenplan_Bodenbedeckung_sw/default/{DATE}/{TileMatrixSet}/{TileMatrix}/{TileRow}/{TileCol}.png","dimensions":["DATE"],"dimensionParams":{"DATE":"2013"},"imageFormat":"image/png","layer":"Parzellenplan_Bodenbedeckung_sw","matrices":[{"identifier":"0","scaleDenominator":178571.428571,"tileSize":[256,256],"topLeftCorner":[2585000,1290000],"matrixSize":[5,4]},{"identifier":"1","scaleDenominator":71428.5714286,"tileSize":[256,256],"topLeftCorner":[2585000,1290000],"matrixSize":[12,10]},{"identifier":"2","scaleDenominator":35714.2857143,"tileSize":[256,256],"topLeftCorner":[2585000,1290000],"matrixSize":[25,21]},{"identifier":"3","scaleDenominator":17857.1428571,"tileSize":[256,256],"topLeftCorner":[2585000,1290000],"matrixSize":[50,42]},{"identifier":"4","scaleDenominator":8928.57142857,"tileSize":[256,256],"topLeftCorner":[2585000,1290000],"matrixSize":[101,85]},{"identifier":"5","scaleDenominator":7142.85714286,"tileSize":[256,256],"topLeftCorner":[2585000,1290000],"matrixSize":[126,107]},{"identifier":"6","scaleDenominator":5357.14285714,"tileSize":[256,256],"topLeftCorner":[2585000,1290000],"matrixSize":[169,143]},{"identifier":"7","scaleDenominator":3571.42857143,"tileSize":[256,256],"topLeftCorner":[2585000,1290000],"matrixSize":[253,214]},{"identifier":"8","scaleDenominator":1785.71428571,"tileSize":[256,256],"topLeftCorner":[2585000,1290000],"matrixSize":[507,429]},{"identifier":"9","scaleDenominator":892.857142857,"tileSize":[256,256],"topLeftCorner":[2585000,1290000],"matrixSize":[1015,859]},{"identifier":"10","scaleDenominator":357.142857143,"tileSize":[256,256],"topLeftCorner":[2585000,1290000],"matrixSize":[2539,2148]},{"identifier":"11","scaleDenominator":178.571428571,"tileSize":[256,256],"topLeftCorner":[2585000,1290000],"matrixSize":[5078,4296]},{"identifier":"12","scaleDenominator":89.2857142857,"tileSize":[256,256],"topLeftCorner":[2585000,1290000],"matrixSize":[10156,8593]},{"identifier":"13","scaleDenominator":35.7142857143,"tileSize":[256,256],"topLeftCorner":[2585000,1290000],"matrixSize":[25390,21484]}],"matrixSet":"swissgrid","opacity":1,"requestEncoding":"REST","style":"default","type":"WMTS","version":"1.0.0"}]},"datasource":[],"lang":"de","rotation":0,"scale":750},"format":"pdf","layout":"A4 Hochformat"}`

and a result like this (bad)
[ngeo_MapBS.pdf](https://github.com/camptocamp/ngeo/files/1740511/ngeo_MapBS.pdf)

In my opinion the result should be identical.

**Comment by jwkaltz** [comment]
Could this be related to https://github.com/camptocamp/ngeo/issues/3555 ?

**Comment by eleu** [comment]
Reported to Jira.

Solution: add printLayers metadata for the WMTS layer concerned.
