### ISSUE TITLE
ngeo doesn't take into account "tilematrixset" of admin for WMTS layers

### ISSUE THREAD

**Issue by gnerred** [camptocamp/ngeo#3555]
Version 2.2.2

When configuring a WMTS layer in admin interface and specifying the tilematrixset (for a layer with 2 tilematrixset available), this value is not taken into account in application, and the default tilematrixset is used. To reproduce : go to https://preprod.cartoriviera.ch/new/ -> the tiles of layer asitvd.fond_cadastral are loaded with tilematrixset 21781 :  

https://ows.asitvd.ch/wmts?layer=asitvd.fond_cadastral&style=default&tilematrixset=21781&Service=WMTS&Request=GetTile&Version=1.0.0&Format=image%2Fpng&TileMatrix=19&TileCol=24&TileRow=38&DIM1=default&ELEVATION=0

But the tiles should have 2056 instead of 21781 : 

https://ows.asitvd.ch/wmts?layer=asitvd.fond_cadastral&style=default&tilematrixset=2056&Service=WMTS&Request=GetTile&Version=1.0.0&Format=image%2Fpng&TileMatrix=19&TileCol=24&TileRow=38&DIM1=default&ELEVATION=0

So ngeo does a reprojection and the final quality is bad. The admin config is the followin : 
![image](https://user-images.githubusercontent.com/1989467/36485684-fc2e0332-171c-11e8-9823-5af7631b4f0d.png)

Here is the getcapabilities : https://ows.asitvd.ch/wmts?service=wmts&request=getcapabilities

**Comment by llienher** [comment]
Can be reproduced on our 2.2 demo.
CGXP applications worked but the layer instantiation was totally different and cannot be comparable here.

**Comment by fredj** [comment]
fixed with #3566
