### ISSUE TITLE
Legends in layertree should have no background color

### ISSUE THREAD

**Issue by gnerred** [camptocamp/ngeo#3557]
Can be seen on all ngeo clients. The legends have a gray background, but should have a transparent one instead, not ? Ping @rbovard @kalbermattenm 

![image](https://user-images.githubusercontent.com/1989467/36486728-7cdcb3fa-171f-11e8-9c44-f403ac4fa180.png)

**Comment by rbovard** [comment]
See my one year ago issue https://github.com/camptocamp/ngeo/issues/2365

**Comment by gnerred** [comment]
Ok thanks ;-)

**Comment by sbrunner** [comment]
https://jira.camptocamp.com/browse/GSGMF-541
