### ISSUE TITLE
Layout issue with app « Google » on iOS

### ISSUE THREAD

**Issue by rbovard** [camptocamp/ngeo#3560]
Project:

* Host: map.nyon.ch
* GeoMapFish version: 2.2.2

Permalink directly where we can reproduce the issue: https://map.nyon.ch/mobile

Steps to reproduce the issue:

* Open right panel
* Click on "Outil de mesure"
* Choose "Longueur"
* The botom buttons are hidden

Result:
![image](https://user-images.githubusercontent.com/4549666/36536447-41bd84a8-17cd-11e8-90a5-aab3d558799d.png)

Expected result:

![image](https://user-images.githubusercontent.com/4549666/36536470-4c6c4e16-17cd-11e8-8048-3fe3d49f9dd1.png)

The issue concern the following environment:

* [Google](https://itunes.apple.com/ch/app/google/id284815942?l=fr&mt=8) on iOS
* User agent:
```
Mozilla/5.0 (iPhone; CPU iPhone OS 11_2_2 like Mac OS X) AppleWebKit/604.1.34 (KHTML, like Gecko) GSA/43.0.185608249 Mobile/15C202 Safari/604.1
```

The following environment is working as expected:

* Chrome or Safari on the same device

**Comment by llienher** [comment]
On iOS 9.3.5, with "google" app, open a "web" view and works as excepted.
On iOS 11.0.3, with "google" app, open a "web" view and doesn't work...
Android version of "google" app always redirect to google chrome.

@ybolognini What should we do about such application that are hybrid between a internal search app and a browser ?

**Comment by sbrunner** [comment]
https://jira.camptocamp.com/browse/GSGMF-542
