### ISSUE TITLE
gmf 2.2.2 - search indicates "no result" but results are fetched (but not displayed)

### ISSUE THREAD

**Issue by svagap** [camptocamp/ngeo#3567]
In gmf 2.2.2 the search sometimes yields "no results" even if results are fetched from server

![anzeigekeineresultate](https://user-images.githubusercontent.com/29245949/36587942-8ab24fa2-187e-11e8-9120-74d8c13cbc40.png)

The coresponding request:
![requestgebaude](https://user-images.githubusercontent.com/29245949/36587954-91fc7e9a-187e-11e8-8279-ed51988ec892.png)

If I add a blank to the search term, and remove the blank again, the correct result is displayed:

![anzeigeretyped](https://user-images.githubusercontent.com/29245949/36588017-c0726758-187e-11e8-8fcb-c87edfac992a.png)

It's not happening always, but after reload of page and/or ?invalidate its happing often. Could not reproduce on demo (But do not know what to search for)
It may be a timing issue, but the request & response timing seams ok (and all search request G, Ge, Geb etc should yield results)

**Comment by ybolognini** [comment]
First we need to reproduce this issue on one of our environments. I tried with several search terms on demo and wasn't able to have a similar behavior.

**Comment by sbrunner** [comment]
https://jira.camptocamp.com/browse/GSGMF-555
