### ISSUE TITLE
Nothing will be displayed when enabling ngeoQueryOptions.queryCountFirst if count exceeds limit

### ISSUE THREAD

**Issue by svareg** [camptocamp/ngeo#3584]
Project:
- GeoMapFish version: 2.2.2

Hi there,
I configured the following options for ngeo queries:

```
gmf.module.value('ngeoQueryOptions', {
  'limit': 200,
  'queryCountFirst': true
});
```
When I select X objects, where **X <= limit**, a first query is sent to the server to count the number of objects, and then a second query is sent to the server to load them. The results are then displayed in a grid.

When I select Y objects, where **Y > limit**, a first query is sent to the server to count the number of objects, but the second query will never be sent, and **no error message will be displayed**. Actually nothing will happen from the user point of view.

When I disable the queryCountFirst option:

```
gmf.module.value('ngeoQueryOptions', {
  'limit': 200,
  'queryCountFirst': false
});
```
Then only one query will be sent, and the first 200 objects will be loaded. 
But there isn't any message either to indicate that all objects could not be loaded.

I would expect an info/error message to be displayed here, at least in the first case.
Thanks!

**Comment by sbrunner** [comment]
https://jira.camptocamp.com/browse/GSGMF-543
