### ISSUE TITLE
Translation of Draw & Measure Tooltips

### ISSUE THREAD

**Issue by svaabs** [camptocamp/ngeo#3596]
In the Draw & Measure component the tooltip with instractions how to finish drawing a line or a polygon is not translated (see screenshot).

![image](https://user-images.githubusercontent.com/9248944/36833705-9c29f94a-1d30-11e8-9f59-028af0ab1591.png)

Project:

* GitHub URL: https://geomapfish-demo.camptocamp.net/2.2/
* GeoMapFish version: 2.2

**Comment by sbrunner** [comment]
+1
