### ISSUE TITLE
goBtnGroup directive - write tests

### ISSUE THREAD

**Issue by fgravin** [camptocamp/ngeo#36]
Write test for `goBtnGroup` and `goBtn` directives

**Comment by elemoine** [comment]
The problem is beyond the `goBtnGroup` and `goBtn` directives. We have tests for the ngeo services, but not for the ngeo directives. We need to be brave and address this sooner rather than later.

**Comment by ybolognini** [comment]
Can we close it?

**Comment by sbrunner** [comment]
No response => close...
