### ISSUE TITLE
Use ng-strict-di for apps

### ISSUE THREAD

**Issue by gberaudo** [camptocamp/ngeo#3695]
In order to ease debugging of Error: [$injector:unpr] Unknown provider: ... errors, we should:
- go through babel annotate in all modes (dev and prod);
-add the [ng-strict-di](https://docs.angularjs.org/api/ng/directive/ngApp#with-ngstrictdi-) attribute to be the gmf apps.

**Comment by sbrunner** [comment]
Shouldn't we report it in Jira?

**Comment by gberaudo** [comment]
OK, done.

**Comment by sbrunner** [comment]
Thanks :-)
