### ISSUE TITLE
sortupdate event seems to be registered more than once.

### ISSUE THREAD

**Issue by rmichaelis** [camptocamp/ngeo#3704]
In our code, the callback function is triggered many times. 
I think this is due to the fact that an event is registered each time the element is dragged and dropped:
https://github.com/camptocamp/ngeo/blob/4444922040f4d10b974aafb6db00538bf6579cb7/src/misc/sortableComponent.js#L115

**Comment by fredj** [comment]
@rmichaelis see #3707
