### ISSUE TITLE
Only change color of search result with colorchooser

### ISSUE THREAD

**Issue by svaabs** [camptocamp/ngeo#3718]
In GMF applications with _colorchooser_ for changing the color of search results, not only the color will be changed but also the style.

For example a blue circle with transparent filling defined like this:
```
const searchFill = new ol.style.Fill({ color: [0, 102, 255, 0] });
const searchStroke = new ol.style.Stroke({ color: [0, 102, 255, 0.7], width: 4 });
  
this.searchFeatureStyle = {
  'default': new ol.style.Style({
    fill: searchFill,
    stroke: searchStroke,
    image: new ol.style.Circle({
      radius: 5,
      fill: searchFill,
      stroke: searchStroke
    })
  })
};
```
![image](https://user-images.githubusercontent.com/9248944/38020916-c6f39540-327b-11e8-8925-29bac9f0d532.png)

will be overwritten after changing color (see https://github.com/camptocamp/ngeo/blob/2.2/contribs/gmf/src/directives/search.js#L755-L782) and displayed like this:
![image](https://user-images.githubusercontent.com/9248944/38020962-efb592a8-327b-11e8-8e3b-e5d9a3fae320.png)

In our opinion changing color with _colorchooser_ should only change the color of the element and not the style. So only stroke and fill color should be adapted to the new color. Everything else like color transparency, stroke width, image style etc. should stay the same as in the default setting (of the customized application).

Project:

* GitHub URL: https://github.com/camptocamp/ngeo/blob/2.2/contribs/gmf/src/directives/search.js
* GeoMapFish version: 2.2

Permalink directly where we can reproduce the issue:
https://map.geo.test.bs.ch/ngeodesktop

Steps to reproduce the issue:

* Search for _Dufourstr. 40, Basel_ --> the default style will be applied like in the first picture
* Use the _colorchooser_ and change the color --> the style is changed like in the second picture

**Comment by sbrunner** [comment]
https://jira.camptocamp.com/browse/GSGMF-554
