### ISSUE TITLE
[apidoc] Try with dgeni

### ISSUE THREAD

**Issue by elemoine** [camptocamp/ngeo#374]
[dgeni] (https://github.com/angular/dgeni) is a JavaScript documentation generator with specific processors for jsdoc and Angular. It sounds like a good candidate for the ngeo documentation.

**Comment by sbrunner** [comment]
Is it relay maintained?
All the commits are between Dec 8, 2013 – Mai 29, 2015... it looks like a one shot project :-/

**Comment by elemoine** [comment]
Most of the work occurs in [`dgeni-packages`](https://github.com/angular/dgeni-packages), whose latest version (0.11.0) was released two days ago. And dgeni is what's used to [document](https://github.com/angular/angular.js/blob/d077966ff1ac18262f4615ff1a533db24d4432a7/docs/config/index.js#L6) Angular itself.

**Comment by sbrunner** [comment]
Effectively I miss that, that looks relay better :-)

**Comment by elemoine** [comment]
@sbrunner, do you agree that in its current state the API documentation is not usable? For that reason, I'd like to remove the link from the README file. I think it's bad advertisement for the project. Do you agree?

**Comment by sbrunner** [comment]
ok

**Comment by ger-benjamin** [comment]
Inconclusive try... Look at the comment under:  fcee9aaf7436a0f45734128135ea603d79624dea
