### ISSUE TITLE
Editing: missing support of type double

### ISSUE THREAD

**Issue by svades** [camptocamp/ngeo#3795]
Attributes of type **double** are not taken into account in the editing window (they don't appear in the list of editable attributes while editing a feature). Nevertheless they appear in the md.xsd.

![edit_window](https://user-images.githubusercontent.com/22655359/39131070-dd3117a4-470e-11e8-9eca-ee53d24e8c59.PNG)

![edit_double](https://user-images.githubusercontent.com/22655359/39130751-30b89a74-470e-11e8-9695-4fdb0adbfeb7.PNG)

Project:
* GitHub URL: https://github.com/camptocamp/baselstadt_mapbs
* GeoMapFish version: 2.2.2

**Comment by ger-benjamin** [comment]
Hi, it's strange, it should be taken into account.
For the one who will fix that, see: https://github.com/camptocamp/ngeo/pull/3650/files#diff-2b86bced02bc3b96df328fea4755888fR50

And also: GEO-1054 and https://github.com/camptocamp/ngeo/issues/3522

**Comment by ybolognini** [comment]
Fixed.
