### ISSUE TITLE
Keep bindToController with scope: true directives when needed

### ISSUE THREAD

**Issue by fgravin** [camptocamp/ngeo#390]
Just a post to discuss about Angular bindToController feature.

Regarding: https://github.com/camptocamp/ngeo/blame/master/src/directives/layertree.js#L144

For example, I think whole section

    var nodeExpr = $attrs['ngeoLayertree'];
    this.node = undefined;
    $scope.$watch(nodeExpr, goog.bind(function(newVal, oldVal) {
        this.node = newVal;
    }, this));

Could be replaced by 
    
    bindToController : { node: '=ngeoLayertree'}

in the directive definition.
We might consider this option for future devs.

You want to use `scope: true` for your directives, but think of using `bindToController: {}` syntax to preserve the power of the `Controller as` feature and to keep bindings with parent scope wihout isolated scope definitions.

**Comment by fredj** [comment]
+1
See also http://toddmotto.com/no-scope-soup-bind-to-controller-angularjs/

**Comment by fredj** [comment]
It's sad that the angular's documentation does not mention it ...

**Comment by fredj** [comment]
In the [angular externs](https://github.com/google/closure-compiler/blob/master/contrib/externs/angular-1.4.js#L434), `bindToController` can be `boolean|!Object<string, string>` so we are able to use this syntax

**Comment by fredj** [comment]
Angular 1.5.0 now officially support this. see: http://angularjs.blogspot.ch/2016/02/angular-150-ennoblement-facilitation.html

**Comment by ybolognini** [comment]
What's the status?

**Comment by ger-benjamin** [comment]
We already use that is some directive, like here : https://github.com/camptocamp/ngeo/blob/master/src/directives/colorpicker.js (see `colors` attributes (both in the directive and in the controller) and the bindToController statement (in the directive).)

But obviously not in old directives (made before AngularJS 1.5) like: https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/src/directives/search.js (see the `clearbutton` for instance).

I've update the guidelines. See: #1501 Can I close this with this PR ?
