### ISSUE TITLE
Legend is not reloaded when zooming in the map

### ISSUE THREAD

**Issue by svareg** [camptocamp/ngeo#3940]
Hello,

Project :
* GeoMapFish 2.2. (NGeo)

When adding a layer to the legend, the legend-symbology is loaded.
For example when loading the theme "Demo" on the test environment here : https://geomapfish-demo.camptocamp.net/2.2

the following query is executed in order to load the legend of the Layer-Group "Group" :
https://geomapfish-demo.camptocamp.net/2.2/wsgi/mapserv_proxy?ogcserver=Main+PNG&cache_version=52e79c1faa0547ec82a42387ef902de2&FORMAT=image%2Fpng&TRANSPARENT=true&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetLegendGraphic&LAYER=osm

The result is the following one : 
![grafik](https://user-images.githubusercontent.com/36037102/40982836-8ce77bca-68de-11e8-9748-65b7f00d3c2c.png)

That's ok.

And when the layer is not visible at the current scale, the legend is an empty picture.
That's ok as well.

But when we zoom in the map, the legend will never be reloaded, even if the objects are now visible on the map, and will remain empty.
The reverse is also true : If the first image was not empty, it will remain not empty even if the data are not visible any more.

That's not good, because the legend must depend on the current scale : the symbology can be different from scale to scale. 

That's not a browser problem, neither a browser-cache problem, we can reproduce it with IE, FF and Chrome : The query is just not sent to the server.

Thanks !

**Comment by sbrunner** [comment]
https://jira.camptocamp.com/browse/GSGMF-517
