### ISSUE TITLE
mobile app scrolling issues

### ISSUE THREAD

**Issue by fredj** [camptocamp/ngeo#399]
from @pgiraud:  I figured that we have scrolling issues on mobile phones. Ideally, only the content of the sidebars should scroll, not the sidebar nor the map.

Problems:

* [x] The sidebar containers are not scrollable, for example the one containing the themes is cut off (see https://github.com/camptocamp/ngeo/pull/522)
* [x] On iOS: The bottom bar hides a part of the map (when in portrait mode).
* [x] On iOS: The page can be "scrolled" when a sidebar is shown (this [library](http://www.jaridmargolin.com/bouncefix.js/) might be interesting)

**Comment by pgiraud** [comment]
I think I have a fix for the height of the map and scaleline being hidden.
