### ISSUE TITLE
[apidoc] example brocken ...

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/ngeo#408]
http://camptocamp.github.io/ngeo/master/apidoc/ngeo.btnDirective.html
http://camptocamp.github.io/ngeo/master/apidoc/ngeo.btngroupDirective.html
http://camptocamp.github.io/ngeo/master/apidoc/ngeo.profileDirective.html
http://camptocamp.github.io/ngeo/master/apidoc/ngeo.sortableDirective.html

**Comment by fredj** [comment]
I'm on it ...
