### ISSUE TITLE
[Full-text search] We should be able to group the result - Optional

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/ngeo#422]
## Features

It must be possible to group the search result, with the title of the group and the results below. This is optional. 

GeoMapFish 1.6:
 * Without grouping -  https://geomapfish-demo.camptocamp.net/1.6/
 * With grouping - http://map.cartoriviera.ch/

Linked to https://github.com/camptocamp/c2cgeoportal/issues/1656

 * [x] Results grouping
 * [x] Use groups sent by server (in GMF 1.6, groups are configured on client)
 * [ ] Activation/deactivation
 * [ ] Remove limit for global number of results on client. This limit should be set on server only

## Layout
Mockups and description of UI workflows

## External Resources
https://camptocamp.github.io/c2cgeoportal/master/developer/webservices.html#full-text-search

## Configuration
What is configurable, where and by whom (user, integrator)

 * Grouping enabled yes/no
 * When grouping is enabled, query string attribute is used to set the maximum number of results per group -  `partitionlimit:"40"`
* The max number of result (`limit`)

## Implementation Examples
Existing code, interesting websites

## Exit-criteria
What must be tested so one can say 'it's done', for example demo example (with checkboxes)

## Documents
Documents to update: test cases, user doc, dev doc (with checkboxes)

* [ ] Dev documentation
* [ ] Code documentation

**Comment by fgravin** [comment]
Something has been done in c2c-org (one request, 2 groups).
http://c2corgv6.demo-camptocamp.com/
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/js/search.js

**Comment by sbrunner** [comment]
But two dataset: https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/js/search.js#L110-L113
