### ISSUE TITLE
When we pan the map she became blue

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/ngeo#423]
on Firefox, not on Chrome

**Comment by fredj** [comment]
The [mobile](http://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/mobile/index.html)  example ?

**Comment by sbrunner** [comment]
Yes !

**Comment by pgiraud** [comment]
@sbrunner is this issue fixed? If yes, how?

**Comment by sbrunner** [comment]
I just can't reproduce it ...
