### ISSUE TITLE
Build fails with Node 5.0

### ISSUE THREAD

**Issue by tsauerwein** [camptocamp/ngeo#424]
```
$ nvm use 5.0
$ make dist
...
mkdir -p .build/
touch .build/node_modules.timestamp
mkdir -p dist/
node buildtools/build.js buildtools/ngeo.json dist/ngeo.js
module.js:339
    throw err;
    ^

Error: Cannot find module 'openlayers/node_modules/closure-util'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/tsauerwein/projects/tests/ngeo/buildtools/build.js:7:15)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
make: *** [dist/ngeo.js] Error 1
```

The problem is that with Node 5 (and npm 3.3.6) `closue-util` is no longer installed in `openlayers/node_modules/closure-util` but in `node_modules/closure-util`.

**Comment by fredj** [comment]
> [...] but in `openlayers/closure-util`.

I've tested with npm v3.4 (installed with `npm install npm@3.4`) and `closure-util` is installed in `node_modules/closure-util`

**Comment by tsauerwein** [comment]
Sorry, my description was wrong. With npm 3.3.6 `closure-util` is installed in `node_modules/closure-util`. Which is a problem because the build scripts expect it to be in `openlayers/node_modules/closure-util` (for example in [build.js](https://github.com/camptocamp/ngeo/blob/master/buildtools/build.js#L7)).

**Comment by fredj** [comment]
Same issue with npm v3.4

**Comment by gberaudo** [comment]
What about depending directly on `closure-util`?

**Comment by tsauerwein** [comment]
> What about depending directly on closure-util?

That would make sense.

**Comment by sbrunner** [comment]
Node 5.0? Just don't forget that the target version on our server is 0.10.29..., and npm 1.4.21

**Comment by tsauerwein** [comment]
For all the development with ol3 I  am using Node 5. And about npm 1.4.21: I wasn't able to build ngeo on a server with npm 1.4.21 because of [this issue](https://github.com/nodejs/nan/issues/414#issuecomment-131742064). So I used Node 4.0 with nvm.

**Comment by sbrunner** [comment]
>  I wasn't able to build ngeo on a server with npm 1.4.21 because of this issue.

This is a critical issue and we should find a solution !!!

**Comment by sbrunner** [comment]
node 5 is a dev version, it's working with node 4 and 6...
