### ISSUE TITLE
Template cache URL...

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/ngeo#425]
The template cache URL building should be better

Actually in the template cache we have url like:
`../src/directives/partials/*.html`
`../contribs/gmf/src/directives/partials/*.html`

That work for example in `src/examples` but for for example in `contribs/gmf/examples` and in `contribs/gmf/apps/mobile`.
And in all example we need to add something like:
```js
// Use the default "scale selector" template.
app.module.value('ngeoScaleselectorTemplateUrl',
    '../src/directives/partials/scaleselector.html');
```

I think that should be auto-generated.

For the first issue we can build tree different template cache and for the second we should have something that will build automatically the `*TemplateUrl`.

**Comment by sbrunner** [comment]
If I get the example of the scale selector: https://github.com/camptocamp/ngeo/blob/master/src/directives/scaleselector.js

I think that the template URL shouldn't be a value but a service with a definition like:
```js
ngeo.scaleselectorTemplateUrl = function(ngeoBaseTemplateUrl) {
  return /// ???? angular is so complex ...
    ngeoBaseTemplateUrl ? scaleselectorTemplateUrl + '/scaleselector.html' : 'ngeo/scaleselector.html'
};
ngeoModule.factory('ngeoScaleselectorTemplateUrl', ngeo.scaleselectorTemplateUrl);
```
the default value `'ngeo/scaleselector.html'` should be the values used in the template cache.

Does it looks good?
A relay related question: How does angular work with default/overwrite value/service?

**Comment by sbrunner** [comment]
Previous comment updated ...

**Comment by fgravin** [comment]
Some work has already been done for template caching in gmf:

https://github.com/ger-benjamin/ngeo/commit/f975a6d55cf586db84c0bc40ab39e060053c7648#diff-b67911656ef5d18c4ae36cb6741b7965R410

**Comment by sbrunner** [comment]
I don't understand this, it's a link on himself?
https://github.com/ger-benjamin/ngeo/commit/f975a6d55cf586db84c0bc40ab39e060053c7648#diff-fd9ecfcd383ec5acd03b05391669c60cR8

**Comment by fgravin** [comment]
> don't understand this, it's a link on himself?

Yes this is recursive, the directive is called for each node, so we have to pass the templateUrl on each call. For me, the value should be in a variable somewhere in the scope or the controller.

But please make comment in right PR instead of this one ;)

**Comment by sbrunner** [comment]
Thanks :-)

**Comment by sbrunner** [comment]
About the the template from the argument I think that we have two advantages:
- Be able to have a component two times with a different template.
- For the application administrator don't have to edit the controller to change the template.

**Comment by sbrunner** [comment]
If we use the attribute it became:
```js
ngeo.baseTemplateUrl = 'ngeo'; // in ngeo.js
ngeoModule.value('ngeoScaleselectorTemplateUrl',
    function(element, attrs) {
      var templateUrl = attrs['ngeoScaleselectorTemplateUrl'];
      return templateUrl !== undefined ? 
          templateUrl :
          ngeo.baseTemplateUrl + '/scaleselector.html';
    });
```
Does it looks good?

**Comment by fgravin** [comment]
Yes something like that !

**Comment by sbrunner** [comment]
OK, thanks @fgravin :-)

**Comment by fgravin** [comment]
As an output of this PR, i would like to write a doc about how examples are run (local, gh-pages, compiled), and explicitly explain what's done by the makefile to make them work (sed, templatecache etc...).

**Comment by fgravin** [comment]
Do you have some piece of code ? :)

**Comment by sbrunner** [comment]
Yes here: #448
