### ISSUE TITLE
`contribs/gmf/build/` should be git ignored

### ISSUE THREAD

**Issue by pgiraud** [camptocamp/ngeo#429]
I may be wrong but when I work on the gmf/apps less files, and do a `make serve`, I get untracked files in `contribs/gmf/build/`.
In my opinion, this directory should be ignored by git.
Can someone please confirm?

Also, is there any reason why we build the css since we're using the `mobile.less` file directly in `index.html`?

**Comment by sbrunner** [comment]
1. yes :-)

2. Gook question we probably needs the `css` to publish the app on the `gh-pages` but it's true that he shouln't be built on the make serve ...
