### ISSUE TITLE
floatthead and goog.require

### ISSUE THREAD

**Issue by mkoryak** [camptocamp/ngeo#4464]
Hi,

> floatThead is an external dependency that is not using webpack. So we provide directly the name because we can't goog.require the module.

Are you interested in a change to floatthead that will make it support goog.require. I am a bit lost about where you actually use goog.require anywhere in your code though. 

And what does the lib need to export to make it work? (I should probably now this... but I don't)

**Comment by gberaudo** [comment]
Hello @mkoryak. Thank you for the proposition.
We are no longer using the closure compiler (goog.require) so I will close the issue.
