### ISSUE TITLE
run tests in a real browser window

### ISSUE THREAD

**Issue by fredj** [camptocamp/ngeo#450]
Find a simple way to be able to run all the unit tests in a browser.

**Comment by tsauerwein** [comment]
I guess you know that you can launch the tests in the browser by setting `browsers: ['Chrome']` in the Karma conf? You will also also have to install `karma-chrome-launcher', see also in the [docs](http://karma-runner.github.io/0.13/config/browsers.html) or [here](http://stackoverflow.com/questions/15906903/debug-in-browser-using-testacular-now-karma). But it is not as nice as the runner we have for ol.

**Comment by sbrunner** [comment]
This don't allow to run the test on a chrome browser with a debugger ...

**Comment by tsauerwein** [comment]
> This don't allow to run the test on a chrome browser with a debugger ...

https://github.com/camptocamp/ngeo/pull/1025 allows to do exactly that.

**Comment by sbrunner** [comment]
Sorry I read your documentation and it ream fixed by #1025, not by your comment ... :-)
