### ISSUE TITLE
The mobile application is broken in local mode

### ISSUE THREAD

**Issue by fgravin** [camptocamp/ngeo#459]
Module 'app' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

**Comment by fgravin** [comment]
Also, the fonts don't load

**Comment by fgravin** [comment]
```html
    <script src="/@?main=js/mobile.js"></script>
```

seems to fix, but will it break the advanced mode ?

**Comment by sbrunner** [comment]
Will be fixed by https://github.com/camptocamp/ngeo/pull/452
