### ISSUE TITLE
How to generate jsDoc ?

### ISSUE THREAD

**Issue by fgravin** [camptocamp/ngeo#463]
We should add a target in the makefile to generate the jsDoc don't we ?
Also, add something in the developper-guide to explain how to generate and visualize the api doc.

**Comment by fgravin** [comment]
Last thing, is the doc pushed to the github-pages ?
What is the link ?

**Comment by ger-benjamin** [comment]
You can generate the doc with: ``make .build/apidoc-[name]``
Your doc will be locally available on ``file:///..../.build/apidoc-[name]``

And to push doc on gh-pages you can do:
 -  ``make gh-pages`` To update ngeo's gh-pages with the content of the master of ngeo.
 -  ``make gh-pages GITHUB_USERNAME=[your-github-name]`` To update gh-pages on your ngeo repository (I don't know if it work if it is not already created) with the content of the master of your ngeo repository.

**Comment by fredj** [comment]
See #464: adds a new apidoc make target (same as ol3)
