### ISSUE TITLE
Print hosted example is broken

### ISSUE THREAD

**Issue by pgiraud** [camptocamp/ngeo#501]
http://camptocamp.github.io/ngeo/master/examples/mapfishprint.html
When clicking on the print button a 500 server error is displayed.

**Comment by sbrunner** [comment]
Good catch but why don't we use the internal version like here?
https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/apps/mobile/index.html#L92

**Comment by pgiraud** [comment]
This comment is probably more relevant for #500.

**Comment by sbrunner** [comment]
Effectively ...

**Comment by fredj** [comment]
It seems to be fixed
