### ISSUE TITLE
Wrong service configuration

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/ngeo#512]
We have some issue here:
https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/apps/mobile/js/mobile.js#L25-L27
and here:
https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/src/controllers/abstractmobile.js#L42-L45

The services URLs can't be in a controller because on the target application because the the client application they will be generated on the fly than it should be in the html file as the full text search:
https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/apps/mobile/index.html#L113

**Comment by fgravin** [comment]
We need to put them in the index.html then ?

**Comment by sbrunner** [comment]
Effectively yes :-)
