### ISSUE TITLE
Create a service for layer creation from theme node

### ISSUE THREAD

**Issue by fgravin** [camptocamp/ngeo#513]
There are several places where we want to create a layer from the themes tree node:
- https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/src/directives/layertree.js#L144
- https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/src/services/themesservice.js#L134

We should refactor that to have it in only one place.
We could create a new Service, as in Luxembourg:
https://github.com/Geoportail-Luxembourg/geoportailv3/blob/master/geoportailv3/static/js/layerfactoryservice.js#L172

It raises another issue, that this service should return a promise (as themesService expects), but layerTree expects a layer, i think we should update ngeo layertree to wait for a promise instead of a layer.

See https://github.com/camptocamp/ngeo/blob/master/src/directives/layertree.js#L195

**Comment by sbrunner** [comment]
Should it be closed?
