### ISSUE TITLE
We whouldn't have generated file in Git

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/ngeo#523]
* contribs/gmf/fonts/gmf-icons.ttf
* contribs/gmf/fonts/gmf-icons.woff
* contribs/gmf/fonts/gmf-icons.eot

For the npm pachage we should build them with https://docs.npmjs.com/misc/scripts.

**Comment by pgiraud** [comment]
I think it's the responsibility of the developer who adds new icons (ie. modifies the gmf-icons.svg file) to also update the icons font files. I don't think it's a good idea to have an nth script to do it automatically.

**Comment by sbrunner** [comment]
I don't agree, we shouldn't duplicated similar thing in github.
