### ISSUE TITLE
Error when searching theme elements

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/ngeo#555]
`Error: featureGeometry is null`

**Comment by fredj** [comment]
Example: https://geomapfish-demo.camptocamp.net/2.0/wsgi/fulltextsearch?query=gestion

**Comment by sbrunner** [comment]
An URL with the full querystring: https://geomapfish-demo.camptocamp.net/2.0/wsgi/fulltextsearch?query=gestion&lang=fr&interface=mobile
I just fix it to have the theme.

**Comment by fredj** [comment]
depends on #578
