### ISSUE TITLE
The concerned layer is not made visible

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/ngeo#556]

**Comment by sbrunner** [comment]
Also conserne the server part?

**Comment by fredj** [comment]
The possible layers to be added are correctly requested to the server, example:
https://geomapfish-demo.camptocamp.net/2.0/wsgi/fulltextsearch?query=caf&lang=en&interface=mobile

But the result [are filtered out](https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/src/directives/search.js#L207)
