### ISSUE TITLE
GMF Layertree hosted example is broken

### ISSUE THREAD

**Issue by pgiraud** [camptocamp/ngeo#570]
https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/layertree.html
GET https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/data/themes.json 404 (Not Found)

**Comment by pgiraud** [comment]
Same error for https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/themeselector.html

**Comment by sbrunner** [comment]
It's ma fault ..., I will fix it :-)

**Comment by fredj** [comment]
@sbrunner see #573
