### ISSUE TITLE
Layers with same Id should be duplicated in GMF layer tree

### ISSUE THREAD

**Issue by fgravin** [camptocamp/ngeo#576]
In https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/mobile/index.html select the OSM theme and watch the layer tree.
The `osm_time` layer is used in 2 groups, but all interactions are bound to the same layer (visibility).

In 1.6, the layers are 2 disctincts layers.

This will may be fixed when we fix the layergroup issue.

**Comment by sbrunner** [comment]
This one: https://github.com/camptocamp/c2cgeoportal/issues/1970 ?

**Comment by fgravin** [comment]
Yes, we need to check #576 after https://github.com/camptocamp/c2cgeoportal/issues/1970 is done

**Comment by sbrunner** [comment]
OK, thanks :-)

**Comment by ger-benjamin** [comment]
Close with #601
