### ISSUE TITLE
Missing Makefile rule "contribs/gmf/build/mobile.js"

### ISSUE THREAD

**Issue by pgiraud** [camptocamp/ngeo#590]
```shell
make cleanall
make build-gmf-mobile-app
```

```
make: *** No rule to make target `contribs/gmf/build/mobile.js', needed by `build-gmf-mobile-app'.  Stop.
```

**Comment by sbrunner** [comment]
does this rule relay needed?
I prefer to replace `build-gmf-mobile-app` and `build-gmf-desktop-app` by `build-gmf-apps`
the advantage is that's it will be easier to add a new application...

**Comment by sbrunner** [comment]
I don't have this error, I have the following error:
```
make: *** No rule to make target 'contribs/gmf/fonts/fontawesome-webfont.eot', needed by 'contribs/gmf/build/mobile.css'.  Stop.
rm contribs/gmf/build/mobile.closure.js .build/app-mobile.json
```
But I run it again and it's working...

**Comment by pgiraud** [comment]
Did you do a cleanall before?

**Comment by sbrunner** [comment]
Yes :-)

**Comment by sbrunner** [comment]
On Travis it just pass ...
https://travis-ci.org/camptocamp/ngeo/jobs/106943330#L605

**Comment by pgiraud** [comment]
Can you please try on a fresh clone on your machine?

**Comment by sbrunner** [comment]
I just reproduce it on travis by chance :-)
https://travis-ci.org/camptocamp/ngeo/jobs/106948857#L1104

**Comment by sbrunner** [comment]
No, finally it's different ...

**Comment by sbrunner** [comment]
is it steal valid?

**Comment by pgiraud** [comment]
The following command still fails:
```shell
make cleanallcache && make build-gmf-apps
```

**Comment by sbrunner** [comment]
It steal working for me ...

**Comment by pgiraud** [comment]
Can someone else please try and confirm that I'm not the only one?

**Comment by fredj** [comment]
On master:
```shell
$ git pull origin master
$ make cleanall
$ make build-gmf-mobile-app
make: *** No rule to make target `build-gmf-mobile-app'.  Stop.
```

**Comment by pgiraud** [comment]
@fredj The `build-gmf-mobile-app` target has been replaced by `build-gmf-apps`.
Can you instead try the following?
```shell
make cleanallcache && make build-gmf-apps
```

**Comment by ybolognini** [comment]
What's the status?
