### ISSUE TITLE
mobile - automatically show the tree when theme is chosen

### ISSUE THREAD

**Issue by pgiraud** [camptocamp/ngeo#594]
Note: please do not work on this until validated.

- [ ] Create a new `gmf-mobile-nav-back` which requires the `gmf-mobile-nav` directive.
- [ ] Add a `navigateBack` or `goBack` in the `gmf-mobile-nav` directive's controller.

The directive watches the expression (`mainCtrl.theme` in our case) and calls the `back` method when appropriate (ie. when the theme selector panel is active).

**Comment by tsauerwein** [comment]
Fixed with https://github.com/camptocamp/ngeo/pull/655

**Comment by ger-benjamin** [comment]
Re-open with https://github.com/camptocamp/ngeo/pull/888

Because` gmf-mobile-navback` is based on a `watch` function (that watch the theme) and:
>Now the "currentTheme" is the theme in the TreeManager. This theme (the object) "never change". >Only its properties change. So I should use a watchCollection.
