### ISSUE TITLE
[Mobile] Click anywhere on panel's title to go back?

### ISSUE THREAD

**Issue by ybolognini** [camptocamp/ngeo#604]
Ruth thinks it would be helpful to be able to click on the whole panel's title to go back to previous panel. For example, clicking on "Background" would go back to main panel, just as if the user clicked on the arrow.

What do you think?  Do we estimate this?

**Comment by kalbermattenm** [comment]
ping @rbovard @gnerred @svarim @vvmalbre @mriedo

**Comment by gnerred** [comment]
Not convinced that it is a good thing to go back to main menu when clicking on "Background" text... When I click on a text, I expect to go somewhere related to the text. Why do not put a bigger or more representative/visible arrow ?

**Comment by kalbermattenm** [comment]
ping @gsollberger (will be included next time... sorry for the spam...)

**Comment by pgiraud** [comment]
I agree with @gnerred. Arrow could be combined with a small text as well with a clear distinction between "arrow + text" and "title".

See examples below.

Also, I think that when clicking on a background layer item, the map should be shown automatically. But then the user should be able to get back to the background layers list in only one action.

![img_5048](https://cloud.githubusercontent.com/assets/319774/12845759/75d88ed0-cc08-11e5-8cb3-a07019c04763.PNG)
![img_5047](https://cloud.githubusercontent.com/assets/319774/12845760/78128214-cc08-11e5-92ed-f88fbc5e0dec.PNG)

**Comment by rbovard** [comment]
For me it's a -1

The solution proposed by @gnerred is maybe better:

> Why do not put a bigger or more representative/visible arrow?

**Comment by svarim** [comment]
+1 for Daniel: bigger (more visible) arrow
I think in mobile most of the users will use the coming swipe-function.

**Comment by pgiraud** [comment]
We propose to add a generic text "Back".
Something looking like the following.
![screenshot from 2016-04-07 14 56 55](https://cloud.githubusercontent.com/assets/319774/14351699/fd8ebb94-fcd0-11e5-9a68-f519b991b87f.png)

**Comment by ybolognini** [comment]
ping @rbovard @gnerred @svarim @vvmalbre @mriedo @gsollberger @svavoi @cedricmoullet @kalbermattenm

Please have a quick look at @pgiraud 's new screenshot

**Comment by vvmalbre** [comment]
For me it's fine.

**Comment by svavoi** [comment]
For me it's fine.

**Comment by gnerred** [comment]
Ok for me

**Comment by rbovard** [comment]
I would prefer a bigger arrow but I can live with this proposition.

**Comment by tsauerwein** [comment]
Fixed with https://github.com/camptocamp/ngeo/pull/1014

**Comment by gsollberger** [comment]
ok for me.
