### ISSUE TITLE
[Mobile/Tablet] Map active when panel is open

### ISSUE THREAD

**Issue by ybolognini** [camptocamp/ngeo#605]
Initial mobile/tablet design included that map is grayed/inactive when panel is open. This is the same as on Google Maps. 

Ruth thinks that it's not a problem on mobile but that it may be a problem on tablet. What do you think?  Note that desktop is a whole different layout.

**Comment by kalbermattenm** [comment]
ping @rbovard @gnerred @svarim @vvmalbre @mriedo

**Comment by gnerred** [comment]
+1 for Ruth

**Comment by kalbermattenm** [comment]
ping @gsollberger (will be included next time... sorry for the spam...)

**Comment by gsollberger** [comment]
+1 for Ruth

**Comment by rbovard** [comment]
I underestand @vvmalbre concerns but the grey indicates that the map is inactive.

In the next example, the map in not grayed when opening left panel but the map is still active, which is logical for me.

![screenshot_2016-02-05-14-55-59](https://cloud.githubusercontent.com/assets/4549666/12848293/38bd9e94-cc19-11e5-94f1-9ee820fb8340.png)

So for me we need to be consistent about that (grey = inactive), so the current situation is fine for me. If you really want to remove the grey, the map should be active with left panel opened but this will need some dev...

**Comment by gnerred** [comment]
I agree with @rbovard , grey = inactive

**Comment by ybolognini** [comment]
I think we all agree that we must be coherent: grey = inactive and not grey = active. 

The question is: do we want to have an active map (and then not grey) when panels are open. Like @rbovard, I feel this will need some dev.

If everybody agrees that it is an interesting improvement, I will put it to "PSC Enhancement" so we can discuss it after delivery of first version.

**Comment by svarim** [comment]
+1 for Rémi: I think the map should still be active (especially for tablet).
And grey = inactive and not grey = active seems pretty logical.

**Comment by ybolognini** [comment]
PSC meeting on May 12 --> Fixed map and active with open menus is needed for version 2.2

**Comment by kalbermattenm** [comment]
PSC meeting decided that this issue can be closed.
