### ISSUE TITLE
[Mobile/Desktop] Close legend automatically when layer deactivated?

### ISSUE THREAD

**Issue by ybolognini** [camptocamp/ngeo#606]
Ruth asks if it would be possible to close the legend automatically when a user deactivates a layer. Everything is possible ;)  but do we want this?  If yes then we can estimate.

**Comment by kalbermattenm** [comment]
ping @rbovard @gnerred @svarim @vvmalbre @mriedo

**Comment by kalbermattenm** [comment]
ping @gsollberger (will be included next time... sorry for the spam...)

**Comment by rbovard** [comment]
And it will automatically be opened if the layer is activated?

It can be a layer option but it's clearly not a need on my side.

**Comment by svarim** [comment]
+1 for Ruth
And for me, the legend has not to be (re-)opened automatically when activating a layer.

**Comment by sbrunner** [comment]
https://jira.camptocamp.com/browse/GSGMF-529
