### ISSUE TITLE
[Mobile/Tablet] Layout details

### ISSUE THREAD

**Issue by ybolognini** [camptocamp/ngeo#614]
The following detail issues would be nice to fix because they would improve the global quality perception. These issues should be easy to implement. If it is not the case, please give feedback before spending too much time. Check with @pgiraud if not sure.

General -> see #670
* <s>[ ] --low priority-- What is the rule for the use of gray vs. black texts and icons?</s>
* [x] French app isn't entirely translated (Background/Data/etc.)

Search
* [x] [Tablet] Magnifier search icon is too close from left border. Keep same space for this icon and cross icon
* [x] When search result has a long name (try "Schweiz"), text is displayed below cross to hide results

Search -> see #671
* [x] [Mobile] Small shadows left and right of search box haven't the same size.
* [x] [Mobile] Buttons left and right of search box should be square just like other buttons.

Search results have a 1-px border all around:
* [x] [Mobile] Remove right/left/bottom borders so results take the whole space.
* [x] [Tablet] Remove bottom and top extra border.

* [x] [Mobile] For mobile with a wide screen (or mobile in landscape mode), align search box to the left and cross to hide search results to the rig.

* [ ] --low priority-- [Mobile] When results are present, map should be hidden. => #778

Data
* [x] Background/themes previews are square but source isn't, so the images are distorted. Use rectangle images instead
* [x] Change layertree icons for groups and layers. @pgiraud knows what icons to use -> see: #644 

Other buttons
* [x] Globally increase size of icons in the buttons. This might be not so easy as all buttons are not the same (zoom buttons are OL buttons)
* [x] Cross to hide search results looks much bigger (fatter) than other button icons. Keep it same size
* [x] Geolocation icon looks smaller than +/- (?)
* [x] Ideally, space between buttons should be:
  * Small between "+" and "-" zoom buttons (same as now)
  * Medium between "-" zoom button and geolocation. Same space between data button and search field (tablet only)
  * Large between buttons and page border (same as now)
* [ ] Milestone 2.1: See https://github.com/camptocamp/ngeo/issues/598

**Comment by pgiraud** [comment]
Distorted themes images/thumbnails
![Uploading Screenshot from 2016-02-11 11:45:12.png…]()

**Comment by blattmann** [comment]
Other buttons

 Globally increase size of icons in the buttons. This might be not so easy as all buttons are not the same (zoom buttons are OL buttons) --> 24px

**Comment by blattmann** [comment]
Search [Tablet]:

Before modification:
![screen shot 2016-02-12 at 10 54 01](https://cloud.githubusercontent.com/assets/1745041/13003675/594e4ace-d177-11e5-8b53-2b1c24a501bf.png)

After modification:
![screen shot 2016-02-12 at 09 09 29](https://cloud.githubusercontent.com/assets/1745041/13003676/596e3096-d177-11e5-8d2e-4c4ffd8d5d03.png)

The grey background is just used to demonstrate the area of the clear icon and is not included in the style sheet.
![screen shot 2016-02-12 at 09 09 19](https://cloud.githubusercontent.com/assets/1745041/13003677/5988a08e-d177-11e5-9508-e540383b07f0.png)

**Comment by blattmann** [comment]
Other buttons (before -> after) -> Icon size: 24px:

![screen shot 2016-02-12 at 11 06 48](https://cloud.githubusercontent.com/assets/1745041/13003964/dab5a566-d178-11e5-9f66-1df318bee2ef.png)
![screen shot 2016-02-12 at 11 05 44](https://cloud.githubusercontent.com/assets/1745041/13003969/e173e430-d178-11e5-9345-bd5ababa2bdf.png)
####################
![screen shot 2016-02-12 at 11 07 03](https://cloud.githubusercontent.com/assets/1745041/13003975/ea720cc4-d178-11e5-93bc-0043a1bebeb8.png)
![screen shot 2016-02-12 at 11 05 55](https://cloud.githubusercontent.com/assets/1745041/13003977/ed9b47e4-d178-11e5-96e7-faa37b20fd96.png)
####################
![screen shot 2016-02-12 at 11 07 09](https://cloud.githubusercontent.com/assets/1745041/13003979/f141445c-d178-11e5-82e7-994606ad1822.png)
![screen shot 2016-02-12 at 11 15 31](https://cloud.githubusercontent.com/assets/1745041/13004097/a31ad274-d179-11e5-9ebe-aea00e946526.png)

**Comment by rbovard** [comment]
Thanks a lot for all those UI improvements.

I have one remark for the search bar. The text is now too close of the magnifier, the margin should be the same one all sides (like it is for the cross):

![image](https://cloud.githubusercontent.com/assets/4549666/13011855/2dea42e8-d1a9-11e5-95eb-3ab1dc65a12a.png)

Maybe also think about using bigger symbols?

**Comment by blattmann** [comment]
I'll take that into account. Thanks for the hint!

**Comment by blattmann** [comment]
![screen shot 2016-02-15 at 08 37 54](https://cloud.githubusercontent.com/assets/1745041/13042255/1e7b7ea4-d3bf-11e5-8cd5-c254c17be86a.png)

**Comment by rbovard** [comment]
Cool, thanks!

Do you plan to do something about the size, to be consistent with other icons?

**Comment by blattmann** [comment]
I will "play" with it a bit and then we can decide I would say?
I will just add my proposals here.

**Comment by pgiraud** [comment]
@rbovard let's decide after some user testing.

**Comment by blattmann** [comment]
![screen shot 2016-02-15 at 11 46 54](https://cloud.githubusercontent.com/assets/1745041/13046504/7a37602c-d3d9-11e5-9dee-8eebfefca482.png)

![screen shot 2016-02-15 at 11 47 51](https://cloud.githubusercontent.com/assets/1745041/13046529/98b0fcb6-d3d9-11e5-8048-55ebe87d6e54.png)

**Comment by fredj** [comment]
> --low priority-- What is the rule for the use of gray vs. black texts and icons?

The black text matches the search text, see https://github.com/twitter/typeahead.js/blob/master/doc/jquery_typeahead.md#options (highlight option)

**Comment by ger-benjamin** [comment]
Translations are now done on all strings on mobile. Please, think about it when you add new string in the app.
