### ISSUE TITLE
Optimize the injection through controller inheritance

### ISSUE THREAD

**Issue by fgravin** [camptocamp/ngeo#634]
It is boring to add the injection in mobile app, then in abstractMobile then in abstract controllers.

We may need to just inject the `$inject` service, and call injection from abstract with

```js
this.$http = $inject.get('$http');
```

**Comment by gberaudo** [comment]
+1

**Comment by fgravin** [comment]
Closed by https://github.com/camptocamp/ngeo/pull/637
