### ISSUE TITLE
Missing target on ".eot" when lauching make serve the first time

### ISSUE THREAD

**Issue by pgiraud** [camptocamp/ngeo#635]
I just removed `touch --no-create` from the Makefile for the font-awesome related target. See https://github.com/camptocamp/ngeo/pull/630

While the `touch --no-create` command was introducing an undesired behavior since the files were removed when stopping `make serve` (with Ctrl-C), it seems that it was not completely useless.

We now have the following issue when we launch `make serve` (first time only) on a fresh new clone:
```
make: *** No rule to make target `contribs/gmf/fonts/fontawesome-webfont.eot', needed by `serve'.  Stop.
```

Additional information: if we're to use "touch --no-create" again, it's better to write it "touch -c" so that we support OSX.

**Comment by sbrunner** [comment]
see: https://github.com/camptocamp/ngeo/pull/630#issuecomment-182773312

**Comment by ybolognini** [comment]
Is it fixed?

**Comment by pgiraud** [comment]
I expect it is.
