### ISSUE TITLE
Layer tree icons

### ISSUE THREAD

**Issue by pgiraud** [camptocamp/ngeo#644]
In the layer tree, for the layers (leaf nodes):

Visibility at current scale:
- visible at current scale: icon "check" (plain),
- not visible at current scale: icon "check-o" (empty)

Selection:
- selected: primary-color + opacity 1,
- not selected: grey + opacity < 1.

Note: I'm not sure about the "primary-color" yet.

|   | in scale | out of scale |
| --- | --- | --- |
| selected | ![screenshot from 2016-02-18 18 46 08](https://cloud.githubusercontent.com/assets/319774/13152522/ed4899f8-d66f-11e5-97f8-2f409ae0bbb4.png)  | ![screenshot from 2016-02-18 18 46 15](https://cloud.githubusercontent.com/assets/319774/13152532/f7ab6cb8-d66f-11e5-9963-6e02cad16710.png)  |
| not selected | ![screenshot from 2016-02-18 18 45 50](https://cloud.githubusercontent.com/assets/319774/13152550/0a4e3b5c-d670-11e5-9149-8616ac1c60ae.png)  |  ![screenshot from 2016-02-18 18 45 57](https://cloud.githubusercontent.com/assets/319774/13152551/0e269ab2-d670-11e5-8e86-11cbaad3498b.png) |

**Comment by blattmann** [comment]
"Change layertree icons for groups and layers."

Leaf nodes (layer) is ok as you already mentioned.
What icons should be used for "groups"?

**Comment by pgiraud** [comment]
Let's only change the layers icons for now. I have to think about the groups icons a bit more.

**Comment by blattmann** [comment]
Thanks for the additional info!

**Comment by ger-benjamin** [comment]
@blattmann On the Scrum meeting right now, we have decided that I take this issue.

**Comment by blattmann** [comment]
@ger-benjamin Ok, thanks for the info.

**Comment by ger-benjamin** [comment]
@pgiraud And for "groups" node ? Which icon I should use ? Did I miss something ?
