### ISSUE TITLE
Set default theme in mobile / desktop apps

### ISSUE THREAD

**Issue by fredj** [camptocamp/ngeo#654]
Spec: https://github.com/camptocamp/c2cgeoportal/wiki/Spec-%23654-Functionalities-in-the-ngeo-application

Ideally, the default theme should come from the `themes` service

**Comment by fredj** [comment]
@tsauerwein I don't think #655 fixes this issue: the default theme is still the (inexistant) `main`

**Comment by tsauerwein** [comment]
Sorry, I referenced the wrong issue.

**Comment by sbrunner** [comment]
With the GeoMapFish this kind of things come from the functionalities, than I don't think that the better way to get it from the theme web service.

For me it's better to put it in a separate web service or in the authentication web service.

What do you think?

**Comment by sbrunner** [comment]
Concerned configuration:
* `default_theme` the default theme.
* `default_basemap` the default background layer.
* `authorized_plugins` the list of restricted plugins that the user can access.
* `queryer_layers` the layers available in the query builder.

**Comment by fredj** [comment]
https://github.com/camptocamp/c2cgeoportal/pull/2456
