### ISSUE TITLE
The background selector mix the layers

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/ngeo#673]
* Open https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/mobile/index.html
* Add a theme -> a layer should be display (overlay)
* Set the backgound from map to blank
* The overlay isn't any more visible and the background map steal be visible ...

**Comment by rbovard** [comment]
Just to be sure, the functionality to configure the basemap for each theme will still work in 2.0? http://docs.camptocamp.net/c2cgeoportal/1.6/integrator/functionality.html#using-functionalities-to-configure-the-basemap-to-use-for-each-theme

**Comment by sbrunner** [comment]
No...

**Comment by sbrunner** [comment]
In the version 2.0 we don't do what's was (in 1.6) specific to the desktop.

**Comment by rbovard** [comment]
Seriously, we will lose all desktop related features?!

Ping @kalbermattenm @vvmalbre

**Comment by sbrunner** [comment]
In the 2.0 yes, because the desktop steal be in CGXP, the desktop related features will be in the version 2.1!

**Comment by ybolognini** [comment]
@rbovard @kalbermattenm @vvmalbre

Let me clarify:

When @sbrunner talks about the "2.0", he means the mobile version that will be presented on 2/29. This includes all 1.6 **mobile** features and also the same features applied to Desktop layout. 

The complete Desktop version is called "2.1". Il will include features that are currently **not** in 1.6 mobile. Configuration of basemap for a theme is a Desktop feature.

**Comment by rbovard** [comment]
Ok, thanks a lot for the clarification @ybolognini. I've little mixed up v2 vs v2., sorry for that...

And for my information, is this functionality will be available in 2.1 mobile or not?

**Comment by ybolognini** [comment]
As background layer components are different on Desktop and Mobile, it isn't planned to have this feature on the Mobile app (Mobile features are basically the same as 1.6). But this could be added as an enhancement.
