### ISSUE TITLE
Search for coordinates

### ISSUE THREAD

**Issue by ybolognini** [camptocamp/ngeo#696]
Add search for coordinates.

When searching for coordinates, the map recenters. Add a marker to the center, just like the highlight in case of search results.

Spec for general coordinate search and marker: https://github.com/camptocamp/c2cgeoportal/wiki/Spec-%23696-Search-for-coordinates-with-marker

**Comment by sbrunner** [comment]
same for points

**Comment by fgravin** [comment]
Related to https://github.com/camptocamp/c2cgeoportal/issues/2044

**Comment by ger-benjamin** [comment]
Close with #855
