### ISSUE TITLE
Search field should always be aligned left and cross aligned right

### ISSUE THREAD

**Issue by ybolognini** [camptocamp/ngeo#707]
It looks like there are now three different behaviors:
* Small screen mobile (like Galaxy S4 Portrait) where search field + cross are centered
* Large screen mobile (like Galaxy S4 Landscape or iPhone 6) where search field is aligned left and cross is aligned right
* Tablet version

We should have only two : 
* Mobile with search field is aligned left and cross is aligned right
* Tablet

Screenshot shows search field + cross centered: should never happen
![galaxy_s4_search](https://cloud.githubusercontent.com/assets/1180264/13175207/1e8f2ce0-d709-11e5-9f5c-d2fdc30ed4f5.jpg)

**Comment by eleu** [comment]
don't forget to set the label on "Ongoing" ;)

**Comment by blattmann** [comment]
I have no rights to change the labels ;)
Thanks for setting it on "Ongoing".

**Comment by eleu** [comment]
all ok then, we will set it.
