### ISSUE TITLE
On tablet, query results are displayed over zoom/geolocation buttons

### ISSUE THREAD

**Issue by ybolognini** [camptocamp/ngeo#711]
On iPad Portrait, results are displayed with a width of 100%. On iPad Landscape, they are displayed on the right. On both cases, buttons are hidden.

Please check with original mockups. Also, I think both cases (portrait and landscape) should behave the same.

![ipad_portrait_query](https://cloud.githubusercontent.com/assets/1180264/13175914/22cec1d0-d70e-11e5-8220-3706fc691b2c.jpg)
![ipad_landscape_query](https://cloud.githubusercontent.com/assets/1180264/13175913/22cda28c-d70e-11e5-904c-f1b49f4623fd.jpg)

**Comment by ger-benjamin** [comment]
> On both cases, buttons are hidden.

@pgiraud That was in the specification... What should I do ?
