### ISSUE TITLE
On iOS, button icons aren't centered horizontaly

### ISSUE THREAD

**Issue by ybolognini** [camptocamp/ngeo#712]
Icons inside buttons (data, tools, geolocation) aren't centered on iPad.

**Comment by pgiraud** [comment]
![screenshot from 2016-02-22 10 56 04](https://cloud.githubusercontent.com/assets/319774/13215127/911b9a9a-d953-11e5-95f3-154e15fa7f7a.png)

The icons are a bit offset to the right. Zoom +/- are correctly centered.

**Comment by ebelo** [comment]
Attention: only to handle in this ticket the 3 icones: geolocation, tool and menu

**Comment by pgiraud** [comment]
Title and description modified accordingly.

**Comment by blattmann** [comment]
I have no rights to change the labels ;)
Thanks for setting it on "Ongoing".

**Comment by eleu** [comment]
can't reproduce this on https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/mobile/ any more -> already fixed?

**Comment by eleu** [comment]
only visible on ipad real device. postponed for the moment.

**Comment by ger-benjamin** [comment]
Exacte. I can say that this issue is visible only with "imported" fonts, like fontAwesome **and** our gmf-icons. Perhaps it's something in the definition of the font but I don't found anybody that has the same problem...

**Comment by ger-benjamin** [comment]
As say in the title, that's on IOS, not only on Ipad
