### ISSUE TITLE
Activate the ngeo localization

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/ngeo#732]
Concern lines
https://github.com/camptocamp/ngeo/blob/master/Makefile#L654-L669

In the same tame the pot files references are wrong ...

**Comment by sbrunner** [comment]
Finally I don't see any text to translate in ngeo ...

**Comment by tsauerwein** [comment]
So we postpone the activation until we have translatable string so that we can test properly?

**Comment by sbrunner** [comment]
done :-)
