### ISSUE TITLE
Loading mobile app without the gmf-icons font

### ISSUE THREAD

**Issue by fredj** [camptocamp/ngeo#740]
If the page is loaded and the gmf-icons are not present, an "unfriendly" string is displayed:
![no_quite_corporate](https://cloud.githubusercontent.com/assets/100959/13256707/13dbcd1c-da4c-11e5-95b3-d70ee2f31efb.png)

**Comment by fredj** [comment]
:hankey: !

**Comment by ger-benjamin** [comment]
Just a really bad coincidence ? http://www.utf8icons.com/character/58880/UTF-8-character

**Comment by sbrunner** [comment]
Visible only it the font Sans Bullshit Sans http://www.sansbullshitsans.com/ is installed...

**Comment by pgiraud** [comment]
@ger-benjamin it's possible by changing codes in the svg file.
https://raw.githubusercontent.com/camptocamp/ngeo/master/contribs/gmf/fonts/gmf-icons.svg

I'm not sure if it's worth.

**Comment by ger-benjamin** [comment]
Why, why did I have this font..?

**Comment by fredj** [comment]
I don't think it's related to "Sans Bullshit Sans"

**Comment by fredj** [comment]
> I'm not sure if it's worth.

Let's hope that all our customers have a solid sense of humor ...

**Comment by sbrunner** [comment]
On my host I don't have this char display...
