### ISSUE TITLE
Must define exactly when query panel should be close

### ISSUE THREAD

**Issue by ger-benjamin** [camptocamp/ngeo#752]
Should it be close:
 - on click on the map but not on a feature ? (currently: yes)
 - on search ? (currently: no)
 - on geolocation ? (currently: no)
 - on opening a menu ? (currently: no)
 - on deactivating the query (e.-g. selecting a measure tool) (currently: yes)

**Comment by sbrunner** [comment]
- on click on the map but not on a feature ?

yes
 - on search ?

yes?
 - on geolocation ?

no?
 - on opening a menu ?

?
 - on deactivating the query

yes

**Comment by ybolognini** [comment]
We keep it as it is today.


    on click on the map but not on a feature ? yes
    on search ? no
    on geolocation ? no
    on opening a menu ? no
    on deactivating the query (eg. selecting a measure tool) yes
