### ISSUE TITLE
Remove the unwanted queries feature's properties (like 'boundedBy')

### ISSUE THREAD

**Issue by ger-benjamin** [camptocamp/ngeo#756]
Currently, we use a quick fix: https://github.com/camptocamp/ngeo/pull/755/files#diff-b4e9ad5ed80b7a2babcad54b5de9a65cR13

**Comment by sbrunner** [comment]
Should be done in OpenLayers?

**Comment by tsauerwein** [comment]
@ger-benjamin Could you please give more information what this is about?

**Comment by ger-benjamin** [comment]
@tsauerwein We wont' display "ol3 features technical informations". And in properties of an ol.Features, we got some of these technical informations (like `boundedBy: [200456 600234 201789 599654]`).

These informations was not retrieved by the equivalent of `feature.getProperties()` in ol2. But there are in ol3.

**Comment by sbrunner** [comment]
@fredj have you more informations to fix that?

**Comment by tsauerwein** [comment]
What's wrong with the current solution of ignoring the attribute?

**Comment by sbrunner** [comment]
For me it's like a hack ... and for example (ol3 side):
I mapserver we create a feature with a geometry and a name and an id (named id),
For technical in the GML mapserver add the boundedBy
=> we shouldn't have it in the ol3 geom properties...
In ol2 it wasn't the case.

The first step is to create an ol3 issue, we want wast time on it if the ol3 main devs don't agree...

**Comment by tsauerwein** [comment]
I am not sure I understand your explanation. But the "boundedBy" is included in the feature properties, because the WFS server is configured to include it. If you don't want "boundedBy", configure your WFS server not to include it.

**Comment by ger-benjamin** [comment]
Problematic properties (namely ol3 properties, not user properties):
 - boundedBy
 - The geom

**Comment by fredj** [comment]
The properties must be filtered with something like:
```js
var properties = feature.getProperties();
delete properties['boundedBy'];
delete properties[feature.getGeometryName()];
```

**Comment by ger-benjamin** [comment]
So I make that in the displayquery component ? Do you agree @sbrunner ?

**Comment by sbrunner** [comment]
I don't know because if we do that, we will copy this 2 or 3 times ...
