### ISSUE TITLE
[Desktop] Theme selector - "loading" message not changed

### ISSUE THREAD

**Issue by pgiraud** [camptocamp/ngeo#760]
https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/desktop

The "loading..." message doesn't disappear even when the default theme is automatically loaded.

![screenshot from 2016-02-25 11 14 06](https://cloud.githubusercontent.com/assets/319774/13316595/023af1d0-dbb1-11e5-901f-1b4f7f263aa9.png)

Expected behavior: this should be automatically changed to the name of the current theme.
https://github.com/camptocamp/ngeo/blob/8705d88c3ad74391b88436eba3ff22ce966fc91d/contribs/gmf/apps/desktop/index.html#L28

**Comment by ger-benjamin** [comment]
I can't reproduce it...

**Comment by sbrunner** [comment]
Works on Chrome but not on Firefox ...

**Comment by pgiraud** [comment]
Not milestone 2.0, you're right! Changed it.
Same wrong behaviour on Firefox or Chrome on my side.

**Comment by fgravin** [comment]
> Same wrong behaviour on Firefox or Chrome

same as well, i will check that.

**Comment by fgravin** [comment]
Actually, on localhost i can't see the issue, but i can on camptocamp.github.io.
@sbrunner is it till master branch deployed on camptocamp ?

**Comment by fgravin** [comment]
I don't reproduce this issue anymore, in any case.
Does anyone do ?

**Comment by rbovard** [comment]
Just reproduced it on camptocamp.github.io

![image](https://cloud.githubusercontent.com/assets/4549666/13919430/b59adcc0-ef6d-11e5-9696-ad654bbfa19d.png)

**Comment by sbrunner** [comment]
> @sbrunner is it till master branch deployed on camptocamp ?

last time about 3 weeks aggo ...

**Comment by fredj** [comment]
Maybe it's related to the https://ows.asitvd.ch/wmts/1.0.0/WMTSCapabilities.xml loading error:
```
XMLHttpRequest cannot load https://ows.asitvd.ch/wmts/1.0.0/WMTSCapabilities.xml. 
No 'Access-Control-Allow-Origin' header is present on the requested resource. 
Origin 'https://camptocamp.github.io' is therefore not allowed access.
```

**Comment by fgravin** [comment]
How do you reproduce ?

**Comment by sbrunner** [comment]
I go on this URL with Firefox and I directly have it ...
https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/desktop/index.html
