### ISSUE TITLE
ngTouch should not be loaded in desktop app

### ISSUE THREAD

**Issue by pgiraud** [camptocamp/ngeo#762]
See https://github.com/camptocamp/ngeo/pull/761#issuecomment-188778158

> As ngTouch is not used for desktop, it is useless to load it.
> I would separate app.module into 2 modules for each platform respectivly, and inject the good module dependencies from each one.

**Comment by sbrunner** [comment]
All the chain is build with the supposition that there isn't any deference like it.
I don't thing that's a good idea to change it for less than 4ko.

In the final desktop version we well also have d3, and probably some angular ui components (table view, date picker, slider, ...?).

Leave is open from now :-)

**Comment by fredj** [comment]
And what if the desktop app is loaded on a laptop with a touch screen ?
