### ISSUE TITLE
Update all dependencies

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/ngeo#770]
Document if any witch one can be updated and why

**Comment by tsauerwein** [comment]
Isn't Greenkeeper doing it's job good enough? Or what do you mean?

**Comment by sbrunner** [comment]
We reject the first pull request #583 because it don't pass, than we should redo it to update everything and fix the issues... 

Just a remark about jsdom, he only works on Node.js 4 or newer, then we wont upgrade it.
