### ISSUE TITLE
Query open by default

### ISSUE THREAD

**Issue by ybolognini** [camptocamp/ngeo#781]
We had a talk during one PSC meeting about if query result window should be expanded or not by default. Question wasn't fully resolved, it looks like for some of you it should be expanded and for some not.

We propose to add a configuration variable to decide if result window should be expanded or not after a query.

**Comment by ybolognini** [comment]
ping @rbovard @gnerred @svarim @vvmalbre @mriedo @gsollberger @svavoi @cedricmoullet @kalbermattenm

Please read description and validate

**Comment by gnerred** [comment]
where is description ?

**Comment by ybolognini** [comment]
@gnerred  Sorry I mean the first comment, the description of the issue

**Comment by gnerred** [comment]
ok sorry, I thought there was more detailed documentation. ok for me

**Comment by rbovard** [comment]
Okay for me.

**Comment by svavoi** [comment]
Okay for us.

**Comment by vvmalbre** [comment]
Ok for us.
