### ISSUE TITLE
Search results over the query window

### ISSUE THREAD

**Issue by ybolognini** [camptocamp/ngeo#784]

**Comment by adube** [comment]
Something already fixed this issue.  Now, when the search box gets focus, the background becomes white, i.e. the query window is no longer on top of the results.

We should close this one.

**Comment by tsauerwein** [comment]
This was a side-effect of https://github.com/camptocamp/ngeo/pull/801. Note that the background only becomes white in the mobile application. I don't know if this ticket also applies to the desktop app?

**Comment by sbrunner** [comment]
We didnt's see that for the desktop app ... => mobile only

**Comment by sbrunner** [comment]
For me we can close it.
