### ISSUE TITLE
User be able to change the tree panel size on desktop

### ISSUE THREAD

**Issue by ybolognini** [camptocamp/ngeo#785]
- [ ] Original size definition by the integrator (plugin parameter)
- [ ] Opening / closing of the layertree by the users

**Comment by ybolognini** [comment]
PSC Meeting on May 12 --> Version 2.2

**Comment by fredj** [comment]
Use https://jqueryui.com/resizable/

**Comment by ybolognini** [comment]
--> GMF 2.4
