### ISSUE TITLE
Définir Ouverture par défaut

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/ngeo#816]
Related to: https://github.com/camptocamp/c2cgeoportal/issues/1708

Use and document the isExpanded attribute in LayerGroup UI_Metadata.

**Comment by pgiraud** [comment]
@sbrunner Is the version 2 theme service already returning isExpanded? It seems like the info is missing. https://geomapfish-demo.camptocamp.net/2.0/wsgi/themes?version=2&background=background
CC @olivierSemet

**Comment by sbrunner** [comment]
Effectively, I should have a look ...

**Comment by olivierSemet** [comment]
I hosted an example of this feature on my GH pages [here](https://oliviersemet.github.io/ngeo/issue-816-ouverture-par-defaut/examples/contribs/gmf/apps/desktop/)

As shown, layer group named "Group" from the "OSM" theme is expanded by default thanks to its isExpanded attributs set to **true**. Others layer groups are not expanded (isExpanded set to false or isExpanded attribut not present for the layer group)

**Comment by pgiraud** [comment]
Can you please add the 'fa-wh' so that the width of the expand-node element doesn't change.

**Comment by olivierSemet** [comment]
Do you mean 'fa-fw' ?

**Comment by pgiraud** [comment]
Yes, sorry.

**Comment by sbrunner** [comment]
fa-fw?
What's does it mean?

**Comment by fredj** [comment]
`fa-fw` fixed width icons, see  https://fortawesome.github.io/Font-Awesome/examples/

**Comment by sbrunner** [comment]
Thanks @fredj
