### ISSUE TITLE
Loading icon

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/ngeo#820]
Related to: https://github.com/camptocamp/c2cgeoportal/issues/1708

**Comment by sbrunner** [comment]
![ex4](https://cloud.githubusercontent.com/assets/353872/13522445/eaeb1dda-e1ef-11e5-9546-94d61bb07b04.png)

**Comment by fredj** [comment]
Are we able to have one loading icon per layer group?
What if two layers from two different groups are loaded with the same ol3 layer? display the "same" icon in the two groups?

**Comment by fredj** [comment]
See http://openlayers.org/en/v3.14.2/examples/image-load-events.html

**Comment by sbrunner** [comment]
Sync with @fredj
