### ISSUE TITLE
Remove Layer group block

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/ngeo#821]
Related to: https://github.com/camptocamp/c2cgeoportal/issues/1708

**Comment by sbrunner** [comment]
![ex5](https://cloud.githubusercontent.com/assets/353872/13522458/03de0230-e1f0-11e5-84b2-51ced1a54d97.png)

**Comment by sbrunner** [comment]
Sync @fredj

**Comment by olivierSemet** [comment]
Please do not close this ticket while PR #1011 is not fully merged because the LayerTree behavior has been modified

**Comment by olivierSemet** [comment]
#1011 has been merge. It's all good.  This issue can be closed @sbrunner. Thank you.
