### ISSUE TITLE
Add two way link from api to example

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/ngeo#834]
For example add a tow way link between 
http://camptocamp.github.io/ngeo/master/examples/control.html
and
http://camptocamp.github.io/ngeo/master/apidoc/ngeo.controlDirective.html

**Comment by blattmann** [comment]
Should I create the PR for this task also for branch 2.0?

**Comment by sbrunner** [comment]
Yes :-)

**Comment by blattmann** [comment]
Thanks ;)
