### ISSUE TITLE
Search - Can customize feature style

### ISSUE THREAD

**Issue by ger-benjamin** [camptocamp/ngeo#869]
Currently, we display searched features with the default overlay style (blue border, blue/transparent fill). In CGXP we can choose the default style and we have a color picker.

Remaining questions for this issue:
- Should we create a colorpicker component ?
- Should we be able to configure a specific style for coordinates search (like a cross instead of the default circle) ?

**Comment by sbrunner** [comment]
Yes two times

**Comment by fgravin** [comment]
> Yes two times

means yes for both ?

**Comment by ybolognini** [comment]
> Should we create a colorpicker component ?

Yes

> Should we be able to configure a specific style for coordinates search (like a cross instead of the default circle) ?

Yes
 
>> Yes two times
> means yes for both ?

Yes

**Comment by fgravin** [comment]
I've created a color picker directive.
#928

**Comment by fgravin** [comment]
Where are the specs ?
Seems the work of @ger-benjamin allow to have different colors for each group of the search, was it wanted ?

So, when the user choose a color from the color picker, does it overload all group styles ?

Can the user manually set a color for the cross if coordinates as well ?

**Comment by ger-benjamin** [comment]
Perhaps that I've went too far. It seems that allowing to have different colors for each group reflet any request (even if I like it).

The original request is to reproduce what are currently existing in GMF 1.6 I've identified:
 - Users can set a default color.
 - Users can choose a color on a colorpicker (on the fly, at any moment)
 - Users can set the style for the default cross on coordinates search.

Perhaps I've missed something...

**Comment by fgravin** [comment]
> Users can set a default color
> Users can set the style for the default cross on coordinates search

By user you mean the platform administrator (with custom params) ?

**Comment by fgravin** [comment]
Could we have more info about the spec @sbrunner @ybolognini ?

Shall we keep the possibility to have one style per search group ???

**Comment by ger-benjamin** [comment]
- Admin can set a default color.
 - Any users can choose a color on a colorpicker (on the fly, at any moment)
 - Admin can set the style for the default cross on coordinates search.

**Comment by sbrunner** [comment]
> Shall we keep the possibility to have one style per search group ???
no

+1 @ger-benjamin

**Comment by pgiraud** [comment]
Design specs to be discussed in WIKI page https://github.com/camptocamp/c2cgeoportal/wiki/Specs-%23869---Color-of-search-result

**Comment by ybolognini** [comment]
Specifications are now ready for validation!

ping @rbovard @gnerred @svarim @vvmalbre @mriedo @gsollberger @svavoi @cedricmoullet @kalbermattenm

**Comment by svavoi** [comment]
Thanks for the specifications "color of search result". In general it's fine for me. 
But I have two questions regarding the coordinate search:

- At the moment the marker of the coordinate search can not be deleted with the delete button of the search. Will this be possible in the future?
- We think it would be nice to be able to change the color as well for the marker of the coordinate search. What is the opinion of the others?

**Comment by vvmalbre** [comment]
Thanks as well from our side for your proposition.

- +1 @svavoi: deleting the marker of the coordinate search should be possible. Changing its color is "nice to have" but doesn't have very high priority.
- Question: Is an area highlight always displayed with a slightly transparent fill? I think an area highlight without any fill would be good (is this configurable)?

**Comment by gnerred** [comment]
+1 @svavoi 
The possibility to have an area without fill is a "nice to have" for us.

**Comment by rbovard** [comment]
> +1 @svavoi: deleting the marker of the coordinate search should be possible. Changing its color is "nice to have" but doesn't have very high priority.

+1

> Question: Is an area highlight always displayed with a slightly transparent fill? I think an area highlight without any fill would be good (is this configurable)?

In 1.6 you can set it via `vectorLayerConfig` (see http://docs.camptocamp.net/cgxp/1.6/lib/plugins/FullTextSearch.html), I hope this will be still possible in 2.1.

In general, I think the possiblity for the user to change the color is not a high priority since the integrator can set the style via options...

**Comment by mriedo** [comment]
+1 @svavoi: deleting the marker of the coordinate search should be possible. Changing its color is "nice to have" but doesn't have very high priority.

+1

**Comment by ybolognini** [comment]
@svavoi @vvmalbre @gnerred @rbovard @mriedo 

Yes, deleting the coordinate marker like we can delete the search result highlight will be implemented.

Yes, we will have the possibility to choose the style of the highlight (similar to vectorLayerConfig).

Coordinate marker won't change color with search colorpicker. But marker style can be configured, symbol itself can be changed if needed

**Comment by rbovard** [comment]
Ok, thanks!

**Comment by gsollberger** [comment]
ok for me.

**Comment by fredj** [comment]
fixed with #1247
