### ISSUE TITLE
theme service and loadThemes

### ISSUE THREAD

**Issue by fredj** [camptocamp/ngeo#877]
It's currently not possible to have:
```js
gmfThemes.getThemeObject().then(function() {
  console.log('loaded');
});
gmfThemes.loadThemes();
```
Because the promise is created in `loadThemes`.

The workaround is to the the `gmf.ThemesEventType.LOAD` event.

**Comment by fgravin** [comment]
Why is it an issue to force the developper to call `gmfThemes.loadThemes()` in the root controller of his app ?

We also could call loadThemes in the constructor of the service (ensure its called once) ?
