### ISSUE TITLE
Fix add_layer remaining issues

### ISSUE THREAD

**Issue by fredj** [camptocamp/ngeo#883]
* [ ] Display a notification message if the selected group is already present in the layer tree (see camptocamp/c2cgeoportal#2072).
* [x] add_layer:
    * if the layer exists in the current theme, set visibility to true

**Comment by sbrunner** [comment]
Can be closed?

**Comment by fredj** [comment]
we still need to display the notification message (see https://github.com/camptocamp/c2cgeoportal/issues/2072)

**Comment by sbrunner** [comment]
OK, thanks :-)

**Comment by ybolognini** [comment]
Duplicate camptocamp/c2cgeoportal#1710
