### ISSUE TITLE
Add layer icon element only when relevant

### ISSUE THREAD

**Issue by pgiraud** [camptocamp/ngeo#887]
Currently a span.layerIcon is added for every single node in the layer tree.
AFAIK, groups (nodes with children) never use a layer icon. So instead of adding an element which is then not displayed, we'd better change the partial so that the element is not added for groups.

@sbrunner Can you please confirm that groups never have icons?

**Comment by pgiraud** [comment]
@olivierSemet `getLegendIconURL` doesn't really need to be changed.

**Comment by olivierSemet** [comment]
@pgiraud So only create DOM elm if node.children is 0 (using-if on the span) do the work

**Comment by sbrunner** [comment]
Yes I confirm :-)
