### ISSUE TITLE
Add ability to expand/collapse branches in layer tree

### ISSUE THREAD

**Issue by pgiraud** [camptocamp/ngeo#892]
Related to https://github.com/camptocamp/c2cgeoportal/wiki/Spec-%231708-Layertree-desktop

Should only be available for depth > 1 for now.
Click on "chevron" icon to open or close group.

![screenshot from 2016-03-16 10 02 46](https://cloud.githubusercontent.com/assets/319774/13806835/507f03e2-eb5e-11e5-99f3-3e8230051d62.png)

**Comment by olivierSemet** [comment]
@sbrunner  As soon as the issue #845 is merged to the master branch, I'll produce an example from my GH pages of the collapse/expand layer groups features

**Comment by olivierSemet** [comment]
I hosted an example of this feature on my GH pages [here](https://oliviersemet.github.io/ngeo/issue-816-ouverture-par-defaut/examples/contribs/gmf/apps/desktop/)

As shown, layer group named "Group" from the "OSM" theme is expanded by default thanks to its isExpanded attributs set to **true**. Others layer groups are not expanded (isExpanded set to false or isExpanded attribut not present for the layer group)
