### ISSUE TITLE
Load directive associated less files in gmf examples

### ISSUE THREAD

**Issue by fgravin** [camptocamp/ngeo#930]
For the moment, the gmf examples doesn't include gmf less files.
For example, the layertree example doesn't load the `layertree.less` file, and just copy the css rules within the example. It's not what we want because the example should exactly match with the component style.

I think we should build all `gmf/less/*.less` files (as we do for `desktop.less` and `mobile.less`) during the `make serve` process.
Then, they could be served for the examples.

**Comment by ybolognini** [comment]
Fixed with Webpack
