### ISSUE TITLE
Use a maintained version of typeahead.js

### ISSUE THREAD

**Issue by fredj** [camptocamp/ngeo#958]
The original typeahead.js project is dead; no update since April 2015.

We should consider switching to a maintained fork, https://github.com/corejavascript/typeahead.js seems to be a good candidate.

**Comment by fredj** [comment]
See also #283

**Comment by tsauerwein** [comment]
:+1: I already lost quite some time for known bugs that haven't been fixed.

**Comment by gberaudo** [comment]
+100 for switching to a maintained fork. +1 to the one proposed by @fredj.

**Comment by sbrunner** [comment]
Does it steal a good choice?

**Comment by romanzoller** [comment]
See also discussion of maintained forks in https://github.com/twitter/typeahead.js/issues/1424 which also mentions https://github.com/algolia/autocomplete.js

The algolia fork seems to have more recent updates than corejs, but I don't know how they differ otherwise.
