### ISSUE TITLE
Zoom levels are not the same on ngeo and cgxp

### ISSUE THREAD

**Issue by gnerred** [camptocamp/ngeo#960]
Zoom level 12 : 

ngeo : 
http://preprod.cartoriviera.ch/v2/mobile/theme/cadastre?lang=fr&baselayer_ref=plan_ville_vevey_2000&map_x=554299&map_y=145546&map_zoom=12

cgxp : 
http://preprod.cartoriviera.ch/v2/theme/cadastre?lang=fr&baselayer_ref=plan_ville_vevey_2000&map_x=554299&map_y=145546&map_zoom=12

**Comment by tsauerwein** [comment]
By default the map resolutions or zoom-levels are calculated from the projection. If your application uses different resolutions, you can set your custom resolutions in `mapViewConfig`:

```
        mapViewConfig: {
          center: [632464, 185457],
          minZoom: 3,
          zoom: 3,
          resolutions: [...]
        }
```
https://github.com/camptocamp/ngeo/blob/f466ce8/contribs/gmf/apps/mobile/js/controller.js#L43-L47

See the OpenLayers 3 documentation for more information: http://openlayers.org/en/master/apidoc/ol.View.html

**Comment by sbrunner** [comment]
In c2cgeoportal words, we speak about the `<package>/static-ngeo/js/mobile.js` file,
I will add some documentation about it :-)

**Comment by ybolognini** [comment]
Some documentation to be added before close, thanks
