### ISSUE TITLE
Query does not work if a non queriable layer is active

### ISSUE THREAD

**Issue by gnerred** [camptocamp/ngeo#962]
This is the error : 
WMS server error. Requested layer(s) are not queryable

Query should not be done on non queriable layers. All is OK if only queriable layers are active on map.

**Comment by fredj** [comment]
Already fixed with #938 ? to be checked

**Comment by gnerred** [comment]
WMS layers are concerned here. The issue https://github.com/camptocamp/ngeo/pull/938 concerns WMTS layers, not ?

**Comment by fredj** [comment]
#938 fixes the `TypeError: Cannot read property 'split' of undefined` error on page load.

**Comment by sbrunner** [comment]
Fixed with #980?

**Comment by sbrunner** [comment]
Steal not working ...

**Comment by sbrunner** [comment]
When the layer have an attrbute queryable with the value false he shouldn't be queryed...

**Comment by sbrunner** [comment]
I see that there is some issue on multiple layers and on groups, than we will have a ``childLayers`` as an array with layername (``name``) and a ``queryable`` attribute.

**Comment by sbrunner** [comment]
To be also compatible with groups we will have in the layers in the theme:
```json
          "childLayers": [{
            "name": "<name>",
            "queryable": (true|false),
             "minResolutionHint": <minResolutionHint>,
             "maxResolutionHint": <maxResolutionHint>
         }]
```
the min max resolution hints will be used by the WFS query...
