### ISSUE TITLE
HTML code in attributes

### ISSUE THREAD

**Issue by rbovard** [camptocamp/ngeo#965]
The HTML code in attributes is not interpreted on mobile.

Example:
`<a href="https://github.com/" target="_blank">Cliquer ici</a>`

**Comment by tsauerwein** [comment]
@sbrunner Can the values in feature attributes always be [trusted](https://docs.angularjs.org/api/ng/service/$sce#trustAs)? Or can queries be made on user provided layers? In that case we would have to [sanitize](https://docs.angularjs.org/api/ngSanitize/service/$sanitize) the values.

**Comment by sbrunner** [comment]
Good question, should we add a metatata with the list of the trsted (HTML) attributes?
For me it's better.

**Comment by tsauerwein** [comment]
> ... list of the trusted (HTML) attributes?

Would this be per layer or global? Global had the risk that a user-provided layer could have an attribute with the same name. Per layer it would be sufficient to flag the whole layer as *trusted* (I think there would be no need to list each trusted attribute of a layer).

For now I would suggest to go with the *sanitize-everything* approach (see https://github.com/camptocamp/ngeo/pull/996). If we see that this causes a problem, we can still introduce a trusted flag in the metadata.

**Comment by sbrunner** [comment]
Per layer, we don't have any global metadata

> I think there would be no need to list each trusted attribute of a layer

It's exactly what I say :-)

> can still introduce a trusted flag in the metadata.

List of attributes...

**Comment by tsauerwein** [comment]
Fixed with https://github.com/camptocamp/ngeo/pull/996
