### ISSUE TITLE
Themes aren't reloaded after login

### ISSUE THREAD

**Issue by rbovard** [camptocamp/ngeo#966]
After login in mobile, the themes aren't reloaded (so we cannot see private layers)

**Comment by tsauerwein** [comment]
@sbrunner This also applies to the desktop app, right?

What exactly has do be done when doing a login or logout? It's not only refreshing the themes, you will also have to hide open query popups, maybe disable tools that are not available to the current user, ...?

**Comment by sbrunner** [comment]
- For the mobile version (in the 2.0 branch), we just have to refresh the theme.

- For the desktop version (in the master branch), we also have to enable the tool available for the current user (disable on logout), but this will be tracked in #654

**Comment by sbrunner** [comment]
> This also applies to the desktop app, right?

Yes

**Comment by tsauerwein** [comment]
Fixed with https://github.com/camptocamp/ngeo/pull/993
