### ISSUE TITLE
Placement of action icons on long layers

### ISSUE THREAD

**Issue by rbovard** [camptocamp/ngeo#968]
If a layer name is too long, the action icons are moved down and overlaps under items

![image](https://cloud.githubusercontent.com/assets/4549666/14146524/374c0dda-f698-11e5-99fa-066871b585a8.png)

In this case, the icons are for the layer `mb_statio_public_restreint`

**Comment by tsauerwein** [comment]
Should the title be cut off ('mb_statio_public_...')? Or should the remaining characters be displayed on a new line?

**Comment by olivierSemet** [comment]
I investigated on the second solution @tsauerwein  and found a way to display on multiple lines the name when its too long. But the solution implies a certain amount of CSS modification (aka not a straightforward solution)

**Comment by tsauerwein** [comment]
@olivierSemet Do you still have that code in a branch?

**Comment by sbrunner** [comment]
On CGXP we use the first solution ...

**Comment by olivierSemet** [comment]
@tsauerwein yes I have. I'll push it on my GH and I'll ping you when it's done

**Comment by tsauerwein** [comment]
> On CGXP we use the first solution ...

@sbrunner  Should it be done like in cgxp?

**Comment by sbrunner** [comment]
The CGXP version is good enough, we will do the simplest version :-)

**Comment by sbrunner** [comment]
Finally in cgxp we don't add the ellipsis, we just make that the icons don't move and don't be covered...

**Comment by sbrunner** [comment]
I just added a layer with the name `Layer with very very very very very long name` but it don't works, see: #1017

**Comment by olivierSemet** [comment]
I can see the layer but this is not a long enough name :-) 
 
<img width="284" alt="capture d ecran 2016-04-12 a 11 46 19 1" src="https://cloud.githubusercontent.com/assets/8366681/14456250/3f3f5568-00a4-11e6-8eb4-2eb82360c4f7.png">
