### ISSUE TITLE
Login error message may not be correctly displayed

### ISSUE THREAD

**Issue by pgiraud** [camptocamp/ngeo#997]
![screenshot from 2016-04-07 14 30 16](https://cloud.githubusercontent.com/assets/319774/14351065/71cb0ac0-fccd-11e5-9ba3-dee5bf0d898f.png)

**Comment by ybolognini** [comment]
All user messages will now have the same look. See https://github.com/camptocamp/c2cgeoportal/wiki/Spec-%232072-User-message 

So HTML "required" should be removed and we only display the "Could not connect" message. We don't want browser's message.

**Comment by adube** [comment]
To clarify:

 * the browser messages will be removed
 * nothing will replace them, i.e. if a user would click "Connect" without filling the form properly, we'll get the default error message

Is that correct ?

**Comment by sbrunner** [comment]
* yes
* I prefer to have a message like « The username is required » / « The password is required » ...

What do you think @pgiraud, @ybolognini?

**Comment by fredj** [comment]
#1258
